### ISSUE TITLE
Automatic enum detection fails if you have a "to" column in model

### ISSUE THREAD

**Issue by Inza** [sferik/rails_admin#1210]
If you create a "to" column in your model, the enum automatic detection will crash your application, because it tries to find out if your model respond to XXX_enum method, where as XXX it uses your model's name. Which is "to" in our case, and every model has a "to_enum" method. Therefore it will crash because it things that your column is enum even if it is something completely different (like datetime in my case).

So the quick workaround is - do not name any of your columns "to", and maybe guys could fix this in rails_admin. 

I would do it, because it should be just one :if which should be put somewhere to the code to exclude the "to" column from the enum field type detection routines. But I was unable to find where the initial call to the enum_method is done in the code...

**Comment by mshibuya** [comment]
Already fixed by #1622.
