### ISSUE TITLE
Make better use of screen width

### ISSUE THREAD

**Issue by brookr** [sferik/rails_admin#1226]
In list views, the vertical navigation on the side reduces the number of columns that can be displayed, triggering that strange horizonal `...` pagination link. 

Is there currently a way to display the Nav menu horizonatally instead of verically to allow more space for columns in the List table? Or can the Model navigation be merged into the header bar?

I'm curious if there already exists some option to address this. My css skills aren't sufficient to make it happen. 

Any ideas?

Thanks!

**Comment by mshibuya** [comment]
#3017 is the answer.
