### ISSUE TITLE
[mongoid] Devise string fields

### ISSUE THREAD

**Issue by m4tm4t** [sferik/rails_admin#1247]
I'm just playing with mongoid and trying RA.

Devise fields (email and all String fields) are interpreted as textarea in RA.

I've added a "name" field and he work as input.

user model:
https://gist.github.com/893651ca8e0513fd5f0e

HTML output:

``` html
<div class="control-group text_type email_field " id="user_email_field">
  <label class="control-label" for="user_email">Email</label>
  <div class="controls">
    <textarea cols="48" data-options="{}" data-richtext="false" id="user_email" name="user[email]" rows="3"></textarea>
    <p class="help-block">Obligatoire. </p>
  </div>
</div>
```

**Comment by mshibuya** [comment]
Done in 875c9ba7c18665f768bc48f118c0e9d0c74cb81a.
