### ISSUE TITLE
Show in App for nested resources

### ISSUE THREAD

**Issue by johnschult** [sferik/rails_admin#1291]
If a resource is nested in routes.rb the "eye" (show in app link) is not displayed. I can see why this is, since the routes are nested.

I have:

```
 resources :categories do
    resources :items do
      resources :foos
      resources :bars
    end
end
```

If I add:

```
resources :items
```

then the eye shows up in the items index and it even correctly goes to the right page, including the nested `category`. Adding similar lines for `foos` and `bars` does not work. The links just resolve to:

```
/foos/<id>
```

**Comment by mshibuya** [comment]
Try https://github.com/sferik/rails_admin/issues/2816#issuecomment-496753798.
