### ISSUE TITLE
Blank multi-select

### ISSUE THREAD

**Issue by Jpunt** [sferik/rails_admin#1369]
I've got a basic has-many-through association:

project.rb:
```ruby
    has_many :project_assets, :dependent => :delete_all, :autosave => true, :include => :asset
    has_many :assets, :through => :project_assets
    attr_accessible :asset_ids
```

project_asset.rb:
```ruby
    belongs_to :asset
    belongs_to :project
```

asset.rb:
```ruby
    has_many :project_assets, :dependent => :delete_all
    has_many :projects, :through => :project_assets
```

I can add new assets through this successfully, but the left part of the multi-select remains blank, so I can't select assets that are already in the model. What could be the reason for this?

**Comment by jwickard-taulia** [comment]
Spent 2 hours trying to figure out why my associations weren't showing up.  They were defined correctly, it was just this issue.

**Comment by redterror** [comment]
Just wanted to pile on here - I'd really like to avoid explaining to my users that this isn't really a bug.  :)

**Comment by daybreaker** [comment]
Throw one more on the pile of people who just spent way too long on this "issue" when all we need is a simple note somewhere around the search box. We have customer service reps who will be using this, and they probably wont remember the required functionality if they infrequently access that part of the edit form.

**Comment by mshibuya** [comment]
How does the note should be read? I couldn't come up with a concise phrase...

**Comment by Jpunt** [comment]
What actually needs to be done is some automatic paging inside the list and xhr-based searching. 

I'm not familiar with the RailsAdmin-codebase, so maybe someone who is can tell us if there already is some infrastructure in place to do something like this?

**Comment by zenkalia** [comment]
Personally I would really like it if the multi select box was disabled and the body said something like "Too many objects, use search box above."

And if you type a query in and there are no results it would stay disabled and read "No objects found."

**Comment by WillMasterJ** [comment]
It took me a while to find this post. I encountered the same issue.

**Comment by mshibuya** [comment]
Added note as described above, thanks @zenkalia !

**Comment by Jpunt** [comment]
Excellent news! 👍

**Comment by zenkalia** [comment]
:heart:

**Comment by SuperMasterBlasterLaser** [comment]
@mshibuya This problem still exists. How to help users to understand that he needs to type on input field?

**Comment by mshibuya** [comment]
What version are you on?
Can you reproduce that in brand-new app?

**Comment by SuperMasterBlasterLaser** [comment]
@mshibuya Version is 0.8.1

Many to one relationship where children are more than 100:

![12](https://cloud.githubusercontent.com/assets/8684688/11910966/016f9a72-a631-11e5-8382-fd049d8d010f.PNG)

Other people, who used my dashboard, thought that models aren't saved correctly. Also, I think `Too many opbjects` word is hardcoded somewhere in Javascripts, which makes impossible to use I18n.

**Comment by modreoci** [comment]
Hmm... I'we got exactly the same problem like 
[zenkalia commented on 8 May 2015](https://github.com/sferik/rails_admin/issues/1369#issuecomment-100043755)
![snimka obrazovky 2016-07-26 10-55-49](https://cloud.githubusercontent.com/assets/10616435/17133144/314c99f6-5325-11e6-8c5a-2f970486028f.png)
There are many records matched search criteria.
Here is part of my Gemfile.lock:
```
    rails_admin (0.8.1)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (~> 4.0)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (~> 0.7)
      rails (~> 4.0)
      remotipart (~> 1.0)
      safe_yaml (~> 1.0)
      sass-rails (>= 4.0, < 6)
    rails_admin-i18n (1.10.2)
    rails_admin_nestable (0.3.2)
      coffee-rails
      haml-rails
      rails_admin (>= 0.6.6)
      sass-rails
```
What now?

**Comment by amicming** [comment]
@modreoci, I reproduced also with Rails 4.2.7.1 and rails_admin 0.8.1

**Comment by modreoci** [comment]
@amicming have you got any solution? Because here is about half a year no response... :-(

**Comment by michel-victor** [comment]
Hi @mshibuya. I have the same problem but with the filtering-select. When I have more than 100 items it doesn't load anything. It works with `associated_collection_cache_all true` but the load is huge. I loved the solution for the multi-select. Could you replicate it in the filtering-select? Thanks for the great job on RailsAdmin.
