### ISSUE TITLE
Adding Checkbox for Boolean's on List action directly

### ISSUE THREAD

**Issue by drale2k** [sferik/rails_admin#1371]
Hi,

i'd like to suggest adding a checkbox instead of the dot directly on the List action. It's very common to have a boolean flag such as "active" for records where you can enable/disable records. At the moment it is really a pain in the as* to edit multiple records.

Here is what i am talking about:
http://cl.ly/image/401C0T421M0w

I'm sure this would be an insane productivity booster. Is this something that can be added relatively easily?

**Comment by mshibuya** [comment]
Already implemented as a plugin:
https://github.com/rs-pro/rails_admin_toggleable
