### ISSUE TITLE
some labels plural; some singular

### ISSUE THREAD

**Issue by brewster1134** [sferik/rails_admin#1399]
for example i have...

```ruby
  config.model Employee do
  end

  config.model User do
  end
```

in my navigation menu the labels are...

Employees
User

User has been in my DB for a long time.  Employee was just added.  It seems that all the models that were created awhile ago are all singular, and new models are plural.  Could this be an issue between versions of rails_admin when the models were created?  that is all i cant think of that would be different.

I do not have an i18n data defined.

Any thoughts here?

**Comment by juampi** [comment]
I was having the exact same issue @chewi described, which was caused by the translations in the [hisea/devise-bootstrap-views](https://github.com/hisea/devise-bootstrap-views) gem.

I'm not very experienced in I18n, so I'm not sure which gem is behaving badly here, but this issue certainly exists.
