### ISSUE TITLE
require: false for rails_admin gem on Gemfile

### ISSUE THREAD

**Issue by elado** [sferik/rails_admin#1411]
Is there any option to require gem only on demand, and not in gem file? Looks like it takes a few seconds to load, which are critical on Heroku apps.

Ideally, the require and config initialization would take place on first access to `/admin`.

I have `SKIP_RAILS_ADMIN_INITIALIZER=true`, but looks like requiring the gem itself takes a few seconds.

**Comment by mshibuya** [comment]
#1428 should have been resolved this.
