### ISSUE TITLE
has_many :through associations filter problem

### ISSUE THREAD

**Issue by barsukov** [sferik/rails_admin#1434]
Hi ,I have a problem with adding has many through association to filter . When I try to add this code :
```
list do
    field :model ,:has_many_association do
          searchable :name
     end
end'
```
and then I add choose filter on the view I give the exception : 

Unknown column 'model.name' in 'where clause': SELECT  `another_model`.* FROM `another_model`  WHERE (((model.name_en LIKE '%test%')))

The same problem I found on the StackOVerflow but it has no answer :( 
http://stackoverflow.com/questions/13529634/rails-admin-searchable-association.
Could you help me to resolve it?

**Comment by vedant1811** [comment]
Is the issue still there? there seems to be an easy fix as per the blog of @barsukov (issue opener): http://blog.endpoint.com/2013/07/hasmany-filter-in-railsadmin.html

**Comment by barsukov** [comment]
Yes if it imlements you can close but I do not remember this issue it has been 2 years ago :smile:

**Comment by rafaelgonzalez** [comment]
The issue is still there. Just had a try with `master`.

I have implemented the solution on that blog post as well, more specifically the one in the comments. The solution in the post does not work for `master`.

**Comment by vincentwoo** [comment]
@sferik any interest in addressing this issue? seems to be a pretty useful feature to have

**Comment by mshibuya** [comment]
@vincentwoo Of course, as long as it does not break existing functionality.
Please refer to the note in https://github.com/sferik/rails_admin/pull/2349#issuecomment-118215266.

**Comment by vincentwoo** [comment]
@mshibuya It seems simple enough to only search `has_many` associations where the programmer has explicitly enabled `searchable` on, with a disclaimer about the performance tradeoffs. In the case that I'm interested in, most records will have 1-4 objects in the association, which is fine for performance.

**Comment by mshibuya** [comment]
Sounds good, could you submit a PR, along with tests?

**Comment by vincentwoo** [comment]
@mshibuya Unfortunately I don't think I have the time/expertise to tackle this right now, but if anyone wants to I'm happy to kick the tires!

**Comment by fmh** [comment]
@rafaelgonzalez, it still does not work for me, even with your solution,
RA , master or 0.7
````ruby
class Order < AR
 has_many :order_clients
 has_many :clients, through: :order_clients
 rails_admin do 
   field :clients do
          searchable :last_name
      end
 end
end

Mysql2::Error: Unknown column 'people.last_name' in 'where clause': SELECT `orders`.* FROM `orders` WHERE ((LOWER(people.last_name) LIKE '%dasddasdas%')) ORDER BY orders.id asc LIMIT 20 OFFSET 0

**Comment by robertdolca** [comment]
@fmh are you using sqlite with rails server? It happened to me and the fix was to restart the server. I don't know why but it happens from time to time and restarting the server works

**Comment by fmh** [comment]
mysql, and i'm in dev mode,

**Comment by fmh** [comment]
@robertdolca , effectively, it does not work every time, maybe a cache issue !

**Comment by robertdolca** [comment]
@fmh with postgresql in production works without any issue. Could you try with MySQL in production and unicorn?

**Comment by fmh** [comment]
It make no sense !, it should work in all cases.

**Comment by Vic-L** [comment]
From this [thread](https://groups.google.com/forum/#!topic/rails_admin/z3578Boilx4), I followed Nick Roosevelt's suggestion and it worked for my case.

````
class Room < ActiveRecord:Base
  has_many :time_slots
end

class TimeSlot < ActiveRecord::Base
  belongs_to :room

  rails_admin do
    list do
      field :day do
        searchable true
      end
      # field :room do
      #   searchable room: :name
      # end
      field :room do
        searchable [{Room => :name}]
        queryable true
      end
    end
  end
end
````

I tried `searchable room: :name` and it was not working, but `searchable [{Room => :name}]` seem to make it work.

**Comment by vergenzt** [comment]
I've been having this same problem but with `has_one through: ...` associations. I'm planning to turn this into a PR at some point, but in the mean time this is a monkey patch I've used to get it working:

```ruby
require 'rails_admin/adapters/active_record'

module RailsAdmin::Adapters::ActiveRecord
  module WhereBuilderExtension
    def initialize(scope)
      @includes = []
      super(scope)
    end

    def add(field, value, operator)
      @includes.push(field.name) if field.is_a? RailsAdmin::Config::Fields::Association
      super(field, value, operator)
    end

    def build
      super.includes(*(@includes.uniq)) if @includes.any?
    end
  end

  class WhereBuilder
    prepend WhereBuilderExtension
  end
end
```

I use it like so:
```ruby
class ModelA < ActiveRecord::Base
  validates :name
end

class ModelB < ActiveRecord::Base
  has_one :model_a
end

class ModelC < ActiveRecord::Base
  has_one :model_b
  has_one :model_a, through: model_b

  rails_admin do
    list do
      configure :model_a
        searchable [:id, :name]
      end
    end
  end
end
```

Works like a charm! I've even used it for a third-order `:through` association (D => C => B => A, search A from D) and it worked.

**Comment by domangi** [comment]
@vergenzt Thanks for your solution, it helped me a lot!!!
But it introduced for me an error on all other queries. 

> NoMethodError (undefined method `page' for nil:NilClass):

Finally I found that the problem was in the build method of your patch. 

```
def build
  super.includes(*(@includes.uniq)) if @includes.any? 
end
```
This method returns nil if includes is empty without calling the super method and that fires the no method exception, when pagination is invoked on the result, e.g. in https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/adapters/active_record.rb:36

`scope = scope.send(Kaminari.config.page_method_name, options[:page]).per(options[:per])
`

I think the correct solution should be this

```
def build
  @includes.any? ? super.includes(*(@includes.uniq)) : super
end
```

So, the complete working patch is now:

```
require 'rails_admin/adapters/active_record'

module RailsAdmin::Adapters::ActiveRecord
  module WhereBuilderExtension
    def initialize(scope)
      @includes = []
      super(scope)
    end

    def add(field, value, operator)
      @includes.push(field.name) if field.association?
      super(field, value, operator)
    end

    def build
      @includes.any? ? super.includes(*(@includes.uniq)) : super
    end
  end

  class WhereBuilder
    prepend WhereBuilderExtension
  end
end
```

**Comment by vergenzt** [comment]
Thanks @domangi! Yeah I ended up discovering that in my own testing but forgot to update my comment here. I'll edit the original comment so no one gets confused. :)

**Comment by asishallab** [comment]
Thank you very much @domangi and @vergenzt. You solved my problem.
Though only partially. The provided solution does not work with

    field :model_a do
      searchable [:id, :name]
    end

only within a `configure` block as you guys provided.

**Comment by domangi** [comment]
@asishallab I don't use a configure block. Give more details about your setup (models and rails_admin) and about the error/misfunction

**Comment by asishallab** [comment]
Dear @domagi,

the following works with the provided solution `WhereBuilderExtension`

    rails_admin do
    list do
      configure :id
      configure :taxon do
        searchable [ :family, :genus, :species, :subspecies_or_strain ]
      end
    end

and this does _not_ work

    rails_admin do
    field :taxon do
      searchable [ :family, :genus, :species, :subspecies_or_strain ]
    end
    end

_No_ error is raised in the second non working case taxon is simply not searched. In older versions of rails_admin it has been searched, indeed.

Does this answer your question?
Cheers!

**Comment by domangi** [comment]
@asishallab I use a field block and it's working:

```
field :location do
      searchable [:address]
end
```

Try looking in your logs how your search is transformed in SQL in both cases. From there you could find why you are getting no results.

**Comment by nallwhy** [comment]
Why @domangi 's solution is not injected yet in this project?

**Comment by mshibuya** [comment]
@nallwhy Because we have alternative solution in the master branch: b92a4d1a30b706d08df2aee4d0a59dad698a0552

**Comment by nallwhy** [comment]
@mshibuya What is the 'eager_load'? How can I use it?
