### ISSUE TITLE
app/models/misc/misc_processor.rb:7: warning: already initialized constant MY_CONSTANT

### ISSUE THREAD

**Issue by ghost** [sferik/rails_admin#1445]
Hello, 

We've enabled Rails Admin in our tests and noticed that classes in our app/models/misc/ folder are being loaded twice. 

The stack trace shows Rails Admin loading our class, then the Rails initializer coming back through and loading it an additional time.  Calling configure in the Rails Admin initializers triggers this, and it's only affecting the classes in the misc/ subfolder.  The problem doesn't appear in development or production.  Is there something unique to testing?  Setting SKIP_RAILS_ADMIN_INITIALIZER to true solves the problem, but we need Rails Admin running for some of our tests.

Any thoughts would be helpful.  Thanks!

Steve & Desmond

**Comment by mshibuya** [comment]
Outdated, please reopen if this is still an issue.
