### ISSUE TITLE
Between 2.0 and 3.0 Drop Downs for belongs_to poly breaks

### ISSUE THREAD

**Issue by rovermicrover** [sferik/rails_admin#1474]
The double drop down, type then record, breaks for me when upgrading between 2.0 and 3.0. They are there but I have no ability to select a type or select a record. I can change a record if its already been selected through the console or previously but thats it.

If I say in my gem file 

```ruby
gem 'rails_admin', '0.2.0'
```

and do a general bundle update it works

If I say on the other hand use 3.0 to the latest

and do a general bundle update it doesn't works

Ruby 1.9.3 
Rails 3.2.11

here is about what I have

```ruby
class Medium < ActiveRecord::Base
...
  belongs_to :creator, :polymorphic => true, :inverse_of => :media
  belongs_to :origin, :polymorphic => true, :inverse_of => :media
...
end
```

```ruby
class Blog < Medium
...
end
```

```ruby
class Bio < Person
...
  has_many :media, :as => :creator, :inverse_of => :creator
..
end
```

```ruby
class Authors < Person
...
  has_many :media, :as => :creator, :inverse_of => :creator
..
end
```

```ruby
class Source < Person
...
  has_many :media, :as => :origin, :inverse_of => :origin
...
end
```

Rails admin config
```ruby
 config.model Blog do
...
    edit do
...
      field :creator do
        searchable true
      end
      field :origin do
        searchable true
      end
...
  end
...
end
```

gemfile
https://gist.github.com/4537305

**Comment by mshibuya** [comment]
Stale.
