### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by dexion** [sferik/rails_admin#1490]
Encoding::CompatibilityError in Rails_admin/main#dashboard

Showing /home/snake/.rvm/gems/ruby-1.9.3-p327@holidays/gems/rails_admin-0.3.0/app/views/rails_admin/main/_dashboard_history.html.haml where line #9 raised:

incompatible character encodings: UTF-8 and ASCII-8BIT
Extracted source (around line #9):

6:       %th.changes= t("admin.table_headers.changes")
7:   %tbody
8:     - @history.each do |t|
9:       - abstract_model = RailsAdmin.config(t.table).try(:abstract_model)
10:       %tr
11:         %td= t.try :username
12:         - if o = abstract_model.try(:get, t.item)

**Comment by bobbdelsol** [comment]
I encountered the same issue.  I wasn't using config.audit_with. 

My solution was to not allow the fields I was using UTF-8 on to be displayed or edited.  I used Javascript from the web console to change values in those fields by adding  a method accessed via $.post.

**Comment by mshibuya** [comment]
Closing this since the history adapter is legacy and will be disused.
#3374
