### ISSUE TITLE
"field" does not inherit all "configure" settings

### ISSUE THREAD

**Issue by joelvh** [sferik/rails_admin#1511]
I use "configure" blocks to setup default rendering for my model attributes and associations. However, when I specify fields in the "edit" block with no options, it does not inherit all the settings fields from the "configure" block. Specifically, :unconfirmed_email should not be displayed when creating a new User, but it is.

    config.model 'User' do
      configure :unconfirmed_email, :string do
        label "Email changed to:"
        visible do
          bindings[:object].persisted? && bindings[:object].unconfirmed_email.present?
        end
      end
      
      edit do
        field :unconfirmed_email
      end
    end

The :unconfirmed_email field should not be displayed, however it is. On the other hand, the label is correct -- it is displayed for the field definition.

**Comment by mshibuya** [comment]
That's expected, because `field` directive forces `visible true`.

**Comment by joelvh** [comment]
@mshibuya what is the correct way to use this to get the result I'm expecting?

**Comment by mshibuya** [comment]
Omitting `edit` block will work.
