### ISSUE TITLE
PaperTrail + Inheritance

### ISSUE THREAD

**Issue by Tuckie** [sferik/rails_admin#1524]
I have a model "Article" that inherits from the model "Page"

Using PaperTrail, the item_type is stored as Page (which is the expected STI behavior) in the versions table.

When I pull up the history, however, it is looking for item_type "Article"
I believe that the issue is located at: https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/extensions/paper_trail/auditing_adapter.rb#L70
and
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/extensions/paper_trail/auditing_adapter.rb#L84

I think changing  `model.model.name` to `model.model.base_class.name` should be enough to fix this?

**Comment by mshibuya** [comment]
Closed by #2865.
