### ISSUE TITLE
Sortable doesn't automatically join required models

### ISSUE THREAD

**Issue by damien-roche** [sferik/rails_admin#1543]
From the guides:

```
    # if you need to specify the join association name:
    # (See #526 and http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html => table_aliasing)
    sortable {Team => :win_percentage}
```

Yet this doesn't automatically join the required models, and so only works with a default_scope which joins those models being sorted. 

Is there another solution to this? Or, could you point me in the right direction on where to implement this and I'll send a pull request.

**Comment by mshibuya** [comment]
You can use eager_load feature, see https://github.com/sferik/rails_admin/commit/b92a4d1a30b706d08df2aee4d0a59dad698a0552.
