### ISSUE TITLE
rails_admin always shows UTC-Time

### ISSUE THREAD

**Issue by hungpk** [sferik/rails_admin#1545]
I set global TimeZone to "Melbourne". This works great in the console, but 
the rails_admin User-Interface always shows the UTC-Time. 

//config/application.rb
config.time_zone = 'Melbourne'

Is there a way to show the TimeZone'd time instead? 

the App is setup with mongoid 3.x/mongodb, Rails 3.2.12

Regards

**Comment by dalpo** [comment]
This issue has been fixed by: https://github.com/sferik/rails_admin/pull/2448

**Comment by dalpo** [comment]
@mshibuya we can close this issue :smile: 

As discussed in the issue https://github.com/sferik/rails_admin/issues/2489  the problem has been already fixed on current rails_admin version.

**Comment by mshibuya** [comment]
:relieved:
