### ISSUE TITLE
Mongoid - Embedded Documents: undefined method `rails_admin_default_object_label_method'

### ISSUE THREAD

**Issue by SeriousM** [sferik/rails_admin#1547]
Hi,

when I use rails_admin in combination with mongoid normally everything works fine but not with embedded documents.

Imaging this scenario:

``` Ruby
class MainDoc
  include Mongoid::Document

  field :name, :type => String
  embeds_many :sub_docs

  accepts_nested_attributes_for :sub_docs
  attr_accessible :name, :sub_docs_attributes
end

class SubDoc
  include Mongoid::Document

  field :docKey, :type => String
  embedded_in :main_doc

  attr_accessible :docKey
end
```

When I startup rails_admin with an empty mongodb database everything looks good. Even when I have added a MainDoc it looks correct.

When I add now a SubDoc to the MainDoc rails_admin starts searching for SubDoc#name or SubDoc#key for presenting the list of SubDocs. This property/method does not exists and so it throws the error `undefined method 'rails_admin_default_object_label_method' for {....}:Hash`.

Of course it is possible to add `object_label_method` to the rails_admin configuration but because the SubDoc is evaluated as a `Hash` this method would run against a Hash instead my SubDoc object. (see bug explaination [here](https://github.com/SeriousM/rails_admin_mongoid_problem/blob/master/app/models/sub_doc.rb#L20))

I have setup an example project [SeriousM/rails_admin_mongoid_problem](https://github.com/SeriousM/rails_admin_mongoid_problem) to demonstrate the behavior. Please run `rake db:seed` before running the application.

Cheers

**Comment by mshibuya** [comment]
I guess this should be an initialization order issue, please make sure to put `mongoid` before `rails_admin` in your Gemfile.
https://github.com/sferik/rails_admin/blob/master/config/initializers/mongoid_extensions.rb
