### ISSUE TITLE
Delete view, too many related records

### ISSUE THREAD

**Issue by sergiocampama** [sferik/rails_admin#1548]
Hello,

I have a model that has_many lots of child records. When clicking on the "x" cross to delete one of these parent records, the request to confirm the deletion can take forever and actually timeout if the child records are too many.

Is there a way to not display the "The following related items may be deleted or orphaned" warning and only load the object that I'm trying to delete?

**Comment by ehsan-khaliki** [comment]
Hey aghull, can you tell me a little more about turning on :no_associated_warning in any model as needed. Thanks

**Comment by aghull** [comment]
was a long time ago but looking at the code it was a custom attribute i made that the templates could use to silence that warning

**Comment by ehsan-khaliki** [comment]
I see, I got it to work by removing rending of the child nodes. thanks

**Comment by mshibuya** [comment]
Fixed by #2491.
