### ISSUE TITLE
NoMethodError - undefined method `rails_admin_default_object_label_method' for #<Hash:0x007fb59db6f9e0>

### ISSUE THREAD

**Issue by deiga** [sferik/rails_admin#1552]
I've just started getting these with some of my models and don't really know why.
I just added a polymorphic relation to one model, could that be a culprit?

https://gist.github.com/5091395

OS X 10.8.2
Ruby 2.0.0-p0
Rails 3.2.11
rails_admin 0.4.5
mongoid 3.1.2

**Comment by mshibuya** [comment]
Merging into #1552.
