### ISSUE TITLE
PJAX error when view doesn't contain HHTML (I think)

### ISSUE THREAD

**Issue by agronemann** [sferik/rails_admin#1575]
Hey,

I'm using v0.4.6. I have a view that looks like this:

```
# app/views/rails_admin/main/magazine_edit.html.erb
<%= @object.name %>
```

When I visit that custom action on a model via RailsAdmin, it doesn't insert the content on the page. It only inserts the content when you do a hard refresh on that page.

It can be fixed by wrapping it inside a div:

```
# app/views/rails_admin/main/magazine_edit.html.erb
<div>
  <%= @object.name %>
</div>
```

Then it works with PJAX too.

Not a critical bug in any way. Just wanted what I discovered. :)

**Comment by mshibuya** [comment]
Looks like to be a limitation of pjax.
