### ISSUE TITLE
Has many not being populated with potential records as options on select.

### ISSUE THREAD

**Issue by dfischer** [sferik/rails_admin#1576]
Locally this works, but on the production server it doesn't.

I have an album, and a photo.

I am using Mongoid.

Album
  has_many :photos

Photo
  belongs_to :album

When I am editing an album locally, any photo that is in the db shows up in the side by side column to add to the records collection.

When I am editing an album on a production instance with thousands of photos, no photos show up in the side by side view to associate a photo to the album collection.

The only way to associate a photo with an album on the production side is to edit the photo and then associate the album from the photo page. Unable to do "bulk" additions to the album collection from the album edit page.

**Comment by brgenius** [comment]
+1
