### ISSUE TITLE
Unsupported field datatype: rich_editor

### ISSUE THREAD

**Issue by Inza** [sferik/rails_admin#1585]
Hi,

I have tried to integrate `rich` to `rails_admin`. I have successfully done it before. But with last stable versions I have got a strange issue:

`Unsupported field datatype: rich_editor`

Some folk had this issue as well and created a question on SO for it: http://stackoverflow.com/questions/13070784/fail-to-integrate-ckeditor-in-rails-admin-gem-use-gem-rich

But so far, no answers are there.

I have created an issue in the rich github repo as well:
https://github.com/bastiaanterhorst/rich/issues/80, I have pasted my stack trace there.

I am not sure if the issue is in `rich` or `rails_admin`, but so far I have been able to confirm, the syntax which is used by `rich` for registering new field_type to `rails_admin` is OK.

Could this have been caused by the recent changes related to JSON security as is listed here? https://github.com/sferik/rails_admin#action-required-security-issue

Thanks for any help!

Kind regards
Tomáš

**Comment by mshibuya** [comment]
Make sure that `gem 'rails_admin'` is placed before `gem 'rich'`, because rich [checks existence of constant `RailsAdmin`](https://github.com/bastiaanterhorst/rich/blob/7cc5d1a89f1c1b9d394e5fcda3d1cadb9b3aaf74/lib/rich.rb#L1) on its first load.
