### ISSUE TITLE
Display all table cells in "List" action

### ISSUE THREAD

**Issue by drale2k** [sferik/rails_admin#1594]
Is there a way to get rid of the table set splitting in Rails Admin, and have it display all table cells without having to paginate with those stupid dots?

![Bildschirmfoto 2013-04-04 um 17 12 37](https://f.cloud.github.com/assets/271416/339597/518966ee-9d3a-11e2-9921-07e83016d00d.png)

We have a lot of data and this is really horrible UX. It is a pain when you have constantly to go here and there because you lose sight of the line and have to go back and make sure that line is the right ID and so on.

 I am ok with having horizontal scrollbars. Any way to configure this?

**Comment by mshibuya** [comment]
#3017 made this possible.
