### ISSUE TITLE
Inconsistent count in dashboard view

### ISSUE THREAD

**Issue by jgv** [sferik/rails_admin#1641]
The progress bars on the dashboard view are showing an incorrect count. I am using RailsAdmin 0.4.8, Ruby 2.0, and encountering the error on Heroku Postgres. The issue appeared after altering a column through the console and updating each record with `save!`.

You can see that while the console is showing 36 records...
 ![36 records](http://cl.ly/image/002j2v1d1X3F/Screen%20Shot%202013-05-14%20at%201.46.49%20PM.png) 

the progress bar in the RA dashboard view for this model is showing only one record....
 ![one record](http://cl.ly/image/2I2l0h2G1Q08/Screen%20Shot%202013-05-14%20at%201.47.15%20PM.png)

This record was created through the web interface after I updated the aforementioned records through the console. Could it be because the model was altered in [two different scopes](https://github.com/sferik/rails_admin/blob/c817613564ee297134f16d81b24b78d987ed1602/lib/rails_admin/config/actions/dashboard.rb#L26)?

Thanks in advance!

**Comment by hajder** [comment]
@jgv did you try restarting the dyno?

**Comment by mshibuya** [comment]
Might be related to 77116d948c869f3c8be2f5048511fc28902a16cf.
