### ISSUE TITLE
Dashboard: count is not right with namespaced models

### ISSUE THREAD

**Issue by thaichan** [sferik/rails_admin#1647]
The count by model is overwritten when having models with namespace.

For example, I have these 2 models A::Alert (30 alerts) and B::Alert (10 alerts)
And in the dashboard view then count is displayed with 10 for A::Alert and 10 for B::Alert instead of 30 for A::Alert.

Is it the right way to replace [abstract_model.pretty_name] by [abstract_model.param_key] ?

I modified the file lib/rails_admin/config/actions/dashboard.rb :
    <        @count[t.pretty_name] = current_count
    ---
    >        @count[t.param_key] = current_count
    30c30
    <          @most_recent_changes[t.pretty_name] = t.first(:sort => "#{t.table_name}.updated_at").try(:updated_at)
    ---
    >          @most_recent_changes[t.param_key] = t.first(:sort => "#{t.table_name}.updated_at").try(:updated_at)

and the file app/views/rails_admin/main/dashboard.html.haml :
    <    - last_used = @most_recent_changes[abstract_model.pretty_name]
    ---
    >    - last_used = @most_recent_changes[abstract_model.param_key]
    18c18,21
    <      %span.show= link_to abstract_model.config.label_plural, index_path, :class => 'pjax'
    ---
    >      %span= link_to abstract_model.config.label_plural, index_path, :class => 'pjax'
    >      - if abstract_model.config.navigation_label
    >        %i.icon-caret-right
    >        %span= abstract_model.config.navigation_label.upcase
    24c27
    <      - count = @count[abstract_model.pretty_name]
    ---
    >      - count = @count[abstract_model.param_key]
    28c31
    <          = @count[abstract_model.pretty_name]
    ---
    >          = @count[abstract_model.param_key]

Thx

**Comment by mshibuya** [comment]
Fixed by #2263.
