### ISSUE TITLE
Confliction with Refinery

### ISSUE THREAD

**Issue by mizanRahman** [sferik/rails_admin#1653]
I am using refinery cms as an engine fo some modules with my rails application. also using rails admin. but rails admin is not working properly with refinery in the stack. 
when I loading admin page any next route is overriden by  refinery page and all requests ia handled by refinery controller instead of RailsAdmin::MainCOntroller. as a result I can not load any model data. always returning 400 not found from refinery page controller.

**Comment by mshibuya** [comment]
Outdated.
