### ISSUE TITLE
JS Errors in 0.4.9

### ISSUE THREAD

**Issue by thatandyrose** [sferik/rails_admin#1678]
I'm using the latest version of rail_admin (0.4.9) and rails 3, and the js on the page just won't work.

It's being caused by a problem with how the bootstrap js is being loaded, but how do you fix it, and why is it happening?

Here's a screenshot of the error. This erros means I can't use the "add filters" menu.

cheers

![screen shot 2013-06-27 at 11 15 45 am](https://f.cloud.github.com/assets/778074/713361/5a84d89a-dec7-11e2-900f-8ced735b89a6.png)

**Comment by mshibuya** [comment]
Please reopen if the problem still exists.
