### ISSUE TITLE
Unsupported field datatype: uuid

### ISSUE THREAD

**Issue by czhae** [sferik/rails_admin#1681]
I use postgres and active-record-postgis adapter

**Comment by horacix** [comment]
Thanks, the proposed solution works for other datatypes as well (Tested with SQL Server varchar)

**Comment by dkperson** [comment]
Thanks, I got this error after getting the 'Ahoy' gem, and the proposed solution fixed it!

**Comment by krainboltgreene** [comment]
I think this can be closed: https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/uuid.rb
