### ISSUE TITLE
RailsAdmin::MainController# (NoMethodError) "undefined method `label' for nil:NilClass"

### ISSUE THREAD

**Issue by thatandyrose** [sferik/rails_admin#1685]
Was doing a very vanilla "export to csv" action. Nothing custom, no associations. Got this error on export:

RailsAdmin::MainController# (NoMethodError) "undefined method `label' for nil:NilClass"

/app/vendor/bundle/ruby/1.9.1/gems/rails_admin-0.4.9/lib/rails_admin/support/csv_converter.rb:61:in `block (2 levels) in to_csv'
/app/vendor/bundle/ruby/1.9.1/gems/rails_admin-0.4.9/lib/rails_admin/support/csv_converter.rb:60:in`map'
/app/vendor/bundle/ruby/1.9.1/gems/rails_admin-0.4.9/lib/rails_admin/support/csv_converter.rb:60:in `block in to_csv'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/csv.rb:1243:in`generate'
/app/vendor/bundle/ruby/1.9.1/gems/rails_admin-0.4.9/lib/rails_admin/support/csv_converter.rb:58:in `to_csv'
/app/vendor/bundle/ruby/1.9.1/gems/rails_admin-0.4.9/lib/rails_admin/config/actions/index.rb:63:in`block (4 levels) in class:Index'
/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/mime_responds.rb:196:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_controller/metal/mime_responds.rb:196:in`respond_to'

**Comment by shakycode** [comment]
Did anyone else figure out this issue?  I'm on 0.3.0 and Rails 3.2.22 and still having this same problem.  I'm stuck with legacy Rails/Rails_admin and haven't figured out how to deal with this or patch.  Sorry for bumping an old issue.
