### ISSUE TITLE
config.audit_with :history not tracking changes to nested resources

### ISSUE THREAD

**Issue by celeryclub** [sferik/rails_admin#1704]
Here are the files I'm using in this setup: https://gist.github.com/stephendavis89/6062958

When I edit through the Image form (the child resource) history is recorded as I expect. But when I edit the Image information through the Term form (the parent resource), a history entry is created with an empty message.

Rails v4.0.0
RailsAdmin v0.5.0

**Comment by mshibuya** [comment]
The legacy :history adapter was removed.
