### ISSUE TITLE
ArgumentError: A copy of AdminAbility has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by erotte** [sferik/rails_admin#1723]
I get an
"ArgumentError: A copy of AdminAbility has been removed from the module tree but is still active!"

when accessing the dashboard in development mode.

My Setup: 
Rails 4.0.0, 
rails_admin 0.5.0, 
devise 3.0.2 
cancan 1.6.10 

cancan is configured as described in the Wiki page:
https://github.com/sferik/rails_admin/wiki/CanCan

This may be an issue with automaic reloadad classes, but I have not clue how to narrow this bug in a reasonable way.

**Comment by vcivelek** [comment]
you can restart the server whenever you have a change in the admin_ability.rb (if restarting the server is not that bad for you though)

**Comment by mshibuya** [comment]
Please reopen on update.
