### ISSUE TITLE
errors in "sub-edits" aren't always visible

### ISSUE THREAD

**Issue by caboteria** [sferik/rails_admin#1735]
When you edit an object, and choose to edit or create an associated object, you get a modal dialog that covers the screen where you can edit that object's fields.  If there are form validation errors when you submit, and the errors are on fields that are "below the fold" there's not indication to the user that the errors happened.  It looks as if the "Save" button is broken and does nothing.

On typical Rails forms there's a message at the top of the form indicating that there were errors, and then the errored fields are highlighted.  In this case there's no form-level error so the user isn't guided to scroll down to find the errors.

**Comment by maximski** [comment]
This is still an issue. Any updates on that?

**Comment by ain** [comment]
Reproduced on 49aafbb.
