### ISSUE TITLE
Suggestion: Consider adding html_attributes to HasManyAssociation

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#1738]
Hi, I'm very new to Rails Admin so I will not submit a pull request. This is only a partial solution and maybe there are better ways to achieve this. Moreover, I didn't make a spec to test this!

I needed to pass some html attributes to has many associations in order to do some javascript customizations (hide/show according to other fields' value)

So I added

``` ruby
register_instance_option :html_attributes do
  {}
end
```

to `lib/rails_admin/config/fields/types/has_many_association.rb`

and replaced

``` haml
.controls{:data => { :nestedmany => true }}
```

with

``` haml
= content_tag :div, nil, field.html_attributes.reverse_merge(class: 'controls', :data => { :nestedmany => true }) do
```

in `app/views/rails_admin/main/_form_nested_many.html.haml`

**Comment by mshibuya** [comment]
It has the `html_attributes`, since its base class have that.
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/base.rb#L133
