### ISSUE TITLE
CKeditor icons asset precompile on Heroku

### ISSUE THREAD

**Issue by acetinick** [sferik/rails_admin#1752]
The CKEditor is working fine on Heroku with rails_admin, however the icons can't be loaded because they are not referencing my asset_host configured on S3.

How can I configure the CKEditor for assets on S3 with rails_admin ?

![screen shot 2013-09-20 at 12 52 37 pm](https://f.cloud.github.com/assets/571649/1178166/03e25668-21a0-11e3-8e5a-cc607d6edd45.png)

**Comment by mshibuya** [comment]
Not related with RailsAdmin.
