### ISSUE TITLE
Custom actions don't create rails_admin routes

### ISSUE THREAD

**Issue by davidgoli** [sferik/rails_admin#1758]
Custom actions appear to be broken, as there's no mechanism by which to invoke routes in custom views.

I've created a custom action (as described at https://github.com/sferik/rails_admin/wiki/Actions) with its own view containing a form, and declared it in config/initializers/rails_admin.rb under

```
RailsAdmin.config do
  ...
  config.actions do
    bulk_create
  end
end
```

When I restart my server and navigate to Rails Admin in the browser, the expected links show up and clicking on the menu tab opens my view. However, I am unable to submit this form since there's no route available in rake routes. Custom actions should automatically appear under rake routes so they can be used in custom get/post cycles.

If this functionality does exist, it should be documented.

**Comment by mshibuya** [comment]
Stale.
