### ISSUE TITLE
Custom actions broke after update from 0.3.0 to 0.4.x

### ISSUE THREAD

**Issue by jerefrer** [sferik/rails_admin#1760]
Hi there,

After updating rails_admin from 0.3.0 to 0.4.9 I started having trouble with custom actions. I tested with 0.4.0, same issue.

Here's what happens:

I get a

    No route matches {:id=>66, :model_name=>"user", :controller=>"rails_admin/main", :action=>"resend_confirmation_instructions"}

when going to the users#index action.

Here is one of the custom action:

    require 'rails_admin/config/actions'
    require 'rails_admin/config/actions/base'
     
    module RailsAdminResendConfirmationInstructions
    end
     
    module RailsAdmin
      module Config
        module Actions
          class ResendConfirmationInstructions < RailsAdmin::Config::Actions::Base
            register_instance_option :visible? do
              authorized? && bindings[:object].class.name == 'User' && !bindings[:object].confirmed?
            end

            register_instance_option :member? do
              true
            end

            register_instance_option :link_icon do
              'icon-envelope'
            end

            register_instance_option :controller do
              Proc.new do
                @object.send_confirmation_instructions
                flash[:notice] = I18n.t('admin.actions.resend_confirmation_instructions.done', :username => @object.username, :email => @object.email)
             
                redirect_to back_or_index
              end
            end
          end
        end
      end
    end

and here's the config/initializers/rails_admin.rb:

    # Register custom user actions
    module RailsAdmin
      module Config
        module Actions
          class ConfirmUser < RailsAdmin::Config::Actions::Base
            RailsAdmin::Config::Actions.register(self)
          end
          class ResendConfirmationInstructions < RailsAdmin::Config::Actions::Base
            RailsAdmin::Config::Actions.register(self)
          end
          class GoToForm < RailsAdmin::Config::Actions::Base
            RailsAdmin::Config::Actions.register(self)
          end
        end
      end
    end

    config.actions do
      dashboard
      index
      new
      export

      resend_confirmation_instructions
      confirm_user
   
      show
      edit
      globalize
      delete
      show_in_app
      go_to_form
    end

Any idea ?

**Comment by cec** [comment]
Hi @jerefrer , 
despite 1.5 years have passed since you posted this issue I'm facing the same problem, with the same gem version.

Do you mind sharing the solution to this?

Thanks,
Cec

**Comment by mshibuya** [comment]
Try requiring your custom action code on top of RailsAdmin initializer.

**Comment by jerefrer** [comment]
@cec Oh well the solution was very simple for us, don't upgrade past 0.3.0 :)

Fortunately for us the project mentioned here will most probably never need more updates ... Phew !

Anyway, good luck, I hope @mshibuya trick will do !
Cheers !
