### ISSUE TITLE
Boolean fields not showing up in embedded Mongoid form

### ISSUE THREAD

**Issue by stevef** [sferik/rails_admin#1763]
I have two Mongoid based models. One is called User. The other is called NflAuthorization. I'm simply trying to get optional check boxes that default to false to show up in an `edit` portion of Rails admin to toggle the values between true and false. This seems to come up empty with Rails Admin as-is. Is this a current issue or am I just not handling it right? Here's a gist of my code:

https://gist.github.com/stevef/53da620f8d996e22259d

**Comment by mshibuya** [comment]
Should have been solved by c262d4080819084e02af7860d7ffd546c4b6e532.
