### ISSUE TITLE
Add `enabled` to actions to allow enabling/disabling links

### ISSUE THREAD

**Issue by sepastian** [sferik/rails_admin#1765]
Currently, the `visible` options allows controlling which (member) actions should be shown. When making a member action invisible, the positions of subsequent links to other member actions change. This is not good from a UI perspective, because a user might click the wrong button after it has moved away from where it normally would appear.

An image says more than 1000 words. So, I added a custom action `publish!`, which should be available for unpublished objects only. Currently, when hiding my action for already published objects, the buttons after `publish!` change position:

![rails_admin_actions](https://f.cloud.github.com/assets/14915/1218135/e78c986e-26b5-11e3-9064-ec8dc2e82cb9.png)

What I am suggesting is a new option called `enabled`, which will always render an icon for an action. However, if `enabled` is `false`, the button would be rendered in gray and no link would be rendered. In `config/initializers/rails_admin.rb`, the `enabled` option would be set for individual members.

```
# config/initializers/rails_admin.rb
config.actions do
  publish do
    enabled do
      not bindings[:object].published?
    end
  end
end
```

And the final result would look like so:

![rails_admin_actions_2](https://f.cloud.github.com/assets/14915/1218137/ea769066-26b5-11e3-9038-74dca7c938a1.png)

This way, all buttons will always stay at the same position.

This would require small changes in the RailsAdmin `application_helper.rb`, namely in `menu_for`. Links should only be rendered if the `enabled` option returns `true` for a member.

What do you think?

**Comment by mshibuya** [comment]
Already implemented by 10655cbf, forcing `visible true` and switching `enabled` will do the job.

**Comment by mshibuya** [comment]
I lied, not implemented yet :bow:

**Comment by ideadapt** [comment]
Hello!

 

New message, please read <http://thomascart.com/girl.php?ooy>

 

kunz@ideadapt.net
