### ISSUE TITLE
Filter by Association date does not work

### ISSUE THREAD

**Issue by xaph** [sferik/rails_admin#1773]
I have 2 models in my project and they are associated with 1-to-n relation. I want to filter my model with associatied model's date field.

My models:
```
class Matchday
  # this model has a date field with the name date
  has_many :matches
end

class Match
  belongs_to :competition
end
```

My rails_admin configuration is like that:
```
config.model 'Match' do
  list do
    field :matchday do
      searchable :date
    end
  end
end
```

When I try to filter matches with matchday it doesn't give me a date select and it also doesn't filter by text like '2013-09-14'. What's the problem or what am I missing?

**Comment by mshibuya** [comment]
Currently RailsAdmin does not support filtering by has_many.
