### ISSUE TITLE
Nested fields won't display

### ISSUE THREAD

**Issue by Allanon29** [sferik/rails_admin#1784]
I have a Product and a Specifications model.
Product has many Specifications.
When I add a product I want to use a nested field to add as many specifications with name and value as the user wants. The association works, but in rails_admin when I click the add new specification button (source code):
```<a class="btn btn-info add_nested_fields" data-blueprint-id="specifications_fields_blueprint" data-association="specifications" href="javascript:void(0)">association="specifications"blueprintId="specifications_fields_blueprint">```

Only a tab will be displayed without the fields (name, value). 

In the Product model I have these which are related to the issue:
:specifications_attributes, :specification_ids
has_many :specifications
accepts_nested_attributes_for :specifications, :allow_destroy => true

In specifications I have:
belongs_to :product

I configured the rails_admin field in the model (product.rb) like this:
field :specifications

Is there anything else I need to set to make the field to behave like the "Nested field tests" field in the demo here?:
http://rails-admin-tb.herokuapp.com/admin/field_test/new

Using rails 3.2.14 and rails_admin (0.4.9)

Best Wishes,
Matt

**Comment by mshibuya** [comment]
You have to provide `attr_accessible` for `Specification` columns.
