### ISSUE TITLE
Unquoted column name failes in ORDER BY in PostgreSQL

### ISSUE THREAD

**Issue by sbwoodside** [sferik/rails_admin#1794]
I have a users table with a field isPromoter, using PostgreSQL.

      rails_admin do
        list do
          field :isPromoter do
            label "Is a Promoter?"
            column_width 120
          end

As shown, this generates the following error:
```
  User Load (1.1ms)  SELECT "users".* FROM "users" ORDER BY users.isPromoter desc LIMIT 20 OFFSET 0
PG::UndefinedColumn: ERROR:  column users.ispromoter does not exist
```

Postgres lowercases column names that are not quoted, the column is called isPromoter, not ispromoter.

If I change to:

      rails_admin do
        list do
          field :isPromoter do
            label "Is a Promoter?"
            column_width 120
            sortable '"isPromoter"'
          end

Then the query becomes:
```
  User Load (10.7ms)  SELECT "users".* FROM "users" WHERE "users"."isPromoter" = 't' AND "users"."id" IN (18)
```

Which generates the correct result.

I think that column names should probably be sorted by default

**Comment by mshibuya** [comment]
Dup of #1631.
