### ISSUE TITLE
"Is Exactly" filter still uses LIKE

### ISSUE THREAD

**Issue by ehoch** [sferik/rails_admin#1819]
Why does is the "Is Exactly" filter using LIKE? This removes any ability to rely on indexes in the list view. Some of my tables have millions of rows making a like of that nature impossible...

**Comment by kevin12gigs** [comment]
This is still an issue with the latest version 0.8.1. As @ehoch mentioned this is **horribly** inefficient, especially for indexed columns. I have put a small patch in that makes it use the '=' operator, and we saw a huge improvement in performance for "Is Exactly" Filters. I simply added this to build_statement_for_string_or_text:

**Comment by rihardssceredins** [comment]
I actually see that when using "is exactly" filter the query built with ILIKE.

**Comment by rihardssceredins** [comment]
When could this be fixed?

**Comment by mshibuya** [comment]
Fixed by #3000.
