### ISSUE TITLE
In list page sorting information is lost when showing unfit fields

### ISSUE THREAD

**Issue by omermtemel** [sferik/rails_admin#1827]
When in a model list action if i show more than 5 or 6 field it splits them into two part. When select second part rails_admin lost sorting information in first part. I hope i am clear enough. It is first time for me to open an issue

**Comment by mshibuya** [comment]
New sidescroll feature will help.
https://github.com/sferik/rails_admin/wiki/Horizontally-scrolling-table-with-frozen-columns-in-list-view
