### ISSUE TITLE
[BUG] Show a dropdown menu for fields which are validated for inclusion in a set number of values

### ISSUE THREAD

**Issue by ktaragorn** [sferik/rails_admin#1851]
For a field like the below

```
 validates :payment_status, inclusion: {in: %w(pending success failed)}
```

It would be more convenient if it showed a dropdown menu instead of a text field as it is now.

p.s. if this is already present in newer versions please feel free to close.. I am on 0.4.4

**Comment by mshibuya** [comment]
PR is welcome if you find such a feature useful.
