### ISSUE TITLE
"NameError: Uninitialized constant Psych::Syck" error starting Rails with JRuby in 2.0 mode due to safe_yaml dependency at 0.9.7

### ISSUE THREAD

**Issue by thoughtchad** [sferik/rails_admin#1856]
Encountered this when switching to Ruby 2.0 on JRuby 1.7.9 when starting rails:
"NameError: Uninitialized constant Psych::Syck"

>> rails s
>> NameError: uninitialized constant Psych::Syck

jruby 1.7.9 (2.0.0p195) 2013-12-06 87b108a on Java HotSpot(TM) 64-Bit Server VM 1.7.0_25-b15 [linux-amd64]
TorqueBox 3.0.0
rails_admin 0.6.0 via master

Traced this to early in Rails bootstrapping to:
jruby_179/lib/ruby/gems/shared/bundler/gems/safe_yaml/lib/safe_yaml/load.rb: 35

Traced the safe_yaml dependecy to rails_admin.

Found this recent issue + commit over at safe_yaml...
"When Syck is not present at all, stub it out and proceed"
https://github.com/dtao/safe_yaml/pull/50
https://github.com/dtao/safe_yaml/commit/f227195b9e3731463f8dd6b2ab6247ce3e0e97c3

Work-around until they bump the Gem version is to include safe_yaml@master in Gemfile, which will take precendence over rails_admin dependency:
gem 'safe_yaml', git: 'https://github.com/dtao/safe_yaml.git'

**Comment by mshibuya** [comment]
Fixed in upstream.
