### ISSUE TITLE
Seeing raw HTML in views and no action button are working

### ISSUE THREAD

**Issue by dtuite** [sferik/rails_admin#1863]
I suspect I must be doing something dumb but I've had a weird issue going on ever since I added RailsAdmin to my Rails app.

Basically I can see raw HTML output at the bottom of all new and edit RailsAdmin forms:

![raw railsadmin html](https://f.cloud.github.com/assets/562403/1727677/8cc777cc-62a2-11e3-9f7e-fd4733bffdee.png)

The action buttons on that page don't work because they are not contained within the `<form>` tag that you would expect them to be. If I inspect the DOM, you can see a `<fieldset>` within which the buttons exist and a sibling `<form>` which wraps the raw HTML output, further down the DOM tree.

![buttons not in form element](https://f.cloud.github.com/assets/562403/1727707/1ee4e1ee-62a3-11e3-8476-5da1ac78fd6b.png)

My first thought was that this is a Pjax issue but there's no JS console errors or important warnings.

My second thought was that some other Gem in my app was clashing with RailsAdmin. I've tried running the app without (for example) turbolinks and [foundation-rails][1] but it doesn't seem to make a difference.

I'm running Rails 4.0.2 on Ruby 2.0.0p247. The issue exists both in development (OX X Mavericks) and in production (Ubuntu 13.10).

Let me know if there's anything else I can do to help diagnose.

[1]: https://github.com/zurb/foundation-rails

**Comment by mshibuya** [comment]
Stale.
