### ISSUE TITLE
Custom member actions feel heavy

### ISSUE THREAD

**Issue by chendry** [sferik/rails_admin#1890]
I've had some troubles writing custom member actions for my models in rails_admin.  For instance, suppose I have an "application" that the user fills out, and I want an admin user to be able to download that application as a PDF.  The best I've been able to come up with is as follows:  (In an initializer:)

``` ruby
module RailsAdmin
  module Config
    module Actions
      class DownloadPdf < Base
        RailsAdmin::Config::Actions::register(self)

        register_instance_options(:member) { true }
        register_instance_option(:pjax?) { false }
        register_instance_option(:link_icon) { 'icon-chevron-down' }

        register_instance_option(:visible?) do
          bindings[:object].is_a?(Application)
        end

        register_instance_option :controller do
          Proc.new do
            send_data @object.to_pdf # ...
          end
        end
      end
    end
  end
end
```

For something as trivial as this (link to download PDF) it would be nice to have something similar to ActiveAdmin's approach that can be defined inline with the model configuration:

``` ruby
rails_admin do
  show do
    member_action :download_pdf do
      send_data @object.to_pdf # ... 
    end
  end
end
```

Also, the action renders itself as a tab on the object's "show" page which is somewhat misleading because the action does not have any sort of a UI - it's a simple link to download a PDF.

Another an issue I had was with having to configure the new list of actions and including my own.  This just feels off in that I need to duplicate a list of actions and in that I would (presumably) need to update that list when I upgrade to future rails_admin version that adds or modifies the list of actions:

``` ruby
RailsAdmin.config do |config|
  # ...
  config.actions do
    dashboard
    index
    new
    export
    history_index
    bulk_delete
    show
    edit
    delete
    history_show
    show_in_app
    download_pdf # my custom action
  end
end
```

I just wanted to get your thoughts on this and see if I'm overlooking or misunderstanding something.  I would be glad to dive in and help if there is any interest in having a lighter-weight approach to adding member actions.

**Comment by mshibuya** [comment]
There's a way to define custom actions on the fly.
https://github.com/sferik/rails_admin/wiki/Actions#define-actions
