### ISSUE TITLE
Asset compilation error

### ISSUE THREAD

**Issue by anthonycollini** [sferik/rails_admin#1907]
Asset precompilation is failing with the following message:

```
environment.context_class.class_eval do
  def asset_path(path, options = {})
  end
end
```

It seems to fail when it hits 
    ../rails_admin-0.6.1/app/assets/stylesheets/rails_admin/jquery.colorpicker.scss)/Users/ac/.rvm/gems/ruby-2.1.0-preview2/gems/sprockets-2.10.1/lib/sprockets/context.rb:241:in `asset_path'

Any thoughts on why this is happening or how to resolve? If I remove rails_admin, everything works as expected.

I have the following in my application.rb
    config.assets.precompile += %w( rails_admin/rails_admin.css rails_admin/rails_admin.js)
    config.assets.precompile += %w( .svg .eot .woff .ttf )

**Comment by RIcky-Gerry** [comment]
@anthonycollini I copy your code and paste in my project, but some errors with me, this is the question:
undefined method `to_path' for "/Users/ricky/work/wiki/app/assets/stylesheets/some_dir/some.css":String
,i use rails 4.2.1 and ruby 2.0.0 , i read the ruby on rails api，also can find method to_path, how can i solve this problem :)

**Comment by sheharyarn** [comment]
@RIcky-Gerry change `to_path` to `to_s`, should work now.
