### ISSUE TITLE
Documentation referencing config.attr_accessible_role needs to be updated

### ISSUE THREAD

**Issue by gsxdsm** [sferik/rails_admin#1910]
Since config.attr_accessible_role is no longer supported, all documentation referencing this should be updated

**Comment by mshibuya** [comment]
Seems to be fixed.

**Comment by viviannguyen** [comment]
Actually, it has yet to be updated.  
https://github.com/sferik/rails_admin/wiki/Base-configuration
I have no idea what I should be doing instead if I'm still using Rails 3.
