### ISSUE TITLE
Disabling inline_edit on a has_many association

### ISSUE THREAD

**Issue by benshimmin** [sferik/rails_admin#1911]
How does one do this?

Setting `inline_edit false` in the relevant field block throws an error; looking at the source, it seems like that instance option isn't registered in `HasManyAssociation` (but it is in `HasOneAssociation`, for instance).

**Comment by amalagaura** [comment]
Kudos on this great project.

I am having this same issue. I don't understand why the inline_edit and inline_add are not configurable on has_many's. I actually have it on a through and they throw exceptions and I cannot disable them. I will see if I can understand it further.
