### ISSUE TITLE
Support for 'Countries' gem - support field type 'Country'

### ISSUE THREAD

**Issue by swistaczek** [sferik/rails_admin#1929]
Hello,
I tried to create admin interface using awesome rails_admin for Mongoid model that has  field type 'Country'. Currently rails_admin don't know how to handle field for this type. 

I will try to figure out and combine small pull request for this issue.

Links:
* [Countries gem](https://github.com/hexorx/countries)

**Comment by mshibuya** [comment]
No plan on this, please consider creating 3rd party plugin.
