### ISSUE TITLE
Error 406 in rails admin with IE

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#1932]
Hi,

I found a very bad issue with old IE versions (8 and maybe 9, but I'm not 100% sure) that unfortunately I still need to support.

When validations fail, IE8 outputs the following error:

![406railsadmin](https://f.cloud.github.com/assets/556268/2178092/35cf2b20-9657-11e3-99fe-8d7600e52a0f.png)

Steps to reproduce:
1. Go to http://hidden-basin-9589.herokuapp.com/admin with IE8
2. Login with `demo@example.com` `demodemo`
3. Click on `Pages` on the left navigation menu
4. Click on `Add new` tab
5. Click on `Save`

Since this is quite random, you may not be able to reproduce it at the first try. If you properly see the validation error message, click the `New` link in the breadcrumb `Dashboard / Pages / New` and retry to save. I tried several times, the maximum number of consecutive successes was 5.

The source code of this application is available here: https://github.com/tagliala/rails-admin-406

This bug doesn't appear in development environment

Please let me know if you think you know the source of this problem

Thanks In Advance

**Comment by mshibuya** [comment]
Let's forget about IE, we're in 2019 now.
