### ISSUE TITLE
Not able to hide or display action icon for record

### ISSUE THREAD

**Issue by LarryCorbin** [sferik/rails_admin#1936]
Hi,
 I have issue with action. where I want to hide action icon based on some condition not on model level but on object(record level). but some how it is not working. please find attached image. I want to disable survey icon if survey is not assigned to product
![screenshot from 2014-03-21 17 24 43](https://f.cloud.github.com/assets/6359321/2482636/3816d94c-b0f0-11e3-8d5f-0f2cd42ff5e8.png)

**Comment by mshibuya** [comment]
Use [`visible` option](https://github.com/sferik/rails_admin/wiki/Actions#controlling-visibility) to control action visibility.
