### ISSUE TITLE
undefined method `[]' for nil:NilClass in Rails 4 when using :has_and_belongs_to_many_association

### ISSUE THREAD

**Issue by tyrw** [sferik/rails_admin#1940]
I've recently upgraded to Rails 4, and everything is working well except for HABTM relationships.  For example, `belongs_to` and `has_many` associations work fine, while `has_and_belongs_to_many` does not:

```
config.model 'Group' do
  field :creator, :belongs_to_association # works fine
  field :posts, :has_many_association # works fine
  field :users, :has_and_belongs_to_many_association # throws exception
  ...
```

The exception thrown is `NoMethodError in RailsAdmin::Main#index`

```
Showing /<path-to-gems>/rails_admin-0.6.1/app/views/rails_admin/main/index.html.haml where line #13 raised:

undefined method `[]' for nil:NilClass
```

Is there any recommended fix or workaround?

**Comment by mshibuya** [comment]
Rails 4 support was dropped.
