### ISSUE TITLE
Support for 'trash' folder implementation for deleted records to restore them when deleted accidentally

### ISSUE THREAD

**Issue by venkatbeehyv** [sferik/rails_admin#1972]
If some one deletes records accidentally and want to restore the things that got deleted, what is the approach we should use? Do we have any existing functionality for this kind of  requirement? If no, can you suggest a good approach to do this?

Thanks in advance. 

Venkat

**Comment by mshibuya** [comment]
Just go soft-deletion, there's [many gems](https://www.ruby-toolbox.com/categories/Active_Record_Soft_Delete) to achieve it.
