### ISSUE TITLE
upgrading from 0.6.0 to 0.6.2 left my site unprotected

### ISSUE THREAD

**Issue by vitaly** [sferik/rails_admin#1977]
from what I can see

    DEFAULT_AUTHENTICATION = Proc.new do
      request.env['warden'].try(:authenticate!)
    end

was changed to

    DEFAULT_AUTHENTICATION = proc {}

which means that if you didn't manually change `authenticate_with` in your `rails_admin.rb` initialiser, your application admin will no longer be protected when upgrading from 0.6.0 to 0.6.2

`!@#!@#!@#`

**Comment by mshibuya** [comment]
We're sorry, will make sure letting users know about possibly unsafe changes.
