### ISSUE TITLE
Associations break Edit view unless fields are specified

### ISSUE THREAD

**Issue by twler** [sferik/rails_admin#1978]
Since upgrading to Rails 4 (though possibly before as well), I've found that associations (`has_many`, `belongs_to`, etc) break my ability to edit within rails_admin.  The error thrown is:

    NoMethodError in RailsAdmin::Main#edit

    Showing /<path>/gems/rails_admin-0.6.1/app/views/rails_admin/main/_form_filtering_multiselect.html.haml where line #47 raised:
    undefined method `i18n_key' for nil:NilClass

    Extracted source (around line #47):
    = link_to "<i class=\"icon-plus icon-white\"></i> ".html_safe + wording_for(:link, :new, config.abstract_model), '#', :data => { :link => new_path(path_hash) }, :class => "create btn btn-info", :style => 'margin-left:10px'

If I comment out the associations, the edit page loads and operates just fine.

As a workaround, I've found that explicitly naming all of the included `field` variables for each model in `config/initializers/rails_admin.rb` avoids this problem, though I'm not entirely sure why.  For future migrations, it would be nice not to have to specify everything in the initializer explicitly.

**Comment by mshibuya** [comment]
Thought to be fixed by 10655cbfe972a2972b6580175f8be7fe2e20572c.
