### ISSUE TITLE
Can rails_admin manages db through restful apis instead of ORM ?

### ISSUE THREAD

**Issue by haozeng** [sferik/rails_admin#1979]
I haven't not worked on rails_admin before and want to ask this noob ques.
I am trying to build a admin app which does not rely on any ORM, it is going to manage a db through its restful apis. Image having a core restful apis are available. Can this be done using rails_admin ? I think a lot of customized works need to be done.

**Comment by mshibuya** [comment]
No, but ActiveResource adaper(proposed in #1377) will handle it, hopefully.
