### ISSUE TITLE
Circular dependency detected

### ISSUE THREAD

**Issue by hopewise** [sferik/rails_admin#1981]
I've installed the gem, 

    mount RailsAdmin::Engine, :at => '/admin'

But when I try to visit http://lvh.me:3000/admin I get this error:

RuntimeError in RailsAdmin::MainController#dashboard
Circular dependency detected while autoloading constant ActiveRecord::AddResetPkSequenceToBase

Any idea?

**Comment by beechnut** [comment]
I am having the same problem, but only in production, a year later.

**Comment by mshibuya** [comment]
This is usually caused by improper namespacing of modules.
See the discussion in #1697.
