### ISSUE TITLE
Deleting objects with HABTM associations causes crash in Rails 4.1.1

### ISSUE THREAD

**Issue by davefp** [sferik/rails_admin#1984]
## Steps to reproduce:
1. [Clone this repo](https://github.com/davefp/admin_test), bundle it, migrate, and start it up. It contains a dummy Rails 4.1.1 app with rails_admin installed and two models with a HABTM relationship (taken from [the HABTM section](http://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association) of Rails Guides)
2. Navigate to the admin (i.e. localhost:3000/admin) and create a single Part object.
3. Try to delete the Part you just created.
## Expected Outcome:

Admin should show the 'are you sure' page with a list of associated objects that might be deleted
## Actual Outcome:

Error thrown:

```
undefined method `parts_assemblies' for #<Part:0x007f93b9dd1400>`
```

Full stack trace here: https://gist.github.com/davefp/8bd2947172c9fb5dbd83

**Comment by mshibuya** [comment]
Rails 4 support was dropped now.
