### ISSUE TITLE
"Last Used" is empty

### ISSUE THREAD

**Issue by srivathsapv** [sferik/rails_admin#1986]
The "Last Used" column in the dashboard table is empty. Is there any configuration that needs to be done? If so its not specified in the wiki documentation.

**Comment by mshibuya** [comment]
`updated_at` column is needed, please refer to the implementation:
https://github.com/sferik/rails_admin/blob/77116d948c869f3c8be2f5048511fc28902a16cf/lib/rails_admin/config/actions/dashboard.rb#L30
