### ISSUE TITLE
Delegate a belongs_to on model's column fail

### ISSUE THREAD

**Issue by gdurelle** [sferik/rails_admin#1987]
I have a 
```ruby
delegate :some_field, to: :some_model
belongs_to :parent_model
```
fails when I try to load admin's model's list. 

I tryed to exclude_fields :the_column but does'nt fix it.
```
MyModel#the_column delegated to parent_model.the_column, but parent_model is nil
```

NB: also had the issue with an ```after_initialize :add_default_values``` and fixed it with dirty ```if parent_model.present? ```. Guess RailsAdmin initialize models on index views...

Any way to get arround the delegate issue ?

**Comment by mshibuya** [comment]
Just provide `allow_nil: true` to the delegate.
