### ISSUE TITLE
show history pagination

### ISSUE THREAD

**Issue by nicolasfranck** [sferik/rails_admin#1988]
It is possible to page manually through history,
by use of the parameter "page".

But the bootstrap pager is not created.

This has probably something todo with this:
```
- unless params[:all] || !@history.respond_to?(:current_page)

  = paginate(@history, :theme => 'twitter-bootstrap', :remote => true)
  = link_to(t("admin.misc.show_all"), send(path_method, params.merge(:all => true)), :class => "show-all btn pjax") unless (tc = @history.total_count) <= @history.size || tc > 100
```

I see in history_index.rb that the auditing_adapter fetches an array,
instead of an ActiveRecord::Relation, that has the method "current_page".

Is this normal behaviour?

**Comment by mshibuya** [comment]
Merging into #1599.
