### ISSUE TITLE
Rails admin should not look up for object params in params hash.

### ISSUE THREAD

**Issue by dpisarewski** [sferik/rails_admin#1992]
I get following error on https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/new.rb#L26:

"no implicit conversion of String into Hash"

It happens because my model name is "Action", so it looks up in params hash for action and gets "new" returned. Model name should not conflict with rails_admin's internal parameters.

**Comment by krishan1390** [comment]
Same here. Please tell me this has been sorted or if there is a suitable workaround

**Comment by SuperMasterBlasterLaser** [comment]
My model name is Action. This happens to me too

**Comment by mshibuya** [comment]
Merging this into #2329.
