### ISSUE TITLE
Rails 4.1 enum support

### ISSUE THREAD

**Issue by dmilisic** [sferik/rails_admin#1993]
[Rails 4.1 introduced enum attributes](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) which don't behave well with RailsAdmin. 

RailsAdmin (v 0.6.2) threats enum attributes as integers by default. This can be "fixed" by adding method to the model, ie.

    enum status: [ :active, :archived ]
    def status_enum
      self.class.statuses.to_a
    end

There is another issue - creating or updating record raises:

    ArgumentError in RailsAdmin::MainController#new 
    '1' is not a valid state

Obviously the controller got `'1'` as a string value which doesn't match any of the states (`'active'`, `'archived'`), nor state as integer (`0`, `1`).
The quick fix might look like:

    def status= value
      if value.kind_of?(String) and value.to_i.to_s == value
        super value.to_i
      else
        super value
      end
    end

It works, but isn't nice. Especially when you have multiple enum attributes.

Looking forward to support for `ActiveRecord::Enum` out of the box.

**Comment by jacekgrzybowski** [comment]
Is there a fix for enum filtering? I use version `0.6.5` and when I attempt to filter by enum column `rails_admin` queries for the actual name of the status instead of integer.

**Comment by Sacristan** [comment]
I wonder if this will be implemented in Rails admin anytime soon

**Comment by almozavr** [comment]
To add localization (default attribute path translation) support, change getter method definition to
```ruby
define_method("#{ name }_enum") {
  self.class.send(name.to_s.pluralize).to_a.map do |k, v|
    translated = I18n.t(k, scope: [:activerecord, :attributes, self.class.to_s.downcase, name.to_s.pluralize])
    processed_key = translated.include?('translation missing') ? k : translated
    [processed_key, v]
  end
}
```

**Comment by dgobaud** [comment]
searching still seems broken even with the monkey patch

PG::InvalidTextRepresentation: ERROR: invalid input syntax for integer: "hunter" LINE 1: ...".* FROM "orders" WHERE ((orders.shift_window IN ('hunter'))... ^ : SELECT "orders".* FROM "orders" WHERE ((orders.shift_window IN ('hunter')) OR ....

shift_window is an enum

**Comment by siegfried** [comment]
@kenchung @fstephany did you get any luck? Same problem here.

**Comment by dgobaud** [comment]
no :(

**Comment by dmilisic** [comment]
@dgobaud you could disble search for that filed (in config/initializers/rails_admin.rb):

    config.model 'Order' do
      configure :shift_window do
        queryable false
      end
    end

**Comment by dgobaud** [comment]
@dmilisic thanks that is what I'm currently doing but I would like search to work ideally

**Comment by mshibuya** [comment]
Done :star2:

**Comment by dgobaud** [comment]
awesome thanks!

**Comment by dgobaud** [comment]
this is still happening in 0.7.0

**Comment by dgobaud** [comment]
never mind it was the old monkey patch causing the problem. removed it and now search seems to work

**Comment by onlyyouandty** [comment]
This is still happening in 1.1.1. Any fix?

**Comment by jeremymarc** [comment]
+1

**Comment by dotdidi** [comment]
@onlyyouandty I also did experience the error in 1.1.1 but solve it by changing the data type of the enum from integer to string. Hope that helps

**Comment by onlyyouandty** [comment]
@dotdidi Enum can only be integer values. If you change it to string, the values won't get stored when you try to fill the form because enum calls in integer like [0, 1, 2]. Have you tried it?

**Comment by dotdidi** [comment]
@onlyyouandty not necesarilty in rails admin
```Ruby
class ReunionRecord

   def graduating_year_enum
      (1950...Date.today.year)
   end

   def class_enum
      ['Regular', 'International', 'Express']

   rails_admin do
      list do

         field :name do
            filterable true
         end

         field :graduating_year do
            filterable true
         end

         field :class do
            filterable true
         end
```
I put the graduating_year and class as :string and the enum works without any errors

**Comment by onlyyouandty** [comment]
You are actually right, based on https://github.com/rails/rails/pull/12747, enum could be string like you said. I will have to figure out why it is not saving as string type in my own case.

**Comment by tinbka** [comment]
It still doesn't work. Having

```ruby
class A < ApplicationRecord
  enum status: %w(a b c)
  rails_admin do
    list do
      field :status, :enum do
        enum {%w(a b c)}
        filterable true
      end
    end
  end
  
  def status_enum
    %w(a b c)
  end
end
```

(substitute `%w(a b c)` with `{a: 0, b: 1, c: 2}`, no difference)

`/a?model_name=a&utf8=✓&f%5Bstatus%5D%5B56339%5D%5Bv%5D=c`

leads to such a query

```sql
SELECT  "as".* FROM "as" WHERE ((as.status IN ('c'))) ORDER BY as.id desc LIMIT $3 OFFSET $4  [["LIMIT", 60], ["OFFSET", 0]]
```

that fails because `as.status` is an **integer field**.

**Comment by tolgap** [comment]
I'd say filtering on an enum is one of the strongest things you can do. Disabling filtering on an enum or "status" field is the worst thing I can do in my interface.

Is there a known workaround by now for having both edit support and filter support for enums?

**Comment by tinbka** [comment]
@tolgap isn't it fixed yet? I've seen the note in the changelog that it was done in 1.3.0 by https://github.com/sferik/rails_admin/pull/2971

**Comment by AlexMcConnell** [comment]
My godawful hacky solution for v0.8.1:

rails_admin.rb
```
RailsAdmin::ApplicationController.class_eval do
  before_action :fix_filters

  def fix_filters
    <code to change params how you need to make them work right>
  end
end
```
