### ISSUE TITLE
Problem with assets precompile on production

### ISSUE THREAD

**Issue by ilyadoroshin** [sferik/rails_admin#1994]
Hey, guys!

`$ RAILS_ENV=production bundle exec rake assets:precompile` gives  `Sass::SyntaxError: File to import not found or unreadable: font-awesome.`

What's wrong? Do I need to add `//= require font-awesome` somewhere or what?
Thanks.

**Comment by vemv** [comment]
@ilyadoroshin thanks for indicating the fix, you just saved me what previsibly would have been a long debugging session.

**Comment by vemv** [comment]
@sferik is this fix safe to commit? It worked in May 2014, it works today. Would be an absolute pity having to fork rails_admin for such a trivial difference.

**Comment by vemv** [comment]
Actually, while `font-awesome.css` stops the error from happening, it results in the asset not being loaded.

A more correct fix is `../font-awesome.css` - prevents the error, and the asset **will** be found/loaded!

**Comment by ilyadoroshin** [comment]
@vemv cool, thanks!

**Comment by redconfetti** [comment]
I ran into this issue myself, but couldn't reproduce it on a fresh Rails application. It turns out I just needed to force bundler to update Sass-Rails from v5.0.1 to v5.0.4 using `bundle update`.

```
$ bundle update sass-rails
...
Installing sass-rails 5.0.4 (was 5.0.1)
...
```

This also caused sass v3.4.9 to update to 3.4.21.
