### ISSUE TITLE
Assets - ui.js not loaded on Production Env (Heroku)

### ISSUE THREAD

**Issue by Florian95** [sferik/rails_admin#1995]
Hello,

I created "app/assets/javascripts/rails_admin/custom/ui.js.coffee"

I add on my env file :   config.assets.precompile += ['rails_admin/rails_admin.css', 'rails_admin/rails_admin.js']
Env file : http://pastie.org/private/ey74sale21xc6yek8sdqq
My public/assets is not commited.
rake assets:precompile works perfectly.

But, on my final rails_admin.js no sign of my ui.js. Any modification is not on my production env.

My versions :
- Rails_admin 0.6.2
- Rails 4.1.0
- Ruby 2.1.1

It works on my development environment.

Thank you,

**Comment by walidvb** [comment]
I couldn't get this to work, am i missing anything?

code is here: https://github.com/walidvb/festor

**Comment by mshibuya** [comment]
I think it might be related to caching, deleting asset cache might work.
