### ISSUE TITLE
Module from '/lib' is not being autoloaded

### ISSUE THREAD

**Issue by timurkhafizov** [sferik/rails_admin#1998]
I've got model:
```ruby
class Domain < ActiveRecord::Base
  include ::UrlHelpers

  ...
end
```

And module placed inside `lib` folder:
```ruby
module UrlHelpers
  def foo
    'bar'
  end
end
```

Also I've got initializer which requires all files in `lib` folder:
`Dir[Rails.root.join('lib/*.rb')].each { |f| require(f) }`

When I start the server I see this:
`[RailsAdmin] Could not load model Domain, assuming model is non existing. (uninitialized constant UrlHelpers)`

I can work with model and it's instances while in main app, but can not see it in RailsAdmin backend.

Please advise.

**Comment by mshibuya** [comment]
Make sure that your 'require' initializer is loaded before RailsAdmin's.
