### ISSUE TITLE
Broken integration with Paper Trail V 3.0.2

### ISSUE THREAD

**Issue by mesbahmilad** [sferik/rails_admin#1999]
The new version of paper train does not work with rails admin.

When accessing model that has paper trail through rails admin the following error is returned;

undefined method `version_class_name'

Refrence:

https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/has_paper_trail.rb

line: 64

**Comment by mshibuya** [comment]
Please update RailsAdmin and see if this still occurs.
