### ISSUE TITLE
?locale=xx is passed on every request, but the locale is at the beginning of the url already

### ISSUE THREAD

**Issue by jmuheim** [sferik/rails_admin#2000]
My routes look like this:

``` ruby
Base::Application.routes.draw do
  scope '(:locale)', locale: /en|de/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # ...
```

The locale is correctly used in Rails Admin, but the generated links all have a `?request=xx` parameter appended to the URL:

![image](https://cloud.githubusercontent.com/assets/1814983/3165586/4420539e-eb56-11e3-862c-c5f570c285ff.png)

![image](https://cloud.githubusercontent.com/assets/1814983/3165591/4e06971a-eb56-11e3-9a28-b8f33516bb18.png)

The `locale` parameter doesn't have any effect, though.

What's going wrong here?

**Comment by LucasAU** [comment]
I've just come across the same thing (in version 0.6.6). It does no harm, just an irritation.

I do not see the `locale` param just in the navigation, it appears to be on all the links - e.g. the model link in the dashboard, the List, Add new, and export tabs in the List of _X_ view.

**Comment by blijblijblij** [comment]
I just had a quick look with `1.4.1` and see 

<img width="238" alt="screenshot 2018-09-17 17 01 47" src="https://user-images.githubusercontent.com/1648248/45631575-75920080-ba9b-11e8-9521-8abade79594c.png">

`X-PJAX-URL: /nl/admin/topper_type?_pjax=%5Bdata-pjax-container%5D`

So I would assume case closed @mshibuya ?
