### ISSUE TITLE
Bootstrap 3 and Rails 3.x dependency

### ISSUE THREAD

**Issue by amseledka** [sferik/rails_admin#2006]
After Bootstrap 3 support was added (https://github.com/sferik/rails_admin/issues/1716), rails dependency updated to v4.0, so at the moment there's no way to use Bootstrap 3 with rails_admin on rails v3.x (https://github.com/sferik/rails_admin/pull/1799#issuecomment-30055299, but e.g. this solution leaves FontAwesome 3, not the last version)

Add rails 3.x support to rails_admin with Bootstrap 3, FontAwesome 4

**Comment by mshibuya** [comment]
We no longer actively maintain rails-3.x branch.
If you need that, please submit PR.
