### ISSUE TITLE
NoMethodError in RailsAdmin::Main#edit - undefined method `inline_add' for RailsAdmin::Config::Fields::Types::String

### ISSUE THREAD

**Issue by TheLarkInn** [sferik/rails_admin#2017]
Hi all, I'm popping across an error that is happening once in awhile when I load any model or view in rails admin. 

The workaround to the issue is to reload, and the error will go away. It seems to pop up every other reload of the page.

Any insight? I looked through issues but didn't see anything that corresponded to this issue.

![screen shot 2014-07-02 at 9 01 28 am](https://cloud.githubusercontent.com/assets/3408176/3456743/c1125774-01f1-11e4-819d-072e226e7336.png)

**Comment by mshibuya** [comment]
Looks like you got something wrong in RailsAdmin configuration(marking non-association field as an association or so).
