### ISSUE TITLE
Records not being populated when implementing ordered associations

### ISSUE THREAD

**Issue by eanlain** [sferik/rails_admin#2036]
I have two models, Recipe and Class that both use a has_many :through association. I was able to successfully set up the Class model to use ordered associated, using a position field in the ClassRecipe linkling model (as outlined in the [wiki](https://github.com/sferik/rails_admin/wiki/Associations-basics)). **In a production environment the list of all recipes does not populate.**

In development, when editing a class I'm able to see both the list of all recipes and a list of recipes associated with that particular class.
![screen shot 2014-08-06 at 10 26 08 am](https://cloud.githubusercontent.com/assets/3578866/3829172/2456875e-1d7e-11e4-83b6-4d3d1de6cdcd.png)

In production, when editing a class the full list of recipes does not populate... I do see the list of recipes already associated with a class.
![screen shot 2014-08-06 at 9 53 35 am](https://cloud.githubusercontent.com/assets/3578866/3829187/4702d5e6-1d7e-11e4-9a3d-84c42c669ef3.png)

If I type something in the filter box some entries for the recipes will pop up in the left hand box.
#### Recipes

``` ruby
has_many :class_recipes, :dependent => :destroy
has_many :claases, through: :class_recipes
```
#### ClassRecipe

``` ruby
belongs_to :class
belongs_to :recipe
```
#### Class

``` ruby
has_many :class_recipes, :dependent => :destroy
has_many :recipes, through: :class_recipes
```

I'm using Rails 4.1.4 and RailsAdmin 0.6.2.

Any thoughts?

**Comment by mshibuya** [comment]
That's what happens with `associated_collection_cache_all false`.
