### ISSUE TITLE
mess in bootstrap-sass' html5 invalid states

### ISSUE THREAD

**Issue by johanneskrtek** [sferik/rails_admin#2037]
in `rails_admin/app/assets/stylesheets/rails_admin/bootstrap/_forms.scss` there seems to be a messy chunk of code at the lines 376 – 378. as bootstrap 2.3.2.2 is no longer maintained it might be a good idea to clean up this part in rails_admin.

at the moment line 373 could be removed without any effective change. or better, instead of using `:focus` for css scoring `body input:invalid, body textarea:invalid, body select:invalid` would be more feasible as it would still be generic but provides two :invalid states, :invalid and :invalid:focus (which i guess these lines are all about).

in any case the `input:focus:invalid:focus` selector doesn't make any sense but has somehow found its way into bootstrap-sass (i could not find the html5 invalid states part in the original boostrap less files).

the current chunk:

    // HTML5 invalid states
    // Shares styles with the .control-group.error above
    input:focus:invalid,
    textarea:focus:invalid,
    select:focus:invalid {
      color: #b94a48;
      border-color: #ee5f5b;
      &:focus {
        border-color: darken(#ee5f5b, 10%);
        @include box-shadow(0 0 6px lighten(#ee5f5b, 20%));
      }
    }

i would propose to go with the `body` selector for scoring, shall i provide a pull request?

**Comment by mshibuya** [comment]
No longer the case, because of migration to Bootstrap 3(#2059).
