### ISSUE TITLE
how to reload filtering-select component with ajax?

### ISSUE THREAD

**Issue by jorgeramos** [sferik/rails_admin#2044]
Using the following Mongoid documents:

```ruby
class Reservation
  include Mongoid::Document
  
  belongs_to :agency
  belongs_to :blocked_seat
end 

class BlockedSeat
  include Mongoid::Document
  
  field :date, type: Date
  belongs_to :agency
end
```

I would like to populate the reservation's blocked_seat field with a scoped query based on the selected agency so that only the ones that belong to that agency are listed. The blocked_seat field needs to be re-populated every time the agency field changes. I'm already listening for the agency change event with javascript and know the id of the selected agency document. How would I go about re-populating the available blocked_seats and then validating to make sure a blocked_seat is selected if the list contains any values?

I would also like to be able to add a datepicker and filter the blocked_seats based on Agency and the selected date.

I am assuming I will have to perform some AJAX calls and repopulate the components accordingly. Any pointers would be greatly appreciated.

**Comment by angelicarosa-spindox** [comment]
Close without a comment... sooooo useful.

**Comment by jorgeramos** [comment]
Hello, apologies for not having made comments when I closed this issue. It’s been such a long time that I don’t even recall the solution if I ever got one. Either way, the ui world has evolved tremendously since then and I would recommend you look for modern admin solutions perhaps built on angular or react. Either way, best of luck to you.
