### ISSUE TITLE
custom layout

### ISSUE THREAD

**Issue by masscrx** [sferik/rails_admin#2063]
Is it possible to change whole layout of rails_admin ? I've found many information about changing fields, label etc, but I'cant find how to change for example class of navigation elements, or how to make dropdown navigation (root model and after hover list with childrens - I've found some code for older version but it doesnt work in the newest). In the newest version is variable 'main_navigation' with generated ul > li elements, and I would like to customize it.

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
