### ISSUE TITLE
rails admin leave access to dashboard even for unauthenticated user

### ISSUE THREAD

**Issue by blset** [sferik/rails_admin#2092]
suppose /admin is the route to rails_admin,
suppose the access is restricted with devise and User class
and ability class and rails_admin configured in a standard way as explained in the docs

visiting the url www.site.com/adminssss you get access to the dashboard with an error message from rails_admin model ssss not found and an error message from devise unauthenticated user

Processing by RailsAdmin::MainController#index as HTML
  Parameters: {"model_name"=>"ssss"}
[RailsAdmin] Could not load model Ssss, assuming model is non existing. (uninitialized constant Ssss)

after that if you click anywhere on the dashboard you are redirected to the sign_in page but you saw the dashboard without being authenticated

visiting the exact url /admin redirects to the sing_in page

with rails_admin 0.6.0/ devise, cancan 1.6.10, devise 3.4.0

**Comment by mshibuya** [comment]
Check if authentication configuration is in place.
https://github.com/sferik/rails_admin/wiki/Authentication
