### ISSUE TITLE
PG::SyntaxError

### ISSUE THREAD

**Issue by eddiefisher** [sferik/rails_admin#2102]
PG::SyntaxError: ERROR: syntax error at or near "references" LINE 1: ...LECT "references".* FROM "references" ORDER BY references... ^ : SELECT "references".* FROM "references" ORDER BY references.updated_at desc LIMIT 1

not working
```SELECT "references".* FROM "references" ORDER BY references.updated_at desc LIMIT 1```
working
```SELECT "references".* FROM "references" ORDER BY "references".updated_at desc LIMIT 1```

**Comment by mshibuya** [comment]
Dup of #1631.
