### ISSUE TITLE
The label for a has many association should be a link to a filtered list view

### ISSUE THREAD

**Issue by yournotokay** [sferik/rails_admin#2122]
A very useful feature for our team is if a user clicks the label of a has many relation, it should bring up the list view of the associated model filtered by the foreign key. The user can then filter, sort or view attributes of the related models.

eg. If Author 1 has many Posts. If you click the Posts it takes you to the Post List View and puts a filter for Author is exactly 1.

I was able to make this work decently well locally with the following but was unsure how to limit it to just the show view:

``` ruby
RailsAdmin::Config::Fields::Types::HasManyAssociation.register_instance_option :label do
  (@label ||= {})[::I18n.locale] ||= abstract_model.model.human_attribute_name association.name
  begin
    bindings[:view].link_to(
      @label[::I18n.locale],
      bindings[:view].rails_admin.index_path(
        model_name: association.klass,
        query: '',
        f: {
          abstract_model.model_name.demodulize.underscore => {
            '1' => {
              o: 'is',
              v: bindings[:model].id
            }
          }
        },
        utf8: '✓'
      ),
      style: 'color:#FFFFFF;',
      class: 'pjax'
    )
  rescue
    @label
  end
end
```

**Comment by ouelletv** [comment]
+1

**Comment by mshibuya** [comment]
Please open a PR if anybody find this useful.
