### ISSUE TITLE
Rails 5 is removing `serialized_attributes` without replacement

### ISSUE THREAD

**Issue by carlesso** [sferik/rails_admin#2127]
Hey guys, just a hand up.

I'm building a project with Rails 4.2 and I'm having:

```
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from type at [cut]/lib/rails_admin/adapters/active_record/property.rb:21)
```

That come from [property.rb](https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/adapters/active_record/property.rb#L20-L26).

**Comment by mshibuya** [comment]
Already fixed by #2140.
