### ISSUE TITLE
How to create a bulk edit form for rails_admin ?

### ISSUE THREAD

**Issue by tmacbg** [sferik/rails_admin#2138]
Hello , I'm trying to create bulk edit form using the rails_admin form helper but this looks like "mission impossible"  for me :) . 
Did someone created that functionality ?
I've created custom action for mass update and started to build the form from scratch - but doesn't look the same with the edit form for single element . 
So my question is did someone build that functionality .

Best regards

**Comment by dmitrypol** [comment]
Any updates on this?

**Comment by tmacbg** [comment]
I've manage to do it with custom action and edit form helper that comes with rails_admin but it's very ugly story ...... but working :)
If you have only one table , not a relation like belongs_to or onetomany it's relatively easy : 
just add 
function in your controller 
Something like this
@objects.each do |object|
@objectToUpdate = Controller.find(object.id)
new_attributes = params.require(":model").permit(table colums that you want to bulk update)

 @objectToUpdate.update_attributes((new_attributes).reject { |k,v| v.blank? })
to reject the blank or the  empty values

Hope that helps

**Comment by dmitrypol** [comment]
Thanks.  Ideally I would like a search form where I can look for all users.first_name = 'bob' and last_name = 'smith' and update them all to something

**Comment by DuyH** [comment]
I've figured out how to get as far as creating a bulk_action to mass edit records for one field for a particular value. But what I really want is the ability to create a custom view in rails admin so I can select from an enum.

It would be great to have a guide of how Rail Admin's bulk delete's confirmation page is being generated because then I could use that as a template for creating my own custom view. Any leads?

**Comment by streetlogics** [comment]
I found this thread and ended up digging through the code to come up with an answer myself. So - here is my question + answer thread on Stackoverflow for anyone else that comes across this - https://stackoverflow.com/questions/57838401/how-do-i-create-a-custom-bulk-action-in-rails-admin/57838402
