### ISSUE TITLE
problems with work of papertrail gem for rails 4.2

### ISSUE THREAD

**Issue by kpblc** [sferik/rails_admin#2144]
hello!
papertrail list, shows something like #User:0x00000004a9df90 instead example_user@mail.com
problem appears after updating rails to 4.2. (rails 4.1.8 all works correctly)

P.S. i'll allready create an issue in papertrail repo https://github.com/airblade/paper_trail/issues/452

P.P.S. in screenshot 
#User:0x00000004a9df90 instead admin@mail.com it's for version rails 4.2. 
correct email showed, then i'll rollback rails to 4.1.8 

![89d85aca-8e13-11e4-8d02-8c53e43857a3](https://cloud.githubusercontent.com/assets/6714004/5567111/f71ca010-8f4d-11e4-892a-e7ccaed8d4a3.png)

**Comment by lognaturel** [comment]
It looks like there is a [pull request](https://github.com/sferik/rails_admin/pull/2187/files) out a fix.

For now, I'm monkey patching it in by putting the following code in `config/initializers/rails_admin_user_for_paper_trail.rb`:

    RailsAdmin::ApplicationController.module_eval do
      def user_for_paper_trail
        _current_user.try(:id) || _current_user
      end
    end

(suggestions for a more elegant alternative welcome!)

**Comment by bbenezech** [comment]
fixed/
