### ISSUE TITLE
No route matches [POST] "/sessions/admin_user"

### ISSUE THREAD

**Issue by vedant1811** [sferik/rails_admin#2147]
After I sign in (in the URL: `/admin_users/sign_in` ) I get this error:

    Routing Error
    No route matches [POST] "/sessions/admin_user"

I have only one Deivse User:

    class AdminUser < ActiveRecord::Base
      devise :database_authenticatable,
            :recoverable, :rememberable, :trackable, :validatable
    end

My `config/rails_admin.rb`:

    RailsAdmin.config do |config|
      ## == Devise ==
      config.authenticate_with do
        warden.authenticate! scope: :admin_user
      end
      config.current_user_method(&:current_admin_user)
      ...
    end

My `routes.rb`:

    Rails.application.routes.draw do

      devise_for :admin_users
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
      ...
    end

Also, if I keep active admin and I change my `routes.rb` to

Rails.application.routes.draw do

      devise_for :admin_users, ActiveAdmin::Devise.config
      ActiveAdmin.routes(self)
      mount RailsAdmin::Engine => '/newadmin', as: 'rails_admin'
    end

Everything, even the redirect back to /newadmin, works fine. I just have to login through a ActiveAdmin looking login screen. It means only the loggin in route isn't working. if the user is already loggen in, things work.

**Comment by mshibuya** [comment]
I guess something might be wrong with your devise setup.
If you could upload the app with minimal reproducible code, I can help you.
