### ISSUE TITLE
Checkboxes have incorrect css class

### ISSUE THREAD

**Issue by thechrisoshow** [sferik/rails_admin#2149]
With the latest rollout to bootstrap 3, the checkbox control has the .form-control added to it. Bootstrap intended these classes for text based inputs, so you end up with checkboxes that look like this:
![wonky checkbox](https://cloud.githubusercontent.com/assets/3727/5595655/c3655bb0-9270-11e4-9653-e412dc4c38b7.png)

One way around this could be to create a _form_field like partial specifically for Boolean types. e.g.
```
  = form.check_box field.method_name, field.html_attributes.reverse_merge({ checked: field.form_value.in?([true, '1'])})
```

..but I'm not sure if this would create any breaking changes

**Comment by bbenezech** [comment]
Thanks. This looks fixed somehow.
