### ISSUE TITLE
Updating model has_secure_password doesn't work with :password in :field

### ISSUE THREAD

**Issue by vedant1811** [sferik/rails_admin#2150]
I have a model that `has_secure_password`

I have defined the model as:

```
edit do
  ...
  field :password, :password
  field :password_confirmation, :password
end
```

But when I update (and leave the password field blank), I get the error "password cannot be blank"

but when I define my model as:

```
edit do
  ...
  field :password
  field :password_confirmation
end
```

it works as expected. The password is changed only if I enter something otherwise the model is updated without providing any password.

Obviously, the problem with this is that passwords are shown in clear text. Not a deal breaker but not what anyone would want either

**Comment by kuboon** [comment]
has_secure_password clears password_digest if you set nil to password.
```
> u.password = 'hoge'; u.password_digest
=> "$2a$10$xIQ.BpyUtXpU/sPguFhAw.vp9DQay99ggSlR8R9ICYKcW6J1Y7Qpu"
> u.password = ''; u.password_digest
=> "$2a$10$xIQ.BpyUtXpU/sPguFhAw.vp9DQay99ggSlR8R9ICYKcW6J1Y7Qpu"
> u.password = nil; u.password_digest
=> nil
```
Unfortunately, password type field in RailsAdmin is implemented like this;
```
          def parse_input(params)
            params[name] = params[name].presence
          end
```

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/commit/72bc03736162ffef8e5b99f42ca605d17fe7e7d0 solves this, too.
