### ISSUE TITLE
Index issue with MySQL and full UTF8 support.

### ISSUE THREAD

**Issue by dimaursu** [sferik/rails_admin#2153]
Due to limitations in MySQL, when switching to full UTF8 encoding (called `utf8mb4` in MySQL), we are unable to create a new index. 

The maximum column size is 767 bytes. Each character is 4 bytes long -> 767 / 4 = 191 characters for the column. 

We hit the limitation here: https://github.com/diaspora/diaspora/blob/develop/db/migrate/0000_create_schema.rb#L340 

Now, we can shorten in the index the `table` and `item` column to solve the issue (apart from changing the table encoding  the 3byte utf8 in MySQL). 

What do you think are good limits for that (tabel and item)? Do you have any other ideas how to mitigate the issue?

**Comment by mshibuya** [comment]
RailsAdmin can do nothing, ActiveRecord handles it.
See rails/rails#9855.

**Comment by dimaursu** [comment]
Thanks, we already solved the problem. It still has some hiccups, because it's hard to cover all edge cases, but it's working rather well.
