### ISSUE TITLE
Error: :en is not a valid locale

### ISSUE THREAD

**Issue by nazarok** [sferik/rails_admin#2155]
if I do not have in available_locales :en, I get an error:

Showing /home/user/.rvm/gems/ruby-2.2.0@project/gems/rails_admin-0.6.6/app/views/rails_admin/main/index.html.haml where line #78 raised:

:en is not a valid locale

This error occurs because the project multiple times specifying an explicit locale: :en.

**Comment by x-ji** [comment]
I also met this error. Is there any way to change the default locale used by railsadmin?

**Comment by emaciek** [comment]
@x-ji I was tired of looking for some good solution so I fixed it with workaround. So go to source code of the gem file like: /home/user/.rvm/gems/ruby-2.1.5/gems/rails_admin-0.6.7/app/views/rails_admin/main/index.html.haml and change :en into suitable translation. In your case it is 'zh-CN'. And it works.

**Comment by sasselin** [comment]
Same thing for me, the fix in https://github.com/sferik/rails_admin/wiki/Troubleshoot do not work.

My site is only in french.

**Comment by sasselin** [comment]
Finally I had to overwrite the file views/main/index.html.haml and change line 78 to put :fr instead of :en.

**Comment by dalpo** [comment]
Take a look also here: https://github.com/sferik/rails_admin/blob/dcb774d7a5629ae129436669f43be63adc455a49/lib/rails_admin/i18n_support.rb

**Comment by nazarok** [comment]
Thanks for this
