### ISSUE TITLE
Treeview List with parent method not work

### ISSUE THREAD

**Issue by fmh** [sferik/rails_admin#2162]
add parent method to model config in rails_admin has no effect

RA 0.6.6
Rails 4.2
example : 
````ruby
config.model 'Client' do
 parent Person
end

config.model 'Consultant' do
 parent Person
end

#navigation
Clients
Consultants
People 
``````

**Comment by mshibuya** [comment]
RailsAdmin doesn't have support for treeview list.
`parent` method is used for other purpose and passing an argument never makes sense.

**Comment by fmh** [comment]
this is what i found in wiki : https://github.com/sferik/rails_admin/wiki/Navigation

**Comment by mshibuya** [comment]
I'm sorry that I've overlooked things... :sweat:
Fixed in the latest master, so please give it a try!

**Comment by fmh** [comment]
good job :smile:
