### ISSUE TITLE
CSV - encoding - special characters

### ISSUE THREAD

**Issue by Preen** [sferik/rails_admin#2169]
When I export to csv I get funny characters for all my special characters when importing it to Excel. I have tried to change the encoding from utf-8 to iso-8859-1 but with no luck. How can I achieve ok characters?

I'm on MAC OSX 10.10.
rails_admin => 0.6.5
rails 4.1.6
ruby 2.1.4

**Comment by nunziofiore** [comment]
+1

**Comment by codealchemy** [comment]
@Preen @nunziofiore have you tried using something like [OpenOffice](http://www.openoffice.org/) and opening the csv as utf-8 (the default output for rails_admin)? I've found OpenOffice/[LibreOffice](https://www.libreoffice.org/) to be much more reliable when it comes to encodings/special characters in csvs.

**Comment by Preen** [comment]
@codealchemy  - It isn't an alternative when you have a client with office. But it works with Google Drive.

**Comment by codealchemy** [comment]
@Preen got it, though it looks to have been addressed in recent releases? Exporting to `Windows-1252` encoding in rails_admin 0.7.0 opens fine with special characters in Excel (on a Mac as well)

**Comment by bbenezech** [comment]
It should have been fixed meanwhile.
