### ISSUE TITLE
Sprockets::Rails::Helper::AssetFilteredError in RailsAdmin::Main#dashboard

### ISSUE THREAD

**Issue by Abdenasser** [sferik/rails_admin#2176]
i'm still facing this problem all the day , it tells me 
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( rails_admin/aristo/images/bg_fallback.png )` to `config/initializers/assets.rb` and restart your server

i'm still adding the lines and it still tell me to add other lines (line by line) it's the first time that happend to me with rails_admin

**Comment by stevenyap** [comment]
I have faced this issue too.
I have solved it by adding the following line to `/config/initializers/assets.rb`:

```ruby
Rails.application.config.assets.precompile += ['rails_admin/**/*', 'fontawesome-webfont.*']
```

Hope this helps you too!
