### ISSUE TITLE
Infinity loading of edit page with a lot of has many associations

### ISSUE THREAD

**Issue by meliborn** [sferik/rails_admin#2178]
Is there a way to split edit fields into two ajax tabs? I know about grouping, but it renders all fields on the page anyway.
As I understand, problem comes from _form_nested_many.html.haml file (it take a lot of time for render)

**Comment by mshibuya** [comment]
Are you using deeply nesting `accepts_nested_attributes_for`s?
If so, this might help:
https://github.com/sferik/rails_admin/wiki/Associations-basics#nested-form
