### ISSUE TITLE
Sidebar treeview list (since to 0.6.6)

### ISSUE THREAD

**Issue by rafaelgonzalez** [sferik/rails_admin#2179]
I just updated from `0.6.5` to `0.6.6` and noticed a cosmetic bug, more specifically the treeview list in the side bar.

See the screenshots below:

**0.6.5**

![screen shot 2015-01-30 at 12 10 40 pm](https://cloud.githubusercontent.com/assets/456921/5969524/14d4a67c-a879-11e4-9dfb-c2b0602686e2.png)

**0.6.6**

![screen shot 2015-01-30 at 12 01 18 pm](https://cloud.githubusercontent.com/assets/456921/5969510/ddea6110-a878-11e4-9692-d3a445385621.png)

I made no changes to the configuration, this is the default behaviour, because:

- `Enquiry` and `Subscription` are classes that inherit from `Engagement`
- `NexusHook` is a class that inherits from `Hook`

The [dedicated wiki](https://github.com/sferik/rails_admin/wiki/Navigation) page as not been updated since June 2014 so I can't tell if something has changed configuration wise.

Specifying `parent` for each model in the config does not change anything.

Also "Navigation" and "Links" seem a bit off.

Cheers.

**Comment by mshibuya** [comment]
Dup of #2162.
Please use the latest master until next gem release.

**Comment by rafaelgonzalez** [comment]
Awesome, thanks.

**Comment by ineu** [comment]
@mshibuya It's not only nesting which is broken. SIdebar looks different in general
0.6.5:
![before](https://cloud.githubusercontent.com/assets/24980/6060795/23d517dc-ad52-11e4-8462-31c3051ca3f0.jpg)
0.6.6 (and latest master):
![after](https://cloud.githubusercontent.com/assets/24980/6060797/29e214b8-ad52-11e4-8240-f3f5d67b5bc7.jpg)

**Comment by ineu** [comment]
So
1. 'Navigation' and 'Links' are styled differently
2. Items are shifted to the left
3. Bigger line-spacing
4. Some strange scrollbar
