### ISSUE TITLE
Modal Has Two Sets of Buttons

### ISSUE THREAD

**Issue by benhutton** [sferik/rails_admin#2181]
![image](https://cloud.githubusercontent.com/assets/61645/6006408/3df3b6ce-aae0-11e4-8554-ecc23cee8a96.png)

I believe that this line is supposed to remove the duplicate set of buttons: https://github.com/sferik/rails_admin/blob/master/app/assets/javascripts/rails_admin/ra.remote-form.js#L73

But https://github.com/sferik/rails_admin/commit/f6d660fae06e97852e61422520e18fb9064f51bd changed `.form-actions` to `.form-group`, which probably should not be removed quite so aggressively.

**Comment by rikkipitt** [comment]
Good shout. ```.form-actions``` isn't a class used in Bootstrap anymore, so perhaps we should leave it in on the _submit_buttons.html.erb partial. I've tested locally and it works fine.
