### ISSUE TITLE
embedded, namespaced models not showing

### ISSUE THREAD

**Issue by psugihara** [sferik/rails_admin#2186]
Having a bit of trouble over here.

In the following example, `Offer::PropertyInfo` does not show up in the rails_admin dashboard:

    class Offer
      include GlobalID::Identification
      include Mongoid::Document
      include Mongoid::Timestamps
    
      field :price, type: Integer
      field :funding_source, type: String
      field :name, type: String
      field :email, type: String
      field :phone, type: String
      field :phone_verified, type: Mongoid::Boolean, default: false
    
      embeds_one :property_info, class_name: "Offer::PropertyInfo"
    
      belongs_to :property
    end
    
    class Offer::PropertyInfo
      include Mongoid::Document
    
      field :street_name, type: String
      field :street_number, type: String
      field :unit_number, type: String
      field :city, type: String
      field :state, type: String
      field :zip, type: String
    
      embedded_in :offer
    end

![Not linked in the admin][1]

Any ideas why this isn't working? I tried putting Offer::PropertyInfo into models/offer/property_info.rb. I also tried adding it to `config.included_models` but no luck. Using mongoid 4.0.1.

Thanks!

  [1]: http://i.stack.imgur.com/GG11s.png

**Comment by mshibuya** [comment]
That's an expected behavior.
Embedded models are only accessible through parent model, so showing them in Dashboard or Left Navigation never makes sense(See 163da3e9).

**Comment by psugihara** [comment]
Thanks for the response.

What's the recommended way to inspect an embedded model's fields?

**Comment by mshibuya** [comment]
Use of `accepts_nested_attributes_for` will allow you to edit `Offer::PropertyInfo` within `Offer` edit form.
Working example is here:
https://github.com/sferik/rails_admin/blob/a24581d5386d9116745a5b584b25d4537487d5a6/spec/dummy_app/app/mongoid/nested_field_test.rb#L9-L12
