### ISSUE TITLE
Required fields block cancel of new form

### ISSUE THREAD

**Issue by soupmatt** [sferik/rails_admin#2190]
If you have a required field on your form and you haven't filled it out, and you click cancel, Chrome will block the form submission and tell you that the field is required. I'm using current master (which is 2f4fc32 as of this writing).

Environment
jruby 1.7 in 1.9 mode and mri 1.9.3
rails 4.1.9
rails_admin 2f4fc32 (0.6.6 is the current release when this commit is HEAD of master)

Browsers Tested:
Safari 8.0.3 on OSX 10.10.2
Chrome 40.0
Firefox 35.0.1

**Comment by soupmatt** [comment]
Perhaps some javascript to add the `novalidate` attribute to the form before submit would do the trick, or do the redirect away from the form in javascript. I'd be happy to do the fix and submit a pull request if you have an idea of how you would want to handle it.

**Comment by mshibuya** [comment]
Thanks for reporting!
