### ISSUE TITLE
export csv give me error unknown encoding name - latin1

### ISSUE THREAD

**Issue by nunziofiore** [sferik/rails_admin#2191]
indipendent from the columns I choose I have always this error:

error unknown encoding name - latin1

**Comment by nunziofiore** [comment]
error is at that line
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/support/csv_converter.rb#L38

**Comment by nunziofiore** [comment]
maybe if you add 'latin1' here

https://github.com/sferik/rails_admin/blob/c71e2d25bf17d5130ee822812d595ef97a1b02e2/lib/rails_admin/support/csv_converter.rb#L6

you can fix the desease

**Comment by nunziofiore** [comment]
ok i tested and in this way you can fix

https://github.com/nunziofiore/rails_admin/commit/0018bdd4bcd093ebc5ed80432395b07064f16318

I have no the right to make a pull request so let the issue open for you

**Comment by ekkans** [comment]
Hi – thanks @nunziofiore!

I have the same problem. Meanwhile it's fixed in the main repo, it's possible to write the following code in ./config/initializers/rails_admin.rb for example

```
module RailsAdmin
  class CSVConverter
    remove_const(:UTF8_ENCODINGS) if (defined?(UTF8_ENCODINGS))
    UTF8_ENCODINGS = [nil, '', 'utf8', 'utf-8', 'unicode', 'UTF8', 'UTF-8', 'UNICODE', 'utf8mb4', 'latin1']
  end
end
```

**Comment by iMacTia** [comment]
Same problem here! Thanks @ekkans! Can't believe this hasn't been fixed yet.
If rails_admin requires particular DB encoding, just let us know...

**Comment by tagliala** [comment]
Hi,

I also run into this issue

Unfortunately `latin1` is not unicode, so adding it to `UTF8_ENCODINGS` is not a solution.

As per https://it.wikipedia.org/wiki/ISO/IEC_8859-1, `latin1` should map to `ISO-8859-1`

**Comment by pamio** [comment]
@ekkans I had the same issue and your workaround fixed it form. However, is it not fixed in the main branch yet ?

**Comment by tagliala** [comment]
Not yet merged, please give a try to my branch:

```rb
gem 'rails_admin', github: 'diowa/rails_admin', branch: 'encoding-fix'
```
