### ISSUE TITLE
undefined method `primary' for #<ActiveRecord::ConnectionAdapters::Column:0x007f444dace278>

### ISSUE THREAD

**Issue by spawnge** [sferik/rails_admin#2192]
I have just updated from rails 4.1.5 to 4.2 and now I have the following error when I try to access the http://localhost:3000/admin/user page: 
`undefined method 'primary' for #<ActiveRecord::ConnectionAdapters::Column:0x007f444dace278>`

Is something wrong with this?
```
def serial?
  property.primary
end
```
I've searched for an answer and found this, which might help but I'm not sure: https://github.com/voormedia/rails-erd/issues/85 and https://github.com/ready4god2513/rails-erd/compare/rails-4.2-support-fix

Thanks in advance for your answers

**Comment by mshibuya** [comment]
This issue was fixed by acfe96dc, so upgrading RailsAdmin to >= 0.6.4 will work.
