### ISSUE TITLE
How to hide custom action from collection view?

### ISSUE THREAD

**Issue by kangguru** [sferik/rails_admin#2193]
I'm trying to hide a custom action from models collection/index view. I've already tried plenty variation of

```ruby
        register_instance_option :member? do
          true
        end
```

or 

```ruby
        register_instance_option :collection? do
          false
        end
```

with `?` at the end, without (as the internet is not really specific about it)

Then i found out about member actions

```ruby

member :verify_person

```
This won't have an effect, besides making the action to loose its icon and falling back to `?`

Do i have to use the `visibility`-option? How to access the current action then? It looks like it just gives me the `controller`

What am i doing wrong? Help is really appreciated!

**Comment by rikkipitt** [comment]
It's ```visible?```

E.g.

```ruby
register_instance_option :visible? do
  current_model = ::RailsAdmin::Config.model(bindings[:abstract_model])
  authorized? && current_model.drafts && bindings[:object].draft?
end
```

Another example [here](https://github.com/dalpo/rails_admin_nestable/blob/master/lib/rails_admin_nestable/nestable.rb).

Docs that might help are on the [rails_admin wiki here](https://github.com/sferik/rails_admin/wiki/Actions#action-visibility-and-bindings).

**Comment by rakvium** [comment]
@kangguru, @rikkipitt, so, to remove the custom action button from the list views, it's okay to do something like this, right?:
```
register_instance_option :visible? do
  # do not show the button on list
  authorized? && bindings[:controller].request.params[:action] != 'index'
end
```
