### ISSUE TITLE
STI Models not showing up in list on edit view

### ISSUE THREAD

**Issue by Swistaku** [sferik/rails_admin#2195]
Hey guys,

I have a subject model which has many details

``` ruby
class Subject < ActiveRecord::Base
  has_many :details, inverse_of: :main_subject, foreign_key: :main_subject_id
end
```

``` ruby
class Detail
  TYPES = %w(article book event product short_course slide_share video website).freeze
  CLASS_TYPES = TYPES.map { |type| "Detail::#{type.camelize}" }.freeze

  belongs_to :main_subject, inverse_of: :details, class_name: Subject
end
```

There are multiple type of details available in application so I have

``` ruby
class Detail::Article < Detail; end
class Detail::Website < Detail; end
class Detail::Video < Detail; end
```

And when I go to edit Subject panel my list for details is empty (the right one with assigned details correctly shows all associated details), and I cannot find a way to make rails_admin fill it with all available details. I've checked on the wiki, and checked issues here, but cannot find any viable solution. Is it rails_admin bug that it doesn't show up STI models in these list or am I missing some kind of config? Thanks in advance for any help :)

![screen shot 2015-02-20 at 09 16 46](https://cloud.githubusercontent.com/assets/640241/6283551/6581c56e-b8e6-11e4-9569-4bce580629df.png)

_the list on the left is empty despite over 200 details available in db, the right one shows nothing because nothing is associated (I've removed associated details, and reloaded page - now cannot even bring those back)_

**Comment by Swistaku** [comment]
With some help from stackoverflow I've found what caused the problem ->

In detail.rb I have enum for difficulty

`enum difficulty: { easy: 1, medium: 2, hard: 3 }`

and when I was typing anything in search field rails_admin was inserting this value into query causing problems -> http://paste.ubuntu.com/10321369/

Don't know if it counts as a bug, if not, please close this issue.

Full discussion is available on the stackoverflow
http://stackoverflow.com/questions/28624886/rails-admin-sti-models-not-showing-up-in-list-on-edit-view

**Comment by dalpo** [comment]
I'm having the same issue

**Comment by mshibuya** [comment]
Merging into #1114.
