### ISSUE TITLE
theming.css.scss seems to be skipped on Heroku

### ISSUE THREAD

**Issue by artemaminov** [sferik/rails_admin#2196]
I've Rails 4.2 application. How to force Heroku's asset pipeline to catch

```
app/assets/stylesheets/rails_admin/custom/theming.css.scss
```

Gemfile includes

```
gem 'rails_12factor', group: :production
```

initializers/assets.rb

```
#tried with and without this line
Rails.application.config.assets.paths << "#{Rails.root}/app/assets/stylesheets/rails_admin/custom" 

Rails.application.config.assets.precompile += ['rails_admin/rails_admin.css', 'rails_admin/rails_admin.js']
```

application.css DOESN'T have any references to theming.css.scss file. I mean there is no

```
require_tree .
require_directory rails_admin
```

So what do I missed?

**Comment by sbull** [comment]
Be sure you've read https://github.com/sferik/rails_admin/wiki/Theming-and-customization, and the referenced issue https://github.com/sferik/rails_admin/issues/738. particularly https://github.com/sferik/rails_admin/issues/738#issuecomment-51494198. My guess is that bumping the `Rails.application.config.assets.version` might do the trick.

**Comment by mshibuya** [comment]
Try https://github.com/sferik/rails_admin/issues/1995#issuecomment-494706399.
