### ISSUE TITLE
url_helpers are broken on rails 4.0.4

### ISSUE THREAD

**Issue by walidvb** [sferik/rails_admin#2200]
Couldn't find this as an issue anywhere in here, hopefully it's not a double post.

When I add  `include RailsAdmin::Engine.routes.url_helpers` to `application_helper.rb`, i can't use the standard url_helpers in views, such as `events_path`. The error returned is:

`
No route matches {:action=>"index", :controller=>"events", :locale=>"en"} missing required keys: []
`

I'm using rails 4.0.4, and you can see the whole config [here](https://github.com/walidvb/festor/tree/47dea9ef3ea12df0bcf2997cc9ac947693203c4e)

**Comment by mshibuya** [comment]
Don't do `include RailsAdmin::Engine.routes.url_helpers`.
If you want to get RailsAdmin path in your app, you can use `rails_admin.dashboard_path`.
http://stackoverflow.com/a/9178022/1418867
