### ISSUE TITLE
query with lowercases of column names

### ISSUE THREAD

**Issue by cs0511** [sferik/rails_admin#2202]
Hi sferik @sferik 

I am using rails_admin in my app. For some reasons we have some columns named 'humanId' and 'accessToken' which was named with CamelCase.

But in your gem, the query will always use lowercase like

```
ILIKE '%song%') OR (LOWER(users.humanId) ILIKE '%song%') OR (LOWER(users.accessToken) ILIKE '%song%') OR (LOWER(users.publicToken) ILIKE '%song%') OR (LOWER(users.avatar_file_name) ILIKE '%song%') OR 
```

Which will case errors?

Could I skip this LOWER function without changing the column name to SnakeCase.

Thank you.

**Comment by mshibuya** [comment]
Dup of #1281.
