### ISSUE TITLE
nested forms are not indented properly since upgrade to Bootstrap3

### ISSUE THREAD

**Issue by cec** [sferik/rails_admin#2205]
Hi,

upgrading from 0.4.9 to 0.6.6 I noticed that nested forms are not indented properly (see picture 1).

I have worked on my RA fork, found the lines causing the issue and solved the problem (see picture 2). 

I'm making a pull request in a few moments so that you guys can review these changes and let me know if I should modify this or if it can be merged.
 
Cheers,
cec

![picture1](https://cloud.githubusercontent.com/assets/386155/6529074/8bde1564-c426-11e4-8484-7c9031840e0d.jpg)
![picture2](https://cloud.githubusercontent.com/assets/386155/6529075/8be11db8-c426-11e4-82f4-9234fc8517d7.jpg)

**Comment by rikkipitt** [comment]
I've not tested this PR yet, but thanks for sorting this out. It was next on my snagging list of Bootstrap 3 upgrade issues to fix. This one has been bugging me for a little while as it looks quite weird before your fix! Cheers! Hopefully @mshibuya can take a look soon and approve it for inclusion.

**Comment by cec** [comment]
@rikkipitt  Nice to know I was not the only one having the issue :)
