### ISSUE TITLE
"syck" gem and ruby 2.2

### ISSUE THREAD

**Issue by danmaz74** [sferik/rails_admin#2209]
I'm upgrading my rails app using rails_admin to ruby 2.2.1, and found a weird error with rails_admin - it said that RailsAdmin was not defined

After a bit of digging, I discovered that the problem was actually that rails_admin uses safe_yaml, which was trying to use Syck, which isn't included by default anymore. I added a gem 'syck' in my gemfile before rails_admin and it apparently works, but this doesn't look like a good solution.

**Comment by mshibuya** [comment]
safe_yaml has [support for both Syck and Psych](https://github.com/dtao/safe_yaml#requirements).
Please ensure that you're not setting `YAML::ENGINE.yamler = "syck"` somewhere in your app(or gems you're using).
