### ISSUE TITLE
bug results in error: ActiveRecord::StatementInvalid in RailsAdmin::MainController#dashboard

### ISSUE THREAD

**Issue by carlcotner** [sferik/rails_admin#2210]
My Rails/Devise User table is "user", which seems to be a reserved word for Postgres, and rails_admin generates the following SQL

>  SELECT "user".* FROM "user" ORDER BY user.updated_at desc LIMIT 1

without quoting the ORDER BY "user", which results in the error given in the subject line. The rest of the error message is

>  PG::SyntaxError: ERROR: syntax error at or near "." LINE 1: SELECT "user".* FROM "user" ORDER BY user.updated_at desc ... ^ : SELECT "user".* FROM "user" ORDER BY user.updated_at desc LIMIT 1

and the error happens here:

>  Extracted source (around line #592):
>
>  590
>  591    def exec_no_cache(sql, name, binds)
>  592        log(sql, name, binds) { @connection.async_exec(sql, []) }
>  593    end
>  594
>  595    def exec_cache(sql, name, binds)

**Comment by carlcotner** [comment]
(Or is this actually a problem with ActiveRecord?)

**Comment by fmh** [comment]
maybe try create table "users"

**Comment by carlcotner** [comment]
Yeah, thanks, I thought of that, but I'd have to change my whole application, so it is not my first choice. Do you happen to know whether the lack of table name quoting in the ORDER BY clause is a rails_admin problem or an ActiveRecord problem?

**Comment by mshibuya** [comment]
Dup of #1631.
