### ISSUE TITLE
Datepicker's z-index too low

### ISSUE THREAD

**Issue by artemaminov** [sferik/rails_admin#2213]
Creating new relation record with date field inside another one (when modal window shows up) will overflow datepicker's popup.

**Comment by mshibuya** [comment]
Dup of #2148, and already fixed in the master.

**Comment by sferik** [comment]
@mshibuya Do you think now is a good time to release a new gem?

**Comment by mshibuya** [comment]
@sferik Releasing as 0.6.7 will be fine :smiley:

**Comment by artemaminov** [comment]
@mshibuya, thanks 😏

**Comment by sferik** [comment]
@mshibuya Sounds good. I just added you as a gem owner on RubyGems.org, so you can build and push the gem yourself if you like. Just ensure all tests are passing, increment the version number in `lib/rails_admin/version.rb` and run:

    bundle exec rake release

This rake task will tag the release, push the tag to GitHub, build a gem package, and push that package to RubyGems.org.

**Comment by mshibuya** [comment]
Thank you @sferik, will do so :star2:
