### ISSUE TITLE
Attribute with conditional presence validation adds "required" attribute on input

### ISSUE THREAD

**Issue by PikachuEXE** [sferik/rails_admin#2218]
I have a column `remote_reference_id` (not a foreign key)
and I have 
```ruby
validates_presence_of :remote_reference_id,
                            unless: :posted_directly?

def posted_directly?
  scraping_source_name.blank?
end
```
When I am trying to create a new record for that model, the input of `remote_reference_id` is required with the HTML5 attribute "required", preventing any submission

Edit: only happens after `0.6.7`

**Comment by mshibuya** [comment]
That's because of the change in #2170.
You could try
```ruby
field :remote_reference_id do
  required false
end
```
to get around this behavior.

**Comment by PikachuEXE** [comment]
Thanks for your workaround.
I currently lock the gem version at `0.6.6` and wait for a fix for this.

**Comment by fourseven** [comment]
I have this as well, the required behaviour completely ignores any conditional validation which is rather frustrating, and is going to be a hassle to go back and disable it on those fields. Here's our use case:

```ruby
class Plan < ActiveRecord::Base
   ...
   validates :name, :presence => true, :if => :signed_up?
   ...
   def signed_up?
      !paid_until.nil?
   end
end
```
