### ISSUE TITLE
Dynamic forms and passing custom params to new action

### ISSUE THREAD

**Issue by StarWar** [sferik/rails_admin#2219]
I followed this railscast at http://railscasts.com/episodes/403-dynamic-forms for creating dynamic forms. I have created a few product types which have different custom fields, and now I want to add a new product which belongs_to some productType and accordingly it has certain dynamic fields which are for this particular product.

I am using **HStore** for storing values for these dynamic fields. Now when I click on new action on rails_admin to add new product it raises an error since it expects a product_type_id which is not being passed and passing it through url also doesn't work.

How do I resolve this issue.

Thanks!

**Comment by mshibuya** [comment]
RailsAdmin doesn't support hstore for now. See #1782.
