### ISSUE TITLE
How can I add locale changer in Rails Admin?

### ISSUE THREAD

**Issue by mitchenkod** [sferik/rails_admin#2220]
Hello! I am using rails admin and I need to add language(locale, I18n) changer to a header or a dashboard. May be there is standard feature how to change locale in rails_admin? If not how can I just add link somewhere (dashboard or header)?

**Comment by Kasvit** [comment]
Does nobody know?

**Comment by felix91gr** [comment]
A link in Dashboard or Header should suffice. I'm also needing to do this. If anyone knows how to add links in Rails Admin, please share.

**Comment by mshibuya** [comment]
Please refer to https://github.com/sferik/rails_admin/wiki/Changing-locale.
