### ISSUE TITLE
[Regression] models with 'has_secure_password' throw InvalidSalt exception when trying to be saved in both new/edit

### ISSUE THREAD

**Issue by vedant1811** [sferik/rails_admin#2227]
It used to work fine for me before but now I am getting `BCrypt::Errors::InvalidSalt in RailsAdmin::MainController#new` error pages when I try to save a model that has the property `has_secure_password`.

I am pasting the trace but the error is being thrown at the wrong place in the application trace:

bcrypt (3.1.9) lib/bcrypt/engine.rb:54:in `hash_secret'
bcrypt (3.1.9) lib/bcrypt/password.rb:66:in `=='
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:315:in `visit_String'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:560:in `block in dump_ivars'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:558:in `each'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:558:in `dump_ivars'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:345:in `visit_String'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `block in visit_Array'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `each'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `visit_Array'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:116:in `push'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:409:in `dump'
paper_trail (3.0.6) lib/paper_trail/serializers/yaml.rb:13:in `dump'
paper_trail (3.0.6) lib/paper_trail/has_paper_trail.rb:265:in `record_create'
activesupport (4.1.10) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (4.1.10) lib/active_support/callbacks.rb:224:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
activesupport (4.1.10) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:503:in `block in call'
activesupport (4.1.10) lib/active_support/callbacks.rb:503:in `each'
activesupport (4.1.10) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:86:in `run_callbacks'
activerecord (4.1.10) lib/active_record/callbacks.rb:306:in `_create_record'
activerecord (4.1.10) lib/active_record/timestamp.rb:57:in `_create_record'
activerecord (4.1.10) lib/active_record/persistence.rb:484:in `create_or_update'
activerecord (4.1.10) lib/active_record/callbacks.rb:302:in `block in create_or_update'
activesupport (4.1.10) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
activesupport (4.1.10) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:86:in `run_callbacks'
activerecord (4.1.10) lib/active_record/callbacks.rb:302:in `create_or_update'
activerecord (4.1.10) lib/active_record/persistence.rb:103:in `save'
activerecord (4.1.10) lib/active_record/validations.rb:51:in `save'
activerecord (4.1.10) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.1.10) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
activerecord (4.1.10) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
activerecord (4.1.10) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
activerecord (4.1.10) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
activerecord (4.1.10) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
activerecord (4.1.10) lib/active_record/transactions.rb:208:in `transaction'
activerecord (4.1.10) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
activerecord (4.1.10) lib/active_record/transactions.rb:268:in `block in save'
activerecord (4.1.10) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
activerecord (4.1.10) lib/active_record/transactions.rb:267:in `save'
rails_admin (0.6.7) lib/rails_admin/adapters/active_record/abstract_object.rb:23:in `save'
rails_admin (0.6.7) lib/rails_admin/config/actions/new.rb:42:in `block (2 levels) in <class:New>'
rails_admin (0.6.7) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
rails_admin (0.6.7) app/controllers/rails_admin/main_controller.rb:22:in `new'
actionpack (4.1.10) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.10) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.10) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.10) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.10) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
activesupport (4.1.10) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.1.10) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.10) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.10) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.10) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.1.10) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.10) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.10) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.10) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.10) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.10) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.10) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.10) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.10) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.10) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.10) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.10) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.10) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.10) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:692:in `call'
railties (4.1.10) lib/rails/engine.rb:514:in `call'
railties (4.1.10) lib/rails/railtie.rb:194:in `public_send'
railties (4.1.10) lib/rails/railtie.rb:194:in `method_missing'
actionpack (4.1.10) lib/action_dispatch/journey/router.rb:73:in `block in call'
actionpack (4.1.10) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.10) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.10) lib/action_dispatch/routing/route_set.rb:692:in `call'
rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
exception_notification (4.0.1) lib/exception_notification/rack.rb:28:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/cookies.rb:562:in `call'
activerecord (4.1.10) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.10) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.10) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.10) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.10) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.10) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.10) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.10) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.10) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.10) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.10) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.10) lib/rails/engine.rb:514:in `call'
railties (4.1.10) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.2) lib/rack/server.rb:264:in `start'
railties (4.1.10) lib/rails/commands/server.rb:69:in `start'
railties (4.1.10) lib/rails/commands/commands_tasks.rb:81:in `block in server'
railties (4.1.10) lib/rails/commands/commands_tasks.rb:76:in `tap'
railties (4.1.10) lib/rails/commands/commands_tasks.rb:76:in `server'
railties (4.1.10) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
railties (4.1.10) lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:8:in `require'
bin/rails:8:in `<top (required)>'
spring (1.2.0) lib/spring/client/rails.rb:27:in `load'
spring (1.2.0) lib/spring/client/rails.rb:27:in `call'
spring (1.2.0) lib/spring/client/command.rb:7:in `call'
spring (1.2.0) lib/spring/client.rb:26:in `run'
spring (1.2.0) bin/spring:48:in `<top (required)>'
spring (1.2.0) lib/spring/binstub.rb:11:in `load'
spring (1.2.0) lib/spring/binstub.rb:11:in `<top (required)>'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/vedant/.rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
bin/spring:16:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"b9XLr84MDKVo87jjJwx+SHS4SriFodSRp84fh1eNY3I=",
 "v1_seller"=>{"name_of_shop"=>"Someone",
 "name_of_seller"=>"Chennai",
 "status"=>"3",
 "email"=>"ahaee@dk.xkm",
 "password"=>"[FILTERED]",
 "password_confirmation"=>"[FILTERED]",
 "address"=>"4th B Cross Rd\r\nBengaluru\r\n560034",
 "latitude"=>"12.934241",
 "longitude"=>"77.615678",
 "phone"=>"+91 5649494649",
 "category_ids"=>["",
 "",
 ""],
 "category_name_ids"=>["",
 ""]},
 "return_to"=>"",
 "_save"=>"",
 "model_name"=>"v1~seller"}

**Comment by mshibuya** [comment]
Try this and see if it works.
http://stackoverflow.com/a/28225594/1418867

**Comment by vedant1811** [comment]
Yes. Thanks. Was a regression but by a depending gem :D
