### ISSUE TITLE
table list page css class name conflict

### ISSUE THREAD

**Issue by TangMonk** [sferik/rails_admin#2232]
I have a model called `ad`, and have 1 record exist on database.

But it do not show on list page:

![image](https://cloud.githubusercontent.com/assets/3498786/6890453/2dfb76a6-d6de-11e4-90c2-55afc21e219a.png)

Notice the count.

If I change the `tr` tag class name `ad_row` to `whatever_row`, it appeared

![image](https://cloud.githubusercontent.com/assets/3498786/6890459/5e56076c-d6de-11e4-9541-abde6656c42e.png)

**Comment by mshibuya** [comment]
Some kind of an ad-blocker or user agent stylesheet might be affecting this.
Try turning them off and see if it works.

**Comment by TangMonk** [comment]
@mshibuya thanks
