### ISSUE TITLE
Upgrading from 0.6.5 to 0.6.7

### ISSUE THREAD

**Issue by williantenfen** [sferik/rails_admin#2235]
Seems like 'Inline_edit' and 'inline_add' aren't working properly when updating from 0.6.5 to 0.6.7. It doesn't shows Edit buttons (inline) even when forced to :true.

**Comment by mshibuya** [comment]
How to reproduce, and what kind of trouble do you have?

**Comment by williantenfen** [comment]
I' had a conditional inline_edit button. It was all ok at 0.6.5, but at 0.6.7 its not rendering when needed. At the attached images an example.
V. 0.6.5:
![0 6 5](https://cloud.githubusercontent.com/assets/3765168/6918152/76f302d6-d781-11e4-9468-c899c6e894fc.png)

V.0.6.7:
![0 6 7](https://cloud.githubusercontent.com/assets/3765168/6918154/7cbdef28-d781-11e4-9f65-6c3f8a1e496a.png)

**Comment by ouelletv** [comment]
It seems related to to 'visible' option that is set in the config.model block. 
Prior 0.6.7, the 'visible' option was hiding the model in the navigation sidebar only but would let you use the inline add/edit buttons, which was perfect. 
In 0.6.7, i have tested that if you set 'visible' to false in that config, the inline add/edit button also disappear which is a problem.

**Comment by sasselin** [comment]
+1 same thing

**Comment by benhutton** [comment]
This is your culprit: https://github.com/sferik/rails_admin/commit/10655cbfe972a2972b6580175f8be7fe2e20572c

I got stung by something else from this commit.

It seems that `visible` has acquired a huge range of meaning all of a sudden. It initially just configured nav bar presence, but now it has come to mean something like "enabled".

**Comment by mshibuya** [comment]
The change in 10655cb is okay. We do not want disabled actions to show up - by default.
The problem is that `enabled?` was checking model's `visible?`. In that way, hiding a model leads to corresponding actions in-executable.

Please try with the latest master, and see if it works for you.

**Comment by fmh** [comment]
my issue #2330 is caused by this change, but how exclude a model (like join table) and keep his attributes accessible in a nested form.
