### ISSUE TITLE
Getting redirected to wrong login page

### ISSUE THREAD

**Issue by waaadim** [sferik/rails_admin#2236]
going to /admin is redirecting me to /users/sign_in

I have to be signed up as a "User" only after that I'm getting the correct "Admin" login page.
is this the expected behaviour ?

rails_admin (0.6.7)

  // routes
  root 'home#index'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  // admin intialize
  config.authenticate_with do
    warden.authenticate! scope: :admin
  end
  config.current_user_method(&:current_admin)

**Comment by mshibuya** [comment]
Do you use `authenticate_user!` in your app's ApplicationController?
If so, it will take control and get you redirected to `User`'s login page, before it reaches to RailsAdmin authentication.

**Comment by waaadim** [comment]
yes, I do have "authenticate_user!" user there, thanks, totally forgot about that
