### ISSUE TITLE
Please consider using SemVer

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#2243]
I know that SemVer allows to change the API if the major version number is 0, but this is like not using SemVer at all.

I prefer to use rails_admin 44.0.0 instead of having a Bootstrap 2 to Bootstrap 3 switch between 0.6.5 and 0.6.6

Please consider to bump the major version number if there is a potential breaking change, so we can immediately check if a gem needs attention

Thanks!

**Comment by mshibuya** [comment]
Thanks for your advice, we're moving toward 1.0.0 now.

**Comment by mshibuya** [comment]
Reopening, because 1.0.0 release will take some more time...

**Comment by mshibuya** [comment]
Closing because we're on 1.0.0 now!
