### ISSUE TITLE
`multipart error` for a accepts_nested_attributes_for model

### ISSUE THREAD

**Issue by vedant1811** [sferik/rails_admin#2251]
I am getting `multipart errors` : https://gist.github.com/vedant1811/1497bb19aeb2aa7f75d8 with the new `Rack` in Rails 4.2. For me it happens just because of `accepts_nested_attributes_for`, even though I do not make any changes to the nested model.

    class V1::CategoryName < ActiveRecord::Base
      has_many :brand_names, :class_name => 'V1::BrandName', dependent: :destroy, inverse_of: :category_name
      has_many :products, :class_name => 'V1::Product', dependent: :nullify
    # commenting this line fixes the issue
    #   accepts_nested_attributes_for :brand_names, allow_destroy: true

      validates :name, :uniqueness => {:case_sensitive => false}
      validates :name, presence: true

      # TODO: add validation for variants uniqueness and lower case

      has_paper_trail
    end

**Comment by mshibuya** [comment]
You should try googling before opening an issue.
http://stackoverflow.com/questions/27773368/rails-4-2-internal-server-error-with-maximum-file-multiparts-in-content-reached

**Comment by vedant1811** [comment]
I have seen that.
Don't you think its an issue that rails_admin uses more than enough multiparts for just changing an attribute?

The issue is using too many multiparts in case of a `accepts_nested_attributes_for` model. rails_admin should edit the nested attributes only if they have been edited. If this is really hard to implement (Probably because how rails_admin is written) you should make this a **wont fix** and mention it somewhere in the wiki.

**Comment by mshibuya** [comment]
Didn't you read [the answer in the bottom](http://stackoverflow.com/a/28819236/1418867)? It's a __bug__ in Rack and RailsAdmin won't do anything about it.
If you feel the need for any kind of precaution on it, go ahead. This is an open source project and Wiki is open to everyone.

**Comment by vedant1811** [comment]
No I read the accepted answer.

I guess it will just be fixed in rake 1.6.1 :D

On Wed, Apr 15, 2015 at 7:40 AM, Mitsuhiro Shibuya <notifications@github.com
