### ISSUE TITLE
Support Conditional Enums

### ISSUE THREAD

**Issue by dyatlov** [sferik/rails_admin#2258]
Hi guys,

I have email settings defined in MailConfig table.
Table has structure: 

```ruby
t.string :name
t.string :value
```
I defined `value_enum` method as following:

```ruby
def value_enum
    return [:yes, :no] if self.name == 'enable_starttls_auto'
    return [:plain, 'login', 'cram_md5'] if self.name == 'authentication'
  end
```

so for 2 options it returns enum values and for others returns nil.
This of course doesn't work :)

I guess that would be an easy fix to support such functionality in RailsAdmin.. just check what method returns. If it is `nil` then render a default type.

**Comment by mshibuya** [comment]
This is a design smell, you'd better use separate columns to express different enums. That's simpler and trouble-free.

**Comment by dyatlov** [comment]
Yes, it clearly smells, but it comes from using this gem: https://github.com/ledermann/rails-settings for settings

This gem saves data in key/value-like storage and depends on setting key I should decide which values are allowed (read as: introduce basic settings validation).

**Comment by mshibuya** [comment]
I didn't actually try it yet, but putting conditional in [`enum`](https://github.com/sferik/rails_admin/wiki/Enumeration#using-the-configuration-approach) configuration might probably work...

But this falls into a usage question and out of scope of issue tracker. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for that purpose, thanks.
