### ISSUE TITLE
Update devise model without password

### ISSUE THREAD

**Issue by passalini** [sferik/rails_admin#2265]
I'm trying to update an user without provide the password, but the field password is required and the password confirmation isn't! I only can update an user if I provide some password, but I can leave the passoword confirmation blank.

It's the first time that it occurs to me and can't find any solution to fix it...

```ruby
# user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wishes
  has_many :addresses

  accepts_nested_attributes_for :addresses
end
```

```ruby
# rails_admin.rb
RailsAdmin.config do |config|
  ## == Devise ==
  config.authenticate_with do
    warden.authenticate! scope: :admin
  end
  config.current_user_method(&:current_admin)

  config.actions do
    dashboard                     # mandatory
    index                         # mandatory
    new
    export
    bulk_delete
    show
    edit
    delete
    show_in_app
  end
end
```

I'm using devise 3.4.1 and rails_admin 0.6.7

**Comment by ezrarush** [comment]
put this in your /config/initializers/rails_admin.rb

```ruby
config.model User do
  update do
    exclude_fields :password, :password_confirmation
  end
end
```
If your devise model is not User than use its name instead. 
Please note, now your rails_admin cannot change user passwords. The solution is to make a new action "change password".

**Comment by mikel** [comment]
Another way to do this (without having to create a custom action) is use a virtual attribute


```
class User < ActiveRecord::Base

  rails_admin do
    configure :set_password

    edit do
      exclude_fields :password, :password_confirmation
      include_fields :set_password
    end
  end

  # Provided for Rails Admin to allow the password to be reset
  def set_password
    nil
  end

  def set_password=(value)
    return nil if value.blank?
    self.password = value
    self.password_confirmation = value
  end
```

Then if you want to change the password in the admin, set the password, otherwise leave it blank

**Comment by passalini** [comment]
@mikel, nice workaround!!! 

I think that the bug still there, but with @mikel's woraroud I can change the password.. So.... Should I close this issue or not?

**Comment by mikel** [comment]
You should close it I think.  It's not really a bug, it's expected behaviour for devise.  The above solves it, so *shrug*

**Comment by yzhanginwa** [comment]
Thanks @mikel !  I had the same issue and your solution looks promising. I'll give it a try :-)

**Comment by Novtopro** [comment]
@yzhanginwa Nice to meet you here!
