### ISSUE TITLE
Rails 4 app crashes during preloading

### ISSUE THREAD

**Issue by beechnut** [sferik/rails_admin#2266]
In development, Rails Admin boots and works perfectly. However, the application crashes in a production environment during preloading, giving the error:

```
/path/to/my/app/lib/rails_admin/config/fields/institution_id.rb:1:in `<top (required)>': uninitialized constant
RailsAdmin::Config::Fields::Types::Base (NameError)
```
The full stacktrace is in this gist: https://gist.github.com/beechnut/6e2710e229fd38a5a723

In config/environments/production.rb, I set `config.eager_load = false`, and the application boots without issue.

I should note that I received this error with both Unicorn and Puma.

Any insight into why this is happening, and what can be done to get around it, would be greatly appreciated.

**Comment by mshibuya** [comment]
Try adding `require 'rails_admin/config/fields/base'` to the top of your custom field type.

**Comment by beechnut** [comment]
I haven't defined any custom field types - the file referenced is produced by the generator. Should I include said line at the top of every model file that uses Rails Admin and uses that particular field?

Also, please don't assume an issue is closed until it's confirmed by the poster. Makes for a lot of unnecessary re-opening and re-closing.

**Comment by beechnut** [comment]
This didn't work, nor did adding `require 'rails_admin'` above it. Still investigating.

Would you reopen this issue? I would not consider it closed.

**Comment by beechnut** [comment]
As shown in the stack trace above, I was inheriting from `RailsAdmin::Config::Fields::Types::Base`. As far as I could tell, this worked fine when the code wasn't preloaded, but failed when preloaded, because there is no constant `RailsAdmin::Config::Fields::Types::Base`, but rather `RailsAdmin::Config::Fields::Base`.
