### ISSUE TITLE
rails_admin_controller? method removed

### ISSUE THREAD

**Issue by sbull** [sferik/rails_admin#2268]
The fix for https://github.com/sferik/rails_admin/issues/2023 apparently removed the `rails_admin_controller?` method. I didn't see an explanation for this. It was added back in https://github.com/sferik/rails_admin/issues/351.

Was there a reason for this? It broke my upgrade from 0.6.6 to 0.6.7.

FWIW, I've had this method in my `ApplicationController`, which I'll implement differently now:

```ruby
  def is_rails_admin_controller?
    respond_to?(:rails_admin_controller?, true) && rails_admin_controller?
  end
```

**Comment by YoranBrondsema** [comment]
I'm having the same problem. I fixed it with a kind of dirty implementation but it works:

````
  def is_rails_admin_controller?
    (self.class.to_s =~ /RailsAdmin::/) == 0
  end
````
