### ISSUE TITLE
Horizontally scrolling tables in list view - pull request potential?

### ISSUE THREAD

**Issue by sbull** [sferik/rails_admin#2272]
I recently worked out a way to make the "list" view tables more useful to me - showing more/all columns with horizontal scrolling and frozen header columns, as I described here: https://github.com/sferik/rails_admin/wiki/Horizontally-scrolling-table-with-frozen-columns-in-list-view
It's mostly done in javascript, but could be better suited to be integrated in the gem instead.

I'm wondering if there would be support for making this a configuration option. If the feature would likely be accepted, I'll work on a pull request for it. I'm sure I'll need some guidance along the way - such as naming for the config option, how to build a test case, etc. Should I take a crack at this, or do you think it's better to live in userland customization instead of in the gem?

**Comment by sbull** [comment]
@mshibuya do you have thoughts on this? Or should I discuss it with someone else? Thanks!

**Comment by iMacTia** [comment]
It should definitely be included as an option for the gem, would make a lot of sense!

**Comment by SuperMasterBlasterLaser** [comment]
@sbull I have used your javascript code, and that kind of result I have got:

![1](https://cloud.githubusercontent.com/assets/8684688/11365296/9b9f3492-92cf-11e5-8aed-4662a8e87fff.PNG)

It "destroys" table.

**Comment by sbull** [comment]
I've slightly updated the JS with rails_admin 0.6.8. Here's what I get (rails_admin 0.6.8, Chrome 46.0).

![railsadminhorizscroll](https://cloud.githubusercontent.com/assets/1115369/11372389/cf7cd36a-9292-11e5-9e00-ea7e3374c090.jpg)

**Comment by martnst** [comment]
+1 on including it with rails_admin per default

**Comment by opensourceame** [comment]
+1 for including it with Rails but I think it should be optional in the config. The JS should also add some classes to the wrapper elements so it's easily to customise the look.

**Comment by twikah** [comment]
+1 on including it with rails_admin as optional in the config!

**Comment by mshibuya** [comment]
#3017 was merged in.
