### ISSUE TITLE
Bootstrap panels

### ISSUE THREAD

**Issue by spavezv** [sferik/rails_admin#2282]
I'm trying to use Bootstrap panel http://getbootstrap.com/components/#panels in a custom view for a custom action, but the style is not applying. I can use a table style http://getbootstrap.com/css/#tables so I assume that bootstrap is included and I can use it. 
Do I need another configuration to use panels?

![panels](https://cloud.githubusercontent.com/assets/1225927/7423217/8d9e0198-ef69-11e4-9d1a-906e5f9d164b.png)
![table](https://cloud.githubusercontent.com/assets/1225927/7423218/8ded32e0-ef69-11e4-8538-bb6a91c33cee.png)

**Comment by rikkipitt** [comment]
I was trying to use panels the other day too... they must not be included in the upgrade from bootstrap 2 to 3. I'll take a look later as I think the panel might look better than the "well" that wraps the filters on the index pages.

**Comment by rikkipitt** [comment]
It seems that the panels file is included in the main bootstrap file which isn't used, and not included in the ```rails_admin.scss.erb``` file... I might make a pull request that fixes and implements the panel instead of wells... might look cleaner in my opinion.

**Comment by spavezv** [comment]
Thanks for the replay. I hope you can solve this problem.
Could you have a look into another issue that I've found:  https://github.com/sferik/rails_admin/issues/2320
To reproduce that one just create a validation for a referenced value (belongs_to) and trigger it, the error is not displaying in the correct position.

**Comment by rikkipitt** [comment]
Hi @spavezv - I fixed it and issued a pull request for inclusion into the main project. Hopefully @mshibuya will merge it in soon :wink:
