### ISSUE TITLE
Problem with kaminari theme

### ISSUE THREAD

**Issue by benjaminwood** [sferik/rails_admin#2283]
I ran into an interesting problem today which is that I'm working on a project which uses both rails_admin & this gem: https://github.com/matenia/bootstrap-kaminari-views

The problem is that both have kaminari themes at this path: `views/kaminari/twitter-bootstrap`. So, when I'm using Kaminari in some non rails_admin view and specify the theme like this:

`= paginate @resource, remote: true, :theme => 'twitter-bootstrap'`

I end up with rails_admin kaminari theme instead of the other gem referenced above. The main issue with this is in regards to the `remote: true` option. When this option is passed, rails_admin adds a 'pjax' class and does not specify `data-remote=true` (standard rails/what I need).

My temp solution was to simply copy the bootstrap-kaminari-views theme into my app /views directory and title it something else.

Possible solution: change rails_admin kaminari theme name to something more specific like 'rails-admin-twitter-bootstrap'.

**Comment by halilim** [comment]
Putting `gem 'bootstrap-kaminari-views'` *after* `gem 'rails_admin'` has an even more interesting effect: it removes styling from rails_admin pagination.

**Comment by klyonrad** [comment]
So which gem is to blame here - who has to fix this?

**Comment by benjaminwood** [comment]
I wouldn't say that either gem is to blame. It's simply a conflict between the two and technically either gem could fix it. Though, as I mentioned above I think it makes most sense that rails_admin changes the name of their theme, since the name of the other gem is `bootstrap-kaminari-views`. IE: I'm not sure what they would change it to.

If the maintainer(s) of rails_admin agree, perhaps one of us can submit a PR.

**Comment by bbenezech** [comment]
@benjaminwood Sure, namespacing bootstrap-kaminari-views to ra-bootstrap-kaminari-views would make sense, no pb.

**Comment by benjaminwood** [comment]
Cool, PR submitted ☝️

**Comment by bbenezech** [comment]
merged!
