### ISSUE TITLE
model not appear in list

### ISSUE THREAD

**Issue by ValenOnish** [sferik/rails_admin#2285]
I just created almost blank app (rails 4.2, ruby 2.1.5) with one model:

rails g scaffold ad user_id:integer category_id:integer city_id:integer start_date:date end_date:date title:string email:string website:string video_link:string description:text affiliation:string status:integer plan_id:integer pro_number:integer

I have two ads, but they're not shown in the list and I cannot edit them.

This issue I found on Firefox, not Safari or Chrome

![rails_admin_bug](https://cloud.githubusercontent.com/assets/5513459/7443228/a83f2ad0-f109-11e4-9de2-dfd84c18db58.jpg)

**Comment by mshibuya** [comment]
Dup of #2232.
