### ISSUE TITLE
rails_admin has_one without toggle button

### ISSUE THREAD

**Issue by TangMonk** [sferik/rails_admin#2290]
![image](https://cloud.githubusercontent.com/assets/3498786/7467408/fa36b042-f32a-11e4-8bef-abf05457cfd1.png)

How to make the single image do not need the toggle button, just only the file upload button, like following :

![image](https://cloud.githubusercontent.com/assets/3498786/7467422/554321d2-f32b-11e4-8792-b3aa9e7fce30.png)

**Comment by mshibuya** [comment]
That's not possible, but you can keep it opened by:
```ruby
field :single_image do
  active true
end
```
