### ISSUE TITLE
How to have collapsed fields of a group on first load of page. 

### ISSUE THREAD

**Issue by prem2014** [sferik/rails_admin#2296]
I am using mongoid db. So I group fields based on their relevance with each other. But I have too many so during the edit I want the groups to be collapsed rather the default behaviour where it show all the fields of group non-collapsed.

**Comment by mshibuya** [comment]
You could try:
```ruby
group :foo do
  active false
end
```

**Comment by prem2014** [comment]
Yeah! it worked. Thanks a lot. Either I missed such property in documentation or it is not listed. If it is the latter then can something be done?. Once again thank you!!
