### ISSUE TITLE
nested forms are not indented properly since fix indentation issue with col-md-offset-2

### ISSUE THREAD

**Issue by fmh** [sferik/rails_admin#2298]
**with col-md-offset-2 css class :**
![capture d ecran 2015-05-17 a 13 34 17](https://cloud.githubusercontent.com/assets/56861/7670145/954fbe26-fc99-11e4-98f2-3d41da5a89a2.png)

**without col-md-offset-2 css class :**

![capture d ecran 2015-05-17 a 13 34 53](https://cloud.githubusercontent.com/assets/56861/7670148/a4835d9e-fc99-11e4-857c-e5a4222bcdeb.png)

**Comment by rikkipitt** [comment]
Hi @fmh - just out of interest... how are you doing those custom layouts? They look great!

Cheers!

**Comment by fmh** [comment]
In my app , I offer the possibility to the user to choose a custom theme. This is a lot of customization of some files (form_builder.rb , *.css, etc.).

![capture d ecran 2015-05-18 a 23 25 25](https://cloud.githubusercontent.com/assets/56861/7690663/d916153e-fdb5-11e4-8fb8-69b8ab76dc0c.png)


application.html.haml
```ruby
= stylesheet_link_tag "rails_admin/main_css/#{current_user.theme}/rails_admin.css", media: :all
```

initializers/assets.rb
```ruby
Rails.application.config.assets.precompile += ["rails_admin/main_css/*"]

**Comment by mshibuya** [comment]
Is there any clue that `col-md-offset-2` is a bad change?
Just fixing your custom theme isn't enough?

**Comment by fmh** [comment]
I tried without any custom theme, only with basic (original theme), and i get the same result.
In my firebug if i remove the col-md-offset-2 class, i get the correct indentation.
