### ISSUE TITLE
Set minimum Sass precision to 8

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#2302]
Refers to #2276, #2277

Bootstrap requires a [minimum sass precision of 8](https://github.com/twbs/bootstrap-sass#sass-number-precision)

This is causing some issues on button height. In example, if you try to append buttons to form controls the result will be 1px wrong

![screen shot 2015-04-27 at 22 41 32](https://cloud.githubusercontent.com/assets/556268/7357512/85389fd6-ed2f-11e4-816c-f4d69dfc2674.png)

I'm not an English native speaker, so I'm not confident in submitting a PR to the readme. I think a copy&paste from bootstrap's docs with some minor edits should be enough

**Comment by linuxonrails** [comment]
+1

**Comment by mshibuya** [comment]
Default precision is 10 now, instead of 5.
https://github.com/sass/sass/pull/2297
