### ISSUE TITLE
Add support for Attachinary

### ISSUE THREAD

**Issue by GeoffTidey** [sferik/rails_admin#2304]
I'd like to be able to use the [attachinary](https://github.com/assembler/attachinary) gem (& consequently cloudinary) with rails admin.

Currently a model with has_attachment (or has_attachments) shows nothing.

**Comment by mshibuya** [comment]
Not going to happen.

**Comment by felipeorlando** [comment]
WTF?! Why?!?!

**Comment by mshibuya** [comment]
Submit PR is you need this, please.
