### ISSUE TITLE
rails admin and CanCan

### ISSUE THREAD

**Issue by hadiab** [sferik/rails_admin#2317]
hi i have a problem with cancan with rails admin 

its block the admin page for all the user including the admin

###############################################

there is what inside my rails_admin.rb

config.authorize_with :cancan

###############################################

this Ability Class ability.rb

    user ||= User.new                   # guest user (not logged in)
    if user.admin?                        # Admin user
      can :manage, :all
    else                                        # Non-admin user
      can :read, :all
    end

##############################################

this User model user.rb

  def admin?
    admin
  end  

##############################################

this is my migration to add admin to user

class AddAdminToUsers < ActiveRecord::Migration
  def change
    add_column :users, :admin, :boolean, :default => false
  end
end

###############################################

thanks...........

**Comment by sbull** [comment]
check https://github.com/sferik/rails_admin/wiki/CanCan

Do you have the following in `ability.rb`?
````
    can :access, :rails_admin
    can :dashboard
````
