### ISSUE TITLE
How to export virtual field

### ISSUE THREAD

**Issue by tmacbg** [sferik/rails_admin#2322]
Hello, 

I have a model that has a virtual fields with values that are time based and now I need to make an export action for this model . Does anyone knows how to make the export action work with virtual fields ?

Thanks

**Comment by mshibuya** [comment]
Explicitly setting the field's `formatted_value` will work.

**Comment by grillermo** [comment]
For future reference

def price
   ...
end

...
    configure :price do
        formatted_value do
            value
        end
    end

    list do
        field :price
    end
