### ISSUE TITLE
bootstrap-wysihtml5 crashes

### ISSUE THREAD

**Issue by vorant94** [sferik/rails_admin#2326]
I've installed bootstrap-wysihtml5-rails gem just as it described [here](https://github.com/sferik/rails_admin/wiki/Wysihtml5)

After it I got this message and the same for js
`Asset filtered out and will not be served: add Rails.application.config.assets.precompile += %w( bootstrap-wysihtml5/index.css ) to config/initializers/assets.rb and restart your server`

I added it and got another message
`Asset was linked to from an alias rather than its exact path. Alias resolving may not be available in production. Use "bootstrap-wysihtml5/index.css" instead of "bootstrap-wysihtml5.css"`

Why did I get it while I'm working in development? Furthermore my assets.rb looks fine:
````ruby
Rails.application.config.assets.precompile += %w( bootstrap-wysihtml5/index.css )
Rails.application.config.assets.precompile += %w( bootstrap-wysihtml5/index.js )
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )

````

what's wrong?

**Comment by mshibuya** [comment]
Dup of #2307, please try the workaround discussed there.
