### ISSUE TITLE
Milestone 0.7

### ISSUE THREAD

**Issue by dalpo** [sferik/rails_admin#2338]
@mshibuya What do you think about to create a develop branch for the future release?
I would like to use the current PRs marked as 0.7 :smiley: 

Thanks

**Comment by rikkipitt** [comment]
+1!

**Comment by dalpo** [comment]
@mshibuya any news? 
btw let me know if you need some help to achieve the next release :wink:

**Comment by mshibuya** [comment]
The master branch is targeting 1.0.0 now :sunglasses:

**Comment by dalpo** [comment]
Great news! :smile: 

Thanks!
