### ISSUE TITLE
Can rails_admin search in attributes of children from children?

### ISSUE THREAD

**Issue by nlsrchtr** [sferik/rails_admin#2342]
With something like [`searchable Team => :name`](https://github.com/sferik/rails_admin/blob/dcb774d7a5629ae129436669f43be63adc455a49/spec/integration/basic/list/rails_admin_basic_list_spec.rb#L173) we can search on `belongs_to` attributes. This is great, but is it also possible to search on something like `searchable Team => { Club => :name }`.

And if this is possible, would it also be possible, if the relation between `Team` and `Club` would be polymorphic? Something like `LineItem => { Orderable => { Creator => :name } ` where I would like to find all LineItems by name of the `Creator`.

**Comment by mshibuya** [comment]
No, not right now.
