### ISSUE TITLE
Unable to Insert Link or Image with rails_admin 0.6.8 / bootstrap-wysihtml5-rails 0.3.3.7

### ISSUE THREAD

**Issue by dmitrypol** [sferik/rails_admin#2344]
I had a problem with rails_admin 0.6.7 with bootstrap-wysihtml5-rails 0.3.1.24 (https://github.com/Nerian/bootstrap-wysihtml5-rails).  Clicking on Insert Link or Insert Image would bring up the insert modal however it would be grayed out and disabled

Upgrading to bootstrap-wysihtml5-rails 0.3.3.7 solved it.  Now I upgraded to rails_admin 0.6.8 and the same problem is back.  Has anyone seen the same issue?  

Original instructions https://github.com/sferik/rails_admin/wiki/Wysihtml5.  I need some of the fixes in new rails_admin so downgrading is not a great option.

**Comment by luizpicolo** [comment]
I'm going through the same problem.

**Comment by anfinil** [comment]
I have the same issue.

**Comment by utkukaynar** [comment]
I have the same problem. Plus gylphicons on the editor are not visible despite they are visible inother rails admin pages in app.

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/issues/2761#issuecomment-494311395
