### ISSUE TITLE
Unable to delete record with specified class name

### ISSUE THREAD

**Issue by neilsmeatom** [sferik/rails_admin#2347]
I believe there may be an error with this and i'm unable to find out anything more. When deleting a product record with following relation:

```
class Product < ActiveRecord::Base
  has_many :articles
end
```
```
class Article < ActiveRecord::Base
  belongs_to :product, :class_name => 'Product', :foreign_key => 'announced_product_id'
end
```
```
Error:
ActiveRecord::StatementInvalid in RailsAdmin::Main#delete
PG::UndefinedColumn: ERROR:  column articles.article_id does not exist
```
I believe this has happened in an update but unsure when this may have occurred.

**Comment by mshibuya** [comment]
This is caused by association misconfiguration, please read ActiveRecord documentation carefully.
