### ISSUE TITLE
I18n.default_locale would be overwrote by config.i18n.default_locale?

### ISSUE THREAD

**Issue by keekun** [sferik/rails_admin#2348]
Follow the default config template, I set

require 'i18n'
I18n.default_locale = :en

In the same time, I worte
config.i18n.default_locale = :cn

What I want to do is different default language settings in customer-side and admin-side, but what I get is both sides be set to :cn 

Thank you for your help

**Comment by mshibuya** [comment]
There's no support for separate configuration on customer-side and admin-side locale now.
