### ISSUE TITLE
PG::UndefinedTable in RailsAdmin::MainController#dashboard

### ISSUE THREAD

**Issue by afxjzs** [sferik/rails_admin#2350]
I'm getting this error, even after a complete uninstall and reinstall. Rails_admin was working fine, and then it just stopped. I thought it was enum related, but i've used the initializer at https://gist.github.com/dmilisic/38fcd407044ace7514df and confirmed that `ActiveRecord::RailsAdminEnum` is loaded.

It seems like no matter what i do, i get this error. I've rebuilt the database several times via migrations (rake db:setup) only, so it's not some zombie table or something. I'm totally stumped. I thought i had something when i found out that enums don't play nice out of the box, but i can't get anything but this error.

Here's the full details:
````
ERROR: relation "errors" does not exist LINE 5: WHERE a.attrelid = '"errors"'::regclass ^

Extracted source (around line #592):
590
591
592
593
594
595
        def exec_no_cache(sql, name, binds)
          log(sql, name, binds) { @connection.async_exec(sql, []) }
        end

        def exec_cache(sql, name, binds)
````
Is there something I am missing? I'm using pretty standard enum implementation and I renamed the rails_admin.rb to z_rails_admin.rb to make sure it loads after the enum initializer mentioned in that gist i linked to.

**Comment by afxjzs** [comment]
I guess i'm the only one getting this error...

**Comment by mshibuya** [comment]
Latest release 0.7.0 has built-in support for ActiveRecord::Enum, so try and see if it works.
If something breaks, please paste full stack trace here.

**Comment by mshibuya** [comment]
Please reopen on update.

**Comment by afxjzs** [comment]
In my gemfile.lock it says i'm using 0.7.0 so that's not the issue. Here's a gist of the full stack trace of the error: https://gist.github.com/afxjzs/828c9af28aa886f4b7d2

Any help is much appreciated. Thanks!

**Comment by afxjzs** [comment]
@mshibuya  Can this please be reopened? I've posted the requested data. Please let me know what else i could post to help sort this out.

**Comment by heidar** [comment]
I was getting the same error cause I have objects in my models folder that do not have associated tables. 

I fixed it by adding a line to the config:

    config.included_models = %w(User Post) # whatever models you want included in rails_admin

Not sure if this applies to you though but figured I'd post it anyway

**Comment by afxjzs** [comment]
@heidar THANKS!

this was the issue. There's no objects in our models folder w/o tables, but the whitelisting was what fixed it. 

Thanks for your help guys!
