### ISSUE TITLE
rails_admin when editing a belongs_to association display user name instead of User id

### ISSUE THREAD

**Issue by shakycode** [sferik/rails_admin#2356]
I'm having a problem with a belongs_to association on a model and being able to edit it with the appropriate username/fullname instead of User 1, User 2, etc.  I posted this on [Stack](http://stackoverflow.com/questions/31356569/rails-admin-when-editing-a-belongs-to-association-display-user-name-instead-of-u) but hasn't gotten any hits.

Here is my rails_admin.rb initializer

````
RailsAdmin.config do |config|
  config.authorize_with do |controller|
    unless current_user.role == 'admin'
      redirect_to main_app.root_path
      flash[:error] = "You are not an admin"
    end
  end

  config.model 'ClockEvent' do
  configure :user, :belongs_to_association
  configure :station, :belongs_to_association
    list do
      field :clock_in
      field :clock_out
      field :user do
        pretty_value do
            value.try(:full_name)
        end
      end
      field :station do
        pretty_value do
            value.try(:station_name)
        end
      end
      field :created_at
      field :updated_at
    end

    show do
      field :clock_in
      field :clock_out
      field :user do
        pretty_value do
            value.try(:full_name)
        end
      end
      field :station do
        pretty_value do
            value.try(:station_name)
        end
      end
      field :comment
      field :hr_comment
      field :created_at
      field :updated_at
    end

    edit do
      field :clock_in
      field :clock_out
      field :user do
        pretty_value do
            value.try(:user).try(:full_name)
        end
      end
      field :station do
        pretty_value do
            value.try(:station_name)
        end
      end
      field :comment
      field :hr_comment
      field :created_at
      field :updated_at
    end
    export do; end
    create do; end
    update do; end
 end
end
````

As you can see on the show and list actions I'm using `pretty_value` and it displays the user.full_name and the station.station_name no problem.  But the main issue I'm having is with the edit action being able to display a drop down of user's with full names instead of User #1 User #2 etc.

I know this probably shouldn't be on the issue list, but the docs for rails_admin don't point me in the right direction and stack is pretty much useless.

If you need any further code or examples, please let me know.

**Comment by teknull** [comment]
I figured this out using enum.

````
edit do
  	  field :clock_in
  	  field :clock_out
      field :user_id, :enum do
        enum do
          User.employee.collect {|p| [p.full_name, p.id]}
      end
    end
  	  field :station_id, :enum do
        enum do
          Station.all.collect {|p| [p.station_name, p.id]}
      end
    end
````

**Comment by zirexba** [comment]
Hey @teknull  I tried your solution but I am still getting object text inside dropdown, what am I doing wrong ? Please check screen shot :https://postimg.org/image/uda502c7r/

**Comment by zirexba** [comment]
After I restarted server rails s now its okay, Works!  Thank you!

**Comment by kasianchuk** [comment]
What should be added to the code to indicate the value that was previously stored, and not the empty input

**Comment by raniaakh** [comment]
why it's not working when i run server on production mode?
