### ISSUE TITLE
Rails admin act as taggable not showing tags

### ISSUE THREAD

**Issue by smander** [sferik/rails_admin#2358]
I have an issue with Rails admin gem and act as taggable gem. I am using heroku. It is just not showing tags, but when i delete tags data and will add new it will show new tags. On localhost it is working too when I delete data from database. It is just blank
```
field :terrains
field :themes
field :activities
field :title do
  label "Tagline"
end    
field :intro do
  label "Overview"
end
field :highlights do
  label "What we love"
end
```

![mrwqvw4](https://cloud.githubusercontent.com/assets/1521305/8679753/3d0ecb36-2a65-11e5-8dd1-d8b3707165f1.png)

**Comment by fmh** [comment]
#2166 
try to define a name or a pretty_name method in your Terrain/Activity models 

`````ruby
class Terrain < AR
 def pretty_name
   self.name # or self.title or other attribute
 end

 rails_admin do
  object_label_method do
      :pretty_name
    end
 end
end
```````

**Comment by mshibuya** [comment]
The newer release does not show the blank box - you'll asked to perform search instead.
a515b37b2959980c60d8878125f6382fd95f9c0e
