### ISSUE TITLE
Doesn't make sense to be able to add/remove :versions in create / edit screens

### ISSUE THREAD

**Issue by pompeyjoe** [sferik/rails_admin#2365]
![image](https://cloud.githubusercontent.com/assets/4830483/8896382/6b744b86-343d-11e5-8166-3650f6bb6b02.png)

**Comment by pompeyjoe** [comment]
Currently, if I plug in paper trail for versioning, when I create or edit an object that has_paper_trail, versions appears as an attribute that I can add / remove versions from.  I can't think of a use case where this makes sense.  At the moment, I'm using:

    rails_admin do
    
        list do
          exclude_fields :versions
        end
    
        show do
           exclude_fields :versions
        end
    
        create do
          exclude_fields :versions
        end
    
        edit do
          exclude_fields :versions
        end
    
        export do
          exclude_fields :versions
        end
      end

**Comment by bbenezech** [comment]
you can do 
```ruby
base do
  exclude_fields :versions
end
```

From RA's POV, there is nothing wrong, and I don't think we should be 'fixing' this.

Thanks for reporting!
