### ISSUE TITLE
Set custom attribute name instead of model's register id

### ISSUE THREAD

**Issue by filipegorges** [sferik/rails_admin#2370]
Hello!

This isn't really an issue with the gem, more like an information request! I'd like to know if it is possible to generate the views/stylesheets from rails_admin somehow, or where can I customize them. 

For example, let's say that I have a car-lending system, and I'd want to set that "X" car belongs to "Y" user, when I'm selecting the cars on my list, I'd see Car #1, Car #2, etc. How can I set it that instead of their IDs, I see a list of their names?

I'm sorry if this is the wrong place to ask, or if this has been answered before, but I really couldn't find this anywhere, the only thing I found was that some time ago you could generate the views via "rails g ...", and now it has been deprecated and you should use the DSL, but through the DSL I can't see/have access to everything I'd like to change, or at least I haven't found out how to use it properly so far D:

Thank you so much for your time!

**Comment by fmh** [comment]
by default rails_admin use name or title attributes as labels.
if you have one of this attribute in your cars model (table), you have nothing to do by default rails_admin use name or title attributes as labels.
if you have one of this attribute in your cars model (table), you have nothing to do. If not, you should add a method in your model and config rails_admin like this :
```` ruby
model cars < AR
 def my_car_name_or_title_or_other
    self.label_attribute # or a string "My super car..."
end 

rails_admin do 
  object_label_method :my_car_name_or_title_or_other
end
end
````
wiki Method for instances label: https://github.com/sferik/rails_admin/wiki/Navigation and https://github.com/sferik/rails_admin/wiki/Base-configuration

**Comment by filipegorges** [comment]
A huge thanks to @fmh for the help and for the really fast reply! The example code ended up like this:

class Car < AR
  def car_model_name
    self.car_model
  end

on my config/initializers/rails_admin.rb

config.model 'Car' do
  object_label_method :car_model_name
end

Thanks again!
