### ISSUE TITLE
Showing fields on specific condition

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sferik/rails_admin#2371]
Hello.

I want to show some fields depending on attributes of user who logged in.

Currently, I use this code to show specific fields on condition:

```
    update do
    include_all_fields
       field :my_field do
            render do
                 if bindings[:view]._current_user._type == 'Owner'
                    bindings[:view].render :partial => "rails_admin/main/#{partial}", :locals => {:field => self, :form => bindings[:form] }
            else
                 ''
            end
         end
       end
    end
```

This gives me some errors on javascript console and has longer loading time when I open that page.

Is there more "elegant" solution for solving this problem?

**Comment by yourivdlans** [comment]
I'm also looking for a good solution to this problem. In my case I want to display a field based on the controller.

In your case I think you can use `bindings[:view].controller.current_user`.

Right now I have something like this, but its not a very elegant solution.

```ruby
edit do
  field :key do
    read_only do
      if bindings[:form].options.key? :parent_builder
        bindings[:form].options[:parent_builder].options[:as] == 'model_name'
      else
        false
      end
    end
  end
end
```

**Comment by SuperMasterBlasterLaser** [comment]
@yourivdlans this gem is too far from having version 1.0 :).

**Comment by yourivdlans** [comment]
Word :)
