### ISSUE TITLE
Using CanCan authorization on custom action

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sferik/rails_admin#2375]
Hello.

I have forked rails_admin_charts gem, which is custom action for rails_admin.

It shows number of models as graph and uses `self` method to query database.

When admin logs in, he can see in graph all models. However, when user logs in he also sees all models.

How to make custom action to get only user's models to show it on graph?

**Comment by mshibuya** [comment]
You can call authorization adapter in your custom action, like: https://github.com/sferik/rails_admin/blob/9abc1be0c1fee006a7a746583461891911fe9330/lib/rails_admin/config/actions/dashboard.rb#L29

**Comment by SuperMasterBlasterLaser** [comment]
Wow, answer after 4 years 😆. At least it wasn't completely forgotten.
