### ISSUE TITLE
Browser validations break save on persisted objects with images

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#2376]
Let's say we have a model with an image

```rb
class Player < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :image, presence: true
end
```

Saving a new object or editing the image is fine
![screen shot 2015-08-10 at 15 44 50](https://cloud.githubusercontent.com/assets/556268/9172910/e1ed4828-3f76-11e5-916b-b9b224f98d4f.png)

but when you try to save a persisted model without editing the image, you get a validation error on the file upload field

![screen shot 2015-08-10 at 15 45 22](https://cloud.githubusercontent.com/assets/556268/9172923/fd2205ca-3f76-11e5-85ce-93ace963a712.png)

Refers to #2339 #2373

**Comment by mshibuya** [comment]
Merged #2373.

**Comment by tagliala** [comment]
btw this is still an issue with browser validations activated (default behaviour)

This should be reopened

**Comment by mshibuya** [comment]
Fixed now, thanks!

**Comment by dalpo** [comment]
:+1: Thanks!

**Comment by tagliala** [comment]
thanks and sorry for not submitting a PR myself
