### ISSUE TITLE
Can I separate rails_admin block from model ?

### ISSUE THREAD

**Issue by TangMonk** [sferik/rails_admin#2380]
for example:

I have User model and rails_admin define:

```ruby
class User < ActiveRecord::Base
  
   rails_admin do
     field :name
   end
end
```

If I create a folder at `app/admin/user_admin.rb`, And how can I separate `rails_admin` block to `app/admin/user_admin.rb`?

is it possiable?

**Comment by mshibuya** [comment]
Using mix-in will work:

`app/models/user.rb`
```ruby
class User < ActiveRecord::Base
  include UserAdmin
end
```

`app/admins/user_admin.rb`
```ruby
module UserAdmin
  extend ActiveSupport::Concern
  included do
    rails_admin do
      field :name
    end
  end
end
```

**Comment by TangMonk** [comment]
nice job!, thanks :+1:
