### ISSUE TITLE
Release master as a new gem version

### ISSUE THREAD

**Issue by sferik** [sferik/rails_admin#2382]
It’s been a couple months since the last official release. In that time, there have been about [50 commits](https://github.com/sferik/rails_admin/compare/v0.6.8...master) with all sorts of new features and bug fixes.

It looks like [the tests are passing](https://travis-ci.org/sferik/rails_admin) and [the dependencies are up-to-date](https://gemnasium.com/sferik/rails_admin). I just wanted to make sure there were no other almost finished features or fixes to get into the release before I cut it.

What do you think @mshibuya? You have a better sense of the open issues and pull requests than I do.

I guess the release should be versioned 0.7.0 (instead of 0.6.9), since it includes some new features (e.g. enum support), not just bug fixes. Very nice work on that, by the way!

**Comment by mshibuya** [comment]
Releasing as 0.7.0 would be fine, I'll do that.

**Comment by mshibuya** [comment]
:ship:

**Comment by fmh** [comment]
🎉🎉🎉

**Comment by dalpo** [comment]
Great release! Thanks guys! :smiley:
