### ISSUE TITLE
Display full name instead of User#1

### ISSUE THREAD

**Issue by simkessy** [sferik/rails_admin#2390]
I applying the solution I found here: http://stackoverflow.com/questions/11658281/rails-admin-display-name-instead-of-id

It works well enough until when I go to the users table and try to create a new user, I get 
`undefined method '+' for nil:NilClass`

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
