### ISSUE TITLE
Broken Client Side Validation for filtering select

### ISSUE THREAD

**Issue by cec** [sferik/rails_admin#2398]
Hi,

when a required attribute is left empty, upon form submission, a tool-tip is shown on the field.

When the required attribute is a relation, the client-side navigation **does not work**.

In Chrome there is no visible reaction, but in the console the following error pops up:
`An invalid form control with name='property[feature_id]' is not focusable.`

In Firefox, the tooltip shows up in a completely wrong location (see picture below).

I'm pretty sure the the cause is that for filtering-select, the **invisible select tag** has the attribute
`required="required"`
and this freaks out Chrome and breaks the positioning of the tooltip on Firefox.

I believe that for associations, the required attribute needs to be moved to the visible controls.

![screen_shot_2015-09-10_at_15_28_02](https://cloud.githubusercontent.com/assets/386155/9789471/a51f45d2-57d0-11e5-85f6-879f32c062af.jpg)

I'd gladly contribute a pull-requrest myself, but I don't understand very much the form-rendering logic in rails-admin.

**Comment by fmh** [comment]
look her #2339

**Comment by SuperMasterBlasterLaser** [comment]
Maybe related to my issue #2492

**Comment by vemv** [comment]
@SuperMasterBlasterLaser it is, so your issue is a duplicated one.

I suggest to close - a high issue count isn't precisely motivating!

**Comment by JIucToyxuu** [comment]
I'm have same problem.

I'm have required field on model and use Enumeration for generate select-box with values. Generated <select> be hidden and have attribute 'required'. It's see like logic error. I think disable HTML validation it's not best solution, because then we will have more requests to server(HTML validation prevent many requests with invalid data). Plus, `config.browser_validations = false` will disable HTML validation for all input elements of rails_admin application.

**Comment by ain** [comment]
Reproduced in for `1.1.0`. Also prevents visible controls to be highlighted, the JavaScript console throws
```
An invalid form control with name='product[product_category_ids][]' is not focusable.
```

Flash notifications do not appear either. Probably because of the JS breakdown. 

I'm calling for escalation, definitely not closure.

**Comment by ivercinsky** [comment]
Hi, anyone found a way to fix this issue?

**Comment by JIucToyxuu** [comment]
No =)

**Comment by williamherry** [comment]
#2905 check this fix
