### ISSUE TITLE
How to create custom action like Export Found ?

### ISSUE THREAD

**Issue by tmacbg** [sferik/rails_admin#2406]
I'm trying to make a custom action that has the functionality of export found - to apply action to all filtered items .

for now I have : 
if request.post?
                @objects = @model_config.abstract_model.scoped

But this works if I predefine scope but not for randomly applied filters.

Any help will be useful .

**Comment by bbenezech** [comment]
This is the issue tracker, if you have a road block, we'd be happy to help, otherwise please try stackoverflow.
You should start with the wiki, then read RA implementation of similar actions.

Good luck!
