### ISSUE TITLE
Only Displaying 5 Records

### ISSUE THREAD

**Issue by JMKelley** [sferik/rails_admin#2415]
My rails_admin is only displaying max 5 records, for the life of me I can't find anywhere in your documentation on how to change the limit? or remove a limit completely?

![image](https://cloud.githubusercontent.com/assets/2053555/10219468/12bcd7dc-6837-11e5-9c98-81bed3b13c6b.png)

Displaying above on my admin dashboard. Ran through Base Configuration.

**Comment by mshibuya** [comment]
There's nothing in RailsAdmin to apply such a limitation.
Providing more information like models and RailsAdmin configuration might help.
