### ISSUE TITLE
false values not displayed in show view when compact_show_view is set to true

### ISSUE THREAD

**Issue by benhutton** [sferik/rails_admin#2416]
I want to keep `compact_show_view = true`, which I understand to be defined as "anything non-nil should show up in show view"

I have a boolean field, and thus I want it to show up in show view when it is set to `false`:

```
> false.nil?
 => false
```

The [show template](https://github.com/sferik/rails_admin/blob/master/app/views/rails_admin/main/show.html.haml#L11) does properly use `#nil?` as the check for whether or not to display values: 

```
- unless values[index].nil? && RailsAdmin::config.compact_show_view
```

The problem is that the `values` array [is constructed](https://github.com/sferik/rails_admin/blob/master/app/views/rails_admin/main/show.html.haml#L3) by calling `#presence` on the `formatted_value`:

```
values = fields.map{ |f| f.formatted_value.presence }
```

Unfortunately,

```
> false.presence
 => nil
```

so

```
> false.presence.nil?
 => true
```

**Comment by begedin** [comment]
:+1:  for this. 

As an additional argument for this being considered a bug, we have a `pretty_value` defined for the boolean field type at https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/boolean.rb#L13

```Ruby
register_instance_option :pretty_value do
  case value
  when nil
    %(<span class='label label-default'>&#x2012;</span>)
  when false
    %(<span class='label label-danger'>&#x2718;</span>)
  when true
    %(<span class='label label-success'>&#x2713;</span>)
  end.html_safe
end
```
