### ISSUE TITLE
CKEditor integration failing for applications deployed under a subdir (relative_url_root)

### ISSUE THREAD

**Issue by cec** [sferik/rails_admin#2420]
Hi, 

I have deployed a rails 4.2 app using rails_admin 0.7 on a server, under *host/poi_database*.

In config/environments/production.rb I set **config.relative_url_root = '/poi_database'**.

When I visit the rails_admin backend, assets are properly loaded, with one exception: 
my CKEditor fields are not being loaded (see picture).

Chrome's console logs a 404 **host/assets/ckeditor/ckeditor.js**
but the correct URL would be
host/**poi_database/**assets/ckeditor/ckeditor.js

I precompiled the assets with 

`RAILS_ENV=production RAILS_RELATIVE_URL_ROOT=/poi_database bundle exec rake assets:precompile`

and the ckeditor assets have been compiled.

**relative_url_root** is ignored.
Am I missing something?
Could this be hardcoded path somewhere in the code?

![screen_shot_2015-10-05_at_18_53_25](https://cloud.githubusercontent.com/assets/386155/10287313/8257362e-6b92-11e5-8fca-c301e7736456.jpg)

**Comment by cec** [comment]
I found the cause: a bug in **lib/rails_admin/config/fileds/types/ck_editor.rb:24**
`"#{Rails.application.config.assets.prefix}/ckeditor/"`
is ignoring the *relative_url_root* configuration.

I made a PR #2422 let me know if this is ok for you guys

**Comment by mshibuya** [comment]
Just setting `config.assets.prefix` to desired value in `config/environments/production.rb` should be enough.

**Comment by cec** [comment]
@mshibuya it is enough indeed.

The reason why I looked for another way is that in the past I had trouble using *config.relative_url_root* and *config.assets.prefix* together (I was getting urls with a double relative_root), but this it not the case anymore.

Thank you
