### ISSUE TITLE
Preventing N+1 queries via includes

### ISSUE THREAD

**Issue by dmitrypol** [sferik/rails_admin#2427]
I love RailsAdmin for basic things but it causes lots of N+1 queries to lookup data.  Is there a way to force it to use includes type query optimizations?

**Comment by fedelcar** [comment]
Is there a way to prevent this? It's kind of a big deal

**Comment by marlborox** [comment]
I have the same question. Have any solutions?

**Comment by jamesfzhang** [comment]
This is a major problem with Rails Admin. For any application at scale, the N+1 queries are a big deal.

**Comment by mshibuya** [comment]
Closed by b92a4d1a30b706d08df2aee4d0a59dad698a0552.

**Comment by StarWar** [comment]
For form with nested associations on edit page, I'm seeing lots of pop ups from bullet. It's still an issue. Is there a configuration option, I should use to enable include. I have several polymorphic associations in a form.

**Comment by ziaulrehman40** [comment]
Anyway somebody resolved this manually or someway other than waiting for updates from maintainer?

**Comment by ziaulrehman40** [comment]
Ok, here is an update, for anyone who is looking for a solution to avoid bullet checks for rails_admin(as not lot of users use rails_admin and it may not worth all the effort to fix eager_load issues in rails_admin flows). 
I provided a custom parent controller like `config.parent_controller = "RailsAdminParentController"` with obviously `RailsAdminParentController` defined in controllers folder following is the definition of that controller

```
class RailsAdminParentController < ApplicationController
  around_action :skip_bullet

  def skip_bullet
    previous_value = nil
    if test_or_dev?
      previous_value = Bullet.enable?
      Bullet.enable  = false
    end
    yield
  ensure
    Bullet.enable = previous_value if test_or_dev?
  end

  def test_or_dev?
    Rails.env.development? || Rails.env.test?
  end
end

```

Hope it helps someone.

**Comment by deepeeess** [comment]
@ziaulrehman40 if anybody ever tells you that you are not the man they are straight up lying - thank you.
