### ISSUE TITLE
How to sort by custom fields in list view

### ISSUE THREAD

**Issue by dmitrypol** [sferik/rails_admin#2433]
In RailsAdmin I can easily create custom fields either by defining a method on the model and including it via field :custom_method or formatted_value like this: field :custom_field do formatted_value{ bindings[:object].something_here } end

The problem is I cannot sort by that column in list view. Anybody have experience with this?

I am using RoR 4.1 with RailsAdmin 0.6.8

**Comment by stevetwitte** [comment]
I am also trying to sort by a custom column in list view any help would be greatly appreciated.

**Comment by bbenezech** [comment]
You can sort with an underlying column, but not with the value itself (RailsAdmin only support sorting with the DB).
Please use the sortable :children_fields api : https://github.com/sferik/rails_admin/blob/29e22a5f4d396f0d1a3c14ce368efaa5c5193a70/lib/rails_admin/config/fields/base.rb#L215

**Comment by aryehbeitz** [comment]
```
has_one :person, through: :pet, source: :person
default_scope { eager_load(:person) }
...

list do
  filters [:person]
  field :person do
    queryable true
    searchable :id
    filterable true
 end
```

**Comment by FunkyloverOne** [comment]
Hey, @ayerdines I believe this is now covered here:
https://github.com/sferik/rails_admin/wiki/List#fields-sorting
