### ISSUE TITLE
Help. Understanding of custom actions. AASM + rails_admin

### ISSUE THREAD

**Issue by rstormsf** [sferik/rails_admin#2437]
Hi, I've read readme on custom actions. Honestly, it's not really user-friendly manual or I'm stupid. 
I'm trying to debug https://github.com/zcpdog/rails_admin_aasm
there are 2 pull requests, I've tried to install those as well. - still no luck.
Issue: I can't understand what `state_event` method should do https://github.com/zcpdog/rails_admin_aasm/blob/master/lib/rails_admin_aasm/field.rb#L107

2) when I choose a state from rails_admin - event is not being triggered.
I do understand that I shouldn't report here, but since maintainer is not active, I want to have some understanding and I've tried my best to understand the problem. Any help is appreciated.

3)Can't understand when this method is called.
https://github.com/zcpdog/rails_admin_aasm/blob/master/lib/rails_admin_aasm/action.rb#L22-L46
I've tried to put breakpoints and it never calls.

4)How would you solve this problem? Basically, when event is selected, it needs to call the event method before model is updated/saved.

5)https://github.com/zcpdog/rails_admin_aasm/blob/master/lib/rails_admin_aasm/action.rb#L50
Should be `:put` method added as well?

6)I can throw away aasm, if you tell me some better alternative that works well with Rails_admin. 
State_machines looks like are not being maintained. 

7)Is there something missing from this gem in order to work with rails_admin?

Please help!

**Comment by rstormsf** [comment]
Looks like Custom action is not what needed. What is needed is to modify Edit action to handle state property differently if changed.

**Comment by mshibuya** [comment]
No updates, closing.
