### ISSUE TITLE
Uploading files from modal view doesn't work

### ISSUE THREAD

**Issue by AlexKlim** [sferik/rails_admin#2442]
When I try to create some object via modal view (modal view contains file upload field) rails_admin sends a broken params 

> Processing by RailsAdmin::MainController#new as JS
>  Parameters: {"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object”=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>{","=>{"object Object"=>nil}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}, "model_name"=>"some_name"}

Any ideas how can I fix it ?

Thanks.

**Comment by mshibuya** [comment]
This should work now, as is confirmed by the test.
https://github.com/sferik/rails_admin/blob/f67defb55ad9d1a1fe8428029c947bcd00b5ce8a/spec/integration/widgets/remote_form_spec.rb#L88-L107
