### ISSUE TITLE
How to pass a form object to the partial fields

### ISSUE THREAD

**Issue by Rattt** [sferik/rails_admin#2452]
I am use it

## Config

```ruby
config.model 'Product' do
    edit do
      field :data do
        partial :my_price_hash_partial, locals: { field: self, :form => bindings[:form] }
      end
    end
  end
```
## Partial code

```ruby
<% field.object.prop_hash.each do |name, value| %>
    <div class="field">
      <%= label_tag name %>
      <%= text_field_tag "product[data][#{name}]", "" %>
    </div>
<% end %>
```
## And Error

But the form object is not defined.
partial :my_price_hash_partial, locals: { field: self, :form => bindings[:form] }
undefined method `[]' for nil:NilClass

How to get the form object?

**Comment by ricardoccpaiva** [comment]
did you manage to solve this @night1ightning ?

**Comment by rob-mcgrail** [comment]
@ricardoccpaiva same question :D
