### ISSUE TITLE
Is there any way get current ip in each update?

### ISSUE THREAD

**Issue by say8425** [sferik/rails_admin#2458]
Hello. I have model has `name`, `url` and `ip`.
And I want to make current ip will be inputted in `ip` when creating or updating.
But you know `request.remote_ip` can not use in model.
And I fount rails_admin config, too.

I try this code
```ruby
# rails_admin.rb
config.model 'Creator' do
    include_all_fields
    edit do
      field :ip, :hidden do
        default_value request.remote_ip
      end
    end
  end
```

But it's not work. Exactly, noting was inputted.
And I have one more question. `default_value` is only works on `create`.
Dose any method works on `update`, too?

**Comment by bbenezech** [comment]
you can access the request object through bindings[:controller]
default_value for update is not supported. You can try something inside your model though.
