### ISSUE TITLE
Error when go to detail page after signout and sign in to rails admin.

### ISSUE THREAD

**Issue by chungphuoc** [sferik/rails_admin#2459]
To reproduce the bug:
1/ Sign out of admin panel.
2/ Sign in to admin.
3/ Go to a detail page of any model. The error will appear
![selection_012](https://cloud.githubusercontent.com/assets/3130979/11029101/099cd376-86f7-11e5-932d-471df8fadb7b.png)

Anyone meet this problems?

Regards,

**Comment by mshibuya** [comment]
Please take a look at #2027.
