### ISSUE TITLE
How do you uninstall rails admin?

### ISSUE THREAD

**Issue by gjackson12** [sferik/rails_admin#2462]
I've tried to run the rake task: 
```
rake rails_admin:uninstall 
```
and it doesn't appear to be working. The error I get: "Could not find generator 'rails_admin:uninstall'. Maybe you meant 'rails_admin:install' or 'rails_config:install' or 'annotate:install'
Run `rails generate --help` for more options." This appears to be accurate as I don't see that generator in the master branch.

**Comment by hut8** [comment]
1) Remove the gem from the Gemfile and run `bundle`
2) Remove the `mount RailsAdmin::Engine => ...` from your `config/routes.rb`
3) Remove `config/initializers/rails_admin.rb`

That's the opposite of what the `InstallGenerator` class does, so that should be it.

**Comment by gjackson12** [comment]
Thanks!

**Comment by gjackson12** [comment]
Just to be sure, there are no tables or migrations of any sort that were ran as a part of the install generator?

**Comment by hut8** [comment]
`rails_admin`'s installation generator does not make migrations. It does lots of introspection, but needs no tables of its own.
