### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$navbar-height"

### ISSUE THREAD

**Issue by D7na** [sferik/rails_admin#2466]
Hi. I'm trying to run a project using the rails_admin gem on heroku, but get the following error when performing assets:precompile:
remote:        I, [2015-11-12T23:13:37.913854 #908]  INFO -- : Writing /tmp/build_be9e6f7c3fc8b833cd6ab95c29eeb71b/public/assets/rails_admin/base/mixins-3e0cccbb54e2038718c2b538a370d24f.css
remote:        rake aborted!
remote:        Sass::SyntaxError: Undefined variable: "$navbar-height".
remote:        (in /tmp/build_be9e6f7c3fc8b833cd6ab95c29eeb71b/vendor/bundle/ruby/2.0.0/gems/r    ails_admin-0.7.0/app/assets/stylesheets/rails_admin/base/theming.scss:16)

Can anyone help me with it?

**Comment by depl0y** [comment]
Getting the same error precompiling my assets.

**Comment by say8425** [comment]
I have same error

**Comment by say8425** [comment]
I solve [this issue](http://stackoverflow.com/questions/9915950/bootstrap-sass-undefined-variable-baselineheight). 
```
Rails.application.config.assets.precompile += %w( *.css *.js )
```
In `/config/initializers/assets.rb`, if you load all css with wildcard then it load partial page firstly. So it makes error.

I solve this problem with loading each css.

```
Rails.application.config.assets.precompile += %w(
application.css apply.css articles.css common.css
company.css creators.css home.css portfolio.css scaffolds.css
external/*.css home/*.css navigation/*.css
 *.js )
```

Of course, I think better solution'll be existed. And [this SO](http://stackoverflow.com/questions/9138946/proper-scss-asset-structure-in-rails) will be helps you.

**Comment by agrun** [comment]
Hi. I have a similar issue with precompiling under jruby 9.0.4.0 (2.2.2).

When running rake assets:precompile --trace I get:

> Sass::SyntaxError: Undefined variable: "$navbar-height".
> X:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/rails_admin-0.8.1/app/assets/st
> ylesheets/rails_admin/base/theming.scss:16
> X:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/sass-3.4.21/lib/sass/script/tre
> e/variable.rb:49:in `_perform'
> X:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/sass-3.4.21/lib/sass/script/tre
> e/node.rb:50:in `perform'
> X:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/sass-3.4.21/lib/sass/tree/visit
> ors/perform.rb:395:in `visit_prop'
> X:/jruby-9.0.4.0/lib/ruby/gems/shared/gems/sass-3.4.21/lib/sass/tree/visit
> ors/base.rb:36:in `visit'
>  ...


Could anybody help me, please?

**Comment by say8425** [comment]
Check your precompile assets. Your assets will be loaded with wild card.

**Comment by agrun** [comment]
Thank you for your answer. I have already 

```
Rails.application.config.assets.precompile += %w( *.css *.js )
Rails.application.config.assets.precompile += %w(rails_admin/rails_admin.css rails_admin/rails_admin.js)
```

in my assets file. Still it won't work.

**Comment by say8425** [comment]
This issue is caused by `wild card`. Please read my answer again.

**Comment by agrun** [comment]
Yes, it worked fine

**Comment by bbenezech** [comment]
`Rails.application.config.assets.precompile += %w( *.css *.js )` sounds like a VERY bad idea. Please don't do this. It will break any css variable cross-dependencies.
