### ISSUE TITLE
CanCan::AuthorizationNotPerformed still persisting

### ISSUE THREAD

**Issue by chrisvel** [sferik/rails_admin#2469]
Hi all,

I am trying to work with Cancancan/Devise (latest versions) and Rails 4.2.1 but I am still getting this exception. I have tried with `check_authorization :unless => :devise_controller?`, `check_authorization :unless => (:devise_controller? || :rails_admin_controller?)` and `check_authorization :unless => : rails_admin_controller?` alone, but nothing works. 

If I comment them out, my RailsAdmin instance loads and everything looks fine. Any ideas ?

**Comment by bbenezech** [comment]
RailsAdmin only deals with explicite auth:
```
RailsAdmin.config do |config|
  config.authorize_with :cancan, AdminAbility
end
```

You probably have a problem with Cancancan's API, not RailsAdmin.
