### ISSUE TITLE
Will rails_admin work with Rails 5 --api?

### ISSUE THREAD

**Issue by goocastro** [sferik/rails_admin#2471]
Since most of _view-specific_ gems and midlewares are not present in **API-Only** Rails 5 project, will rails_admin work? Do I have to manually add something?

**Comment by NuckChorris** [comment]
Should theoretically still work since this is a self-contained Rails Engine

**Comment by goocastro** [comment]
Going to download --edge and test it tonight. 
:+1:

**Comment by mayank-istar** [comment]
did that worked @goocastro

**Comment by bbenezech** [comment]
Waiting for first RC ;)
