### ISSUE TITLE
When will the next gem release be?

### ISSUE THREAD

**Issue by vincentwoo** [sferik/rails_admin#2472]
I've been pegged to master for a while.

**Comment by mshibuya** [comment]
It will be very soon, but one release-blocker is left:

- [ ] #2474

**Comment by sferik** [comment]
@mshibuya Now that #2474 is resolved, are we ready to make a new release or are there some other issues you’d like to address first?

**Comment by mshibuya** [comment]
I'm now woking on another fix(which addresses #2467's scenario 1), so please give me a little time to finish it.

**Comment by dalpo** [comment]
`v0.8.0` has beed released! https://github.com/sferik/rails_admin/commit/4a7dfe908ac5c427f802b82ab9e6f90cb5d48947 :fireworks:

**Comment by mshibuya** [comment]
Done! :shipit:
