### ISSUE TITLE
Bulk Email custom action

### ISSUE THREAD

**Issue by dekhaus** [sferik/rails_admin#2473]
Hi All

  I need some help adding Bulk/Batch Email functionality to my RailsAdmin backed Rails app.   Conceptually - this bulk email functionality is similar to the built-in bulk-delete - in that a set of records will be selected on the index page which are then 'processed' on the 'bulk action' (for lack of a better term) page.

  The difference being that when the 'bulk email' batch function is clicked (by selecting the Bulk Email tab icon/button) the user will be taken to a page where they can a) review the set of 'things' selected on the previous index page and b) enter the text for the bulk email by filling in text input fields (subject, message, etc...).

  With all this in mind - I created a custom action plugin called 'rails_admin_batch_email'.  The custom action was created using the 'plugin' gem creation method.  I updated my Gemfile, ran bundle and everything works fine.

  I then customized the rails_admin_batch_email.rb file as follows (essentially copying what I thought made sense from lib/rails_admin/config/actions/bulk_delete.rb) ...

require "rails_admin_bulk_email/engine"

module RailsAdminBulkEmail
end

require 'rails_admin/config/actions'

module RailsAdmin
  module Config
    module Actions
      class BulkEmail < Base
        RailsAdmin::Config::Actions.register(self)

        register_instance_option :collection do
          true
        end

        register_instance_option :link_icon do
          'icon-envelope'
        end

        register_instance_option :http_methods do
          [:get, :post]
        end

      end
    end
  end
end

  I also updated my en.yml file to include any strings that I want to display.

  I then replaced the contents of my 'view' file (rails_admin_bulk_email/app/view/rails_admin/main/bulk_email.html.haml) with the contents of the the bulk_delete 'view' file (app/views/rails_admin/main/bulk_delete.html.haml).

  Lastly - I updated my rails_admin initializer to reference the custom action.

  When I select some of model records from the list view and click the 'Bulk Email' bulk action - I get the following error ...

    "undefined method `rails_admin_default_object_label_method' for nil:NilClass"

  Any idea(s) why ?  

  My thought is that I missed some step thas actually collects the records I selected on the 'index' page and because this step was missed there are no selected records when I get to my view page (which is just a copy of the bulk delete page).

  Any help would be greatly appreciated.

Thanks
Dave

**Comment by bbenezech** [comment]
you need to implement some contoller logic:

```ruby

register_instance_option :controller do
   proc do
     @objects = list_entries(@model_config, :destroy)
   end
end
```

You can use https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/bulk_delete.rb#L15
as a startup template.

Cheers!
