### ISSUE TITLE
Password Protecting Rails_Admin

### ISSUE THREAD

**Issue by bilalmajeed** [sferik/rails_admin#2480]
Hey, first of all, thanks for making this gem. I love it

But I have a question is it possible to password protect the rails_admin page without using devise or cancan. I just want it to so that, when you go to the page, it prompts you to enter a password and then displays the page after verification.

Thanks

**Comment by maximski** [comment]
You need to build that authentication part yourself. I don't know why you would not want to use devise for that.

**Comment by bilalmajeed** [comment]
I just assumed you guys might have a built in feature for this. But your right, I ended up creating my own authentication part.. 

Thanks
