### ISSUE TITLE
When using the "Add new (model_name)" button and removing it afterwards you can't save anymore

### ISSUE THREAD

**Issue by voyera** [sferik/rails_admin#2485]
I have a model named "Trip" with another named "Itinerary".

The relations goes as follow:
* A Trip has many Itinerary.
* Trip accepts_nested_attributes_for Itinerary - allow_destroy: true

When editing a Trip, I decide to click the "Add new Itinerary" button twice... but figure that I only need to add one for that Trip so I remove one of them clicking the red remove button (with the garbage bin icon). 

Once that's done, I can't submit the form anymore. This is happening because it seems like rails_admin only hides the deleted item. Since I validate the presence of some fields, the form isn't able to submit since those, now deleted, fields aren't filled.

I hope this is clear enough for someone to understand, don't hesitate if you have any questions! :)

**Comment by SuperMasterBlasterLaser** [comment]
I think there is discussion about it. #2443

**Comment by SuperMasterBlasterLaser** [comment]
Look at #2490

**Comment by mshibuya** [comment]
Dup of #2443.
