### ISSUE TITLE
rails_admin 0.8.1 mongoid issue

### ISSUE THREAD

**Issue by Nekromancer** [sferik/rails_admin#2489]
Issue while filtering sth gives me that stacktrace:

```
NoMethodError (undefined method `from_string' for nil:NilClass):
  vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/config/fields/types/bson_object_id.rb:38:in `parse_value'
  vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/abstract_model.rb:115:in `parse_field_value'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/adapters/mongoid.rb:115:in `block in query_conditions'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/adapters/mongoid.rb:114:in `each'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/adapters/mongoid.rb:114:in `query_conditions'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/adapters/mongoid.rb:40:in `all'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/controllers/rails_admin/main_controller.rb:131:in `get_collection'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/controllers/rails_admin/main_controller.rb:37:in `list_entries'
  vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/config/actions/index.rb:30:in `block (2 levels) in <class:Index>'
  /usr/home/media30/domains/apki.org/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
```

On adress (for example) `http://apki.org/admin/user?model_name=user&utf8=%E2%9C%93&query=wold`

Before update (on version 0.7) everything worked just fine.

**Comment by dalpo** [comment]
May be related with: https://github.com/sferik/rails_admin/commit/cee8a5a202b92034cf04ef6021d652967d6d1100

Could you try to monkey patch the rails_admin `BsonObjectId` field class and put the follow lines into an initializer?

```ruby
require 'rails_admin/config/fields/types/string'
require 'rails_admin/config/fields/types/bson_object_id'
require 'mongoid'

module RailsAdmin
  module Config
    module Fields
      module Types
        class BsonObjectId < RailsAdmin::Config::Fields::Types::String
          OBJECT_ID = begin
            if defined?(Moped::BSON)
              Moped::BSON::ObjectId
            elsif defined?(BSON::ObjectId)
              BSON::ObjectId
            end
          end
        end
      end
    end
  end
end
```

Does it work?

**Comment by Nekromancer** [comment]
Yes. this code does the trick. Any plans to fix this in future release?

**Comment by dalpo** [comment]
I hope to make a PR with more specs soon!

**Comment by Nekromancer** [comment]
Great, thanks a lot :)

**Comment by SuperMasterBlasterLaser** [comment]
@dalpo  Sorry for offtopic. There are some drawbacks in displaying Date in this gem. It shows only in UTC. For example I need GTC, some use PST. I needed to use monkey patch.

http://stackoverflow.com/questions/21370504/how-to-set-the-time-zone-of-datetime-values-in-railsadmin

**Comment by dalpo** [comment]
@SuperMasterBlasterLaser Are you using mongoid?
Is related to this issue https://github.com/sferik/rails_admin/issues/1545?

Could we move the discussion on that issue, or eventually to a new one?

**Comment by SuperMasterBlasterLaser** [comment]
@dalpo Ohh.. That issue has been already fixed on current version. I have updated gem only yesterday.

**Comment by dalpo** [comment]
No worries :wink:

**Comment by Nekromancer** [comment]
Any chance for fix? I'm operating on monkey patch but it's pretty ugly ;)

**Comment by dalpo** [comment]
@mshibuya this PR https://github.com/sferik/rails_admin/pull/2495 should fix the issue. :wink:

**Comment by mshibuya** [comment]
:smiley_cat:

**Comment by dalpo** [comment]
Thanks @mshibuya :wink: 
 Btw, what do you think about to release a new rails_admin `v0.8.2` with the related fix?

@Nekromancer do you confirm that the current master works well with mongoid?

**Comment by Nekromancer** [comment]
@dalpo Yes, current master works fine. I'd love v0.8.2 too :)
