### ISSUE TITLE
Form control with name is not focusable error on browser.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sferik/rails_admin#2492]
After solving issues of nested models, I have encountered new problem. 

For example you have `Parent` and `Child` model. `Parent` has many `Children`. `Child` has validation of precense of `Parent`.

In rails_admin when you try to create `Child` and not assign Parent then click to Save. It gives Javascript error: 

        An invalid form control with name='child[parent_id]' is not focusable.
![1](https://cloud.githubusercontent.com/assets/8684688/11492933/86a9a5c4-981d-11e5-9e6d-e65a75b071a4.PNG)

And I have found why this is happening. This drop-down form element **is not drop-down at all**. It is input text field with autocomplete Jquery functionality.

The real select field that assigns Parent to Child is here:

![2](https://cloud.githubusercontent.com/assets/8684688/11492984/15bab5be-981e-11e5-9c73-174ee0ad86b8.PNG)

HTML inspector shows that select field that assigns parent has **`display:none` style among with required type!**. 

When user clicks to Save and this field is empty, browser validation will be promted. Browser tries to focus to it, because it has `display:none` value it throws javascript error that is mentioned above.

**Comment by SuperMasterBlasterLaser** [comment]
This could be resolved by using this code:

    RailsAdmin.config do |config|
      config.browser_validations = true
    end

This makes browser side validations useless.

**Comment by JIucToyxuu** [comment]
It's not solution, but dirty hack. Because will disabled all HTML validation.

**Comment by AlexWheeler** [comment]
setting style to `opacity:0;pointer-events: none; cursor: default;` over display: none could fix this problem.  It is hidden (although still in the dom) and focusable.  Might be worth looking into.

**Comment by ivercinsky** [comment]
i have the same issue but with ck_editor. 

I fixed the select with using the suggestion of AlexWheeler but i cant hook the js function to change the css properties of the ck_editor. 

Does anyone have had this issue ?

Thanks

**Comment by Zmokizmoghi** [comment]
Same here
gem version: rails_admin (1.2.0)

**Comment by bpicolo** [comment]
@SuperMasterBlasterLaser  this shouldn't have been closed. Validations are totally busted for required fields that get autocomplete dropdowns

**Comment by fatosmorina** [comment]
I had the same issue. I figured out that I had set `required true` for a relation that I was not filling in when I was adding a new element. Removing `required true` solved my issue.
