### ISSUE TITLE
How do I do custom bulk action?

### ISSUE THREAD

**Issue by tiagoovieira** [sferik/rails_admin#2493]
I want to create a bulk action, like export and delete, but to do a bulk update of an attribute in the database. In my case I want to change all the selected objects attribute `status` from false to true. How would I do that? I'm struggling with the documentation to create custom actions

**Comment by dmitrypol** [comment]
I wrote a blog post on it http://dmitrypol.github.io/2015/09/10/rails_admin.html.  I would add something like this to the custom action.  
register_instance_option :bulkable? do
  true
end

**Comment by streetlogics** [comment]
I found this thread and ended up digging through the code to come up with an answer myself. So - here is my question + answer thread on Stackoverflow for anyone else that comes across this - https://stackoverflow.com/questions/57838401/how-do-i-create-a-custom-bulk-action-in-rails-admin/57838402
