### ISSUE TITLE
When filtering it filters on model but it would be nice if it also filtered on related models

### ISSUE THREAD

**Issue by voyera** [sferik/rails_admin#2494]
I have the following model named Reservation

it belongs_to Trip and User

Ideally I would like the option to filter the reservation by a Trip's name for example.  Is this already implemented, because right now it doesn't allow me to. The only things I can filter are the actual Model's information which is the trip_id and user_id.

**Comment by dalpo** [comment]
Take a look at the "_Fields searching_" section of https://github.com/sferik/rails_admin/wiki/List

**Comment by voyera** [comment]
Thank you @dalpo ! Closing the issue :)
