### ISSUE TITLE
font-awesome <i> elements need "fa" class

### ISSUE THREAD

**Issue by vemv** [sferik/rails_admin#2496]
While font-awesome loads correctly, the rails_admin-generated `<i>` element is incomplete.

![image](https://cloud.githubusercontent.com/assets/1162994/11590693/2cbe3116-9a92-11e5-8840-8ad6157f3264.png)

It needs the 'fa' class in addition to the already added 'fa-times' (or fa-whatever) class.

**Comment by vemv** [comment]
Actually adding 'fa' wasn't enough.

My fix was discarding the whole FA class translation mechanism rails_admin uses.

https://github.com/vemv/rails_admin/commit/77788dc03af33dab4a31e40d4f23d8692f1ec95e

**Comment by bbenezech** [comment]
Looks like everything is back in order. Thanks!
