### ISSUE TITLE
Query limit disappears when overriding scope to unscoped 

### ISSUE THREAD

**Issue by knovoselic** [sferik/rails_admin#2497]
Hi,

somewhere in the wiki I found a way to force RailsAdmin to use `unscoped` scope, instead of the `default_scope`, like this:

    list do
      scopes [:unscoped]
    end

It does work, but unfortunately it also gets rid of query limit. Instead of setting the limit to 20, it sets it to 0 and tries to load my whole DB.

Is this supposed to happen or is this a bug? Is there a way to use `unscoped` with correct limit?

Thanks!

**Comment by CollinGraves** [comment]
If I'm not mistaken, the scope limiting is happening in `config.fields.association.rb#41`:

```
register_instance_option :associated_collection_scope do
      associated_collection_scope_limit = (associated_collection_cache_all ? nil : 30)
      proc do |scope|
        scope.limit(associated_collection_scope_limit)
      end
end
```

Seems to me like the easiest thing for you to do is simply re-scope the limit after you do a full unscope.

```
list do
  scopes([:unscope]).limit(associated_collection_scope_limit)
end
```

I haven't been able to test the above solution (writing this from my phone) so let me know if things go awry.

**Comment by knovoselic** [comment]
Hey @CollinGraves, thanks for the reply. Unfortunately, your idea doesn't work because `scopes([:unscope])` returns just an array of symbols (`[:unscoped]`), so I can't set the limit in there. Any other ideas?

**Comment by knovoselic** [comment]
I'm closing this as I don't see how this is possible without changing rails admin code. Calling `unscoped` on a `Mongoid::Criteria` object removes previously applied limit. If any other scope is used (other than unscoped), this works as expected.
