### ISSUE TITLE
Define format for datetime don't work

### ISSUE THREAD

**Issue by jrgvf** [sferik/rails_admin#2499]
It's don't work.

RailsAdmin.config do |config|

  # For config format of datetime
  config.models do
    fields_of_type :datetime do
      strftime_format "%Y-%m-%d"
    end
  end

  ...

end

But if i include this configuration in this model it's work fine.

RailsAdmin.config do |config|

   ...

  config.model 'HomeMessage' do
    field :created_at
    field :name
    field :email
    field :fone
    field :message
    fields_of_type :datetime do
      strftime_format "%Y-%m-%d"
    end
  end

  ...

end

**Comment by mshibuya** [comment]
`config.models` does not accept block, it can't be used for bulk configuration.
