### ISSUE TITLE
No Colorpicker instructions in Wiki

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sferik/rails_admin#2500]
When I looked over contents of this gem, I have found out that there are a colorpicker javascript files and ruby field files. The main problem is that, there is nothing written about colorpicker in Wiki!

Is there some kind of instructions that makes users to use colorpicker on field?

**Comment by TangMonk** [comment]
try this:

```ruby

rails_admin do
    field :color, :color
end
```

**Comment by SuperMasterBlasterLaser** [comment]
@TangMonk well... that worked. This definitely must be added to wiki. Thanks.

**Comment by voyera** [comment]
I added it to the Wiki: https://github.com/sferik/rails_admin/wiki/Fields#existing-custom-field-type-color-picker-field

If there are other pre-made custom fields I made it so the section can easily be generalized.

**Comment by SuperMasterBlasterLaser** [comment]
@voyera veeeery nice. :+1:
