### ISSUE TITLE
undefined method `total_count' for #<PaperTrail::Version::ActiveRecord_Relation>

### ISSUE THREAD

**Issue by minyoung** [sferik/rails_admin#2503]
Going to the history page (using `PaperTrail` for the auditing) and showing all history throws an error:
> undefined method `total_count' for #<PaperTrail::Version::ActiveRecord_Relation>

(example url: http://localhost:3000/admin/model/history?all=true)

From what I can tell, this seems to only affect when showing all history. What I've dug up so far:

Where is this missing `total_count` defined? [Kaminari::ActiveRecordRelationMethods](https://github.com/amatsuda/kaminari/blob/90a1cd0084807ee160ecf48f8a630458a7f1cfc7/lib/kaminari/models/active_record_relation_methods.rb#L12)
Where is this module included? [Kaminari::ActiveModelExtension](https://github.com/amatsuda/kaminari/blob/90a1cd0084807ee160ecf48f8a630458a7f1cfc7/lib/kaminari/models/active_record_model_extension.rb#L15)
It seems like this module is only included when `Kaminari.config.page_method_name` on the `ActiveRecord::Model` is called though?
Well, when is `Kaminari.config.page_method_name` called? [RailsAdmin::Extensions::PaperTrail::AuditingAdapter.listing_for_model_or_object](https://github.com/sferik/rails_admin/blob/817e34bc6a653e3d4f0948dabeb63317be954ad8/lib/rails_admin/extensions/paper_trail/auditing_adapter.rb#L99) (which corresponds to the stack trace)
And it seems like `Kaminari.config.page_method_name` is only called when `all` is falsey.

So, if I'm understanding this correctly, then when `all` is truthy, `Kaminari.config.page_method_name` is not called, which means that the inclusion of `Kaminari::ActiveRecordRelationMethods` is not triggered, hence the missing method `total_count`.

What now? A couple ideas (in no particular order) comes to mind

* just call `Kaminari.config.page_method_name`? But then the default limit (25) takes place. So then use a high limit? e.g. `versions.page.limit(100000)`
* if `total_count` is missing, then fall back to `count`? e.g. `versions.try(:total_count) || versions.count`
* remove `Show all` and instead make the items per page configurable?

I've tested the first 2 ideas, and both of them work.

Thoughts? Opinions? Other suggestions?

Top few lines of the stack trace:
```
activerecord (4.2.0) lib/active_record/relation/delegation.rb:136:in `method_missing'
activerecord (4.2.0) lib/active_record/relation/delegation.rb:99:in `method_missing'
rails_admin (0.8.1) lib/rails_admin/extensions/paper_trail/auditing_adapter.rb:101:in `listing_for_model_or_object'
rails_admin (0.8.1) lib/rails_admin/extensions/paper_trail/auditing_adapter.rb:74:in `listing_for_model'
rails_admin_history_rollback (0.0.3) lib/rails_admin_history_rollback/config/actions/history_index.rb:26:in `block (2 levels) in <class:HistoryIndex>'
rails_admin (0.8.1) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
rails_admin (0.8.1) app/controllers/rails_admin/main_controller.rb:22:in `history_index'
```

**Comment by vborshchov** [comment]
Hello, @minyoung. I want to solve this issue using the second method:

> - if total_count is missing, then fall back to count? e.g. versions.try(:total_count) || versions.count

Can you tell me there exactly I have to use this code`versions.try(:total_count) || versions.count`. Thanks

**Comment by minyoung** [comment]
Hi @vborshchov, you'd want to modify this line: https://github.com/sferik/rails_admin/blob/817e34bc6a653e3d4f0948dabeb63317be954ad8/lib/rails_admin/extensions/paper_trail/auditing_adapter.rb#L100 and replace `versions.total_count` with `versions.try(:total_count) || versions.count`

Your monkey patch also works. If you don't want to modify upstream library code, then going with the monkey patch might be better since it's clearer and should still work next version. We opted to go with the monkey patch until this is fixed in rails_admin itself.

**Comment by minyoung** [comment]
This issue can also manifest as ``undefined method `total_pages' for #<PaperTrail::Version::ActiveRecord_Relation>`` when using "Show All" on the model listing page.

Again, it's `Kaminari.config.page_method_name` being selectively called on the relation. This time in [RailsAdmin::Adapters::ActiveRecord#all](https://github.com/sferik/rails_admin/blob/v0.8.1/lib/rails_admin/adapters/active_record.rb#L35-L37).

Those pagination options are populated in [RailsAdmin::MainController#get_collection](https://github.com/sferik/rails_admin/blob/v0.8.1/app/controllers/rails_admin/main_controller.rb#L125). Which is called by [RailsAdmin::MainController#list_entries](https://github.com/sferik/rails_admin/blob/v0.8.1/app/controllers/rails_admin/main_controller.rb#L37), and that's where it looks at the `all` parameter to decide whether to include the pagination options or not.

`list_entries` is called in [RailsAdmin::Config::Actions.Index](https://github.com/sferik/rails_admin/blob/v0.8.1/lib/rails_admin/config/actions/index.rb#L30), which is where the `@objects` is populated for view rendering (which is where the exception is ultimately thrown from).

In this case, maybe just not render the pagination controls if we're showing all? i.e. In [app/views/rails_admin/main/index.html.haml](https://github.com/sferik/rails_admin/blob/v0.8.1/app/views/rails_admin/main/index.html.haml#L109)

    .col-md-6= paginate(@objects, theme: 'twitter-bootstrap', remote: true) unless params[:all]

**Comment by bbenezech** [comment]
@minyoung  @vborshchov  What is your opinion on where this should be fixed? Kaminari, PaperTrail or RailsAdmin?
If RailsAdmin, can you provide a PR?

**Comment by minyoung** [comment]
I think that this should be fixed in RailsAdmin. The crux of the problem is that Kaminari selectively adds extension methods to `ActiveRecord_Relation`'s (they're added when the `page` method is called). In the case of showing all objects, we don't call the `page` method (we're showing all the objects after all).

I've created a pull request with the simplest fixes. I haven't had the time to look into adding tests (yet).

**Comment by minyoung** [comment]
Ah, the second [exception](https://github.com/sferik/rails_admin/issues/2503#issuecomment-172979305) I came across was caused by my monkey patch to work around the first exception. My bad about that.

**Comment by minyoung** [comment]
Fix got merged in :)
