### ISSUE TITLE
`No such file or directory - nodejs` on 0.8.1

### ISSUE THREAD

**Issue by TangMonk** [sferik/rails_admin#2504]
I have create a folder `nodejs` at my rails project folder, It's ok my rails_admin 0.6.8

When I upgrade rails_admin gem to 0.8.1 will throw me an error:

![image](https://cloud.githubusercontent.com/assets/3498786/11708270/52a00f66-9f48-11e5-9b0d-04e9b0c83de0.png)

**Comment by bbenezech** [comment]
Weird!
coffeescript compilation does not like your nodejs folder..
This does not look RailsAdmin related, I cannot help you much, sorry.

**Comment by TangMonk** [comment]
thanks
