### ISSUE TITLE
History missing for only some models

### ISSUE THREAD

**Issue by ptrikutam** [sferik/rails_admin#2506]
Hi there. First of all thank you sooooo much for putting together this excellent library. This is great work and it's very much appreciated.

I'm having an issue where history for some of my models are not showing up. It show up for some, but not others.

I'm using:
[The master branch of rails_admin](https://github.com/sferik/rails_admin/commit/95ad1c2dc28234d1fcf7db7d5e1fd989989a0c05)
mongoid (5.0.1)
mongoid-audit (1.1.0)
ruby 2.1.2

I have another custom built admin software and the history shows up properly for all my models there. I've also checked in the rails console, and the history does exist. Any idea what might be going on here?

**Comment by bbenezech** [comment]
It's too vague. Can you reopen with more details if you still have the issue?
