### ISSUE TITLE
The default dashboard "last used" field is very expensive and should be removed

### ISSUE THREAD

**Issue by vincentwoo** [sferik/rails_admin#2514]
In [`dashboard.rb`](https://github.com/sferik/rails_admin/blob/817e34bc6a653e3d4f0948dabeb63317be954ad8/lib/rails_admin/config/actions/dashboard.rb#L30), RailsAdmin does the following for every table by default:

```ruby
@most_recent_changes[t.model.name] =
  t.first(sort: "#{t.table_name}.updated_at").try(:updated_at)
```

This is an ENORMOUSLY expensive call for any table that is not indexed on `updated_at`. For example, on my app: 

```
coderpad-rails=# EXPLAIN SELECT  "pads".* FROM "pads"  ORDER BY pads.updated_at desc LIMIT 1;
                                 QUERY PLAN
----------------------------------------------------------------------------
 Limit  (cost=25411.89..25411.89 rows=1 width=1203)
   ->  Sort  (cost=25411.89..25811.53 rows=159859 width=1203)
         Sort Key: updated_at
         ->  Seq Scan on pads  (cost=0.00..24612.59 rows=159859 width=1203)
(4 rows)
```

This is occasionally causing complete HTTP timeouts in my application. I don't want to add an index just to service this dashboard, either. I'm going to turn off statistics entirely because there doesn't seem to be a way to disable just this behavior, but I'd recommend either adding a flag or just showing something much easier, like the `created_at` time on the last row in the table.

**Comment by shakycode** [comment]
@vincentwoo I'm having the exact same problem in both old versions of rails_admin and new versions.  It's super expensive to load the stats page and often my app will timeout for 2-4min at a same.

Is there any way to disable the stats to avoid these expensive calls?

**Comment by codealchemy** [comment]
@vincentwoo @shakycode The stats bar can be disabled (more on that [here](https://github.com/sferik/rails_admin/wiki/Dashboard-action#disabling-record-count-bars)):

```ruby
RailsAdmin.config do |c|
  c.actions do
    dashboard do
      statistics false
    end
  end
end
```

You could also build your own custom dashboard in `app/views/rails_admin/main/dashboard.html.erb` (or `.haml`, depending on your project)

**Comment by vincentwoo** [comment]
I did that as well, but I think it is not a good default for rails_admin to have.

**Comment by bbenezech** [comment]
What should we do instead?
Is the sorting important?
If not, maybe you can provide a pull request sorting by id?

**Comment by vincentwoo** [comment]
I can. Are you open to that idea?

**Comment by bbenezech** [comment]
Sure!
We'll call it "last entries" instead of "last updates" I guess. :dancers:
