### ISSUE TITLE
Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`

### ISSUE THREAD

**Issue by abelorian** [sferik/rails_admin#2515]
When I deploy a project with: ```bundle exec rake assets:precompile RAILS_ENV=production```

Node version: v0.12.7
Ruby version: ruby 2.2.1p85}
Rails: 4.2.3
Error:

```autoprefixer: /home/deploy/bta/releases/20151231223027/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:202:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.```

```autoprefixer: /home/deploy/bta/releases/20151231223027/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:231:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.```

```autoprefixer: /home/deploy/bta/releases/20151231223027/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:270:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.```

```autoprefixer: /home/deploy/bta/releases/20151231223027/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:1483:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.```

```autoprefixer: /home/deploy/bta/releases/20151231223027/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:1593:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`. ```

**Comment by anfinil** [comment]
+1

**Comment by tagliala** [comment]
This warning was bothering me too :)

**Comment by VincentSim** [comment]
I have the same issue

**Comment by embasbm** [comment]
Hi everyone, I'm getting the same issue you are talking about above. How do you fix this warning? editing the gem file in bundle/ruby/2.2.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb ?
