### ISSUE TITLE
Append new options to select via coffescript

### ISSUE THREAD

**Issue by Strollager** [sferik/rails_admin#2517]
Hello! 
I'm trying to make dependent select using coffescript. After selecting value from first select I send a request to receive options for the second select. The new values I add to the second select. But they do not appear in the list.

depended_pages.js.coffee:
```coffeescript
$(document).ready ->
  $('#parent_site').change ->
    $.ajax '/admin/get_depended_pages?site_id=' + this.value,
      type: 'POST'
      dataType: 'html'
      error: (jqXHR, textStatus, errorThrown) ->
        alert("#{textStatus}: #{errorThrown}")
      success: (data, textStatus, jqXHR) ->
        pages = $('#page_parent_id')
        pages.empty()
        data = jQuery.parseJSON(data)
        for element in data
          console.log element
          pages.append($("<option></option>").attr("value", element[1]).text(element[0])).html()
```

Before select element(in first select, #parent_site):
<img width="1440" alt="2016-01-04 00 09 12" src="https://cloud.githubusercontent.com/assets/11654565/12080776/a48f881e-b277-11e5-8b59-a36584f83d56.png">
After select element:
<img width="1440" alt="2016-01-04 00 09 22" src="https://cloud.githubusercontent.com/assets/11654565/12080777/ab2b5d74-b277-11e5-8397-563b1bbba597.png">

I append new options, but the list is not disclosed. What am I doing wrong? Help, please.

**Comment by bbenezech** [comment]
This is out of the scope of the project.
Please try StackOverflow of code related questions.
If you end up hitting a wall with RailsAdmin's API, please reopen with the specifics.
