### ISSUE TITLE
Hide navigation_static_links for specific role.

### ISSUE THREAD

**Issue by AlexKlim** [sferik/rails_admin#2519]
Hi, how can I hide navigation_static_links for specific role ?

For example: I want to show the links for _admin_, but I don't want to show the links for _manager_.

Thanks.

**Comment by codealchemy** [comment]
There doesn't appear to anything you can do in the initializer for this (no access to [`bindings`](https://github.com/sferik/rails_admin/wiki/Actions#visible-block) when setting `config.navigation_static_links` there), however you could add a `:before_filter` in your application controller to handle this:

```ruby
class ApplicationController < ActionController::Base
  before_filter :hide_static_nav_for_non_admins

  private

  def hide_static_nav_for_non_admins
    RailsAdmin::Config.navigation_static_links = {} unless current_user.role == 'admin'
  end
end
```

**Comment by bbenezech** [comment]
You cannot remove the action per role, but you can hide/show it per role:
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/show_in_app.rb#L11

**Comment by AlexKlim** [comment]
@bbenezech What is it ? I think, the link is not about static_links 
@codealchemy Thanks, I'll try !

**Comment by bbenezech** [comment]
Sorry I misread you!
I thought this was about actions!
Please reopen if needed.

**Comment by dedman** [comment]
@AlexKlim did you work out a good answer to this? I don't like the idea of putting this sort of logic in the application_controller.rb.

**Comment by AlexKlim** [comment]
@dedman 
If I am not mistaken, I added 
` config.authorize_with :cancan, AdminAbility` to the rails_admin.rb (config file) 

and create rules for roles. 

and as far as I remember don't forget to add 

```
can :access, :rails_admin
can :dashboard
```

feel free ping me, if it doesn't help

**Comment by codealchemy** [comment]
@dedman if you'd like to keep that out of the controller, I believe another way to handle this would be to set (or override, depending on your config) the static nav when defining roles (which I believe @AlexKlim was alluding to), ex:

```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      rails_admin_static_links('Admin link' => 'https://domain.com')
      can :manage, :all
    else
      rails_admin_static_links('User link' => 'https://domain.com')
      can :access, :rails_admin
      can :dashboard
      can :read, :all
    end
  end

  private

  def rails_admin_static_links(links)
    RailsAdmin.config { |c| c.navigation_static_links = links }
  end
end

```
