### ISSUE TITLE
RailsAdmin with polymorphic associations

### ISSUE THREAD

**Issue by dmitrypol** [sferik/rails_admin#2520]
I am using, Rails 4.1, RailsAdmin 0.8.1 and Mongoid 5.0.1. I defined has_many / belongs_to relationship between Products and Pictures RailsAdmin generates a Product dropdown in the Picture model. I can choose Product or I can search for Product.

I implemented polymorphic association between Products, Pictures and Employees. Now when I edit Picture I have 2 dropdowns - to choose type (Product or Employee) and 2nd to choose the actual record.

The problem is RailsAdmin is trying to load the entire Employee or Product list into 2nd dropdown. I have many thousands Employees and eventually it timeouts. Any ideas how to search?

**Comment by agentfuture** [comment]
+1

**Comment by bbenezech** [comment]
dup #2461

Maybe you can try the diff on your side, then reports your findings on the PR?
It looks like he was close to the end.
