### ISSUE TITLE
Allow in multiple select has_many to duplicate the choice

### ISSUE THREAD

**Issue by gabrieletassoni** [sferik/rails_admin#2521]
Hello,
I'm trying to understand if there's a rails_admin way to specify that a multi select for has_many has a way to allow duplicate adding of associated records, before trying to figure out by myself on how to add this feature, since I didn't found documented it, I'd like to know if it's already implemented and could be enabled in some way.

Thank you for the help,
Gabriele Tassoni

**Comment by Jamevid** [comment]
:+1:

**Comment by Jamevid** [comment]
One work around could be to use has_many field to the join table with nested attributes in the form. 
And then use belongs_to field to select the field to connect. 

Some this like:

edit do 
   field :to_join_table # (has many) with accept_nested_attributes_for in the model
....
end

### JOIN TABLE FORM:
edit do 
  field :the_record_you_want_to_link # belongs_to field
....
end

In that way you could link duplicate records in the same form.

**Comment by bbenezech** [comment]
@gabrieletassoni Not possible, sorry!
