### ISSUE TITLE
Ru locale link missing

### ISSUE THREAD

**Issue by frontandstart** [sferik/rails_admin#2522]
On [translations](https://github.com/sferik/rails_admin/wiki/Translations) wiki page.
link to [rails_admin.ru.yml](https://gist.github.com/eugene-auduchinok/a68ca164e05e77e00ce1#file-rails_admin-ru-yml) is 404
I find one of fork in [pavelbel](https://gist.github.com/pavelbel/2266376) account

**Comment by mshibuya** [comment]
Revised.
The wiki is editable by anyone, please feel free to update it.
