### ISSUE TITLE
documentation: date_format 

### ISSUE THREAD

**Issue by u007** [sferik/rails_admin#2523]
hi,

it would be nice to have this in the wiki to state on how to configure datetime for input.
something like:

setting datetime format in en.yml (or your locale.yml)
en.time.formats.long

this can be set in en.yml

otherwise, you may set the datetime by declaring in the configuration, etc:
```
field :created_at do
    date_format do
      :short
    end
end
```

**Comment by bbenezech** [comment]
Sure, the wiki is opened to everyone ;)
