### ISSUE TITLE
Can't get embeds_many working with Mongoid and Rails 4

### ISSUE THREAD

**Issue by alexbezhan** [sferik/rails_admin#2524]
I have the following model with `embeds_many` association for `reddit_threads`, but it doesn't show up in the form.

```
class Product
  include Mongoid::Document
  embeds_many :reddit_threads
  accepts_nested_attributes_for :reddit_threads, allow_destroy: true
end

class RedditThread
  include Mongoid::Document
  embedded_in :product
  field :url, type: String
end
```

**Comment by bbenezech** [comment]
Can you check what is happening here: 
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/adapters/mongoid/association.rb#L83

What does `Product.nested_attributes_options` look like? Does `reddit_threads` show up?
