### ISSUE TITLE
Cequel::Record support

### ISSUE THREAD

**Issue by orenmazor** [sferik/rails_admin#2527]
Hey guys, I did a bit of work to get this working for one of our projects. Is there any interest in my fleshing this out and PRing it at master?

https://github.com/orenmazor/rails_admin/commit/203a099454bb35943807a3dba4426916c9b0afab

**Comment by bbenezech** [comment]
Hi @orenmazor 

I won't merge it (I cannot maintain this) but if you could make a plugin out of this, Cequel users would probably be pleased. If some work is needed in RailsAdmin internals, I'll gladly accept a PR.

Thanks a lot.

**Comment by orenmazor** [comment]
Hey, no worries. I actually abandoned it because it's fundamentally wrong to be making these kind of queries against cassandra. (aggregate stuff like select count(*) from blah cause all kinds of shitty performance)
