### ISSUE TITLE
Enable filtering for custom fields

### ISSUE THREAD

**Issue by andyentity** [sferik/rails_admin#2534]
When I create a virtual/formatted field in a list-view I want to be able to apply filters to it like on any of the other non-virtual fields. Right now it is possible to make the virtual field appear in the filter dropdown-menu but filtering simply doesn't work. 

```
config.model Book do
 list do
    field :virtual_test do
      formatted_value do
        bindings[:object].users.pluck(:street)
      end
      filterable true
      searchable true
    end
  end
end
```
The reason is that rails_admin performs filtering via SQL queries directly on the database columns.

It would be good to make it possible to perform filtering also on virtual fields without quieries but by code.

#2433 is related.

**Comment by manuel-burato** [comment]
same here :-(

**Comment by bbenezech** [comment]
Same answer as #2433 : RailsAdmin only deals with underlying ORM for search/filter.
`children_fields` can tell RailsAdmin which fields the ORM should look into.

**Comment by thauburger** [comment]
Is use of `children_fields` documented anywhere on the wiki? I didn't see it after some looking.

**Comment by FunkyloverOne** [comment]
I believe it's now covered here:
https://github.com/sferik/rails_admin/wiki/List#fields-searching

**Comment by allanohorn** [comment]
@FunkyloverOne I don't think that it is, field searching looks like it is still operating strictly at a DB level and there isn't anything in the documentation indicating you can search for virtual fields

**Comment by Menghongli** [comment]
Howeverm you can now specify custom search by:
```
      RailsAdmin.config do |config|
        config.model Book do
          list do
            search_by :custom_search
          end
        end
      end

scope :custom_search, ->(query) { where(name: query.reverse) }
```
