### ISSUE TITLE
datetime not saving when locale is :es

### ISSUE THREAD

**Issue by mp2apps** [sferik/rails_admin#2535]
Excuse me for my poor english.
If you try to save a datetime value in a model while using the official :es translation, the value will not be saved, instead you get a nil field.
Using the default_locale = :'en' will save the value without problems

**Comment by nicovak** [comment]
I just had the same issue, you have to specify the strftime_format options in your field like this:
I think there is an override

```
field :my_field do
  strftime_format do
    '%d-%m-%Y %H:%M:%S'
  end
end
```

I think the issue comes from the local translation file which is including PM or AM + extra informations and the parser is loosing itself.

**Comment by mp2apps** [comment]
Thanks for your response I added your snippet in "rails_admin.rb"
`config.model 'Agenda' do
    list do
        field :inicio do
            strftime_format do
                '%d-%m-%Y %H:%M:%S'
            end
        end
    end
end`

where Agenda is my model and inicio is my field, but I doesn't got results :(

**Comment by bbenezech** [comment]
It should work with master now. Thanks for reporting.

**Comment by rodeofly** [comment]
Exact same problem here, at edit, it was displaying %Hh under datepicker so after rsierra's hint in another issue, I put : 
```
rails_admin do
  edit do
      field :schedule_at do
        strftime_format 'Le %d %B %Y à %H\h%M'
      end
    end
    list do
      field :schedule_at do
        strftime_format '%d.%m.%Y.%H\h%M'
      end
    end
  end
```

Good display at edit but not saving ! Changing edit to
```
strftime_format '%d-%m-%Y %H:%M:%S'
```
made it saved but displayed a \h in list view. I fixed everythings... Bref ! if it can help !!!

**Comment by yurijmi** [comment]
I have the same problem with latest version of this gem but with russian locale. @nicovak solution worked. I think you should reopen this issue. Or at least add @nicovak solution to Wiki.

**Comment by DanAndreasson** [comment]
I experience the same issue. 

Rails 5, rails_admin 1.1.1 and swedish locale.

Filtering does not work either

**Comment by jjercx** [comment]
Same issue with :es locale, rails 4 and rails_admin 1.1.1. As @yurijmi, i think this should be reopened or documented. Had a hard time finding this

**Comment by amed** [comment]
:de locale

`rails 5.1.4`
`rails-admin 1.2.0`

Same issue 😕

**Comment by amed** [comment]
Adding [rails-i18n](https://github.com/svenfuchs/rails-i18n) gem solved the issue.

**Comment by limjinsun** [comment]
Having same issue. Would anyone help to guide where to start? I have several datetime fields. not only one.

**Comment by alibaobaid** [comment]
@bbenezech 

> It should work with master now. Thanks for reporting.
this issue still exists,  how can I solve this one could please help me here as I stuck with it and the above solutions not worked for me

**Comment by alibaobaid** [comment]
> Adding [rails-i18n](https://github.com/svenfuchs/rails-i18n) gem solved the issue.

@amed I added the gem and bundle it does not solve the issue is there are any other configuration should I added to fix that one

**Comment by amed** [comment]
@alibaobaid 
Theoretically it should work without setting configurations. What are the versions that you are using?

**Comment by alibaobaid** [comment]
> @alibaobaid
> Theoretically it should work without setting configurations. What are the versions that you are using?

@amed 
`rails 6.0.3.4`
 `rails_admin 2.0.2` 
 `rails-i18n 6.0.0`
 I get deep into a lot of solutions all of them solve that by format but in my case formate is not solving the issue finally I figure out that my issue caused because Datepicker passed numbers in ٠١٢٣٤٥٦٧٨٩ style and rails can not convert that style to date. can you help me by fixing this issue to force Datepicker to pass the date in 0123456789 numbers type even when the locale ar thanks in advance

**Comment by amed** [comment]
@alibaobaid 
Actually inputs are related more to the platform, browser handles formatting the correct date object and send it to the server. I just created a test project with the following version:
```
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
gem 'rails_admin', '~> 2.0'
gem 'rails-i18n', '~> 6.0.0'
```
Everything seem to be functioning as expected. I am using MacOS Big Sur v11.1

The example project:  https://github.com/amed/rails-admin-i18n-example
