### ISSUE TITLE
Found a bug in Latest wysihtml-toolbar.min.js v0.5.5

### ISSUE THREAD

**Issue by yogeshbhade20** [sferik/rails_admin#2536]
Hello,

I am using this script in my project but i have found a bug in latest version of this script.
/*! wysihtml - v0.5.5 (2016-01-06) */

When i make any word hyperlink it works, but after it if i want to remove hyperlink from that word then i clear the link but the word remains also anchor without any hyperlink.

Would you like to solve it in this version because it works in v0.5.0

**Comment by bbenezech** [comment]
Wrong project @yogeshbhade20 !
