### ISSUE TITLE
Rails_Admin, Sorcery + CanCanCan

### ISSUE THREAD

**Issue by JohnnyR1co** [sferik/rails_admin#2537]
Hello, When I use Sorcery with CanCanCan gem I had a had a mistake "You are not authorized", but my user had all abilities to manage all, for a few days. To fix this error I add config.current_user_method(&:current_user), like in Devise gem... So I think you should add this in Wiki

**Comment by bbenezech** [comment]
Can you update https://github.com/sferik/rails_admin/wiki/Sorcery if needed?

Thanks.
