### ISSUE TITLE
Image upload in modal

### ISSUE THREAD

**Issue by nicovak** [sferik/rails_admin#2538]
Hi, i'm new in ruby ecosystem but i'll try to explain my problem, by the way, thank you for this gem :)

Im hurting to a wall, I'm trying to upload images through a one to many relationship and it dont works.
Nothing happen when i submit form and I have a console error : 
`Uncaught TypeError: $.rails.callFormSubmitBindings is not a function`
I only see the parent entity change to 'Edit' view and datas are not persisted.

The line which is causing problem seems to be:
`if (!$.support.submitBubbles && $().jquery < '1.7' && $.rails.callFormSubmitBindings(form) === false) return $.rails.stopEverything(e);` in jquery.remotipart

If i dont put any images to my associated entity I have no problems so I tried with carrierwave and paperclip but the problem remains.

I hope you will be able to help me,
Cordially

**Comment by dheaven92** [comment]
I have exactly the same issue. Hope, somebody know, how to solve it.

**Comment by clutchman** [comment]
Same for me when i use the modal upload to add a Rich media.

**Comment by bbenezech** [comment]
I have upgraded remotipart. Can you guys try again and reopen if it still shows up?

**Comment by clutchman** [comment]
It's ok for me.
Thanks for your quick upgrade.

**Comment by tskorupka** [comment]
Still broken
Using rails_admin 0.8.1

**Comment by dedman** [comment]
Just had this problem too, I'm surprised there aren't more people commenting here. Thanks for your fix @bbenezech. For those flicking to the bottom of the issue to see the solution, just switch to the master branch and it will be fixed. (I have locked to the most recent commit, so it doesn't keep changing)

`gem 'rails_admin', github: 'sferik/rails_admin', ref: '49aafbb'`

I assume this issue will be fixed with the next release after 0.8.1. Thanks for the great gem guys!

**Comment by ain** [comment]
I've just reproduced it on `0.8.1` as well:

```
TypeError: $.rails.callFormSubmitBindings is not a function. (In '$.rails.callFormSubmitBindings(form)', '$.rails.callFormSubmitBindings' is undefined)
```

Switching to 49aafbb resolved the problem.

**Comment by pmaojo** [comment]
The fix using the ref '49aafbb' makes another error pop in my app:

`NoMethodError at /servicio/1/edit ================================= > undefined method `to_sym' for nil:NilClass rails_admin_globalize_field (0.4.0) `

**Comment by shivareddy547** [comment]
Hi 

I am facing Same issue .
if (!$.support.submitBubbles && $().jquery < '1.7' && $.rails.callFormSubmitBindings(form) === false) return $.rails.stopEverything(e);

Can anybody have solution..?.

Thanks in advance.

Thanks
Shiva.A

**Comment by Novik** [comment]
> if (!$.support.submitBubbles && $().jquery < '1.7' && $.rails.callFormSubmitBindings(form) === false) return $.rails.stopEverything(e);

This is because expression ('1.12.1' < '1.7') is a true ;)
Try to copy standard jquery.remotipart.js file from the last version of remotepart to the app/assets/javascripts/rails_admin/jquery.remotipart.fixed.js.

**Comment by ant919191** [comment]
Novik, could you tell me how I can download your plugins for ruTorrent? Many thanks!

**Comment by Novik** [comment]
@ant919191 From the project's github repo of course. 

And some correction to the above - 
> Try to copy standard jquery.remotipart.js file from the last version

This will not work, you need simply comment this line (if (!$.support.submitBubbles && $().jquery < '1.7'...) in the original jquery.remotipart.fixed.js
(Of course, this is correct only for case, when you use jQuery >= 1.7)
