### ISSUE TITLE
Conditional field override

### ISSUE THREAD

**Issue by gabrieletassoni** [sferik/rails_admin#2544]
Hello,
I'm trying to figure out if there's a way to set the field type conditionally, something like (that's obviously pseudo code, since it can't work this way):
```
list do
  field :demo, :boolean unless bindings[:view]._current_user.admin?
  field :demo, :integer if bindings[:view]._current_user.admin?
end
```
Thank you for the help,
Gabriele

**Comment by bbenezech** [comment]
The saddest thing is you actually can.
Just define it twice, then make each one visible for each profile.
And now you know why RailsAdmin is completely unmaintainable.

**Comment by gabrieletassoni** [comment]
Ok, thanks I'll try, I can swear I tried it, but if I can remember well it didn't worked for me, I'll give it a try, but I can see that it must really work as you say, I probably had done some mistakes.

Thank you again.
