### ISSUE TITLE
Form fields working in mobile browser? :)

### ISSUE THREAD

**Issue by Jamevid** [sferik/rails_admin#2548]
Only has_many multi-select is not working properly for me in mobile browser (in form view). All other field types seems ok. 

I tried with new Acer and Samsung phones/tablets. 
Or is multi-select supposed to work on the mobile? 

Thanks for any input! :-)

**Comment by bbenezech** [comment]
It works but it is completely counter intuitive :(
The rails multi-select widget is 2 multiple selects with JS that passes option from left to right and vice-versa.

With that in mind you should be able to use it, but it is definitely tacky.

I would love to see a better UX for multi-select. If you feel like trying this... (but it is some work)

**Comment by Jamevid** [comment]
ok thanks! :)
