### ISSUE TITLE
Using encrypted attributes (attr_encrypted) with searchable

### ISSUE THREAD

**Issue by kayzee** [sferik/rails_admin#2550]
I'm using attr_enctyped to encrypt a number of fields in my model, including first_name, last_name in the Profile->User association.

```
field :profile do
  searchable [:first_name, :last_name]
  filterable false
  queryable true
  visible false
end
```

I end up getting an exception: `Mysql2::Error: Unknown column 'profiles.first_name'` because the first_name column doesn't exist, it is just an attr_accessor for the `profiles.encrypted_first_name` field.

Is it possible to search the encrypted attributes?  I have access to `Profile.encrypt_first_name(value)` and `Profile.encrypt_last_name(value)`, but I can't figure out how to get search working.

**Comment by bbenezech** [comment]
You can map to another column, but that won't help you with the encrypted value: you cannot search encrypted data unless you decrypt it.
RailsAdmin uses the DB to search and decryption can only be done in rails, so... :(

**Comment by kayzee** [comment]
Thanks for the reply!  I noticed that RailsAdmin is using SQL to grab the search results, so I have accepted defeat for now.  We will have to choose to encrypt or search.

**Comment by tejaswinipatil** [comment]
Is there any new implementation done for supporting search with encryption ?
