### ISSUE TITLE
CI failure Bundler::GemRequireError

### ISSUE THREAD

**Issue by bbenezech** [sferik/rails_admin#2552]
https://travis-ci.org/sferik/rails_admin/jobs/107236882

```ruby
Bundler::GemRequireError: There was an error while trying to load the gem 'rails_admin'.
```

@mshibuya do you know what this is about? Is it random?

I hate debugging CI stuff. Someone help.

**Comment by bashcoder** [comment]
I'm getting this same error in my dev environment when trying to upgrade to ruby-2.2 from ruby-2.1. Even tried setting the bundle path to `vendor/bundle` instead of the default path and rebuilding, but to no avail.

**Comment by bbenezech** [comment]
@bashcoder Ok, all errors happen with ruby 1.9.3 or 2.0.0 (and consistently)
Other rubies are not impacted. Thanks for pointing in the right direction.

Wondering of we should continue testing those. 1.9.3 is ooold, 2.0.0 is sometimes used by people that have GC issues on heroku with 2.X, but other than that it was shortlived.

@mshibuya do you want to pull the plug?

**Comment by ryana** [comment]
I ran into this on:

* rails_admin 0.6.2
* rails 4.2.1
* ruby 2.3.0

When I commented out the rescue/re-raise that Bundler does, I saw this error underneath:

```
/Users/ryan/.rvm/gems/ruby-2.3.0@ramen/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
```

Adding this to my Gemfile allowed tests to run:

`gem 'safe_yaml', '1.0.4'`

**Comment by pazaricha** [comment]
Same issue here. After upgrading to ruby 2.2.4 I get the same error when trying to load the Rails server.

**Comment by ntlk** [comment]
I am also experiencing this on upgrade from Ruby 2.2.0 to 2.3.0

**Comment by ryana** [comment]
Hey I just realized this might not be clear, but my comment above https://github.com/sferik/rails_admin/issues/2552#issuecomment-185955912 is a possible solution to this.

Force `safe_yaml` to be version `1.0.4` and see if that solves the problem for you.

**Comment by ntlk** [comment]
@ryana Unfortunately I can’t do that, as the app is still on Rails 3 the latest version of rails_sdmin I can use is 0.4.9, which depends on safe_yaml ~> 0.6

Does this mean there is no way to upgrade to a recent version of Ruby without having to upgrade Rails for rails_admin to work?

**Comment by ryana** [comment]
I wouldn't go so far as to say there's _no way_ to upgrade but so far I don't know what it is. Sorry :disappointed:

**Comment by ntlk** [comment]
@ryana no worries. Thanks!

**Comment by johnantoni** [comment]
had the same issue, fixed using

    gem 'safe_yaml', '0.6.3'

**Comment by mshibuya** [comment]
RA no longer depends on `safe_yaml`.
