### ISSUE TITLE
Can not filter the list view after upgrade to 0.8.1

### ISSUE THREAD

**Issue by palin** [sferik/rails_admin#2556]
Hi,

I upgraded from 0.7.0 to 0.8.1 and the only problem I noticed is that I can not filter records when I'm at the list view of any model.

**Reproducing:**
I go to any model list view, click 'Add filter' on the right side of the screen, then try to select let's say 'id' or anything else and nothing happens.

JS throws errors:

First:

``` js
SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data
```

Which is for this line (rendered html):

``` html
<script>RailsAdmin.I18n.init('en-GB', JSON.parse("{\&quot;true\&quot;:true,\&quot;false\&quot;:false,\&quot;is_present\&quot;:\&quot;Is present\&quot;,\&quot;is_blank\&quot;:\&quot;Is blank\&quot;,\&quot;date\&quot;:\&quot;Date ...\&quot;,\&quot;between_and_\&quot;:\&quot;Between ... and ...\&quot;,\&quot;today\&quot;:\&quot;Today\&quot;,\&quot;yesterday\&quot;:\&quot;Yesterday\&quot;,\&quot;this_week\&quot;:\&quot;This week\&quot;,\&quot;last_week\&quot;:\&quot;Last week\&quot;,\&quot;number\&quot;:\&quot;Number ...\&quot;,\&quot;contains\&quot;:\&quot;Contains\&quot;,\&quot;is_exactly\&quot;:\&quot;Is exactly\&quot;,\&quot;starts_with\&quot;:\&quot;Starts with\&quot;,\&quot;ends_with\&quot;:\&quot;Ends with\&quot;,\&quot;too_many_objects\&quot;:\&quot;Too many objects, use search box above\&quot;,\&quot;no_objects\&quot;:\&quot;No objects found\&quot;}"))</script>
```

And the second JS error (which is caused by the first one):

``` js
TypeError: this.translations is undefined
```

In rails_admin `application.html.haml` we've got the line:

``` haml
RailsAdmin.I18n.init('#{I18n.locale}', JSON.parse("#{j I18n.t("admin.js").to_json}"))
```

`JSON.parse` can not parse `\&quot;`. 

Overriding default layout and adding `.html_safe`, so that it looks like this:

``` haml
RailsAdmin.I18n.init('#{I18n.locale}', JSON.parse("#{j I18n.t("admin.js").to_json.html_safe}"))
```

solves the problem

I tried to write a capybara test, but it works properly there without adding `html_safe`. I can not explain that. Does anyone have the issue as well?

**Comment by Darep** [comment]
We're experiencing this issue as well, but a little bit differently. For us, the string for JSON.parse() comes out like this:

```javascript
JSON.parse("{"true":true,"false":false,"is_present":"Is present","is_blank":"Is blank" [...etc]
```

The `"` inside `JSON.parse("")` should be escaped to `\"`, but for some reason they are not.

My thinking is that this is caused by different JSON encoders/gems returning differing JSON with the `.to_json` method call. For example, we are using a slightly customized version of Rails 4.0's `ActiveSupport::JSON::Encoding`, though even when I reverted the customizations we still got this error.

One possible fix could be to escape & JSONize the `I18n.t("admin.js")` translation data manually so different gems & patches wouldn't affect Rails Admin 😂

**Comment by Darep** [comment]
Quick note that we upgraded to Rails 4.2 and then to rails_admin 1.3.0 which fixed this for us :)

**Comment by mshibuya** [comment]
The change in 0a5a45757e730b12de2b76b72e8b711ade6874ee will make this kind of issue less likely.

**Comment by deepakmahakale** [comment]
I am facing a similar issue with rails 6 and rails_admin 2.0.2

any notes will be helpful
