### ISSUE TITLE
views and controllers of rails_admin

### ISSUE THREAD

**Issue by bobur554396** [sferik/rails_admin#2563]
I have installed rails_admin gem. I want to create partial for my field, but I don't have any views folder of rails_admin. How can I generate views and controllers of this gem?

**Comment by rob99** [comment]
If you want to customize the edit view, you can specify a partial.  See here:

https://github.com/sferik/rails_admin/wiki/Fields#form-rendering

There's doesn't seem to be a way to override a partial in the show or list views though...
