### ISSUE TITLE
Is there a way i can apply scope depending on the current user?

### ISSUE THREAD

**Issue by delgiudices** [sferik/rails_admin#2572]
I currently have this model in my application. 

```
class Category < ActiveRecord::Base

  scope :for_user, ->(user) { where(user_id: user.id) }

  belongs_to :user

end
```

And i want to be able to apply :for_user scope in the list action of the admin section.

I'm trying to do

```
list do
  scopes [:for_user]
end
```

But of course this ends up in an error ( wrong number of arguments ).

Is there a way i can achieve this, if there is this should be documented, if there's not this should be added.

**Comment by Preen** [comment]
+1

**Comment by Sshobhit** [comment]
+1

**Comment by caferrara** [comment]
I'm trying to solve the exact same problem.  Any thoughts would be most appreciated.
