### ISSUE TITLE
Integration of Google Calendar

### ISSUE THREAD

**Issue by bobur554396** [sferik/rails_admin#2578]
Hi everyone, I'm using rails_admin gem, and I want to integrate Google Calendar into my admin dashboard. In dashboard only super admin can add/delete/edit events. And in front-end side will be also this Google Calendar, but only will be static(read only). I already created app in Google Console and set Enable Calendar API and I have client_id and client_secret. But I do not know how to integrate into rails_admin this calendar. 

thank you in advance!

**Comment by nicovak** [comment]
You should maybe create a custom fiield or a custom action. E.g embeded google calendar in a menu tab (same level as export, list, etc actions). You will also need to include your javascript in the asset pipeline, create ` app / assets / javascripts / rails_admin / custom / ui.js` and require your script + add your logic.
