### ISSUE TITLE
Question: How does one change the number of records being showed before the selector for has_many associations displays "Too many objects, use search box function"

### ISSUE THREAD

**Issue by kaizenx** [sferik/rails_admin#2583]
Question: 
How does one change the number of records being showed before the selector for has_many associations displays "Too many objects, use search box function"

**Comment by mshibuya** [comment]
`default_associated_collection_limit` is what you're looking for.
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config.rb#L45
