### ISSUE TITLE
rails_admin display multiple images

### ISSUE THREAD

**Issue by Prashanth-M** [sferik/rails_admin#2588]
am using rails_admin, I want to display the Gallery of images to each product. For different products I want to add different images.

I've got my Product model with has_many :gallery association and my Gallery model with belongs_to :product association.

How to display the multiple images under Product model show option? Thanks.

```
          show do |c|
            field :title
            field :description
            field :price
            field :quantity
            field :display_image
            field :galleries do
                    end
          end
```

It just displays the all image url's instead of the image? Need help on this. I have spent 3 days on this but no answer found...

**Comment by railites** [comment]
I am facing similar issue, i am trying to add multiple links.

**Comment by mshibuya** [comment]
Multiple file upload feature is for that.
5bb2d375a236268e51c7e8682c2d110d9e52970f
