### ISSUE TITLE
Cannot remove associations in nested form

### ISSUE THREAD

**Issue by goofansu** [sferik/rails_admin#2592]
Javascript error when click the trash icon, like:

`Uncaught Error: Syntax error, unrecognized expression: a[href=#unique-id-1458570775915]`

**Comment by colavitam** [comment]
This is more than a javascript issue, as the associations are not actually removed (even newly created ones) when the form is submitted, leading to validation failures.

**Comment by colavitam** [comment]
This is fixed on the master branch

**Comment by goofansu** [comment]
Thanks
