### ISSUE TITLE
How to display embedded documents?

### ISSUE THREAD

**Issue by knovoselic** [sferik/rails_admin#2600]
Let's say I have the following classes:

```
class User
  include Mongoid::Document
  
  field :name
  embeds_many :devices
end

class Device
  include Mongoid::Document
  embedded_in :user

  field :name
  field :os
end
```

How do I display all user's devices in user's show action? How do I configure fields from `Device` (which should be display, how they should be displayed, etc.)?

**Comment by dmitrypol** [comment]
I was also stuck on this issue.  I ended up building custom methods in the parent class and included them in RA show page.  Not very clean.

**Comment by mshibuya** [comment]
Use `accepts_nested_attributes_for` to enable nested form. 
https://github.com/sferik/rails_admin/wiki/Has-many-association

**Comment by knovoselic** [comment]
@mshibuya Still doesn't happen with show action, embedded documents get serialized like this:
```
Device #56f3f4e74b72693168060000
```

**Comment by pardha-billa** [comment]
I'm facing same issue. Have any workaround?

**Comment by dmitrypol** [comment]
create a custom name method in the embedded model, that will get you something.
