### ISSUE TITLE
Integrating ActiveRecord::Enum with PostgreSQL Enumerated Types and Rails Admin

### ISSUE THREAD

**Issue by afarriaga** [sferik/rails_admin#2601]
I have implemented PostgreSQL enumerated types using Active Record in a rails 4.2.4 application following the tutorial below:

http://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/

The rails_admin gem has worked out-of-the-box for traditional enum fields that use numbers and texts. For this particular implementation, what happens is that when I attempt to change the gender and save, the field is emptied. In other words, the database shows a nil value for the gender attribute. The value attribute of the option elements in the rails admin ui are showing the correct strings.

I checked the rails_admin wiki and typed several search queries into google but haven't found yet any info about this. Thanks.

**Comment by AlexEscalante** [comment]
You may have a look at this:

https://github.com/sferik/rails_admin/issues/1993

While I haven't used the Rails 4.1 enum type yet, I've used `Enumerize` several times and it works very well:

https://github.com/brainspec/enumerize

**Comment by afarriaga** [comment]
Yeah thanks. It works well now. This issue may be closed.
