### ISSUE TITLE
Refile image displaying looks broken

### ISSUE THREAD

**Issue by sandric** [sferik/rails_admin#2605]
Hey there. I'm all new to rails_admin, worked all the time with active_admin, but now decided to try out rails_admin, and all looks great, but refile's images in admin panel. So I have a user model with avatar field on it, which is refile's attachment. As I understood, the work for integrating was already done by #2385 and the fact that I can select new images from edit view says that rails_admin understands that its refile's image. The thing is that in index and show views its displayed as link with relative path of image, which is wrong, or not? I never used rails_admin gem as I told before, so I'm not quite sure if that default behavior and I need some further tweaks, but I couldn't find any in wiki. If thats the case - please guide me. If not - I'm currently using 5.0.0.beta2 rails gem and master's head of sinatra - could this cause problems maybe? I also tried to describe in initializer refile's field type like that:

``` ruby
  config.model 'User' do
    list do
      field :name
      field :email
      field :avatar, :refile
    end
  end
```

The result is the same as with default config.

Thx.

**Comment by sandric** [comment]
Update - I made it work manually, by specifying by hand config for model, if that will be helpful:

```ruby
config.model 'User' do
    list do
      field :name
      field :email
      field :avatar, :refile do
        pretty_value do
          if (bindings[:object].avatar) 
              bindings[:view].image_tag bindings[:view].attachment_url(bindings[:object], :avatar, :fill, 100, 100)
          end
        end
      end
    end

    show do
      field :name
      field :email
      field :avatar, :refile do
        pretty_value do
          if (bindings[:object].avatar) 
              bindings[:view].image_tag bindings[:view].attachment_url(bindings[:object], :avatar, :fill, 300, 500)
          end
        end
      end
    end

    edit do
      field :name
      field :email
      field :avatar, :refile do
        pretty_value do
          if (bindings[:object].avatar) 
              bindings[:view].image_tag bindings[:view].attachment_url(bindings[:object], :avatar, :fill, 300, 500)
          end
        end
      end
    end
```

**Comment by mshibuya** [comment]
Could not reproduce, please reopen if the problem persists.
