### ISSUE TITLE
Encoding to Windows-1250

### ISSUE THREAD

**Issue by kacpermigala** [sferik/rails_admin#2610]
I got error :_ incompatible character encodings: UTF-8 and Windows-1250_
when i try to show something with chars from Poland ie. 'ąęźć'

in my application.rb i got:
config.encoding = "windows-1250"

In database.yml:
encoding: windows-1250

How can i show params in windows-1250 in rails admin panel?

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
