### ISSUE TITLE
Rails Admin runs user code when accessing admin page

### ISSUE THREAD

**Issue by stephenedwards** [sferik/rails_admin#2611]
Hi, 

I installed your gem on a new project and it worked fine so I wanted to integrate it into an existing project and I ran into a problem. 

I installed rails_admin with the following

**Ruby** 2.1.5
**Rails** 4.1.8

**Gemfile**

```
gem 'rails_admin'
gem 'ckeditor'
```

```
bundle install
rails g rails_admin:install (choose default namespace /admin)
rails s
```

So far so good no errors. 

However when I accessed _/admin_, my rails app suddenly started a custom function that I wrote once that happens to insert thousands of lines into delayed_job... This ruby file is in a sub directory under lib.

**/lib/company/fxmailing.rb** This is not the complete class but I don't think the business logic really matters in this case.

```
class Fxmailing
  def self.never_ordered
    customers = Customer.where(*CUSTOM LOGIC*)
    customers.each do |c|
      Custommailer.delay.never_ordered(c.id)
    end
  end
end
```

I would like to copy output but once I access admin page, it races off and I can't even cancel (rails s) anymore. opening new terminal and sudo rebooting is the only way out.

**Comment by mshibuya** [comment]
Putting `raise` in fxmailing.rb will help track down the problem. It will produce a stack trace, which includes source location that triggered the execution.

**Comment by mshibuya** [comment]
Please reopen on update.
