### ISSUE TITLE
authorization error

### ISSUE THREAD

**Issue by ATouhou** [sferik/rails_admin#2612]
Hi.
I'm not so skilled in ruby and I get stuck at the following papertrail error:

Apr 14 18:33:10 XXXXXXXXXXXXXXXXX:  I, [2016-04-14T12:33:10.032559 #4507]  INFO -- : {"method":"GET","path":"/XXXXXXXX/","format":"html","controller":"rails_admin/main","action":"dashboard","status":500,"error":"CanCan::AuthorizationNotPerformed:This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.","duration":2054.21,"view":242.7,"db":32.87,"params":{"controller":"rails_admin/main","action":"dashboard"},"time":"2016-04-14T12:33:07.977-04:00","remote_ip":"194.XXXXXXXX","stacktrace":"'[]'","@timestamp":"2016-04-14T16:33:10.031Z","@version":"1","message":"[500] GET /XXXXXXXXXXX/ (rails_admin/main#dashboard)"}

Any ideas how to move past this point? I've tried some combinations in rails_admin.rb   but didn't manage to get anything working

**Comment by mshibuya** [comment]
The error `CanCan::AuthorizationNotPerformed` says it all.
