### ISSUE TITLE
Virtual Enum Field Not Working

### ISSUE THREAD

**Issue by cec** [sferik/rails_admin#2615]
Hi,

having issues to add a virtual field (_change_importance_) of type enum for the edit section of one model.

The values for the virtual enum are meant to be provided by

```
  def change_importance_enum
    {little: 0, a_lot: 1}
  end
```

and here is the configuration of the field

```
field :change_importance, :enum do
  formatted_value { 0 }
end
```

I put 0 as formatted_value, because there is no actual data to provide a value for _change_importance_: the value is volatile and has meaning only in the scope of the current request.
I'm overriding the edit action of this model by placing my own controller in front of MainController from routes.rb. In my controller I determine whether or not to run a certain routine depending on the value of _change_importance_.

**The problem is** that when rendering, `_form_enumeration` calls `field.form_value`, which calls `form_default_value`, which calls `value`, which raises the usual error of a virtual field not declaring a formatted_value.

Can I override `form_value` for a specific field somehow?

**Comment by slbug** [comment]
Similar issue. Rails 5.rc1, rails_admin from master

Model: 

```ruby
  class User < ApplicationRecord
    attr_reader :role
  end 
```

```ruby
  config.model User do
    include_fields :user_name, :role

    field :role, :enum do
      enum do
        ['user', 'admin']
      end

      pretty_value
         bindings[:object].display_role
      end
    end
  end
```

And it just crashes ```NoMethodError: undefined method `defined' for nil:NilClass``` on <pre>"rails_admin-122cbf0b4fdd/lib/rails_admin/config/has_fields.rb", line 92, in block in fields</pre>

**Comment by slbug** [comment]
My issue gone after removing role from include_fields

**Comment by mshibuya** [comment]
You can define #value like this:
```ruby
field :change_importance, :enum do
  def value
    0
  end
end
```
