### ISSUE TITLE
ArgumentError in RailsAdmin::Main#dashboard

### ISSUE THREAD

**Issue by yohn89** [sferik/rails_admin#2618]
I got this error in production env.

rails version:4.2.5.2
rails_admin version ref: 355dc80

```
vendor/bundle/ruby/2.2.0/bundler/gems/rails_admin-355dc80f8a20/app/views/rails_admin/main/dashboard.html.haml where line #30 

arguments passed to url_for can't be handled. Please require routes or provide your own implementation
```

**Comment by mshibuya** [comment]
Does this solution work?
http://stackoverflow.com/questions/20660604/using-the-correct-url-for-method-in-a-rails-engine-spec

**Comment by yohn89** [comment]
@mshibuya 

Yes, It works. Thanks for sharing this solution.
I was including the line  `Rails.application.routes.url_helpers` in one controller, remove that line it works.

Thanks again !
