### ISSUE TITLE
Mongoid raise_not_found_error false cause undefined method for nil class

### ISSUE THREAD

**Issue by ppascualv** [sferik/rails_admin#2623]
Problem and workaround explained here: 

http://stackoverflow.com/questions/36911558/rails-admin-undefined-method-associations-for-nilnilclass/36911559#36911559

**Comment by ericcf** [comment]
@pabliiitoo are you able to write a unit test for this issue?

**Comment by pabliiitoo** [comment]
@ericcf I don't know how you test with diferent config files from 'wrapper' application.
If you can introduce me telling me which gems I need to meet or what part of code, I will try it.
Thank you.

**Comment by dfabreguette-ap** [comment]
This is blocking for me in production - any idea when this can fixed ?
