### ISSUE TITLE
Rails 5 alias_method_chain deprecated

### ISSUE THREAD

**Issue by confact** [sferik/rails_admin#2632]
Hi!

Testing Rails 5 with rails_admin and i got this message when running the app:
`DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from singleton class at /home/vagrant/.rvm/gems/ruby-2.2.5/bundler/gems/rails_admin-122cbf0b4fdd/lib/rails_admin/adapters/mongoid/extension.rb:14)`

If i understood it correctly you have to move around the code to fix this deprecated message.
Would love if this could be fixed.

**Comment by nazarok** [comment]
+1

**Comment by alexfarrill** [comment]
+1

**Comment by h8rry** [comment]
Any feedback on this? Still getting this.

**Comment by PikachuEXE** [comment]
[MongoID already fixed this a year ago](https://github.com/mongodb/mongoid/commit/c661f9de9ddc37558108fd7e6db48e8ec6de4c7c)

**Comment by PikachuEXE** [comment]
#2864 opened
