### ISSUE TITLE
Could not find table 'rails_admin_histories'

### ISSUE THREAD

**Issue by hendranata** [sferik/rails_admin#2639]
i am not really sure how to use audit/admin history.

when i use this:
 config.audit_with :history, Post

and enable both : 
history_index
history_show

it shows an error:
Could not find table 'rails_admin_histories'

can u help me to provide clear steps how to produce history/log for each model in rails_admin?

**Comment by bensheldon** [comment]
I believe that `audit_with :history` has been deprecated: https://github.com/sferik/rails_admin/wiki/Internal-audit-plugin

Papertrail is the recommended audit plugin: https://github.com/sferik/rails_admin/wiki/Papertrail

**Comment by mshibuya** [comment]
@bensheldon is right, thanks for the answer.
