### ISSUE TITLE
User.association

### ISSUE THREAD

**Issue by jcdavison** [sferik/rails_admin#2641]
Is there an obvious way to display records that are only associated with the authenticated user?

Assuming we have something like `User` and `Waffle` and there is standard `has_and_belongs_to_many` relationship between user and waffle, is it possible to have the admin interface display something like `current_user.waffles` in the `/admin/waffles` interface ?

**Comment by jcdavison** [comment]
see this SO post I've written, http://stackoverflow.com/questions/37490983/rails-admin-how-to-display-only-the-current-users-associated-records

**Comment by swapnilchincholkar** [comment]
@jcdavison 

I think showing current user's associated data should be within scope of your application logic & not under admin's scope. Either you will end in making every user as admin to see their waffles OR If admin wants to see all waffles then it will conflict with your logic. 

In rails app you can have code for current users waffles something like at "/users/:id/waffles" or "users/waffles" whatever..."/admin/waffles" should point to all waffles for admin's access, isn't it?

If you want something like admin will select any user & see that user's waffles, then you can create your own custom action, please refer to [End Point's Blog](http://blog.endpoint.com/2012/03/railsadmin-custom-action-case-study.html) & [Paul Rugel-Hiatt's blog](http://blog.paulrugelhiatt.com/ruby/rails/2014/10/27/rails-admin-custom-action-example.html)
