### ISSUE TITLE
Kaminari's Mongoid integration has been extracted

### ISSUE THREAD

**Issue by skalee** [sferik/rails_admin#2643]
I'm using Rails Admin with Mongoid and following deprecation warning has just appeared:

    DEPRECATION WARNING: Kaminari Mongoid support has been extracted to a separate gem, and will be removed in the next 1.0 release. Please bundle kaminari-mongoid gem.

In my project Kaminari is used only from Rails Admin. At the moment Rails Admin constraints Kaminari version to `~> 0.14`.

**Comment by dmitrypol** [comment]
I have rails_admin (0.8.1) with mongoid (5.1.3).  Once I added `gem 'kaminari-mongoid' `to my Gemfile the warning went away.

**Comment by mshibuya** [comment]
Add it to your app's Gemfile, it's user's responsibility to set it up correctly.

**Comment by marceloboeira** [comment]
>  Add it to your app's Gemfile, it's user's responsibility to set it up correctly.

Once you lock mongo in the gem's Gemfile you need to add the valid lock versions of the dependencies.
