### ISSUE TITLE
Show in app action disappears

### ISSUE THREAD

**Issue by PapePathe** [sferik/rails_admin#2644]
Hello @team. 

I recently updated rails_admin and i discovered the show_in_app button is no longer available. 

Any help?

**Comment by thedanielhanke** [comment]
Hello @PapePathe.

Any information?

(Config, authorization, etc)

**Comment by ouelletv** [comment]
@PapePathe @thedanielhanke Any updates on this?

**Comment by thedanielhanke** [comment]
@ouelletv as this public timeline shows, @PapePathe did not reply ;)
in case you have the same issue, paste information about your models config, rails_admin config, authorization-adapter details etc pp. anything that helps from asking a local witch to look into the glass - mine is broken :/  cheers ;)

**Comment by ouelletv** [comment]
Unfortunatly, I did not find what was the problem. I found a workaround tho... I created a custom rails_admin action (I named it Preview) which works exactly the same as the RailsAdmin default ShowInApp action. I literally copy pasted the code from the ShowInApp action from this repo.
Hope it helps!
