### ISSUE TITLE
Looking for sample of custom bulk action

### ISSUE THREAD

**Issue by dekhaus** [sferik/rails_admin#2647]
Hi All

I'm comfortable writing custom actions that operate on a single instance of a model.  

I'm now trying to write a custom bulk action and am having some trouble.

I'm basing my implementation on the BulkDelete action (bulk_delete.rb).  What's odd about my code is that the 'request.get?' portion of the 'proc do' is never called - so RailsAdmin doesn't have  a chance to generate a UI.  I need there to be a UI because I need to get some data from the user.  

Like I said - I implemented custom actions that operate on a single member 'instances', so I do understand how to customize RailsAdmin.  What I don't understand - and need help with, is exactly what I need to do to implement a custom bulk_action that first gets some user_data (say some value that all selected instances need to be updated with) and then updates all the selected instances.

Any help would be greatly appreciated.

Thanks
Dave

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.

**Comment by streetlogics** [comment]
I found this thread and ended up digging through the code to come up with an answer myself.  So - here is my question + answer thread on Stackoverflow for anyone else that comes across this - https://stackoverflow.com/questions/57838401/how-do-i-create-a-custom-bulk-action-in-rails-admin/57838402
