### ISSUE TITLE
Add padding to the main container area

### ISSUE THREAD

**Issue by DannyBen** [sferik/rails_admin#2648]
I believe it would not hurt to add a 50-100px padding to the main container area, so that HTML elements are never found at the very bottom of the page.

This will prevent situations like this:
![github](https://cloud.githubusercontent.com/assets/2405099/15805008/dde4ecb4-2b24-11e6-9f98-8516e79bf4d0.png)

**Comment by mshibuya** [comment]
Please submit PR is you need this.
