### ISSUE TITLE
Getting a I18n::ArgumentError on empty date

### ISSUE THREAD

**Issue by arthurnn** [sferik/rails_admin#2653]
So in a model I have a date that it is an empty String on the database. And because of that I get this error:
`I18n::ArgumentError - Object must be a Date, DateTime or Time object. "" given.:`
see full stacktrace: https://gist.github.com/arthurnn/8d17e2c75fc9fa9d34758bce630af0b7

changing [this if](https://github.com/sferik/rails_admin/blob/5a5c0387ee26fe6e6bbb5c97b9e863da1ac603d3/lib/rails_admin/config/fields/types/datetime.rb#L64) to:

```
  if (time = (value || default_value)) && time.respond_to?(:strftime)
```

fixes the issue. Is that the right solution? if so I can write a PR with a regression test.

Thanks

**Comment by hafizio** [comment]
I experience the same issue.

**Comment by mshibuya** [comment]
Closed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a .
