### ISSUE TITLE
export to cvs: exception: undefined method `encoding' for nil:NilClass, when table (or scope) is empty

### ISSUE THREAD

**Issue by gabrieletassoni** [sferik/rails_admin#2656]
Hi,
I'm experiencing an issue with rails_admin 0.8.1, trying to export an empty table, instead of just creating an empty csv file, it throws this error:

`undefined method`encoding' for nil:NilClass

Extracted source (around line #38):

```
def to_csv(options = {})
  # encoding shenanigans first
  @encoding_from = Encoding.find(UTF8_ENCODINGS.include?(@abstract_model.encoding) ? 'UTF-8' : @abstract_model.encoding)
  @encoding_to = Encoding.find(options[:encoding_to].presence || @encoding_from)

  csv_string = generate_csv_string(options)
```

Rails.root: -hidden-

Application Trace | Framework Trace | Full Trace
vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/support/csv_converter.rb:38:in `to_csv'
vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/lib/rails_admin/config/actions/index.rb:74:in`block (4 levels) in class:Index'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_controller/metal/mime_responds.rb:217:in `call'`

How could I avoid this error?
Thank you,
Gabriele

**Comment by whw** [comment]
+1 - I am also experiencing this error on 0.7.0

**Comment by deependersingla** [comment]
Any update on this?

**Comment by sahilchopra** [comment]
+1

**Comment by nrailsy97** [comment]
+1

**Comment by codealchemy** [comment]
A similar issue (https://github.com/sferik/rails_admin/issues/2796) was resolved with https://github.com/sferik/rails_admin/commit/464440cbdea7147634f020cde21c4606d3629dc5 (part of releases since [`1.1.1`](https://github.com/sferik/rails_admin/blob/master/CHANGELOG.md#111---2016-12-25)) - Is this still happening on recent releases?

**Comment by mshibuya** [comment]
This should not happen in the current codebase, I guess.
