### ISSUE TITLE
Support for PaperTrail 5

### ISSUE THREAD

**Issue by coorasse** [sferik/rails_admin#2660]
When using Paper trail 5 the following warning appears: 

> user_for_paper_trail is present, but whodunnit has not been set.
> PaperTrail no longer adds the set_paper_trail_whodunnit callback for
> you. To continue recording whodunnit, please add this before_action
> callback to your ApplicationController . For more information,
> please see https://git.io/vrTsk

**Comment by mshibuya** [comment]
Done in 9c42783aa65b704f4a5d467608c49b746c47b81b.
