### ISSUE TITLE
German date formatting corrupt

### ISSUE THREAD

**Issue by ain** [sferik/rails_admin#2668]
When using German locale, `created_at` and `updated_at` come across in corrupt format, e.g.: 

```
t 04, 2016 17:30
```

**Platform**:
- rails_admin 49aafbb
- rails_admin-i18n `1.10.2`
- rails `4.2.6`

**Comment by thedanielhanke** [comment]
@ain solved meanwhile? 

if not, `time.formats.long` is the key if i am correct. what does

```
I18n.locale = :de
DateTime.now.in_time_zone.strftime(I18n.t('time.formats.long'))
```
give you in return?

**Comment by mshibuya** [comment]
Closed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a .
