### ISSUE TITLE
Error:Get available generators script executes with errors:

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sferik/rails_admin#2673]
Hello

I have just installed Rials 5 with ruby 2.3. I have added this gem like this:

`gem 'rails_admin', github: 'sferik/rails_admin`

When I run `bundle install` command, I get that kind of error:

    Error:Get available generators script executes with errors:
    Error:D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-   5.0.0/lib/action_dispatch/middleware/stack.rb:108:in `assert_index': No such middleware to insert after: ActionDispatch::ParamsParser (RuntimeError)
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:80:in `insert_after'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/configuration.rb:69:in `block in merge_into'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/configuration.rb:68:in `each'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/configuration.rb:68:in `merge_into'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:507:in `block in app'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:504:in `synchronize'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:504:in `app'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:347:in `each'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:347:in `call'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    Error:	from D:/Ruby23-x64/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in ` `run_initializers'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:328:in `require'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:60:in `generate'
    Error:	from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'

**Comment by mshibuya** [comment]
Currently there's no official remotipart release with support for Rails 5.
You have to point my fork
```
gem 'remotipart', github: 'mshibuya/remotipart'
```
as described in Installation section of README.
https://github.com/sferik/rails_admin#installation
