### ISSUE TITLE
Updated example needed for using active_record_enum fields in filtering/searching

### ISSUE THREAD

**Issue by jessesanford** [sferik/rails_admin#2676]
It's currently not clear if it is possible to use ActiveRecord enum fields for searching/filtering. What is the correct syntax for it with the 1.0.0rc version for rails_admin? Is it the same for Rails 4.2 and Rails >=5? Can you show two examples if there are differences? Are any monkey patches still necessary? Can it simply be done with syntax like "field :status, :enum" ? It seems that when I try that searching still causes postgres error for trying to search an integer column with a string value:

`ActiveRecord::StatementInvalid in RailsAdmin::Main#index
Showing /workspace/admin/vendor/ruby/2.2.0/gems/rails_admin-1.0.0.rc/app/views/rails_admin/main/index.html.haml where line #92 raised:

PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "error"
LINE 1: ...FROM "results" WHERE ((results.status IN ('error')) ...`

**Comment by onlyyouandty** [comment]
Did you find a way around this?

**Comment by jessesanford** [comment]
No I still cannot search and filter with enums unfortunately. Has anyone else found the correct dsl syntax to make this happen?

**Comment by lucianoiscool** [comment]
+1

**Comment by tbilous** [comment]
+1

**Comment by mshibuya** [comment]
Wiki was updated.
https://github.com/sferik/rails_admin/wiki/Enumeration#activerecord-enumsrecommended
