### ISSUE TITLE
ActiveRecord::StatementInvalid in RailsAdmin::Main#edit 

### ISSUE THREAD

**Issue by hammadxcm** [sferik/rails_admin#2685]
ActiveRecord::StatementInvalid in RailsAdmin::Main#edit
Showing /Users/hammadkhan/.rvm/gems/ruby-2.3.0/gems/rails_admin-1.0.0.rc/app/views/rails_admin/main/_form_filtering_select.html.haml where line #10 raised:

PG::UndefinedColumn: ERROR:  column roles.user_id does not exist
LINE 1: SELECT  "roles".* FROM "roles" WHERE "roles"."user_id" = $1 ...
                                             ^
: SELECT  "roles".* FROM "roles" WHERE "roles"."user_id" = $1 LIMIT $2

**Comment by hammadxcm** [comment]
I am not using Role model yet. I just defined relation only bt rails g migration add_roll_id_to_user roll_id:integer

**Comment by mshibuya** [comment]
That's the problem, you must have your associations/models fully set-up to use RailsAdmin.
