### ISSUE TITLE
Update dependency for Haml gem

### ISSUE THREAD

**Issue by Schwad** [sferik/rails_admin#2686]
https://github.com/haml/haml/blob/025b89f421a31cd18db5cacdbcf69cbec893322f/lib/haml/version.rb 

Haml is up to `5.0.0.beta.2`, this gem currently has a dependency of `~> 4.0`

https://github.com/sferik/rails_admin/blob/60edfe4050dc83ca236c619516bceab796191cd9/rails_admin.gemspec

**Comment by k0kubun** [comment]
Looks like https://github.com/sferik/rails_admin/pull/2840 solved this. Enjoy Haml 5.

(You may need https://github.com/sferik/rails_admin/pull/2870.)
