### ISSUE TITLE
Routing docu improvements

### ISSUE THREAD

**Issue by ain** [sferik/rails_admin#2687]
Current [Using RailsAdmin routes](https://github.com/sferik/rails_admin/wiki/Using-RailsAdmin-routes#link-to-your-application-from-railsadmin-usually-from-a-config-block) should be improved.

__Situation__:

1. Create model `Kaboom` with field `kaboom:integer` 
2. Configure model for linkage:

  ```ruby
  configure :kaboom do
    pretty_value do
      if value.present?
         linked_kaboom = Kaboom.find(value)
         unless linked_kaboom.nil?
           bindings[:view].link_to(linked_kaboom.title, bindings[:view].rails_admin.kaboom_path(linked_kaboom))
         end
      end
    end
  end
  ```

__What happens__:
```
undefined method `kaboom_path' for #<ActionDispatch::Routing::RoutesProxy:0x000000059894f0>
```

__What's the right path reference in the above scenario?__

Version under question: eefa8ac

**Comment by mryuriy** [comment]
@ain You mixed up approaches from documentation: 
- if you want to have a link within rails_admin then you going to use 
 bindings[:view].rails_admin.show_path(model_name: 'kaboom', id: linked_kaboom.id)
- or a external link within your application routes(excluding rails admin):
 bindings[:view].main_app.kaboom_path(linked_kaboom)

**Comment by ain** [comment]
Excellent! Thanks for the support @mryuriy. 

I think the points you made here would be of great help in the docu.

**Comment by thedanielhanke** [comment]
@ain can this be closed?
