### ISSUE TITLE
Can someone help me, my assosiation category not show in stock model rails_admin

### ISSUE THREAD

**Issue by wicky-info** [sferik/rails_admin#2689]
I have category model to show in stock model but category name not show , only category#id, like 
when klik dropdown
category#4
category#3
category#2
category#1
here is my source code
## config/initializers/rails_admin.rb

![screenshot from 2016-08-15 06 04 44](https://cloud.githubusercontent.com/assets/8560064/17652739/004c6022-62af-11e6-8bfa-e3d8d4935ef8.png)
## and this /admin

![screenshot 2016-08-15 06 04 16](https://cloud.githubusercontent.com/assets/8560064/17652747/47ab8984-62af-11e6-9991-179f6c12171e.png)
thank you for help me

**Comment by mryuriy** [comment]
@wicky-info by default raild_admin config has config.label_methods == [:name, :title], probably your Category has another field that's going to be label_method. If you want to add specific label method only for one model (Category) then within model's config use:
`object_label_method :some_label_field`

**Comment by wicky-info** [comment]
yes my category have field like this 
config.model Category do 
edit do
field :name 
end
end 
but now I use Category for assosiation with Stock Model
config,model stock do 
edit do
field :name_stock
field :category
end 
end
my question is why category name did'nt show in Stock only Id category ? thanks for your help

**Comment by thedanielhanke** [comment]
is this solved meanwhile?

**Comment by wicky-info** [comment]
not yet @thedanielhanke, I will try 
config,model stock do
edit do
field :name_stock
field :category.name
end
end

**Comment by thedanielhanke** [comment]
`category.name` will not work.

what are your model-field-names for category exactly + what did you configre in rails-admins config for `label_methods` ?

**Comment by wicky-info** [comment]
@thedanielhanke  I Have category model with field name:string, and category belongs_to :stock and stock model has_many :categories, I want to chose category field name in stock model. thanks for your help.

**Comment by thedanielhanke** [comment]
@wicky-info  yes i understand that point, still i need your active-record column names for the Category model, not its rails_admin fields ;)

**Comment by RogerioLira** [comment]
I Had the same problem, you need to rails_admin.rb set up in the model:
[https://github.com/sferik/rails_admin/wiki/Models](url)
[https://github.com/sferik/rails_admin/wiki/Models#the-object_label_method-method](url)

**Comment by wicky-info** [comment]
thank you @RogerioLira  I will try.
