### ISSUE TITLE
About jsonb field

### ISSUE THREAD

**Issue by marlborox** [sferik/rails_admin#2694]
I have one field jsonb type.But i use search function, it show me exception error.
error message : A JSON text must at least contain two octets!
Do you have any solutions,please? 

extracted source :
  # \* _array_class_: Defaults to Array
  def parse(source, opts = {})
    Parser.new(source, opts).parse <---
  end

**Comment by sbull** [comment]
Looks like dup of https://github.com/sferik/rails_admin/issues/2502
