### ISSUE TITLE
Downgrade to jquery2 to avoid pjax bug

### ISSUE THREAD

**Issue by mendelk** [sferik/rails_admin#2696]
I'm using `rails_admin` in a Rails 4.2.6 app, and am experiencing the bug reported in defunkt/jquery-pjax#634. This is due to `rails_admin` using jquery 3. This breaks `rails_admin` functionailty.

Perhaps until it gets resolved, `rails_admin` should `//= require jquery2`?

Thanks!

**Comment by sviechnikov** [comment]
I have the same issue.. 
I think, it's can be fixed by adding jquery-migrate. But it need to add before pjax defining.

**Comment by patleb** [comment]
I don't see any requires about jquery 2 or 3 here [here](https://github.com/sferik/rails_admin/blob/dca8911f240ea11ebb186c33573188aa9e1b031d/app/assets/javascripts/rails_admin/rails_admin.js)... not sure that your bug is related to rails admin. Thx for pointing out jquery-migrate @sviechnikov.
