### ISSUE TITLE
rails_admin + cancancan

### ISSUE THREAD

**Issue by marlborox** [sferik/rails_admin#2697]
I got this error. "uninitialized constant Main" I dont't know how to fix?

version:
gem 'rails_admin', '1.0.0.rc'
gem 'rails', '~> 5.0.0.rc2'

**Comment by jasnow** [comment]
Need more details. Can you share a link to your repo?

**Comment by marlborox** [comment]
MY config/initializers/rails_admin.rb

require "rails_admin/application_controller"
module RailsAdmin
  class ApplicationController < ::ApplicationController
    load_and_authorize_resource
  end
end

error:
NameError in RailsAdmin::MainController#dashboard
uninitialized constant Main

Extracted source (around line #268):              
266      names.inject(Object) do |constant, name|
267        if constant == Object
268          constant.const_get(name)
269        else
270          candidate = constant.const_get(name)
271          next candidate if constant.const_defined?(name, false)

**Comment by mshibuya** [comment]
Your app appears not to be set up properly.
