### ISSUE TITLE
Postgres SELECT count(*) is slow

### ISSUE THREAD

**Issue by ostinelli** [sferik/rails_admin#2699]
First of all, thank you for your work!

Here's something that bit me today: in counting items (`SELECT COUNT(*) FROM table`), Postgres must walk through all rows ([source](https://wiki.postgresql.org/wiki/Slow_Counting)), hence it can become too slow for dashboard and pagination.

We have some tables of 1-10 Mio entries, and this is killing Rails Admin (the query analysis tells us that it takes around 10-20 seconds just to count the rows). Right now, we have disabled the dashboard and those tables.

I'm not sure what to recommend here. There are alternatives to count the number of rows quickly, for instance as explained in [this StackOverflow](http://stackoverflow.com/a/14571935) answer.

Any recommendations?

**Comment by mshibuya** [comment]
You can disable dashboard statistics if you don't need it.
https://github.com/sferik/rails_admin/wiki/Dashboard-action#disabling-record-count-bars

**Comment by ostinelli** [comment]
@mshibuya: if you read my post, you'll see that I already did, and pagination is the issue.
It's alright if you don't want to fix this, I'd hope you would read that the issue here is _pagination_, but ok. All the best.

**Comment by mshibuya** [comment]
I've misread you, I got it now.
There's a little things we can do about pagination. Someday, somebody might build whole-sophisticated pagination library, which won't perform `COUNT(*)` query. But that's out of the scope of RailsAdmin, and we won't discuss it here.
Thanks for using RailsAdmin, and giving us the suggestion.

**Comment by ostinelli** [comment]
Thank you for your reply.

**Comment by SauloSilva** [comment]
@ostinelli I was having this problem until I found [this](https://github.com/sferik/rails_admin/blob/e20ff43dae2de4fd132d7214525b4a3fa5c01361/app/views/rails_admin/main/index.html.haml#L109)

`list { limited_pagination true }`

I hope help you

**Comment by Sergezdv** [comment]
it would be nice to be able to manage the counting strategy... in a model I can use something like this

```
  def self.count
    begin
      to_sql
      super
    rescue Exception => e
      ActiveRecord::Base.connection.exec_query("SELECT reltuples AS approximate_row_count FROM pg_class WHERE relname = '#{table_name}'")[0]['approximate_row_count'].to_i
    end
  end
```

this reduces the counting time for large tables from 22 to 0.13s
but now I have not figured out whether it can be applied to the page, and while you have to turn off statistics

**Comment by mltsy** [comment]
Adding this monkeypatch to rails_admin.rb (or another initializer) seems to do the trick at least for the dashboard, and pagination on unfiltered results:
```ruby
module ActiveRecordAdapterMonkeyPatch
  def count(options, scope)
    if model.respond_to?(:approximate_count) &&
       options.empty? &&
       scope == all
      model.approximate_count
    else
      super(options, scope)
    end
  end
end
RailsAdmin::Adapters::ActiveRecord.prepend(ActiveRecordAdapterMonkeyPatch)
```

Using this, you can add an `approximate_count` method to any model (or your ApplicationRecord class) to do an approximate count instead of a `.count`, like this:

```ruby

  def self.approximate_count
    query = "SELECT reltuples AS approximate_row_count FROM pg_class WHERE relname = '#{table_name}';"
    result = connection.execute(query)
    result.first["approximate_row_count"]
  end
```

Note: This won't work with filtered results, since that counting technique only gives you an estimate of how many rows are in the full table (which is why it falls back to the default implementation if options or scope are specified).

`limited_pagination` (mentioned above) is still a good option to use on list views to avoid errors with trying to page past the end of bad estimates, or DB thrashing trying to count filtered results.  This is mostly useful for the dashboard.

**Comment by kotsiuruba** [comment]
@mltsy thank you. That helped me a lot :+1: 
One more addition I would add it `if` statement:
`if model.respond_to?(:approximate_count) && options.empty? && (scope.blank? || scope == all)`
On the `dashboard` page `scope` value is `nil`
