### ISSUE TITLE
Image size on Show page

### ISSUE THREAD

**Issue by Joshfindit** [sferik/rails_admin#2700]
Currently the show page shows the thumbnail.

It makes more sense to have this be a full-width image as this is a place to look at detail.
How do we accomplish this?

**Comment by mshibuya** [comment]
I'm not sure of necessity of that, but it will be possible to provide configuration option within [FileUpload field](https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/file_upload.rb). PR is welcome.
