### ISSUE TITLE
Need to correctly infer if a relationship is optional or not

### ISSUE THREAD

**Issue by tosbourn** [sferik/rails_admin#2702]
In Rails 5 `belongs_to` relationships are required by default.

However if you just have;

```
class Model < ApplicationRecord
  belongs_to :other_model
end
```

Then RailsAdmin marks this field as optional. This can be addressed in the model by doing;

```
class Model < ApplicationRecord
  belongs_to :other_model, required: true
end
```

It would be nice if RailsAdmin took into account the version of Rails when deciding if a relationship is required or not.

**Comment by ordinaryzelig** [comment]
I think the reason is because the validation is actually getting killed somehow. I subitted an issue: https://github.com/sferik/rails_admin/issues/2785.

**Comment by tosbourn** [comment]
@ordinaryzelig nice, I will close this issue.
