### ISSUE TITLE
Move "last links" show/edit/delete/showinapp buttons to the left side

### ISSUE THREAD

**Issue by dgleba** [sferik/rails_admin#2704]
I am have been looking for documents on how to move the edit button to the left side of the list view. I haven't found anything.

Can someone help me with how to move these buttons?

![screenshot-9_1_2016 10_09_57 am-chrome legacy window_audit _ rail263 admin - google chrome](https://cloud.githubusercontent.com/assets/4622715/18170533/a1ba165e-702c-11e6-9765-e901a490f7c6.png)

**Comment by mshibuya** [comment]
Not possible via configuration, but can be achieved by overriding view template.
