### ISSUE TITLE
Filter refresh button is broken

### ISSUE THREAD

**Issue by klyonrad** [sferik/rails_admin#2705]
this code https://github.com/sferik/rails_admin/blob/v1.0.0.rc/app/views/rails_admin/main/index.html.haml#L54

Produces broken html

when I change the line to
`%button.btn.btn-primary{type: "submit", :'data-disable-with' => '<i class="icon-white icon-refresh"></i>'.html_safe + t("admin.misc.refresh")}`

This also counts as a very good example that is a good practice the follow to ruby style guide:
**Do not use double quote strings when you don't need interpolation!** https://github.com/styleguide/ruby/strings#strings

**Comment by mshibuya** [comment]
Fixed by #2706.
