### ISSUE TITLE
remote url

### ISSUE THREAD

**Issue by readergirltracey** [sferik/rails_admin#2708]
Is their a way to use remote file uploading in rails admin

**Comment by luizpicolo** [comment]
Upload to AWS for example?

**Comment by readergirltracey** [comment]
no as in the file upload input allow for upload from online sources

**Comment by dalpo** [comment]
@readergirltracey this isn't an issue related to rails_admin.

You could implement your own setter method (es. `def remote_asset_url=(url)`) to store a remote asset or simply use an existing gem like carrierwave that already implemented it: https://github.com/carrierwaveuploader/carrierwave#uploading-files-from-a-remote-location
