### ISSUE TITLE
NoMethodError in RailsAdmin::MainController#index 

### ISSUE THREAD

**Issue by foliwe** [sferik/rails_admin#2710]
undefined method `per' for #<Article::ActiveRecord_Relation:0x007f4bfa548498>       

arel.public_send(method, *args, &block)
      else
        super
      end
    end
  end
I get this error when i click on any model name in the admin panel

I don't know if and missing some configurations

**Comment by Kosai106** [comment]
I've started to get this too, which is odd seeing as everything worked just fine for the longest time.

**Comment by mshibuya** [comment]
Have you checked this?
https://github.com/sferik/rails_admin/wiki/Troubleshoot#conflict-between-will_paginate-and-kaminari

**Comment by Kosai106** [comment]
@mshibuya I actually realised right after I posted what the issue was, and it was indeed will_paginate.

Lucky for me, I don't need it in my project anyway as it turns out. :)
