### ISSUE TITLE
Failed to apply :id constraints to member action.

### ISSUE THREAD

**Issue by wenkun-tonghui** [sferik/rails_admin#2716]
I wan the :id property accept dots inside url, for example, http://dev:3000/admin/namespace~model/a.b.c can be routing correctly to the rails main controller.

However, the following statement in rails application doesn't work for my case,
 mount RailsAdmin::Engine => '/admin', :as => 'rails_admin', constraints: { id: /[\w+.]+/ }

Meanwhile, if I modify the source code in "RailsAdmin::Engine.routes.draw" to be this one,

RailsAdmin::Config::Actions.all(:member).each { |action| match "/#{action.route_fragment}", action: action.action_name, as: action.action_name, via: action.http_methods, id: /[\w+.]+/ }

It works correctly. Anyone has a better solution to apply this change on the rails application routes?

**Comment by mshibuya** [comment]
This is rather a question on Rails routing, not an issue of RailsAdmin.
