### ISSUE TITLE
Make id field clickable and redirect to the show

### ISSUE THREAD

**Issue by amrdruid** [sferik/rails_admin#2717]
the question seems naive but I'm new to rails admin

I need to make the id column clickable, so when I click on the object's id I can be redirected to the show 

![selection_055](https://cloud.githubusercontent.com/assets/6736430/18626260/286d14c8-7e54-11e6-85c4-5d1bfe7f10ef.png)

And can't I override these views ?

**Comment by brilyuhns** [comment]
@amrdruid See if this works for you
```ruby
config.model Booking do
    list do
      field :id do
        formatted_value do
          path = bindings[:view].show_path(model_name: 'Booking', id: bindings[:object].id)
          bindings[:view].link_to(bindings[:object].id, path)
        end
      end
      ....
end
```

**Comment by amrdruid** [comment]
Many thanks !
