### ISSUE TITLE
Custom action with back_or_index

### ISSUE THREAD

**Issue by jamesfzhang** [sferik/rails_admin#2718]
If you're using a custom action, how do you make sure that `back_or_index` works properly? It currently always return to the main index instead of the previous page because `back_to_index` checks for `return_to` param to be set. This gets annoying when you click on a custom action from a paginated or filtered index.

**Comment by mshibuya** [comment]
Populating hidden `return_to` field in your custom action form should work:
https://github.com/sferik/rails_admin/blob/dca8911f240ea11ebb186c33573188aa9e1b031d/app/views/rails_admin/main/_submit_buttons.html.haml#L3

**Comment by drkaleem** [comment]
This solution assume there is a custom form as well in use. Is there any other alternatives when not using custom forms but just custom controller. Like may be some config in the rails_admin.rb file ?

**Comment by drkaleem** [comment]
This still does not work. Im using RA 1.4.2 and it has the above mentioned code change. But the behavior of redirect_to back_or_index from a custom controller always takes back to index page.
