### ISSUE TITLE
Unable to autocomplete while searching - Arabic

### ISSUE THREAD

**Issue by amrdruid** [sferik/rails_admin#2719]
I have an issue that whenever I try to type a name for autocomplete, it works properly with english letters and doesn't work with arabic 

Here's an example with english letters 
![selection_065](https://cloud.githubusercontent.com/assets/6736430/18720628/fde85c00-802c-11e6-9139-72f5fd609823.png)

doesn't work with arabic though

**Comment by mshibuya** [comment]
What does 'doesn't work' mean? What did you expect and actually get?

**Comment by amrdruid** [comment]
@mshibuya When the list is Arabic, no query I enter matches any arabic string in the list no matter how identical, does it occur with any non-english languages ?

**Comment by mshibuya** [comment]
You have to set your database collation properly to query on non-ascii characters. Googling 'collation' with RBDMS you use may help.
