### ISSUE TITLE
Failed to configure current user

### ISSUE THREAD

**Issue by pavelvasev** [sferik/rails_admin#2721]
I have own auth system. How may I tell to RailsAdmin which `current_user` object should RailsAdmin use?

I tried to use advice from page https://github.com/sferik/rails_admin/wiki/Devise 

```
config.current_user_method(&:current_user)
```

But it seems the example refer to some `current_user` method defined in RailsAdmin module...

And my `current_user` method is defined in ApplicationController of my main application.

So, what is the correct what to tell RailsAdmin which current_user object should it use?

**Comment by amicming** [comment]
yes, that is the problem. 

I tried like 
```config.current_user_method(&:current_user)``` was ```config.current_user_method { current_user }```

now if I click on link ```admin/user/2``` , I am getting ```stack level too deep```.

Second, if I am not replacing ```config.current_user_method { current_user }``` TO ```config.current_user_method(&:current_user)```, I am getting error like method not found it should be ```_current_user```.

**Comment by amicming** [comment]
working for me, when I configured ```config.parent_controller = "::ApplicationController"``` in ```config/initializers/rails_admin.rb```. Hope this help.

**Comment by plukevdh** [comment]
@amicming's solution worked for me.

**Comment by mlt** [comment]
Did anything change? I tried setting `config.parent_controller` as described above, but I'm still getting
```ruby
undefined local variable or method `current_user' for #<RailsAdmin::MainController:0x00000000066308e8> Did you mean? _current_user
```
Rails 4.2.10, rails_admin 1.2.0

**Comment by mlt** [comment]
I had to define `pundit_user` as an alias for my `current_user` method in my *ApplicationController*. Also I had to `dashboard?` method to my ApplicationPolicy.
