### ISSUE TITLE
Accepts_nested_attributes_for not working (in v 1.0.0)

### ISSUE THREAD

**Issue by Jamevid** [sferik/rails_admin#2722]
Firstly, AWESOME JOB with version 1.0.0! :) :) :)

The example:
1. accepts_nested_attributes_for :comments
2. Comment model has belongs_to :post  (so should create a ui-autocomplete-input)..but gives the error: 
"Uncaught TypeError: Cannot set property '_renderItem' of undefined"

Please see attached pic. 

I tried with different projects and models and nothing worked. 

Rails admin 1.0.0
Rails 5.0.1

<img width="764" alt="screen shot 2559-09-26 at 9 25 00 pm" src="https://cloud.githubusercontent.com/assets/947258/18838220/e2e53510-8430-11e6-9288-63a468714d6f.png">

Thanks again! :)

**Comment by demoabc** [comment]
+1 
I also have this problem. 
I am work with rails 4.2.1 and mongoid.

**Comment by Jamevid** [comment]
RailsAdmin 0.6.6  and Rails 5.0.0 seems to work well with very nested forms :)

If someone wants to try it out:

1. In gemfile
gem 'nested_form' 
gem 'safe_yaml'   
gem "font-awesome-rails" 
gem 'rack-pjax', github: 'afcapel/rack-pjax'
gem 'remotipart', github: 'mshibuya/remotipart'
gem 'rails_admin', '0.6.6', :path => 'vendor/rails_admin-0.6.6' 

2. In ra.nested-form-hooks.coffe
Replace "a[href=" with "a[href=\\" .....find and replace in editor

3. In property.rb  
replace "model.serialized_attributes[property.name.to_s]" with "model.type_for_attribute(property.name).class == ::ActiveRecord::Type::Serialized"

**Comment by ericchapman** [comment]
I am seeing the same thing.  It appears to only happen when the array is empty

**Comment by benhutton** [comment]
We are seeing this as well. Anybody have a workaround or an idea at a fix?

**Comment by hchasey** [comment]
+1 — same issue here....
