### ISSUE TITLE
CSV column order bug

### ISSUE THREAD

**Issue by silva96** [sferik/rails_admin#2727]
When mixing up schema fields and custom methods in the export configuration we would like the csv to preserve the order of the columns as they were defined in the configuration.

But [this line of code](https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/support/csv_converter.rb#L12)

`@methods = [(schema[:only] || []) + (schema[:methods] || [])].flatten.compact`

Is taking all schema fields first, then all methods and , so the order is messed up.

The workaround is to define columns as methods.

example:

should be as field like this
`field :bank_name`

redefined as custom method

``` ruby
field :bank_name_column do
  formatted_value do
    t = bindings[:object]
    t.bank_name
  end
  label 'Bank Name'
end
```

**Comment by mshibuya** [comment]
Merging into #2580.
