### ISSUE TITLE
Deleting records on the dummy app doesn't work

### ISSUE THREAD

**Issue by mattruzicka** [sferik/rails_admin#2728]
Trying deleting the record at: http://rails-admin-tb.herokuapp.com/admin/team/152/delete

The reason I tried to do this on the dummy app is that it wasn't working for me locally. In fact, it appears that none of the 'POST' actions are working for me or the dummy app.

I'm using rails_admin 1.0, Rails 4.2.6, and Ruby 2.2.3p173

Thanks.

**Comment by mshibuya** [comment]
Demo site is not working fine right now, sorry for inconvenience.
