### ISSUE TITLE
Custom Action fails to download correct file with any file format

### ISSUE THREAD

**Issue by itsrishav** [sferik/rails_admin#2730]
As the file which I'm sending is ZIP format but after getting downloaded its a nested zip which on opening creates another zip file and just goes on.

So basically this is my custom action where I'm calling my Service which will create a zip file through gem rubyzip and I'm sending the file_path of the created zip file with is on my local machine(e.g file_path as "#{Rails.root}/abc.zip")

```
    else
      # all your code that does the work
      import_params = params.require(:documents)
                            .permit(:email)

      if import_params[:email].present?
        @result = Download::Forms.call(mail_id: import_params[:email])
        if @result[:status]
          flash.now[:notice] = 'File Downloaded'
          send_file(
                @result[:file_path],
                filename: @result[:file_name],
                type: "application/zip"
          )
        else
          flash.now[:error] = "Failed to Download because #{@result[:error_message]}"
        end
      else
        flash.now[:notice] = 'Please Enter Email Address'
      end
      @result
    end
```

As I also send the @result in the end so that I can also try link_to method to download the file but all in vain. I'm using Rails 4.2.6

Some more information regarding the file types is that I tried a txt file and a pdf file also to check whether they are downloading properly but the same result they got downloaded but they were not proper as txt file was containing nothing and pdf can't be opened.

The files are getting downloaded with my custom action name and not from the file name which is the right naming if I download a file from any simple action. 

Any help will be really appreciated.

**Comment by itsrishav** [comment]
I ended up by _mailing_ the zip file created as I still didn't figure out why the file is not getting downloaded by the **send_file** method

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
