### ISSUE TITLE
Incorrect path resolution

### ISSUE THREAD

**Issue by airled** [sferik/rails_admin#2731]
I do not know if it is really issue. I have deployed my rails app on a server and run it under nginx. Nginx config has proxy_pass directive to http://localhost:3003. All links on my ordinary pages look fine but on rails admin page there is 'localhost' everywhere.
![2016-10-02-162843_1366x768_scrot](https://cloud.githubusercontent.com/assets/10863999/19020888/a8ef85a4-88bd-11e6-90f6-b53ee1c689c6.png)
Is there a way to correct it somehow?

**Comment by pasierb** [comment]
add Host header to location definition

```
location @your_cluster {
  proxy_pass ...
  proxy_set_header Host $host
}
```
