### ISSUE TITLE
Record Not Found

### ISSUE THREAD

**Issue by godzilla74** [sferik/rails_admin#2734]
I'm getting the above error after trying to update a record.  Looks like it saves, but instead, I'm sent back to the main `/admin` page with the following message:

![screen shot 2016-10-04 at 5 10 54 pm](https://cloud.githubusercontent.com/assets/737720/19093888/2531c14c-8a5b-11e6-94bb-9dcf4595118a.png)

Seems like the attributes that throw this message were added as a later migration after running `rails g rails_admin:install`.

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
