### ISSUE TITLE
Should not set datefield to string (of other locale) it cannot parse back

### ISSUE THREAD

**Issue by aurimus** [sferik/rails_admin#2735]
I'm getting this with any model that has `datetime` because the locale is Norwegian and it cannot parse the date back.

![screenshot from 2016-10-06 13-26-02](https://cloud.githubusercontent.com/assets/1052992/19152132/7639d3c2-8bc8-11e6-9d88-051b69cd68db.png)

![screenshot from 2016-10-06 13-25-11](https://cloud.githubusercontent.com/assets/1052992/19152143/7ae9b86a-8bc8-11e6-99b8-8f68b8b7664c.png)

**Comment by aurimus** [comment]
May it be because of Norwegian datename, that is - it can't parse the date description?

**Comment by Fattouh92** [comment]
did you solve this, the same happens to me with arabic locale

**Comment by aurimus** [comment]
Yes, basically you set it to output the date in other format. Maybe @str1fe can help you out

**Comment by mshibuya** [comment]
Closed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a .
