### ISSUE TITLE
Could not edit and delete: No route matches [POST] /admin/model/id/edit and /admin/model/id/delete

### ISSUE THREAD

**Issue by zekedran** [sferik/rails_admin#2739]
Started a new rails 5 api project, created models, added `rails_admin`. I could see a beautiful admin panel running on /admin, I could do everything except `edit` and `delete`.

    {"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [POST] \"/admin/city/3/edit\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"}...]}}
    {"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [POST] \"/admin/city/3/delete\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"}...]}}`

I checked my routes, and infact POST was not present on EDIT or DELETE

	Routes for RailsAdmin::Engine:
	  dashboard GET         /                                      rails_admin/main#dashboard
	      index GET|POST    /:model_name(.:format)                 rails_admin/main#index
	        new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
	     export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
	bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
	bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
	       show GET         /:model_name/:id(.:format)             rails_admin/main#show
	       edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
	     delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
	show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app

**Comment by zekedran** [comment]
Saw one similar SO Post [here](http://stackoverflow.com/questions/19381685/no-route-matches-post-for-delete-and-update). I think this happens because `rails-5-api` removed many middleware that were not required for `api`s

Solution is adding this in `application.rb`

    config.middleware.use Rack::MethodOverride

**Comment by zekedran** [comment]
Wufff! It's there in [troubleshoot page](https://github.com/sferik/rails_admin/wiki/Troubleshoot#no-route-matches-post-for-delete-and-update) of this wiki!

I suggest mentioning this in **how to install** itself.

**Comment by thedanielhanke** [comment]
@zekedran so this issue can be closed in order to clean up?
