### ISSUE TITLE
undefined method `inline_edit' for #<RailsAdmin::Config::Fields::Types::HasManyAssociation:0x00000006766a50>

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [sferik/rails_admin#2744]
I have found interesting error:

My code in `rails_admin.rb` file is this:

```
  config.model Category do
    edit do
      field :speeches do
        inline_add false
        inline_edit false
      end
    end
  end
```

When I open my rails_admin panel it shows me this:

```
 NoMethodError in RailsAdmin::MainController#dashboard
 undefined method `inline_edit' for #<RailsAdmin::Config::Fields::Types::HasManyAssociation:0x00000006766a50> Did you mean? inline_add
```

However, if I remove `inline_edit` it works.

Inline edit exists in has_many association, it could be called when user double-clicks to models name and editing modal appears.

**Comment by thedanielhanke** [comment]
@SuperMasterBlasterLaser the `has_many` association in rails_admin simply does not feature a inline_edit option. its currently limited to `has_one` and `belongs_to`.

so this is not a bug. ;)

**Comment by thedanielhanke** [comment]
see https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/has_many_association.rb#L20

**Comment by SuperMasterBlasterLaser** [comment]
@thedanielhanke But when I double click on name of my model, edit modal appears.

**Comment by thedanielhanke** [comment]
@SuperMasterBlasterLaser ah cool. even `nested_form false` does not help in this case. that might indeed be a bug. :+1: 
maybe you might want to rephrase this issues title to point on beein unable to disable this.

**Comment by SuperMasterBlasterLaser** [comment]
@thedanielhanke Updated my question as you asked.

**Comment by Jamevid** [comment]
👍

**Comment by elsupergomez** [comment]
I have the same problem.
Doble click show modal form to edit.
I mark nested_form false but nothing change.

**Comment by mshibuya** [comment]
Dup of #1911.
