### ISSUE TITLE
Couldn't edit/show/export User model

### ISSUE THREAD

**Issue by likelion-donghun** [sferik/rails_admin#2745]
On /admin panel, I can do show, edit, destroy on all the model except the  user model.
Below is the result of page

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Is this needed any more setting?

Thankyou for your contributions.

**Comment by thedanielhanke** [comment]
@likelion-donghun your description lacks the actual situation, including 

- your setup (rails version, ruby, etc)
- your rails-admin configs
- your models (relevant parts)
- what you actualy did (What exactly triggered your error).

futher, your "result" is the rendered 500 server error. 
please provide the error-messages  from your rails-log etc. 

w/o that information its hard to even think about it.

**Comment by mshibuya** [comment]
Please reopen on update.
