### ISSUE TITLE
current_user method broken with manual authorization

### ISSUE THREAD

**Issue by ChetCorey** [sferik/rails_admin#2753]
config.current_user_method(&:current_user)
does not call ApplicationController current_user method. Insted it calls the RailsAdmin::MainController looking for current_user.

NoMethodError in RailsAdmin::MainController#dashboard

undefined method `current_user' for #<RailsAdmin::MainController:0x007fccdb1e0348> Did you mean? _current_user

From what I have read I am doing it correctly

**Comment by mshibuya** [comment]
`RailsAdmin::ApplicationController` no longer inherits from `ApplicationController` by default, see the changelog for detail:
https://github.com/sferik/rails_admin/blob/master/CHANGELOG.md#changed

**Comment by blairanderson** [comment]
from docs: To keep old behavior, add `config.parent_controller = '::ApplicationController'` in your RailsAdmin initializer.
