### ISSUE TITLE
Back button doesn't work as expected

### ISSUE THREAD

**Issue by sbwoodside** [sferik/rails_admin#2754]
Running rails_admin (1.0.0.rc), rails (4.2.6)
Chrome (mac) Version 54.0.2840.87 (64-bit)

In general the back button doesn't seem to work.

**What happens:**

I go to one of my lists and click on the info button for a record. When I hit the browser back button, it goes back to the last page prior to rails admin.

**Expected:**

I would expect it to take me back to the list view.

**Comment by patleb** [comment]
I think this is a pjax related issue...

**Comment by evanboho** [comment]
This seems to work with current version 1.3.x. Consider closing?
