### ISSUE TITLE
Black screen on adding hyperlink in wysihtml5

### ISSUE THREAD

**Issue by Eggwise** [sferik/rails_admin#2761]
I am trying to add a hyperlink in a description field of a related (one to many) object.
When i add an hyperlink and press the insert link button, both the modals get closed and a dark layer appears. Creating a link in a non related object (so not inside a modal) works just fine.

**Comment by 1aurabrown** [comment]
+1

**Comment by mshibuya** [comment]
This is the upstream issue, feels discouraging...
https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues/212
