### ISSUE TITLE
dependent destroy question

### ISSUE THREAD

**Issue by lbalceda** [sferik/rails_admin#2762]
Hi, just had a question about how Rails Admin handles triggers for dependent destroy on associations since I didn't see anything about it on the wiki.

in our case, have a company with many users.  e.g. :
```
class Company
  has_many :users, dependent: :destroy
end
```

However, when manipulating the users picklists from company#edit in rails admin, it seems to be triggering the destroy and deleting any users that are removed from the company. is this expected behavior ?

for reference, this is the kind of picklist I am referring to:  
![image](https://cloud.githubusercontent.com/assets/601632/20152978/79013164-a675-11e6-8c71-1c46147fba2d.png)

**Comment by Petesta** [comment]
👍

**Comment by mshibuya** [comment]
It is how ActiveRecord handles dependent destroy, RailsAdmin does nothing special about it.
