### ISSUE TITLE
CanCanCan and Rails_Admin working randomly. Must be my fault... help!

### ISSUE THREAD

**Issue by pmaojo** [sferik/rails_admin#2765]
I want to have an admin and other role (salesman) comercial, that can only see one model, without one field (USER).

I defined the abilities of one role like this:

class Ability
  include CanCan::Ability
  def initialize(user)
    if user.admin?
      can :access, :rails_admin
      can :manage, :all
    end
    if user.comercial?
      can :access, :rails_admin
      can :manage, Inmueble
      can :dashboard
      RailsAdmin.config do |config|
        config.model Inmueble do
          exclude_fields :user, :asignacions
          weight -1
          field :asignacions do
            visible false
          end
        end
      end
    end
  end
end

The problem is that when I load rails_admin, most times the field USER that only has to be hidden for "comercial" is also hidden for Admin... but sometimes it works as I expected

**Comment by mshibuya** [comment]
Do not place `RailsAdmin.config` block in Ability class, it must be initialized upon application start and be placed in `config/initializers/rails_admin.rb`.

**Comment by pmaojo** [comment]
Thankyou @mshibuya. 
But then how do I make different configurations for different roles?

**Comment by mshibuya** [comment]
The answer is here:
https://github.com/sferik/rails_admin/wiki/Fields#controlling-by-logic

**Comment by pmaojo** [comment]
Thankyou

**Comment by pmaojo** [comment]
So I could do this?

RailsAdmin.config do |config|
  config.model 'Team' do
    list do
      field :name
      field :created_at
      field :revenue do
        visible do
          bindings[:view].current_user.admin?
        end
      end
    end
  end
end

I don´t know what bindings[:view]
