### ISSUE TITLE
How to make the field of has_many(with belongs_to) not like many_to_many

### ISSUE THREAD

**Issue by imWildCat** [sferik/rails_admin#2767]
```ruby
class Author < ApplicationRecord
  has_many :books
end

class Book < ApplicationRecord
  belongs_to :author
end

class CreateAuthors < ActiveRecord::Migration[5.0]
  def change
    create_table :authors do |t|
      t.string :name

      t.timestamps
    end
  end
end

class CreateBooks < ActiveRecord::Migration[5.0]
  def change
    create_table :books do |t|
      t.belongs_to :author, foreign_key: true
      t.string :name

      t.timestamps
    end
  end
end
```

In this example, books should belong to authors. But if I edit authors, it shows all of the books. One author can 'take' the book of others away.

![qq20161114-0](https://cloud.githubusercontent.com/assets/2396817/20287228/34135b3e-aac3-11e6-8a81-2a7b84ad4440.png)

I may not need this kind of `multiselect` field, but a field in which I can edit and delete existing related 'books' and add new 'books' with the foreign key of the current `author`. How can I do that?

Many thanks.

**Comment by mshibuya** [comment]
You might be interested in nested-forms, you can enable it by putting `accepts_nested_attributes_for :books, allow_destroy: true` in Author model.
https://github.com/sferik/rails_admin/wiki/Has-many-association
