### ISSUE TITLE
Not shown as responsive on iPhone (both Safari & Chrome)

### ISSUE THREAD

**Issue by imWildCat** [sferik/rails_admin#2768]
![img_0114](https://cloud.githubusercontent.com/assets/2396817/20287993/097fe1da-aac8-11e6-9c10-ab928489ffc9.PNG)

**Comment by patleb** [comment]
correction [here](https://github.com/patleb/rails_admin/blob/master/app/views/layouts/rails_admin/application.html.haml#L6)

**Comment by mshibuya** [comment]
I believe #2664 has solved this.
