### ISSUE TITLE
can't show image in list view

### ISSUE THREAD

**Issue by qx** [sferik/rails_admin#2769]
```
  field :image do
        visible true
        pretty_value do
          bindings[:view].tag(:img, {:src => bindings[:object].image.url(:small)})
        end
      end
```

Get these code
`<td class="image_field carrierwave_type" title=""><img src="http://www.xxxx.com/uploads/advertise/image/6/small_75f5bcfc-710f-419b-826e-fc142dad3e2b.jpg" style="display: none !important;"></td>`

```
 style="display: none !important;
```
Where to set?

**Comment by mshibuya** [comment]
Looks like an ad-blocker issue.
