### ISSUE TITLE
Objects are not stored by id and so not rendered by id

### ISSUE THREAD

**Issue by folubode** [sferik/rails_admin#2778]
Just noticed objects are not stored by id and so not rendered by id. When I edit it back end, it get's deleted even from database.

This is how the items are stored in rails_admin backend and so rendered as listed here. However, rails instruction is to be rendered by id i.e. by Entity # such as Entity #394, Entity #395, Entity #396, ... 

![objects1](https://cloud.githubusercontent.com/assets/11522615/20470846/401ccf98-b011-11e6-9ad2-c137baa8a62d.png)

not sure if I'm missing something or this is a bug?

**Comment by mshibuya** [comment]
For the record label(e.g. `Entity #397`), see [object_label_method](https://github.com/sferik/rails_admin/wiki/Models#the-object_label_method-method).
For records being deleted, you'd better check behavior of ActiveRecord's `dependent: destroy`, which might not be what you're thinking of.

**Comment by folubode** [comment]
Sorry don't understand

**Comment by mshibuya** [comment]
If you need a support, use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin).
