### ISSUE TITLE
Missing translation after many request in short time

### ISSUE THREAD

**Issue by martnst** [sferik/rails_admin#2780]
Hi, 

we have a server running our app with rails_admin together with an internal REST API. Frequently the API gets hit with many many requests in a short time. This somehow causes the application to drop the translation data resulting in errors like `Translation missing: en.admin.actions.index.title`. 

Restarting the application (which is run by Passenger) will resolve the issue until the API gets hit again. 

Any help to further debug this issues or work around it will be appreciated. Is there a way to reload the translations in case it got dropped?

**Comment by fredriksundstrom** [comment]
I actually get this on pretty much every other pageview of the admin dashboard, to be honest. I can re-produce about every 2nd refresh by just clicking the same menu item.

**Comment by mshibuya** [comment]
This might be related to the thread-safety issue #2942, which was fixed recently.
Please try the master branch and see if it works.
