### ISSUE TITLE
Parameters getting nilled out after parse_input

### ISSUE THREAD

**Issue by 8vius** [sferik/rails_admin#2781]
I have some specs in my app that test out certain actions with rails admin. Some are failing, specifically editing specs, because some parameters are unset after `fields.each { |field| field.parse_input(target_params) }` in `MainController`, this happens because they fall into the default `parse_input` in `lib/rails_admin/config/fields/base.rb` which is blank and is supposed to be overriden. Any thoughts on this?

**Comment by mshibuya** [comment]
Yes `#parse_input` mutates `params`, that's all.
