### ISSUE TITLE
Roll your own authentication with rails 5

### ISSUE THREAD

**Issue by obromios** [sferik/rails_admin#2791]
With rails 4, I had a custom authentication in ```config/initializers/rails_admin.rb``` using
```
RailsAdmin.config do |config|
  config.authenticate_with do
    raise 'You must be admin' unless signed_in? && current_user.admin?
  end
end
```
However, when I upgraded to ```rails 5```, I get the following error
`undefined method 'signed_in?' for #<RailsAdmin::MainController:0x007fbe38628ab0>`
How do I fix this?
P.S This question was first asked on [SO](http://stackoverflow.com/questions/41072923/roll-your-own-authentication-with-the-rails-admin-gem-stops-working-with-rails-5).

**Comment by obromios** [comment]
The usual view helpers, like signed_in? or current_user are no longer accessible in the initializer, so the solution that I came up with was:

```
config.authenticate_with do
    current_user =  User.find_by_id(session[:user_id])
    raise 'You must be admin' unless current_user.try(:admin?)
  end
```
As far as I am concerned, this solved the issue for me. However, it does not answer why the view helpers are no longer available.

**Comment by tapostrophemo** [comment]
I'm using Sorcery, and it was breaking with a similar issue. I noticed that rails_admin was loading up Sorcery::Controller methods, but wasn't pulling in any overrides I had (e.g., customizing :not_authenticated in my rails app's ApplicationController). The solution was to to set rails_admin's :parent_controller to my ApplicationController.

More discussion found here - http://stackoverflow.com/questions/39971235/current-user-undefined-in-rails-admin-with-clearance

**Comment by obromios** [comment]
This looks like a good solution, which I had seen it before I developed my workaround.
