### ISSUE TITLE
Rails 5 and duplicated navigation

### ISSUE THREAD

**Issue by lorenzosinisi** [sferik/rails_admin#2792]
I was using the gem on version 1.1.0 with Rails 5 when I noticed that some items in the navigation (the one on the left) were duplicated. I forked the project and fixed the issue as you can see here https://github.com/sferik/rails_admin/compare/master...modomoto:unique-navigation-items?expand=1

Would it be the case to fix it here too?

**Comment by mshibuya** [comment]
Looks like configuration issue, pasting your RailsAdmin configuration will help.

**Comment by mayoms** [comment]
@mshibuya fyi I experienced the same issue, with the default config. My solution as follows:

```
module RailsAdmin::Config
  class << self
    alias_method :original_models, :visible_models

    def visible_models(bindings)
      original_models(bindings).uniq(&:label)
    end
  end
end
```
