### ISSUE TITLE
Model Action colliding with rails_admin internals

### ISSUE THREAD

**Issue by wlads** [sferik/rails_admin#2795]
Created a new model named **Action** with simple attributes and apparently rails_admin have some conflict between the name of the model and the internal abstraction used.

Reproducible steps:
```sh
rails new MyApp
rails g model Action name
rails db:migrate
# append to Gemfile: gem 'rails_admin', '~>1.0'
bundle install
rails g rails_admin:install
rails s
# open: http://localhost:3000/admin/action/new
```

[Gist with stack trace](https://gist.github.com/wlads/cf8f7e07e10bfbd0e62ee6b28d0a6bc9#file-development-log)

ENV: 
- macOS Sierra: 10.12.2
- Ruby: 2.3.1
- Rails: 5.0.0.1
- rails_admin: 1.1.0

**Comment by mshibuya** [comment]
Dup of #2329.
