### ISSUE TITLE
Params not passed to modal form ? (rails_admin 1.1.1)

### ISSUE THREAD

**Issue by Jamevidi** [sferik/rails_admin#2800]
Are params not passed to modal form anymore? 

Example that used to work:
`     default_value do `
`         bindings[:controller].params[:list_id]`
`     end`

Thanks for any input! :-)

**Comment by Jamevid** [comment]
In case anyone is interested in a quick fix you could try this:

```
  -new_params = params.to_hash.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}
  -new_params.delete(:model_name)
  -path_hash = path_hash.merge(new_params)
```

...paste it right before "= link_to "<i class=\"icon-plus icon-white\"></i> ".html_safe" in _form_filtering_select.html.haml and _form_filtering_multiselect.html.haml
