### ISSUE TITLE
URL params not accessible in associated_collection_scope block (Rails admin 1.1.0 / Rails 5)

### ISSUE THREAD

**Issue by Jamevidi** [sferik/rails_admin#2803]
It works great in default_value block  :-)

```
default_value do
  bindings[:controller].params[:my_custom_url_param]
end
```

But not in associated_collection_scope block:

```
associated_collection_scope do
  bindings[:controller].params[:my_custom_url_param]
end
```

I tried with Rails Admin 1.1.1, 1.1.0, 0.6.6 and Rails 5.

**Comment by mshibuya** [comment]
That's unlikely, please make sure that you're not misspelling the key `:controller`.
