### ISSUE TITLE
Related Dropdowns

### ISSUE THREAD

**Issue by RocKhalil** [sferik/rails_admin#2811]
Is there a way to filter a dropdown list based on another dropdown's value ? 
For example, if we have: `Class` and `Student` Models where `Student` have `class_id`; is there a way to filter the `Students` shown in the dropdown based on the selected `Class` ?
I've also asked this question on [StackOverflow](http://stackoverflow.com/questions/41504138/rails-admin-related-dropdowns/41559436)

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/wiki/Associations-scoping
