### ISSUE TITLE
Override show_in_app?

### ISSUE THREAD

**Issue by davidwparker** [sferik/rails_admin#2816]
I've read over this: https://github.com/sferik/rails_admin/wiki/Actions

And it doesn't have any example of overriding the show_in_app action.

My route has `get :blah, as: something` and rails_admin falls down when the show_in_app button is clicked.

I'd like to change the action to be custom. Is this possible?

Thanks!

**Comment by ianbayne** [comment]
@davidwparker Did you ever find a solution to this? I'm facing a similar issue now where `show_in_app` isn't able to find an object looked up by its slug.

**Comment by davidwparker** [comment]
@ianbayne - I switched to ActiveAdmin, which is infinitely more powerful.

**Comment by mshibuya** [comment]
Overriding `controller` option of `show_in_app` is the answer.

```ruby
  config.actions do
    ...
    show_in_app do
      controller do
        proc do
          redirect_to main_app.url_for(@object)
        end
      end
    end
  end
```
