### ISSUE TITLE
Base url is not correct on reverse_proxy

### ISSUE THREAD

**Issue by Australhawk** [sferik/rails_admin#2819]
Im using Rails5API and Rails_admin 1.1.1 Some links use 0.0.0.0:3000 as base url instead using relative path (as other routes do). NOTICE: IM ON PRODUCTION SO 0.0.0.0 is not the correct url

OK
![OK Route Companies List](https://cloud.githubusercontent.com/assets/4383129/22325521/38d0942c-e38d-11e6-9d14-556f20bb00ff.png)

WRONG
![Wrong Route Company Add](https://cloud.githubusercontent.com/assets/4383129/22325593/7e9767e2-e38d-11e6-8526-9d8ce5c7be82.png)

WRONG
![Wrong Route Company List on Side menu](https://cloud.githubusercontent.com/assets/4383129/22325614/99e7c82a-e38d-11e6-8499-db03034eb61d.png)

UPDATE: This bug happens when i do a reverse_proxy on nginx. Same app on heroku works perfect. 
UPDATE: Fixed with application.rb => config.action_controller.default_url_options

**Comment by dx7** [comment]
Same problem here. Setting `config.action_controller.default_url_options = { host: 'example.com', port: 80 }` can be used as a workaround.

**Comment by spacewaffle** [comment]
If we're serving on https should we use 443 or still on 80? I've got an nginx reverse proxy as well and am redirecting from 80 to 443 for ssl.

**Comment by 1054949000** [comment]
> config.action_controller.default_url_options

undefined method `action_controller' for RailsAdmin::Config:Module (NoMethodError)
