### ISSUE TITLE
Time of Day not being used in query, yet shows up in query as if it were

### ISSUE THREAD

**Issue by npendery** [sferik/rails_admin#2820]
When filtering by a date field using the `Between...and...` filter, it always goes to the beginning of the start date and end of the end date in the code [here](https://github.com/sferik/rails_admin/blob/ffa30e0563e86a91bf88a312911b77d1bfffc2dc/lib/rails_admin/abstract_model.rb#L179).

I would suggest that the time of day either be removed from the UI or update the query to include the time of day. Picture example here:
![notification___fastaff_portal_admin](https://cloud.githubusercontent.com/assets/12616684/22336993/e5907ac8-e3b1-11e6-941c-159dbd8013d2.png)

I can submit a PR with the update if provided a direction of either: a) Remove time option from UI, b) Remove `.beginning_of_day`/`.end_of_day` from the time submitted to the query

**Comment by manuel-zulian** [comment]
Having the same issue, it seems this code was introduced with a commit for mongo. Resorted to monkey-patch for now.

**Comment by manuel-zulian** [comment]
Warning: if you go for option b, and remove the beginning/end of day calls, you break the filters for "today" and "yesterday" options, so check if the dates are equal before doing that.

**Comment by mshibuya** [comment]
Fixed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a.
