### ISSUE TITLE
When will rails_admin 1.1.2 be released?

### ISSUE THREAD

**Issue by koic** [sferik/rails_admin#2826]
I'd like to use kaminari 1.0.x. Related PR #2810 has already been merged.

Would prefer not to be linking to master in our Gemfile.

Related ISSUE #2823.

Thanks.

**Comment by swistaczek** [comment]
Please release new version @sferik  :)

**Comment by PikachuEXE** [comment]
I think it would be great to have it release sooner than later
There are always more bugs to be fixed

**Comment by pschambacher** [comment]
Please? 😄

**Comment by mshibuya** [comment]
🚢  https://github.com/sferik/rails_admin/commit/3d12fd1b6ea4ab70f149cd6a70deb3ca18207083

**Comment by koic** [comment]
@mshibuya Thank you so much for the release!

**Comment by pschambacher** [comment]
Much appreciated!
