### ISSUE TITLE
How to display only admin users in multi-select box

### ISSUE THREAD

**Issue by radhakmk** [sferik/rails_admin#2835]
```
class Project < ApplicationRecord
     has_and_belongs_to_many :users
end

class User < ApplicationRecord
    has_and_belongs_to_many :projects
    scope :superadmin, ->  {where(superadmin_role: true)}
end
```

> Join table : projects_users (project_id, user_id)
> User has roles (SuperAdmin, Developer, Appowners) etc...

While adding a new project, I can able to see the User listed (in multi-select box it display all the user by default), but i need to see only users who has superadmin role.

I would appreciate your help on this.

PFA users multi-select box image
![untitled](https://cloud.githubusercontent.com/assets/524746/22944942/726b08f6-f2c0-11e6-8c1b-c38415e35b15.png)

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
