### ISSUE TITLE
How to sort custom field for asociated list

### ISSUE THREAD

**Issue by tuxtux59** [sferik/rails_admin#2836]
Hi,

I'm looking for a way to order a list by children count for an object but when I use `sortable true` the app fails

here the used code

`config.model User do
    list do
      field :name
      field :objects_count, :integer do
        def value
          bindings[:object].objects.count
        end
        filterable true
        sortable true
      end
    end
end`

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
