### ISSUE TITLE
jQuery 3 causing errors in Rails admin

### ISSUE THREAD

**Issue by MatthiasRMS** [sferik/rails_admin#2838]
A few things where broken in Rails admin (multiselect for associations, for example), and after opening the browser's console, there was this error:

`Cannot read property 'push' of undefined`
`RailsAdmin is not defined`

After doing some quick research, it turns out that since Rails Admin uses jQuery 3, this error appeared. 

I had to copy all of the gem's javascript folder to my app's assets, and change:
`//=  require 'jquery'` 

to:

`//=  require 'jquery2'`

in` rails_admin.js`.

It's definitely not a good solution, but the only one I've found so far. I can't imagine being the only one with this issue. Has this been addressed somewhere else ? I couldn't find anything related yet.

**Comment by jklimke** [comment]
I propose a 'solution' / fix for first error "Cannot read property 'push' of undefined" in
#2842

**Comment by MatthiasRMS** [comment]
Thanks @jklimke , but I'm trying to find a solution without adding quick fixes or snippets of code which would much likely break with upcoming releases. Reverting to jQuery 2 doesn't break anything. See: 
https://github.com/sferik/rails_admin/pull/2839

**Comment by mshibuya** [comment]
Don't you use `jquery-rails`?
https://github.com/rails/jquery-rails#installation
The name `jquery` is for jQuery 1.x, if you need jQuery 3.x you should require `jquery3` in your application.
