### ISSUE TITLE
Error in jquery.pjax when used with jquery 3

### ISSUE THREAD

**Issue by jklimke** [sferik/rails_admin#2842]
i recently upgraded my app to jquery 3.

There is an error left that i could not fix instantly.

`Uncaught TypeError: Cannot read property 'push' of undefined
    at VM578 jquery.pjax.self-aa02343….js?body=1:733
    at VM578 jquery.pjax.self-aa02343….js?body=1:743`

Affected line in jquery.pjax.js:
`
// Add the state property to jQuery's event object so we can use it in
// $(window).bind('popstate')
if ( $.inArray('state', $.event.props) < 0 )
  $.event.props.push('state')
`

Cause by this change in jquery 3

https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed

On could either (pretty bad solution) add the props array if undefined or change how this works in order to be compatible with future versions.

What do you think ?

**Comment by BjornMelgaard** [comment]
my solution

**Comment by mshibuya** [comment]
See the solution here:
https://github.com/sferik/rails_admin/issues/2838#issuecomment-401527294
