### ISSUE TITLE
ActionView::Template::Error (File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by kbighorse** [sferik/rails_admin#2843]
I'm installing ```rails_admin``` for the first time and seeing this error right away. Here is the diff of my ```Gemfile.lock```, I don't know whether posting the entire ```Gemfile``` or ```.lock``` file would be helpful: https://gist.github.com/kbighorse/af4985d16ac665e42e652b5d82cc9ab3

If I ```git checkout -- .``` the error goes away. I've encountered the error immediately after modifying the ```Gemfile``` and again after running ```rails g rails_admin:install```.

Bourbon is installed:
```
$ gem list bourbon

*** LOCAL GEMS ***

bourbon (5.0.0.beta.7)
```

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
