### ISSUE TITLE
Raise ArgumentError, "#{other.inspect} is not an ActiveRecord::Relation"

### ISSUE THREAD

**Issue by realvjy** [sferik/rails_admin#2854]
I have User, Media and Image Model.
User has_many Medias.
Media has_many Images.

Whenever I tried to access Media from dashboard got

StandardError in RailsAdmin::MainController#index
Media(id: integer, title: string, remark: text, created_at: datetime, updated_at: datetime, user_id: integer) is not an ActiveRecord::Relation
Extracted source (around line #48)
	

        instance_exec(&other)
      else
        raise ArgumentError, "#{other.inspect} is not an ActiveRecord::Relation"
      end
    end

similar error for other when try to acess edit user action.

**Comment by khadzhinov** [comment]
Have same issue (

**Comment by khadzhinov** [comment]
So in my case it was wrong pundit policies for model!

**Comment by ertaquo** [comment]
@khadzhinov please can you tell what was wrong in your policies and how you fixed it?

**Comment by Kameshwaran** [comment]
@realvjy I hope you are facing the issue, bcoz your naming convention is wrong.
The model name should have been 'Medium'. Not media.
When you define the associations, it should have been like,
`
   User has_many :media
   Medium has_many images
`
