### ISSUE TITLE
rails_admin fetch model data based on devise current_user

### ISSUE THREAD

**Issue by uzaif313** [sferik/rails_admin#2861]
i am trying to give privileges to normal user to access admin panel for managing there resource via rails_admin but i am not getting any solution.does it achievable with rails admin 

in default behaviour of rails_admin its get all records from db for specific model resources but in my case i need to get data only for logged in user #

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
