### ISSUE TITLE
Multiselect widget for has many association

### ISSUE THREAD

**Issue by Diethart** [sferik/rails_admin#2863]
Hello everyone. 

I wonder to know, is there any way to disable this widget? I need user be able to create new objects or edit them by double click, but I don't need multi-assignment functions.

**Comment by clurdish** [comment]
Maybe look into [nested attributes](https://github.com/sferik/rails_admin/wiki/Has-and-belongs-to-many-association). This allows you to create and edit related records with nested attributes inline on the form without selecting from existing records.
