### ISSUE TITLE
Rails Admin + Carreirwave -> rails admin sends additional attributes with PUT request?

### ISSUE THREAD

**Issue by beniutek** [sferik/rails_admin#2867]
I'm using Rails 5 with rails_admin and carrierwave gems.

I have a model Photo and and image uploader mounted on it (as per carrierwave documentation), looks roughly like this:

```
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :project

  validates :name, presence: true
  validates :image, presence: true
end
```

Given I have already some Photo objects created I can see a list of them in the rails_admin admin view.

And I start editing one of them And I edit name And I proceed to save it

Then rails admin fires some of it's magic and photo is being saved but after this action the image dissapears.

I have been digging a little in what request are being fired and rails_admin fires a PUT request with such params:

```
{
 "authenticity_token"=>"xxx",
 "photo"=>{
   "name"=>"test2",
   "description"=>"ewdeeweeeeeeefwe",
   "project_id"=>"3",
   "image_cache"=>"",
   "main"=>"0",
   "about_us"=>"0"
},
"return_to"=>"http://localhost:3000/panel-admin/photo?model_name=photo", "_save"=>"", "model_name"=>"photo", "id"=>"29"
}
```

the corresponding update in SQL looks like this:

```
  SQL (0.5ms)  UPDATE "photos" SET "description" = $1, "image" = $2 WHERE "photos"."id" = $29  [["description", "ewdeeweeeeeeefwe"], ["image", "20170414_"], ["id", 29]]
```

so somehow rails admin sends an empty(?) image name, that is being saved to the database.

I image it might have something to do with the 

```
"image_cache"=>""
```

being empty but I have no idea how to ensured that this value is filled properly (or not sent at all during request)

I have checked to form generated by rails_admin for the admin interface and it already has hiddent attributes that I assume should do the task?

Any help or guidance would be great! :)

**Comment by mshibuya** [comment]
`image_cache` is harmless as long as it is empty string.
I guess the problem is in your code, showing your model and uploader code will help track down the problem.
