### ISSUE TITLE
Destroy objects in background jobs

### ISSUE THREAD

**Issue by MatthiasRMS** [sferik/rails_admin#2883]
Some records have a lot of associations, and can require a long time to destroy, some times leading to a server timeout. 

How can I move the destroy action to a background job using active job or sidekiq ?

Couldn't find anything related in the documentation

**Comment by thedanielhanke** [comment]
Create your own custom action (e.g. DeleteAsync) and use it as documentation explains. 

The actions controller then creates the asynchronous job for deleting that very record.
