### ISSUE TITLE
Callbacks in custom actions

### ISSUE THREAD

**Issue by FunkyloverOne** [sferik/rails_admin#2885]
Hi guys! I'm trying to create a gem with custom action with callbacks...

You can check it's [README](https://github.com/FunkyloverOne/rails_admin_invite#usage), so will see how bad I'm currently using them.

Firstly there was normal syntax for callbacks, but then I realized, that the variables I'm passing to them remain unchanged in action's scope. I think it's related to implementation of `RailsAdmin::Config::Configurable#register_instance_option`

I would like to have something like `RailsAdmin::Config::Configurable#register_instance_callback` for example, or maybe you could just tell me where I do something wrong.

**Comment by mshibuya** [comment]
Merging into #1293.
