### ISSUE TITLE
Exception raised when using with cancancan 2.x & Mongoid

### ISSUE THREAD

**Issue by PikachuEXE** [sferik/rails_admin#2888]
cancancan 2.0 dropped support for mongoid
https://github.com/CanCanCommunity/cancancan/blob/develop/CHANGELOG.rdoc

Error was:
`NoMethodError - undefined method 'accessible_by' for SomeMongoidDocument:Class`

**Comment by coorasse** [comment]
Maybe you want to look into cancancan-mongoid. we released the first beta version. fyi there is also another issue with cancancan 2.0 https://github.com/CanCanCommunity/cancancan/issues/413
