### ISSUE TITLE
NameError with virtual field from Devise

### ISSUE THREAD

**Issue by luizkowalski** [sferik/rails_admin#2891]
Our `User` model has a virtual field `confirmed?` from Devise, as follow:

```
show do
      field :confirmed?
```

since some days, we start see this error on Sentry:

`@confirmed?_registered' is not allowed as an instance variable name` due to this snippet:

has_fields.rb in field at line 12:
```
if field
  field.show unless field.instance_variable_get("@#{field.name}_registered").is_a?(Proc)
end
```

we are using rails_admin 1.1.1 with Ruby 2.2.5

**Comment by pcstout** [comment]
I'm getting the same error. Did you find a fix for this?

**Comment by canadaduane** [comment]
Also seeing this error, and it appears to be intermittent in dev env, which implies some sort of race condition. The field is different for us (in our case, `@ehub_experiment?_registered`) and is defined in the model as a method (`ehub_experiment?`).

**Comment by christiandennis** [comment]
I'm also experiencing something similar. but it's only happening in development environment like @canadaduane said

**Comment by santonrod** [comment]
I don't know if it's the same situation with devise, but I had a similar issue with a method ending in a '?'.
I solved this using a formatted value like so:
```
field :confirmed do
    formatted_value do
            value = bindings[:object].confirmed?
    end
    label do
         "Confirmed?"
     end
 ```
