### ISSUE TITLE
How can I easily add Save Search / Filter functionality?

### ISSUE THREAD

**Issue by bhushangahire** [sferik/rails_admin#2900]

**Comment by grillermo** [comment]
You can "save a search filters" by bookmarking it, all the search params are on the url.

**Comment by yagooar** [comment]
@grillermo Doesn't sound like a professional solution though. Why not be able to store filters same way as the List / Edit / etc. tabs?

**Comment by grillermo** [comment]
You can, through scopes, but these are not user configurable.
