### ISSUE TITLE
Rails Admin's use of cancan(can) is incorrect and is erroring with v2

### ISSUE THREAD

**Issue by hlascelles** [sferik/rails_admin#2901]
When loading the main dashboard, the cancan(can) adapter tries to `authorise(:dashboard, nil)`.

Not passing in any model (the `nil`) is incorrect use of cancancan, [according to a maintainer](https://github.com/CanCanCommunity/cancancan/issues/413#issuecomment-315382980).

Can we change the `authorise` to pass in `:rails_admin` as the "model"? I understand this is a breaking change. Perhaps do it if `cancancan` is seen to be v2 or higher?

**Comment by edslocomb** [comment]
Bump.

We're working around this for now by [using a separate ability class](https://github.com/sferik/rails_admin/wiki/CanCanCan#use-different-ability-classes-for-front-end-and-admin) for the rails_admin gem.

**Comment by farmisen** [comment]
I don't understand how using a separate ability class would solve the problem. This new adapter class does tho: https://github.com/CanCanCommunity/cancancan/issues/413#issuecomment-314063045

**Comment by kekoa428** [comment]
I'm trying to figure out how to install this new adapter/extension for cancancan. Where do I place it in the project?
