### ISSUE TITLE
Retain form data in case of browser crash or site being unreachable

### ISSUE THREAD

**Issue by StarWar** [sferik/rails_admin#2907]
We have a too large a form having several nested models and when the browser crashes or site is unreachable or some local network connectivity issue occurs, we lose all the form data and need to redo all of that. Isn't it possible to save the form data in local browser storage until the form is submitted successfully?

**Comment by grillermo** [comment]
I suggest you resolve this with a browser addon. Google
save form chrome
save form firefox
You'll find plenty of options. Sorry i just don't think this responsability belongs to this gem.

**Comment by mshibuya** [comment]
Dup of #1139.
