### ISSUE TITLE
How to display a tableless model on the rails admin dashboard

### ISSUE THREAD

**Issue by ektaverma1** [sferik/rails_admin#2924]
Hi Everyone,

I am trying to display a particular model (which does not have backend table ) but unable to do so.

The rails admin code does not picks it up and does not gets displayed on dashboard.

I have already defined the  model configuration inside RailsAdmin initializer file.

Please suggest what could be missing here.

Thanks in advance.

**Comment by iSarCasm** [comment]
Where is that model stored than? How would you like to interact with it in RailsAdmin?

**Comment by ektaverma1** [comment]
@iSarCasm currently I have an empty Active Record table created in database for rails admin to pick it up and display as link on dashboard.

So basically I have a custom action that performs some operations on AWS s3. I just want to add a link on the admin dashboard that would redirect to that custom action view.

For instance, when a user clicks on 'Partners' link, it should be redirected to my custom action and not the default list page. I don't want the list action either.
<img width="1381" alt="github" src="https://user-images.githubusercontent.com/932579/30361145-f1342de0-9872-11e7-881a-eac42935bee7.png">

Thanks
