### ISSUE TITLE
Custom New action or new view for a paricular model

### ISSUE THREAD

**Issue by divyanshumehta** [sferik/rails_admin#2929]
Can I have a custom new action or a new view for a particular model. Like I have three models but I would like to have a diffrent `new` action page for a particular. Adding a `view/rails_admin/main/new.html.erb` render the view for all the models but I want to use this view only for one model

Actually I want to modify the new form for a paricular model. I want that some fields in new form to be  populated by some defaults

**Comment by divyanshumehta** [comment]
Ok I figured out all I had to do is to use partials for field for edit action like 
```
config.model Model do
    edit do
      field :attribute do
        partial 'new_partial'
      end
     end
  end

```
and place the partial in `app/views/rails_admin/main/_new_partial.html.erb`

**Comment by buncismamen** [comment]
@divyanshumehta hello can you close this issue if its already solved?

**Comment by divyanshumehta** [comment]
Sure,
