### ISSUE TITLE
Talos Security Advisory for rails_admin  (TALOS-2017-0450)

### ISSUE THREAD

**Issue by regiwils** [sferik/rails_admin#2931]
The Cisco Talos team found a security vulnerability impacting rails_admin customers. As this is a sensitive security issue, this email is to request a PGP key for further communication. If no PGP key, please provide a point of contact/email address to send report via plain text file.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. http://www.cisco.com/web/about/security/psirt/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

**Comment by mshibuya** [comment]
Dup of #2984.
