### ISSUE TITLE
actions are not working on rails 5

### ISSUE THREAD

**Issue by luizkowalski** [sferik/rails_admin#2936]
I'm upgrading to Rails 5.1 and I'm seeing this error:
```ruby
RuntimeError:
  Action dashboard already exists. Please change its custom key.
```

I didn't touched rails_admin.rb in the migration. this is the relevant snippet:

```
config.actions do
    # root actions
    dashboard do
      statistics false
    end
    bulk_cancel_order
    tenant_invoice
    btr_tenant_invoice
    feature_toggle

    # collection actions
    index
    new do
      except [DeviceLog, Adyen::Order, AffiliateTransaction]
    end
    export
    history_index do
```

if I remove `dashboard`, then I get an error for the next action `bulk_cancel_order` and same goes for all actions

I'm using rails_admin 1.2.0

**Comment by mshytikov** [comment]
Hi, run into the same issue. 
Probably you just need to double check your configs etc. to make sure that all your classes/modules are resolved/loaded correctly. 
In my case, it was failing with the error when I was running RSpec.
I found that I had an invalid file in `config/initializers/`.
After fixing a typo in my file issue was solved.

**Comment by mshibuya** [comment]
Please reopen on update.

**Comment by asnad** [comment]
facing same issue while running tests after upgrading to rails 5.2.1

**Comment by asnad** [comment]
@luizkowalski can you please update how did you solve this?

**Comment by asnad** [comment]
Thanks I checked that there were two models which were not exists and I removed them from config and it worked.
