### ISSUE TITLE
How to add a link in rails admin export page ?

### ISSUE THREAD

**Issue by hmtanbir** [sferik/rails_admin#2940]
I want to add a link or button beside of `Export to CSV` button in any model's export page. 
But I don't know the best way. 
Is there any procedure to add an extra link/button in export page ?
Please inform me as soon as possible.

**Comment by radvc** [comment]
@hmtanbir you can use javascript/jquery to append anchor/button tag element beside Export to CSV button

**Comment by hmtanbir** [comment]
Can you give me an example?

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
