### ISSUE TITLE
time_picker setting wrong time for a :time field in app with a configured time_zone

### ISSUE THREAD

**Issue by cec** [sferik/rails_admin#2945]
**Description**
Ruby 2.3.4, Rails 4.2 using RailsAdmin 1.2.0 app with
```
Rails.application.config.time_zone
Europe/Zurich
```
```
Rails.application.config.active_record.default_timezone
:local
```

I have a model with a **:time** column.
RA renders a timepicker for the field as expected.
**User picks** time 18:00.
Value sent to the **database is 20:00**.

From Rails console, if I set the attribute directly on the model to Time.current or Time.now the correct value is saved.

Running with debugger on, I picked the time 12:00 and noticed that at 
``RailsAdmin::Config::Actions::Edit`` line 27, the picked time is contained in params as a 12:00 UTC time (+00).
However, upon ``@object.save``, ActiveRecord is sent the value 14:00 UTC.

Our timezone is UTC+1. And we are in summer time (thus +1 hour).
The two hours increase is not a coincidence.

I'm afraid that this bug affects everyone that configured a timezone.

This might also be what was poorly described in #2549

@bbenezech  I will downgrade the gem to find which release introduced the bug

**Comment by alphaone** [comment]
@cec I know this is almost 2 years old. Did you solve this problem?

**Comment by mshibuya** [comment]
DateTime handling was completely reworked in https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a, please let me know if you still see this happen.
