### ISSUE TITLE
Custom Action Url Link

### ISSUE THREAD

**Issue by newfylox** [sferik/rails_admin#2950]
Is there a way to customize the link that is generated for a custom action?

e.g. I have a root action `myaction` and in the dashboard, I want the link to be something like `/admin/myaction?myparam=1`

I want a default query param when I first visit my action and I don't want to handle this logic (first visit) in the controller with a useless variable.

Thanks

**Comment by RocKhalil** [comment]
Usually, you handle these stuff using cookies or session variables,
Even if it's possible, it's not a good solution to do it.
