### ISSUE TITLE
Compatibility issues with jQuery 3+ and jQuery UI prior to ver 12.0

### ISSUE THREAD

**Issue by jakephot** [sferik/rails_admin#2951]
Hello. I am getting this error on colsole when clicking on pulldown menu on RailsAdmin. The pulldown items are rendered but in the wrong place out of the default scope of the window.

```
Uncaught TypeError: elem.getClientRects is not a function
```

I believe this is due to incompatibility between jQuery 3+ and jQuery UI prior to version 12.0. RailsAdmin is dependent on `jquery-ui-rails (~> 5.0)`, and the latest 5.0.x is [bundled with `jQuery UI 1.11.4`](https://github.com/jquery-ui-rails/jquery-ui-rails/blob/master/VERSIONS.md). 

The details of this compatibility issue is [described here](https://github.com/vanderlee/colorpicker/issues/132).

**Comment by LennonR** [comment]
+1 I'm getting this same error on Chrome
