### ISSUE TITLE
Deleting a model breaks /admin page

### ISSUE THREAD

**Issue by masudhossain** [sferik/rails_admin#2955]
If i delete a model, going to /admin will give errors. Is there a way to blacklist or remove certain models ?

**Comment by RocKhalil** [comment]
Of course you can hide a model;
There are 2 ways to do so in Rails Admin:

1. List the included models only:
`config.included_models = [ User, Cart, etc.. ]`

2. List the excluded models only:
`config.excluded_models = [ UserAddress, CartItem, etc..  ]`

Both of them should be in `config/initializers/rails_admin.rb`
