### ISSUE TITLE
Gem Load Error is: uninitialized constant Haml::Util::Sass  

### ISSUE THREAD

**Issue by kashiftufail** [sferik/rails_admin#2956]
I shift from ruby from 1.9.3 to 2.2.5. Then this error occur while

loading rails_admin gem.

full error trace is below

/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:84:in rescue in block (2 levels) in require': There was an error while trying to load the gem 'rails_admin'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Haml::Util::Sass
Backtrace for gem load error is:
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/haml-3.1.8/lib/haml/util.rb:348:intry_sass' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/haml-3.1.8/lib/sass/rails3_shim.rb:1:in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/sass-3.5.3/lib/sass/root.rb:1:in' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/sass-3.5.3/lib/sass/util.rb:11:in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/sass-3.5.3/lib/sass/version.rb:2:in' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/haml-3.1.8/lib/haml/util.rb:347:in try_sass'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/haml-3.1.8/lib/sass.rb:6:in' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bootstrap-sass-2.3.2.2/lib/bootstrap-sass/sass_functions.rb:1:in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bootstrap-sass-2.3.2.2/lib/bootstrap-sass.rb:10:inload!' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bootstrap-sass-2.3.2.2/lib/bootstrap-sass.rb:51:in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/rails_admin-0.0.5/lib/rails_admin/engine.rb:4:in' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/rails_admin-0.0.5/lib/rails_admin.rb:1:in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:inrequire' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in block (2 levels) in require'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:ineach' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in block in require'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:ineach' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in require'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler.rb:114:inrequire' /home/kashif/rails/alisa/metnet/config/application.rb:7:in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:53:inrequire' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:53:in block in <top (required)>'
/home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:50:intap' /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:50:in <top (required)>'
script/rails:6:inrequire' script/rails:6:in <main>'
Bundler Error Backtrace:
    from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:80:inblock (2 levels) in require' from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in each'
    from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:inblock in require' from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in each'
    from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:inrequire' from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/bundler-1.16.0/lib/bundler.rb:114:in require'
    from /home/kashif/rails/alisa/metnet/config/application.rb:7:in' from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:53:in require'
    from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:53:inblock in ' from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:50:in tap'
    from /home/kashif/.rvm/gems/ruby-2.2.5@metnet2/gems/railties-3.2.11/lib/rails/commands.rb:50:in' from script/rails:6:in require'
    from script/rails:6:in'

Any instructions?

**Comment by Klockner** [comment]
@kashiftufail Is it still a problem?

**Comment by mshibuya** [comment]
Stale.
