### ISSUE TITLE
Wrong code syntax from Wiki

### ISSUE THREAD

**Issue by JIucToyxuu** [sferik/rails_admin#2967]
Section https://github.com/sferik/rails_admin/wiki/Cancancan#create-an-extension-for-cancancan.

Method 'fetch_action_and_subject'  contain code with wrong syntax.
Be: subject = model_object || abstract_model&.model
Should: subject = model_object || abstract_model && abstract_model.model

**Comment by mshibuya** [comment]
It's the safe navigation operator, introduced in Ruby 2.3.
https://bugs.ruby-lang.org/issues/11537
