### ISSUE TITLE
`acts-as-taggable-on` rails 5.2 Compatibility issues :(

### ISSUE THREAD

**Issue by rgbskills** [sferik/rails_admin#2969]
Hello,

I tried everything on the internet before opening this ticket including `rails_admin_tag_list`and custom partials, everything I could think of I tried and I just cant get this Gem to work.

Here is where I am stuck:

When I create a product and edit it, I can add remove tags as I please.. But when I add tags on a new not yet created product I get this error:

<img width="1196" alt="screen shot 2017-12-14 at 17 09 20" src="https://user-images.githubusercontent.com/5773622/33998885-94af77f6-e0f1-11e7-8fc2-def60e6085a5.png">

Please someone help me.

**Comment by rgbskills** [comment]
This problem is being addressed here: https://github.com/mbleigh/acts-as-taggable-on/pull/872

**Comment by rgbskills** [comment]
I removed acts as taggable due to inactivity of the gem and moved on. I dont think this will ever be fixed so I am closing this issue.

**Comment by glendel** [comment]
Please go to here : [Pull Request #887](https://github.com/mbleigh/acts-as-taggable-on/pull/887) to see all the ready to merge and to use solutions to work with the "[acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on/pull/887)" gem with Rails 5.2! It is fully tested and ready to go! It is just missing to merge the changes into the main project!
