### ISSUE TITLE
ActiveRecord::RecordNotUnique , inserts id when creating user

### ISSUE THREAD

**Issue by applecrusher** [sferik/rails_admin#2972]
Hello All, 

I seem to be getting a problem when inserting into the users table. I am not sure why, but only that it is getting the current user's id (confirmed by seeding additional user). I know the solution would be to remove adding the id when adding users, but I don't know how and have been trying to find the right file for 30 minutes. I am using MYSQL. The error is below

```
ActiveRecord::RecordNotUnique in RailsAdmin::MainController#new
Mysql2::Error: Duplicate entry '1' for key 'PRIMARY': INSERT INTO `users`
```

Any possible solution to this? I am willing to fix if someone just points me to the right file(s). Thanks!

**Comment by mshibuya** [comment]
Looks like the same with #1203.
