### ISSUE TITLE
viable_models ignores multi-model files

### ISSUE THREAD

**Issue by mlt** [sferik/rails_admin#2979]
While it may be not-so-rails way to stash several models into a single file, nevertheless this is my case. I group models into modules. Hence [viable_models](https://github.com/sferik/rails_admin/blob/ead1775c48754d6a99c25e4d74494a60aee9b4d1/lib/rails_admin/config.rb#L322-L336) does not "unfold" those.

Can we [check descendants of ActiveRecord::Base](https://stackoverflow.com/a/10712838/673826)?

**Comment by mshibuya** [comment]
It does, you'll need to manually configure `included_models`.
I discourage you to use such a setup since it's incompatible with [Zeitwerk](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html) anyway.
