### ISSUE TITLE
Specify columns in query

### ISSUE THREAD

**Issue by szechyjs** [sferik/rails_admin#2981]
I have a table that stores large amounts of binary data in a column. This table gets referenced by a foreign key. I like to be able to associate this data through rails_admin, however doing so greatly slows down the page load times as the query `SELECT "data".* FROM "data"` is performed on the database. This can return hundreds of megs of data, which greatly slows things down.

I have the binary columns excluded from rails_admin using the `exclude_fields` config, however this does not help. It would be nice if rails_admin would take into account the included and excluded fields when making queries. In my case all I need to query for is `id, name` which would result in a response of several K of data rather than 100's of MB.

**Comment by elisbresciani** [comment]
try passing your field in app/config/rails_admin.rb
like this:
```
             list do
                    
                     field :tags do
                              queryable true
                              searchable [:name]
                              # searchable [{:tags => :name}]
                              filterable true
                            end
              end
```
