### ISSUE TITLE
Time Picker won't set value!

### ISSUE THREAD

**Issue by Gonzalo9823** [sferik/rails_admin#2986]
Hey! I'm having a problem whit the date time picker! I can select my value and everything but at the moment I try to save it sends a nil to de database even when I don't change any value for e.x.: I go to see my user, I don't change anything and it makes all my dates values nil! HELP PLEASE!

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
