### ISSUE TITLE
Show users currently active on a post

### ISSUE THREAD

**Issue by StarWar** [sferik/rails_admin#2991]
For Our Websites, we have several authors and moderators. I want a way to prevent users from unknowingly saving and editing each other's content, or prevent moderator from editing content while the author is editing content.

I think showing currently active user on the current post's show and edit view would be a nice way. Or there's some other and better approach to this.

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
