### ISSUE TITLE
Export gives junk characters for chinese text

### ISSUE THREAD

**Issue by rohankumar032** [sferik/rails_admin#2994]
Hi Team,

Sorry, it this was answered before.

When we try to do a "Export to CSV" it works fine for LibreOffice Calc. But, the same on a windows machine gives messy characters for chinese text on excel.

Please let me know if it needs any more detail.

Regards.

**Comment by rohankumar032** [comment]
Please help here !

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
