### ISSUE TITLE
content_for tags not working

### ISSUE THREAD

**Issue by ianubhav** [sferik/rails_admin#3002]
I m trying to add a custom JS and CSS through the [content_for](http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-content_for) method but the code is not executing in between the tags
Here is my code

<% content_for :head do %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/css/selectize.default.min.css" integrity="sha256-+2lyWXApzbDj+vHaoYRVsx253cXaQ11xVCzPg34SVC4=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.min.js" integrity="sha256-HyBiZFJAMvxOhZoWOc5LWIWaN1gcFi8LjS75BZF4afg=" crossorigin="anonymous"></script>
<% end %>

**Comment by mshibuya** [comment]
To inject your custom JavaScripts, follow the instruction below:
https://github.com/sferik/rails_admin/wiki/Theming-and-customization
