### ISSUE TITLE
ArgumentError in RailsAdmin::Main#dashboard

### ISSUE THREAD

**Issue by hyungsok** [sferik/rails_admin#3005]
I got this error in development env.

rails version:4.2.10
rails_admin version: 1.3.0

[ error content ]

comparison of Fixnum with Time failed
`
Extracted source (around line #78):
        from_time = from_time.to_time if from_time.respond_to?(:to_time)
        to_time = to_time.to_time if to_time.respond_to?(:to_time)
        from_time, to_time = to_time, from_time if from_time > to_time
        distance_in_minutes = ((to_time - from_time)/60.0).round
        distance_in_seconds = (to_time - from_time).round
`

**Comment by mshibuya** [comment]
Full stack trace, please.
