### ISSUE TITLE
Non standard column names cannot be sorted.

### ISSUE THREAD

**Issue by psaitu** [sferik/rails_admin#3008]
We have a column name with nonconventional casing like "isEnabled" and when we try to sort it we get an error 
`PG::UndefinedColumn: ERROR:  column apninfo.isenabled does not exist `
Many of our column names are nonconventional and sorting those columns leads to the same error. Is it possible to override this behavior and take column names as is without lowercasing when trying to sort?

**Comment by mshibuya** [comment]
Dup of #1281.
