### ISSUE TITLE
build_statement_for_datetime_or_timestamp removes the time components

### ISSUE THREAD

**Issue by enthusiasmus** [sferik/rails_admin#3011]
I wonder why this method doesn't allow a `datetime` with a custom time, but instead resets the time information to the beginning and the end of the day? So the user never can make use of the time components when filtering for example by `created_at`.

```
def build_statement_for_datetime_or_timestamp
  start_date, end_date = get_filtering_duration
  start_date = start_date.to_time.try(:beginning_of_day) if start_date
  end_date = end_date.to_time.try(:end_of_day) if end_date
  range_filter(start_date, end_date)
end
```
Thanks in advance!

**Comment by mshibuya** [comment]
Fixed by https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a.
