### ISSUE TITLE
"We're sorry, but something went wrong." in development env

### ISSUE THREAD

**Issue by SebouChu** [sferik/rails_admin#3012]
# Description

On a Rails project, if I force an error (e.g. RoutingError) in development environment, the stack trace is printed in the browser, no problem (First screenshot below). 
But after installing RailsAdmin, the stack trace is only printed in the console but not on the browser, showing the "We're sorry, but something went wrong" (Second screenshot below). 
An ActionView::Template::Error appears in the console with RailsAdmin installed. (see "Console logs" section below)

# Console logs

- [Without RailsAdmin](https://gist.github.com/SebouChu/8adb72bfabf8ffed613df0008eed901b)
- [With RailsAdmin](https://gist.github.com/SebouChu/61445265868ff66bdcedf1b9af329e98)

# Screenshots

## Without RailsAdmin :

![screenshot from 2018-04-11 09-01-41](https://user-images.githubusercontent.com/7761386/38601206-120800ca-3d67-11e8-8441-35f7c4fc7f3a.png)

## With RailsAdmin :

![screenshot from 2018-04-11 09-02-12](https://user-images.githubusercontent.com/7761386/38601205-11ea6c90-3d67-11e8-970b-2394a91c9cea.png)

**Comment by buncismamen** [comment]
can you share your routes.rb too?

**Comment by SebouChu** [comment]
I forced the RoutingError by using a fake path but if you want
``` ruby
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

**Comment by CristopherVidalMachado** [comment]
Your rails version is 5.20?

**Comment by SebouChu** [comment]
Yes but I had the issue two days ago with Rails 5.1.6

**Comment by spb829** [comment]
I got a same issue with ruby 2.4.1, rails 5.0.7

**Comment by sac2171** [comment]
Had this happen to me as well. Happens when you do not run:

```
 rails g rails_admin:install
```

Something in the package without installing breaks Rails' error view, which makes any exception go to the production (rather than development) 500 page.

**Comment by spikeheap** [comment]
^ I've just checked, and the same error occurs even if you don't mount RailsAdmin (step 8 above)

**Comment by Yanchek99** [comment]
Seems like it is an issue from remotipart https://github.com/JangoSteve/remotipart/issues/194

**Comment by morylab** [comment]
I got a same issue with Ruby2.4.4,  Rails5.1.6

**Comment by junster90** [comment]
Looks like it's an issue with `remotipart (1.4.0)`.

You can choose to downgrade remotipart by:

1) Opening your `Gemfile.lock`
2) Find and replace `remotipart (1.4.0)` with `remotipart (1.3.0)`
3) `bundle` and restart your server

**Comment by mshibuya** [comment]
remotipart 1.4.1 is out, upgrade will solve the problem.

**Comment by ph03n1x** [comment]
I'm having this issue and I have remotipart 1.4.2 currently.

**Comment by Marktempest** [comment]
I installed the gem 'better_errors "and I solved the problem momentarily, but then it came back to me as soon as I created new resources ... does anyone know how to solve it?
