### ISSUE TITLE
 rails_admin keep giving me undefined local variable or method `rails_admin' when access dashboard

### ISSUE THREAD

**Issue by rahmatullah5** [sferik/rails_admin#3016]
I've followed this:

https://github.com/sferik/rails_admin

And I think I've done everything needed, bundle install, rake db:migrate etc but I can't get rid of:

undefined local variable or method "rails_admin" for #<#<Class:0x0055e4c3e49c30>:0x0055e4c2e61db8>

![image](https://user-images.githubusercontent.com/16495060/39318424-48e35296-49a8-11e8-892b-d2c0ccbda0e1.png)

I've open question in stackoverflow too [](https://stackoverflow.com/questions/49987793/rails-admin-keep-giving-me-undefined-local-variable-or-method-rails-admin-when)

**Comment by pythonboy1** [comment]
See RailsAdmin Work on get and post method for a action and you are using the link tag for submitting the data on template use rails_admin_for as an example to use it.

`<%= rails_admin_form_for @object, :url => item_change_path(:model_name => @abstract_model.to_param, :id => @object.id), :as => @abstract_model.param_key,:method => :post ,:html => { :class => 'form-horizontal denser'} do |form| %>`

here item_change_path is a path of ItemChange class created on Action module manually.

**Comment by Congrammers** [comment]
I got same error if I use scope as in route:

```
 scope :object, as: :object do
      mount RailsAdmin::Engine => '/data_manager', as: 'rails_admin_data_manager'
end
```

to resolve it I simply move it outside the scope as so
`mount RailsAdmin::Engine => 'object/data_manager', as: 'rails_admin_data_manager'`

**Comment by p3drosola** [comment]
Thanks for the fix @Congrammers . Works as expected

**Comment by pskl** [comment]
@rahmatullah5 Why did you close this? Imho its an open issue and should be addressed by the maintainers.
