### ISSUE TITLE
How to suppress "Where to mount" prompt

### ISSUE THREAD

**Issue by saravanabalagi** [sferik/rails_admin#3023]
When we do `rails g rails_admin:install`, the following prompt appears:
`?  Where do you want to mount rails_admin? Press <enter> for [admin] >`

Is there a way to suppress the prompt?

Or something like:
`rails g rails_admin:install --path='/required_path'`
with --path defaulting to `/admin` if not specified

**Comment by mshibuya** [comment]
You can pass an argument to skip it.

```bash
$ rails generate rails_admin:install restricted
           -  Using [restricted] for question 'Where do you want to mount rails_admin?'
       route  mount RailsAdmin::Engine => '/restricted', as: 'rails_admin'
      create  config/initializers/rails_admin.rb
```
