### ISSUE TITLE
belongs_to filter problem when same model

### ISSUE THREAD

**Issue by jdevmulti** [sferik/rails_admin#3024]
this happens to me when for example when : 
```ruby
class User

  belongs_to :manager, class_name: "User", inverse_of: :collaborators
  has_many :collaborators, class_name: "User", inverse_of: :manager

  field :title, type: String
  field :full_name, type: String

  ....

end
```

My rails_admin config : 
```ruby
RailsAdmin.config do |config|
  config.model User
    list do
      field :manager
      ...
    end
  end
end
```
A string filter for the field manager is added in the RA view with the dropdown "contains, start_with" etc...
But it seems that when i want to filter a user by its manager's title or fullname it doesn't work and filters the user itself not his manager. This only happens to me when i reference the model itself.
Otherwise it works great for other models and associations

**Comment by dmilisic** [comment]
Maybe there is something wrong with the associations. Is table column named `user_id` or `manager_id`? Perhaps you need to add `foreign_key` property to association definitions. Also use symbols for `inverse_of` properties:
```ruby
class User

  belongs_to :manager, class_name: "User", inverse_of: :collaborators
  has_many :collaborators, class_name: "User", inverse_of: :manager

end
```
