### ISSUE TITLE
How to use https for rails_admin?

### ISSUE THREAD

**Issue by Julyyq** [sferik/rails_admin#3026]
I wanna use https for my website, I configured nginx properly, add set HOST env variable to https domain in application.yml file then everything is working fine, but my rails admin left navigation label link still starts with http, even I can't find any config file to do that. I saw that rails admin navigation link is absolute link, so I think there must be a place to get host by rails admin.

How can I figure it out? Thanks in advance.

**Comment by sarink** [comment]
Well, this is weird. I have exactly the _opposite_ problem.

**Comment by sarink** [comment]
Update: Just set `config.action_controller.default_url_options` (it accepts a hash with a `protocol` key) in your `<environment>.rb` file
