### ISSUE TITLE
Is it compatible with rails 5.2 --api

### ISSUE THREAD

**Issue by dachinat** [sferik/rails_admin#3030]
I'm trying to set up RailsAdmin with Rails v.5.2 API only project. I came up with some article that said "RailsAdmin handles conversion of project into non-API mode for it automatically". However, I was disappointed; I was getting blank screen, on Devise's log-in, I think it could not render as HTML.

Should latest version `~> 1.3` work with Rails `5.2` API out-of-the-box, so I have to consider revisiting my configuration, or should I give up on this?

**Comment by dachinat** [comment]
#3014 helped.

**Comment by kchronis** [comment]
@dachinat I'm still having this issue after adding `config.excluded_models = ['ActiveStorage::Blob', 'ActiveStorage::Attachment']`. Was there anything else you had to do?

**Comment by kchronis** [comment]
@dachinat there isn't anything in the logs, I just get a 401 redirect and it renders an empty Devise::SessionsController#new page. Would you mind sharing which middelware you have added and your rails_admin.rb initializer?

**Comment by dachinat** [comment]
@kchronis I have changed whole thing afterwards, because I needed more things (for example records would not update, etc.), but this is what I have picked from the commit log for the time I resolved blank screen problem:

**config/application.rb**
```
config.middleware.use Rack::MethodOverride
config.middleware.use ActionDispatch::Flash

config.middleware.use ActionDispatch::Cookies
config.session_store :cookie_store, key: "_app_name_session"
config.middleware.use ActionDispatch::Session::CookieStore, config.session_options

```
**config/initializers/rails_admin.rb**

config.excluded_models = ['ActiveStorage::Blob', 'ActiveStorage::Attachment']
```

This worked with Devise views, but they were not styled, so later I decided to use HTTP Basic Auth with Warden.

If you still get an error, I can set up an example app, so we can resolve your issue.

**Comment by kchronis** [comment]
@dachinat I'm still getting the same results even after adding in the middleware to `application.rb`. I'm running Rails 5.2 with rails_admin 1.3.0 which I believe is the same setup as you had.

**Comment by dachinat** [comment]
@kchronis 
Here, you can see commits for Devise and RailsAdmin setup, https://github.com/dachinat/rails_admin_demo/commits/master

_Project was generated using `rails new rails_admin_demo --api --skip-spring -J -T --database=postgresql`_

**Comment by kchronis** [comment]
@dachinat it works! Initially, I was seeing the same results after setting the rails_admin `parent_controller` then noticed that you also have to explicitly set it in the devise initializer. You saved me a lot of time, I owe you a beer!
