### ISSUE TITLE
Throws error while creating/editing record with json fieldtype

### ISSUE THREAD

**Issue by tannakartikey** [sferik/rails_admin#3033]
I have a model which has a column named `data` with `json` datatype (the migration is included below).

Viewing the record works fine. Edit record screen also opens without any error.
After editing, on submit, it thros the error. On visiting new record path (i.e. `http://localhost:9999/admin/action/new`) it thorws the same error.
[Error stack trace](https://gist.github.com/tannakartikey/7f943001b6a9c2ebaa6c4c76fc905461)

Ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
Rails version: Rails 5.1.4
Database: psql (PostgreSQL) 9.5.13

```
class CreateActions < ActiveRecord::Migration[5.1]
  def change
    create_table :actions do |t|
      t.references :activity, foreign_key: true
      t.references :user, foreign_key: true
      t.json :data

      t.timestamps
    end
  end
end
```

**Comment by mshibuya** [comment]
Dup of #2329.
