### ISSUE TITLE
Limited Pagination on 0.7.0?

### ISSUE THREAD

**Issue by georgeu2000** [sferik/rails_admin#3038]
I tried to use limited pagination, but got:

```undefined method `limited_pagination' for #<RailsAdmin::Config::Sections::List:0x00007fba84d7b9f0>```

Is it available in 0.7.0? Is there any documentation on when this feature was added?

**Comment by mshibuya** [comment]
Added in 1.3.0.
https://github.com/sferik/rails_admin/commit/bc904de181caebedb653a08a81925079c90eb3f4
