### ISSUE TITLE
Font Awesome broken

### ISSUE THREAD

**Issue by dostapn** [sferik/rails_admin#3039]
my app use gem font-awesome-sass 5.0.x
rails_admin use font-awesome-rails 4.7.x

after add rails_admin gem application.css imports font-awesome.css from font-awesome-rails 4.7.x
and all style was broken

wtf?

**Comment by haroldus-** [comment]
@dostapn see this [issue](https://github.com/bokmann/font-awesome-rails/issues/194) which provides a workaround. In my case I got the scss files and imported them in my `application.scss` file following the font awesome [instructions](https://fontawesome.com/how-to-use/on-the-web/using-with/sass). It is a way to use rails admin and fa 5 (and font-awesome-sass gem) at the same time

rails_admin should probably switch to font-awesome-sass given that font-awesome-rails has not progressed
