### ISSUE TITLE
Stuck at - rails g rails_admin:install

### ISSUE THREAD

**Issue by igor031** [sferik/rails_admin#3050]
![capture](https://user-images.githubusercontent.com/41880702/43403294-02c9d598-9415-11e8-9595-c68cdb0925b2.PNG)

When i type in rails g rails_admin:install in git and after it ask me this it gets stuck.
I just press enter.
![capture2](https://user-images.githubusercontent.com/41880702/43403426-4e271104-9415-11e8-9c83-3c2274d930a0.PNG)

What is the reason?

**Comment by mshibuya** [comment]
Dup of #2334.
