### ISSUE TITLE
Redirect flashes broken

### ISSUE THREAD

**Issue by dansteele** [sferik/rails_admin#3053]
Howdy,

After upgrading from v1.3.0 to 1.4.0, my flashes on redirect seem to have broken throughout my application, not limited to the engine itself.

No matter how I try and set the flashes (`flash[:notice] = ` or `redirect_to my_url, notice: 'hello'`), they only seem to appear when the back button is used on the redirected-to page.

Tested on Rails 5.2.0, Rails 5.2.1, and using jquery-ui-rails 5.0.5 and 6.0.1

Keeping this gem at v1.3.0 for now

**Comment by wlipa** [comment]
Might be to do with the flash middleware and https://github.com/sferik/rails_admin/issues/3048

**Comment by mshibuya** [comment]
I guess so, closing this.
