### ISSUE TITLE
Could not find generator 'rails_admin:install'.

### ISSUE THREAD

**Issue by bitcoiners** [sferik/rails_admin#3054]
Following installation instructions I tried:
rails g rails_admin:install
```
Running via Spring preloader in process 29298
Could not find generator 'rails_admin:install'. Maybe you meant 'test_unit:system', 'channel' or 'integration_test'
Run `rails generate --help` for more options.
```
using Rails 5.2 and rails admin 1.4

gem 'rails_admin', '~> 1.4'

bundle installed with no errors.

**Comment by montells** [comment]
I am having the same issue. How did you solve?

Thanks

**Comment by montells** [comment]
`spring stop` restarting spring I solved
