### ISSUE TITLE
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "applications" does not exist

### ISSUE THREAD

**Issue by abepark01** [sferik/rails_admin#3062]
I am running rails_admin `1.4.0` with ruby `2.5.1` and `rails 5.2.1` and getting an error saying `PG::UndefinedTable: ERROR:  relation "applications" does not exist`

![screenshot 2018-08-29 19 20 49](https://user-images.githubusercontent.com/7087312/44825732-c90dde80-abc0-11e8-8064-48ac5bfcb441.png)

The problem is I don't have an applications model and so I am not sure where it is finding a reference to this table.

I do have a model called `CollectiveApplication` and `PositionApplication`, but I reference these models by `collective_applications` and `position_applications`

<details>
  <summary>ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "applications" does not exist</summary>
  <code>
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "applications" does not exist
LINE 8:                WHERE a.attrelid = '"applications"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"applications"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):

activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
activesupport (5.2.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
activesupport (5.2.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (5.2.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/Users/admin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
activerecord (5.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:749:in `column_definitions'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
activerecord (5.2.1) lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
activerecord (5.2.1) lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
activerecord (5.2.1) lib/active_record/model_schema.rb:466:in `load_schema!'
activerecord (5.2.1) lib/active_record/attributes.rb:234:in `load_schema!'
activerecord (5.2.1) lib/active_record/attribute_decorators.rb:51:in `load_schema!'
activerecord (5.2.1) lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/admin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.2.1) lib/active_record/model_schema.rb:456:in `load_schema'
activerecord (5.2.1) lib/active_record/model_schema.rb:346:in `attribute_types'
activerecord (5.2.1) lib/active_record/attribute_methods.rb:230:in `has_attribute?'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:245:in `aggregate_column'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:268:in `execute_simple_calculation'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:238:in `perform_calculation'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:145:in `calculate'
activerecord (5.2.1) lib/active_record/relation/calculations.rb:52:in `count'
rails_admin (1.2.0) lib/rails_admin/adapters/active_record.rb:43:in `count'
rails_admin (1.2.0) lib/rails_admin/config/actions/dashboard.rb:26:in `block (3 levels) in <class:Dashboard>'
rails_admin (1.2.0) lib/rails_admin/config/actions/dashboard.rb:24:in `each'
rails_admin (1.2.0) lib/rails_admin/config/actions/dashboard.rb:24:in `block (2 levels) in <class:Dashboard>'
rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:22:in `dashboard'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
railties (5.2.1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/builder.rb:63:in `call'
bullet (5.7.6) lib/bullet/rack.rb:14:in `call'
remotipart (1.4.2) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
airbrake (7.3.5) lib/airbrake/rack/middleware.rb:48:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.6.4) lib/rack/proxy.rb:57:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
**Airbrake: {"id"=>"0005749d-8054-1c99-3240-77fee6db4b27", "url"=>"https://airbrake.io/locate/0005749d-8054-1c99-3240-77fee6db4b27"}
  </code>
</details>

**Comment by abepark01** [comment]
```
module Collective
  class Application < ApplicationRecord
    belongs_to :competition, class_name: 'Collective::Competition'
    belongs_to :project
  end
end
```
It seems like `rails_admin` is taking issue to the namespaced model.

What I did was delete this model and the corresponding table from the schema and database.

I got the same error for another model Collective::Competition and got a similar error
```
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "competitions" does not exist
LINE 8:                WHERE a.attrelid = '"competitions"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"competitions"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
```

**Comment by mshibuya** [comment]
Closing because of the discussion in above issue.
