### ISSUE TITLE
Use rails_admin with API only Rails 5.2 without asset_pipeline

### ISSUE THREAD

**Issue by idknox** [sferik/rails_admin#3065]
I was told rails_admin would work "out of the box" with a Rails API only app. I have no asset pipeline as I have no need for assets outside of rails_admin. Is there a way to load the rails_admin assets external to the asset pipeline? This is the error I'm seeing:

`ActionView::Template::Error (The asset "rails_admin/rails_admin.css" is not present in the asset pipeline.):
`

**Comment by hainakus** [comment]
hi @idknox i have rails_admin working with rails api 5.2 out of the box.

**Comment by buncismamen** [comment]
have you added the required middleware?

**Comment by fabiantorresm** [comment]
Prueba activar las middelwares, https://medium.com/alturasoluciones/como-hacer-funcionar-activeadmin-en-una-aplicacion-rails-habilitada-como-api-61138656e07
