### ISSUE TITLE
shrine support

### ISSUE THREAD

**Issue by jacek213** [sferik/rails_admin#3067]
Hello,

Has anyone tried to marry rails_admin and shrine? 

What would be useful:

* seeing thumbnails of attachments
* form field for uploading/updating an attachment
* ability to delete an attachment

**Comment by janko-m** [comment]
Yes, see [rails_admin_shrine](https://github.com/iquest/rails_admin_shrine).

**Comment by jacek213** [comment]
Well, I currently use a slightly modified version of it right now. 

Would be nice if some good men could make a gem of it :)

**Comment by mshibuya** [comment]
#3081 is in the master now.
