### ISSUE TITLE
Sharing CSS with app

### ISSUE THREAD

**Issue by stan74fr** [sferik/rails_admin#3082]
I would like to use rails_admin for my app. Unfortunately I spent a lot of time designing custom CSS for the app and I just need to make it automatically available to the admin pages. I do not want to have to replicate... is this supported? ( i used to do it with gem administrate). thanks much for your help.

**Comment by mshibuya** [comment]
Pulling RailsAdmin's CSS in your app should be enough.
https://github.com/sferik/rails_admin/blob/0a5a45757e730b12de2b76b72e8b711ade6874ee/app/views/layouts/rails_admin/application.html.haml#L9
