### ISSUE TITLE
logout_method does not work

### ISSUE THREAD

**Issue by sarink** [sferik/rails_admin#3090]
Well, the title's kind of a lie. The `logout_method` _does_ correctly set the `:method` for the url helper, and I can verify that the `data-method` attribute is properly set on the `a` tag in the dom.

However, regardless of the value of this attribute, the browser seems to always sends a `POST`, no matter what. Some cursory research suggests this maybe has to do with the `rails-jquery_ujs` client-side javascript (which should, presumably, intercept the click and fire off a request using the method from the data attribute)?

**Comment by mshibuya** [comment]
That's the expected behavior, the HTTP method for the actual request is still `POST` but `Rack::MethodOverride` will override it by referring to the `_method` parameter.
https://github.com/rack/rack/blob/8be612ab949cf2eba7f4231ef17052a68315f911/lib/rack/method_override.rb#L7
