### ISSUE TITLE
Troubles with assets on production

### ISSUE THREAD

**Issue by matron-app** [sferik/rails_admin#3092]
Rails_admin 1.4.2
Rails 5.2.1

rails admin include on production:
```
<link rel="stylesheet" media="all" href="/assets/rails_admin/rails_admin.css">
<script src="/assets/rails_admin/rails_admin.js"></script>
```
assets precompiled as rails_admin-58cab71323dd933de6~8dbce03b0d33e76b586d5f00fbb.js│
etc

**Comment by mshibuya** [comment]
This is an asset pipeline configuration issue.
