### ISSUE TITLE
Feature Request: Disable query field per model

### ISSUE THREAD

**Issue by PikachuEXE** [sferik/rails_admin#3093]
This field is used by our internal team to search record by ID ONLY
But it generates slow db queries and affecting performance since the number of columns is large
I want to enforce them to add filter on ID to search by ID

https://github.com/sferik/rails_admin/blob/9abc1be0c1fee006a7a746583461891911fe9330/app/views/rails_admin/main/index.html.haml#L54

**Comment by mshibuya** [comment]
Use the [Custom Search](https://github.com/sferik/rails_admin/wiki/Custom-Search) feature.
