### ISSUE TITLE
Admin role

### ISSUE THREAD

**Issue by sarink** [sferik/rails_admin#3098]
How would I restrict certain fields (like setting the user's `role`) to only admin users? I want to ensure that only administrators are allowed to change the `role` attribute for a given user.

I can hide the dropdown for non-admin users, but will that actually prevent a crafty/malicious user from `POST`ing the data in the form and working around this?

I also want to limit the values available in the dropdown, for example, a regular admin should be able to update user's `role`s, but only a _superadmin_ should be able to create other superadmins.

Is there some sort of controller create-or-update-user-model hook where I can code this behavior myself? Or is there some combinations of options I can use? I'm not sure where to begin.

Thanks!

**Comment by buncismamen** [comment]
have you check the wiki ?
https://github.com/sferik/rails_admin/wiki/Authorization
