### ISSUE TITLE
NoMethodError in RailsAdmin::MainController#edit

### ISSUE THREAD

**Issue by meandkareem** [sferik/rails_admin#3106]
I'm receiving this error when I try to use multiple file upload after I already have some files uploaded.

NoMethodError (undefined method `reject' for "image/upload/v1548349484/sdcltowofv3v7dokhkvv.pdf":String):

      before = before.reject(&:blank?).map do |value|   ---> This line is causing error 
        if value.is_a?(String)
          uploader = blank_uploader
          uploader.retrieve_from_store!(value)

  
carrierwave (1.2.3) lib/carrierwave/mounter.rb:130:in `remove_previous'
carrierwave (1.2.3) lib/carrierwave/mount.rb:349:in `remove_previously_stored_files'

I added this function from wiki but it doesn't help 
```
 def files=(files)
    appended = files.map do |file|
      uploader = _mounter(:files).blank_uploader
      uploader.cache! file
      uploader
    end
    super(files + appended)
  end
```

when I manually delete files I can save without any problems.

Rails 5.2  
Carrierwave 1.2.3

**Comment by mshibuya** [comment]
This is a configuration issue, you seem to have a singular column value for multiple file upload.
