### ISSUE TITLE
Can't edit user / devise

### ISSUE THREAD

**Issue by franklindch** [sferik/rails_admin#3110]
Error on edit the user in rails_admin for one of his field : ```PG::NotNullViolation: ERROR:  null value in column "encrypted_password" violates not-null constraint```. This encrypted password field by devise is however optional.
Any change made lately on the gem?
Thanks !

**Comment by VincentSim** [comment]
Yes you have to downgrade to a prior version of devise to be supported (i.e. devise 4.5.0)
in your gemfile :   
```
gem 'devise', '~> 4.4', '< 4.6'
```

@sferik I think it is on your roadmap to fix it :)

**Comment by franklindch** [comment]
Thanks Vincent indeed this solved the pb ! @sferik any thought?

**Comment by dzirtusss** [comment]
![image](https://user-images.githubusercontent.com/20628911/54443826-224af300-474a-11e9-9d9c-c8a2e8476513.png)

Now this becoming a more PITA issue, since 4.5.0 has security issues and 4.6.0+ does not work

as well CC thread from Devise https://github.com/plataformatec/devise/pull/5044

**Comment by mshibuya** [comment]
Fixed by https://github.com/sferik/rails_admin/commit/72bc03736162ffef8e5b99f42ca605d17fe7e7d0.
