### ISSUE TITLE
Improvement: Get rid of coffeescript dependency

### ISSUE THREAD

**Issue by woidda** [sferik/rails_admin#3111]
Actually this is a pretty easy task. If I had more time to be able to do the intial setup -- checking out rep etc -- I would do this via a pull request. 

CoffeeScript is kind of obsolete with modern versions of ES and TypeScript.

Hence, this just as a small improvement suggestion:
* There are only a couple of [CoffeeScript files in this repo](https://github.com/sferik/rails_admin/search?l=coffeescript)
* With [decaffeinate](https://decaffeinate-project.org/repl/) these transfiles are translated to ES6 in seconds (it works pretty well -- I tried it with the files)
* Then you can remove the `coffee-rails` dependency.

Thanks to anybody willing to do this. This makes a lot of projects using this gem leaner.

**Comment by mshibuya** [comment]
It would be fantastic, waiting for PR!

**Comment by RocKhalil** [comment]
Will try to do it myself this week :-)

**Comment by mroderick** [comment]
@mshibuya #3168 removes CoffeeScript from this project

**Comment by GMorisot** [comment]
To note... If you add CKeditor to Rails admin, the bit of code in the [docs](https://github.com/railsadminteam/rails_admin/wiki/CKEditor) to make it work in nested forms depends on coffeescript.
