### ISSUE TITLE
Rails Admin Home Button Messing Up With My Rails Layout

### ISSUE THREAD

**Issue by usmanijazgit** [sferik/rails_admin#3118]
I have tried looking for an answer online regarding this but I can't seem to find any solution. I am using the rails_admin gem in my rails application. Everything seems to work fine but when I click the Home button in the Admin Workspace portal it messes up with the layout of my application, for which I have to refresh the page to get it back to normal. Also if I refresh the admin page after it's been loaded and then click on the home button it's working fine - same is the case with the charts section that I have in the admin panel. I have to refresh it the first time for it to show up

Please check the images.

<img width="1031" alt="Screenshot 2019-03-12 at 19 07 15" src="https://user-images.githubusercontent.com/15088837/54305810-f1d74d80-45bf-11e9-8569-cf5e231ddccd.png">

<img width="1329" alt="Screenshot 2019-03-12 at 19 07 34" src="https://user-images.githubusercontent.com/15088837/54305819-f996f200-45bf-11e9-84ca-083bd9c163d9.png">

<img width="1011" alt="Screenshot 2019-03-12 at 19 07 53" src="https://user-images.githubusercontent.com/15088837/54305832-ff8cd300-45bf-11e9-8442-b82ded247525.png">

**Comment by mshibuya** [comment]
Looks like a pjax issue, try adding `data-pjax="0"` to links which needs layout change.
