### ISSUE TITLE
Loosen up dependency of coffee_rails

### ISSUE THREAD

**Issue by jasnow** [sferik/rails_admin#3124]
Can you please loosen up the dependency of coffee_rails gem in in rails_admin.gemspec file?
Currently:
``` 
spec.add_dependency 'coffee-rails', '~> 4.0'
```
Latest version of coffee-rails is 5.0.0.

Thanks

**Comment by jasnow** [comment]
Unclear about coffee-rails and rails_admin dependency relationship so closing this for now.

**Comment by stephancom** [comment]
👍

**Comment by stephancom** [comment]
Problem is that upgrading to Rails 6 gives you a coffee_rails deprecation warning, fixed here:

https://github.com/rails/coffee-rails/commit/cbf6af63ac57cea246b75275ba50769d12f43316

coffee-rails 5 isn't quite ready yet, but the version exists:

https://github.com/rails/coffee-rails/issues/113

@jasnow try this in your Gemfile for now:

```
gem 'coffee-rails', '~> 4.2', github: 'rails/coffee-rails', tag: 'v4.2.2'
```

**Comment by jasnow** [comment]
@stephancom - Tried your suggestion but the warning still there. Thanks for the idea.
