### ISSUE TITLE
Integrating 2 independent gems with rails_admin

### ISSUE THREAD

**Issue by felix91gr** [sferik/rails_admin#3130]
Hi all,

I'm currently working on a project that's intended to be only edited from the Admin Panel.

This project's content will be localized to three languages, at the moment this is being done with the [Globalize](https://github.com/globalize/globalize) gem. The integration with `rails_admin` is being done through the [Rails Admin Globalize Field](https://github.com/scarfacedeb/rails_admin_globalize_field) gem. 

Now, however, we want to have rich text submissions for three of our plaintext-based localizable fields. There are [four](https://github.com/sferik/rails_admin/wiki/Text) gems that integrate with `rails_admin` to proportionate rich text editing, but I can't find anything regarding them and `globalize` together in the context of the `rails_admin` gem.

Will this be a moot attempt? Or is it possible to integrate two extension gems for `rails_admin` to work on the same fields?

Any help / tips / links are appreciated.
-- Félix

**Comment by mshibuya** [comment]
They don't work on the same field.
For [this example](https://github.com/scarfacedeb/rails_admin_globalize_field#usage), configuring :globalize_tabs normally and using rich-text editors for :title and :desc is enough.

**Comment by felix91gr** [comment]
> They don't work on the same field.

I don't understand what you mean. How can I configure `globalize_tabs` and rich-text editors at the same time without them clashing?

Maybe I'm not looking at the right rich-text editor. I was trying action text, maybe that's not what I should use?

**Comment by mshibuya** [comment]
The issue tracker is for tracking issues, please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request.

**Comment by felix91gr** [comment]
Oh, I see. Sorry for the inconvenience 🙂
