### ISSUE TITLE
Nested relation not showing up on edit page

### ISSUE THREAD

**Issue by sedubois** [sferik/rails_admin#3131]
I have a Rails 4.2 app with a `Testimonial` model which has 3 relations on a `LocalizedString` model:

```ruby
class Testimonial < ActiveRecord::Base
  belongs_to :title, foreign_key: :title, class_name: "LocalizedString", dependent: :destroy
  belongs_to :quote, foreign_key: :quote, class_name: "LocalizedString", required: true, dependent: :destroy
  belongs_to :author, foreign_key: :author, class_name: "LocalizedString", required: true, dependent: :destroy
  accepts_nested_attributes_for :title, :quote, :author
end
```

I have built custom Rails admin pages where I can CRUD these testimonials without issue. Now I want to instead use `rails_admin` to simplify my code and also to benefit from its many other features. I followed the `rails_admin` setup instructions (using rails admin 1.4.2) and the pages with my various models show up properly, however the testimonials' nested relationships to the `LocalizedString` model do not show up at all (title/quote/author are invisible):

<img width="350" alt="Screenshot 2019-05-07 at 16 05 46" src="https://user-images.githubusercontent.com/4217871/57301809-7fc44600-70e2-11e9-8d7b-6a6b01377c39.png">

At one point while writing this post, those 3 properties did show up, but with just basic integer pickers. I have no idea why (they're gone again now; hard-refresh and dev server restart did not help).

<img width="250" alt="Screenshot 2019-05-07 at 15 45 38" src="https://user-images.githubusercontent.com/4217871/57300515-a46aee80-70df-11e9-9935-cc17588e008d.png">

Here is the DB schema:

```ruby

  create_table "localized_strings", force: :cascade do |t|
    t.string   "en",         null: false
    t.string   "fr",         null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "testimonials", force: :cascade do |t|
    t.integer  "title"
    t.integer  "quote",      null: false
    t.integer  "author",     null: false
    t.integer  "rating"
    t.date     "date"
    t.string   "permalink"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "testimonials", ["author"], name: "index_testimonials_on_author", using: :btree
  add_index "testimonials", ["quote"], name: "index_testimonials_on_quote", using: :btree
  add_index "testimonials", ["title"], name: "index_testimonials_on_title", using: :btree
  add_foreign_key "testimonials", "localized_strings", column: "author"
  add_foreign_key "testimonials", "localized_strings", column: "quote"
  add_foreign_key "testimonials", "localized_strings", column: "title"
```

I have another model with a relation on LocalizedString which shows up fine:

<img width="300" alt="Screenshot 2019-05-07 at 15 54 52" src="https://user-images.githubusercontent.com/4217871/57300923-76d27500-70e0-11e9-942e-29e241ed0cb5.png">

Here is the code of that model:

```ruby
class ThoughtOfTheDay < ActiveRecord::Base
  belongs_to :localized_string, required: true, dependent: :destroy
  accepts_nested_attributes_for :localized_string
  ...
end
```

The only difference is that `Testimonial` has several relations on `LocalizedString` so I had to use custom column names. NB: I didn't put the foreign key column on LocalizedString because that model is supposed to be used for many other strings in the app and I don't want it to be cluttered with many sparse columns. It looks much more logical to me to put the title/quote/author columns on the testimonials, and thus make use of `belongs_to` on the `Testimonial` model.

Would you have an idea what is going on with the title/quote/author properties not showing up? Is there something cached by rails_admin somewhere that I should delete? I am not super experienced with Rails, and brand new with rails_admin. All help would be appreciated, thank you very much!

**Comment by mshibuya** [comment]
That's because you're naming foreign_keys improperly.
https://stackoverflow.com/questions/50896922/foreign-key-with-a-name-of-an-existing-model

**Comment by sedubois** [comment]
Great, that works! Thanks so much.

```ruby
class RenameTestimonialStrings < ActiveRecord::Migration
  def change
    rename_column :testimonials, :title, :title_id
    rename_column :testimonials, :quote, :quote_id
    rename_column :testimonials, :author, :author_id
  end
end
```

```ruby
class Testimonial < ActiveRecord::Base
  belongs_to :title, class_name: "LocalizedString", dependent: :destroy
  belongs_to :quote, class_name: "LocalizedString", required: true, dependent: :destroy
  belongs_to :author, class_name: "LocalizedString", required: true, dependent: :destroy
  accepts_nested_attributes_for :title, :quote, :author
end
```

<img width="400" alt="Screenshot 2019-05-08 at 8 56 21" src="https://user-images.githubusercontent.com/4217871/57352810-2f46fa00-716f-11e9-9f77-9f6214ac3bd9.png">
