### ISSUE TITLE
Date field gets deleted, is detected as datetime

### ISSUE THREAD

**Issue by sedubois** [sferik/rails_admin#3134]
Rails admin half of the time displays and allows to select a time, even for fields of type `date` and not `datetime`. This is what it sometimes shows (correct):

<img width="158" alt="Screenshot 2019-05-10 at 11 51 53" src="https://user-images.githubusercontent.com/4217871/57514895-20e91180-731a-11e9-96c7-da9f480ad114.png">

But just when reloading the page, sometimes it shows this, apparently randomly:

<img width="187" alt="Screenshot 2019-05-10 at 11 52 02" src="https://user-images.githubusercontent.com/4217871/57514935-33fbe180-731a-11e9-94ea-52d3fd0bea34.png">

The same display issue applies to the edit page.

But more importantly, when editing the record, randomly the date gets deleted upon saving. So because of this, any time I edit a record, I need to go and check if the date was preserved, otherwise I need to go and enter it again (hoping I remember what the value was).

Using rails_admin 1.4.2 and DB schema:
```ruby
  create_table "testimonials", force: :cascade do |t|
    ....
    t.date     "date"
  end
```

EDIT: the issue remains (and even gets worse) if the type is set explicitly in the config:
```ruby
  config.model 'Testimonial' do
    list do
      ...
      field :date, :date
    end
  end
```

Even in that case the time is shown:

<img width="388" alt="Screenshot 2019-05-10 at 11 44 33" src="https://user-images.githubusercontent.com/4217871/57515652-d23c7700-731b-11e9-886a-b166285f720f.png">

But more importantly, in this case the date field then gets silently nullified every single time when the record is edited.

**Comment by sedubois** [comment]
I wonder if it somehow relates to the fact that every time the admin pages get rendered, they seem to randomly choose between the English and French locales available in the app (no idea how to fix that). Then the value might be rejected because the date format is different between both languages.

**Comment by mshibuya** [comment]
A similar issue exists, could you take a look?
https://github.com/sferik/rails_admin/issues/2837

Basically, RailsAdmin does not change locale at all. It's your app's responsibility to set it up correctly.

**Comment by sedubois** [comment]
Thanks, that seems to have been the issue.

**Comment by sedubois** [comment]
Actually it hasn't. My locale still randomly loads in English/French, and randomly my date values get deleted when saving. 

So this can stay closed, but because it's a duplicate of #3140.

**Comment by sedubois** [comment]
This workaround seems to work (use same date format in both locales).

```yaml
# config/locales/rails.en.yml
en:
  time:
    formats:
      long: "%Y-%m-%d %H:%M:%S"

# config/locales/rails.fr.yml
fr:
  time:
    formats:
      long: "%Y-%m-%d %H:%M:%S"
```

**Comment by Shaglock** [comment]
@sedubois Thank you for the workaround. I think after updating gems I started to get this issue, my date fields were just set to `nil` after editing anything, but your workaround helped me
