### ISSUE TITLE
Cannot render anchor tag with field formatted_value 

### ISSUE THREAD

**Issue by sedubois** [sferik/rails_admin#3138]
I configure a model's field rendering with `formatted_value` as followed (based on the [docs](https://github.com/sferik/rails_admin/wiki/Fields#output-formatting)):

```ruby
  config.model 'Subscription' do
    fields do
      # https://github.com/sferik/rails_admin/wiki/Fields#making-all-fields-readonly-by-default
      read_only true
      self.defined = false
      self.order = nil
    end
    configure :status do
      read_only false
    end
    configure :expires_at do
      read_only false
    end
    configure :stripe_subscription_id do
      formatted_value do
        bindings[:view].tag(:a, { href: "#{Stripe::BASE_URL}/subscriptions/#{value}" }) << value
      end
    end
    list do
      fields :id, :user, :status, :expires_at, :subscription_type
      include_all_fields
    end
    edit do
      fields :status, :expires_at
    end
  end
```

1/ First issue: on the **list** view, at first the anchor is not generated once having scrolled to make the column visible (by clicking "..." which adds "set=1" in the URL):

<img width="188" alt="Screenshot 2019-05-14 at 15 45 51" src="https://user-images.githubusercontent.com/4217871/57698885-5ca81200-765f-11e9-8d94-77bb6c6580cc.png">

Only after reloading the page does `formatted_value` get called properly so that hyperlinks can be clicked:

<img width="186" alt="Screenshot 2019-05-14 at 15 35 32" src="https://user-images.githubusercontent.com/4217871/57698276-f078de80-765d-11e9-925d-e4f4bf0898a5.png">

2/ The **show** view generates scrambled HTML with the anchor duplicated and spanning the next 2 fields:

<img width="176" alt="Screenshot 2019-05-14 at 15 34 37" src="https://user-images.githubusercontent.com/4217871/57698286-f7075600-765d-11e9-9ee0-20aebcaba79a.png">
<img width="692" alt="Screenshot 2019-05-14 at 15 34 25" src="https://user-images.githubusercontent.com/4217871/57698289-fa9add00-765d-11e9-810d-6d24613d3fbf.png">

**Comment by mshibuya** [comment]
This notation never makes sense, consult with official Rails documentation.

```ruby
bindings[:view].tag(:a, { href: "#{Stripe::BASE_URL}/subscriptions/#{value}" }) << value
```

**Comment by sedubois** [comment]
OK I was taking inspiration from the wiki doc about image tags and was naively thinking that the code should be similar for anchor tags (why wouldn't it?). Anyway I found this works:

```ruby
    configure :stripe_subscription_id do
      formatted_value do
        bindings[:view].content_tag(:a, href: "#{Stripe::BASE_URL}/subscriptions/#{value}", &method(:value))
      end
    end
```
