### ISSUE TITLE
Action Text support

### ISSUE THREAD

**Issue by mshibuya** [sferik/rails_admin#3144]
https://edgeguides.rubyonrails.org/action_text_overview.html

**Comment by mshibuya** [comment]
Documentation added.
https://github.com/sferik/rails_admin/wiki/ActionText

**Comment by vnguyen13** [comment]
@mshibuya , How do you use actiontext with rails_admin?

**Comment by nezirz** [comment]
@mshibuya old question but let me add comment its about rails 7.0.4 and you need just to do:
1 - **bin/rails action_text:install**

2 - # app/models/message.rb
    
    class Message < ApplicationRecord
      has_rich_text :content
    end 
    
3 - in case that you see broken images you will need this setting 
    Use mini_magick , just include in `config/application.rb`

**config.active_storage.variant_processor = :mini_magick**

**Comment by mshibuya** [comment]
Good, could you update the Wiki entry as well?
https://github.com/railsadminteam/rails_admin/wiki/ActionText
