### ISSUE TITLE
Bug: editing nullable boolean forces it to false

### ISSUE THREAD

**Issue by sedubois** [sferik/rails_admin#3145]
When a model has a boolean which can be `nil`, the "Show" tab indeed shows the boolean as `nil` with the help of a grey icon:

<img width="137" alt="Screenshot 2019-05-25 at 15 43 12" src="https://user-images.githubusercontent.com/4217871/58369492-d8c61380-7f03-11e9-84b5-1876542a7cad.png">

However in the Edit tab, the value is displayed as an unticked checkbox instead of reflecting the fact that the value is `nil`:

<img width="249" alt="Screenshot 2019-05-25 at 15 43 24" src="https://user-images.githubusercontent.com/4217871/58369497-ec717a00-7f03-11e9-8fc6-f9bc90e986db.png">

And when saving the Edit form, it then applies the value `false` to the field, instead of keeping it `nil` as it should. It means that currently I cannot use `rails_admin` to edit my records' other fields, out of fear of inadvertently modifying these boolean values which should stay `nil`.

**Comment by RocKhalil** [comment]
What's the difference between having a boolean set as `nil` or `false` ? both cases it's a `false` statement.

**Comment by sedubois** [comment]
`nil` can be used to represent the absence of information, `false` represents information. Anyway the Ruby language itself allows booleans fields to have those 3 values, just as many other languages allow as well. At the very least the editor shouldn't coerce `nil` fields into `false`.

**Comment by RocKhalil** [comment]
Yup, totally get that. However, how can you know if the value was set by the user as `false` or as `nil` ? Maybe having a `dropdown` is a better option than a `checkbox` ?

**Comment by sedubois** [comment]
Maybe use 3 radio buttons?

**Comment by RocKhalil** [comment]
Good idea;

When `nullable` is set to false, we can use `checkbox`; otherwise, 3 radio buttons 👍

**Comment by nick-bigger** [comment]
I ran into this same issue! While it is being worked on, I have a basic workaround:

```
field :boolean_field, :enum do
  enum do
      [['True',true],['False',false],['Null',nil]]
  end
end
```

Unfortunately, no option will show in the dropdown for 'Null', but the field will show 'Optional' and can be cleared and saved correctly. And on the show page 'Null' _will_ show correctly. Hope this helps!

**Comment by yuvalt** [comment]
What worked for me is: 

```
def boolean_field_enum
	[['True',true],['False',false],['Null',nil]]
end
```
