### ISSUE TITLE
Any info on when is the next release planned for?

### ISSUE THREAD

**Issue by vincentwoo** [sferik/rails_admin#3147]
The last release was from September of 2018, and I've been running off of the `master` git branch for many months now. It would be nice to have a release cut with all the bugfixes since a year ago.

**Comment by klyonrad** [comment]
Most importantly are the pinned dependencies to other gems (coffee-rails and rails comes to mind), so please release a version.

Are there any things that are blocking a release currently? Can the community help out in some way?

**Comment by mshibuya** [comment]
[Current milestone](https://github.com/sferik/rails_admin/milestone/12) needs some more work, so I just pushed the latest master as 2.0.0.beta.

```ruby
gem 'rails_admin', '~> 2.0.0.beta'
```
