### ISSUE TITLE
Bug: Clicking on items in "Add filter" menu doesn't work

### ISSUE THREAD

**Issue by rihardssceredins** [sferik/rails_admin#3152]
Hi!

Thank you for releasing 2.0.0.beta.
After deploying it to production and clicking on any of the items in "Add filter" menu produces TypeError about translations. Is it something that we've to configure on our side or this is a issue on your end?
Reproducible on latest versions of Chrome and Safari.

<img width="1185" alt="Screenshot 2019-06-11 at 14 27 52" src="https://user-images.githubusercontent.com/23099574/59268553-9fa4d780-8c55-11e9-9199-073771ad44fe.png">
<img width="1086" alt="Screenshot 2019-06-11 at 14 32 28" src="https://user-images.githubusercontent.com/23099574/59268611-c19e5a00-8c55-11e9-8842-1f665b3f1cd6.png">

**Comment by rihardssceredins** [comment]
Forcing asset precompilation manually after deploying seems to have fixed the issue. Is that normal behaviour?

**Comment by mshibuya** [comment]
> Forcing asset precompilation manually after deploying

What does _forcing_ mean? Don't you precompile assets on deployment?

**Comment by mshibuya** [comment]
Please reopen on update.
