### ISSUE TITLE
Dynamic "optional" | "required" labels 

### ISSUE THREAD

**Issue by emmanuelperotto** [sferik/rails_admin#3153]
I have a "User" model that has a "role" field. Based on the role I want to validate the presence of city and school.

```ruby
class User < ApplicationRecord
   validates :role, presence: true
   validates :city, presence: true, if: -> { student? || professor? }
   validates :school, presence: true, if: -> { student? || professor? }

   belongs_to :city, optional: true
   belongs_to :school, optional: true

   enum role: %i[student professor admin]
end
```
But when registering a new user and seting its role to "student" it shows me that the field is "optional" instead of "required"

![image](https://user-images.githubusercontent.com/26353371/59299632-82770580-8c63-11e9-88f6-a9773c697360.png)

How can I change the label based on a dynamic validation?

**Comment by mshibuya** [comment]
Currently there's no way to change labels dynamically on client side(the label need to be changed based on current role selection to fulfill your needs). My recommendation is adding a label like `Required for student or professor`.
