### ISSUE TITLE
NoMethodError '[]' in RailsAdmin::Main#dashboard

### ISSUE THREAD

**Issue by FloweryCoder** [sferik/rails_admin#3160]
I'm receiving this error when opening the dashboard in rails_admin. 
undefined method '[]' for nil:NilClass
Code trace: 
/gems/rails_admin-1.4.2/app/views/rails_admin/main/dashboard.html.haml where line # 15 raised:
undefined method `[]' for nil:NilClass
lib/rails_admin.rb:37:in `block (2 levels) in <class:Dashboard>'
`render @action.template_name, status: (flash[:error].present? ? :not_found : 200)`

Env settings: 
rails_admin (0.8.1) 
Ruby: 2.3.1 
Rails: 4.2 

Upgraded to: 
rails_admin (1.4.2)
Ruby: 2.4.6 
Rails: 5.2 

After I upgrade I see the error. 
If I open the dashboard link: domain.com/admin/ - error is raised 
If I open any other link: domain.com/admin/card - it works perfectly 

I looked up everywhere in open and closed issues, also on stackoverflow, not sure why this error happened. 
It seems flash object is nil and so cannot access the hash values? but not sure why it returns nil in this step? 
Any body can help? Thanks.

**Comment by mshibuya** [comment]
You seems to monkey-patching RailsAdmin, update your patch based on the latest implementation.
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/dashboard.rb

**Comment by FloweryCoder** [comment]
Thanks. Yes definitely, I checked differences in the file code, and figured out the error. 

> 
> 
> You seems to monkey-patching RailsAdmin, update your patch based on the latest implementation.
> https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/dashboard.rb
