### ISSUE TITLE
problems with Locale= MX-es

### ISSUE THREAD

**Issue by erniux** [sferik/rails_admin#3161]
Do you have a Locale file for :es?  Because I had my app with locale=MX-es, but rails_admin, do not recognize it and I have to set every translation manually, could you please help me with a locale in Spanish?

Thanks in advance.

**Comment by mshibuya** [comment]
Locales other than en are here, you need to add them yourself.
https://github.com/sferik/rails_admin/wiki/Translations

**Comment by erniux** [comment]
Thank you.
