### ISSUE TITLE
CKEditor local config.js

### ISSUE THREAD

**Issue by strangerxx** [sferik/rails_admin#3162]
How overwrite config.js for CKEditor from local and don`t load from cdn?

**Comment by mshibuya** [comment]
What did you try and what happened?

**Comment by strangerxx** [comment]
I overwrite config.js for CKEditor from local storage, but include default config from cdn.

**Comment by mshibuya** [comment]
Paste actual code, please.

**Comment by strangerxx** [comment]
I add file in app/assets/javascripts/ckeditor/config.js
`
CKEDITOR.editorConfig = function( config )
{
  // Define changes to default configuration here. For example:
  config.language = 'fr';
  config.uiColor = '#AADC6E';
};
`
but include cdn config

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/config.js?t=J39A"></script><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/skins/moono-lisa/editor.css?t=J39A"><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/lang/ru.js?t=J39A"></script><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/styles.js?t=J39A"></script><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/plugins/scayt/skins/moono-lisa/scayt.css?t=J39A"><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/plugins/scayt/dialogs/dialog.css?t=J39A"><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/plugins/tableselection/styles/tableselection.css"><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/plugins/wsc/skins/moono-lisa/wsc.css?t=J39A"><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/plugins/image/dialogs/image.js?t=J39A"></script><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/skins/moono-lisa/dialog.css?t=J39A">`
and 
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.11.4/config.js?t=J39A"></script> `
overwrite my config.

**Comment by mshibuya** [comment]
There was a glitch in passing custom config location to CKEditor. I've fixed it in the master and added [an instruction](https://github.com/sferik/rails_admin/wiki/CKEditor#configuration) in the Wiki.

**Comment by strangerxx** [comment]
Thank you

**Comment by seanwmitchell** [comment]
Thanks, this worked perfectly with rails 6.0.2.1, ruby 2.6.3, ckeditor gem 5.0.0 and rails_admin 2.0.1

I can use the assets/ckeditor/config.js file perfectly.

My issue was that the upload to server options in the image button of CKeditor weren't showing.
