### ISSUE TITLE
Paid help: undefined method `sidescroll_frozen_columns' for #<RailsAdmin::Config::Sections::List

### ISSUE THREAD

**Issue by Andrew-Max** [sferik/rails_admin#3174]
I'm trying to render rails_admin pages in a controller outside of the engine so I can do heavy customization on some of the views. I"ve gotten this working to a large degree but the index pages fail with: undefined method `sidescroll_frozen_columns' for #<RailsAdmin::Config::Sections::List

I've dug pretty deep into the code and cannot seem to figure out why this isn't getting loaded by the abstract class

Is there any chance one of the main maintainers (@bbenezech , @sferik , @mshibuya , @kaapa , @gunn ) would be interested in some hourly consulting to either help me resolve my issue or come up with a better way to do what I'm trying to do?

If so please contact me at andrew.max89@gmail.com

**Comment by mshibuya** [comment]
Can you paste full stack trace?
I'm afraid that you're mixing 1.x release of RailsAdmin and the latest view template.

**Comment by mshibuya** [comment]
Stale.
