### ISSUE TITLE
Rails_Admin issues on saving, error indicates validation problems

### ISSUE THREAD

**Issue by VinylVault** [sferik/rails_admin#3176]
Hi All, 

Hoping you can help with this, it's starting to mess with my head :frowning: 

In my database (sqLite), I have currently about 20 tables  some which relate in some way or other to other tables.  

I have some relationships created with `belongs_to:`, `has_many:` and `has_many:  x through: :y`  which seem to work to a degree, by that I mean it works properly from command line, but everything goes to hell in a handbasket when i try to do anything in Rails_Admin.

I think it has something do do with the `has_many:` relationships, listing all the belonging fields in a multi-select list.  I just tried to change a text field, to update an image URL, and got back the validation error `_y_ must exist` which all of them do separately, if they didn't the record i'm trying to edit couldnt have been created. (I've checked that it works at command line in that way and was proved correct).

If anyone has any thoughts on how I can prove this, or fix it, please all help appreciated

**Comment by mshibuya** [comment]
Please be more specific, providing actual codes and the result of command line execution will help.
