### ISSUE TITLE
Rails admin is broke my page style

### ISSUE THREAD

**Issue by Klashe** [sferik/rails_admin#3178]
I updated to version 2.0.0.beta today and for some reasons not known to me the navigation styling of my website broke which didn't happen when I was using the previous version. I've rails 5.2.3 version installed on my machine.

I used bo0tstrap for for general styling except for the navigation which I used normal css for.

**Comment by mshibuya** [comment]
Can you reproduce this with newly generated Rails app?

**Comment by Klashe** [comment]
It works with no issue on rails 6.0.0.rc1 app.

**Comment by mshibuya** [comment]
Good to hear that, closing then.

**Comment by Klashe** [comment]
So does it mean the latest version isn't compatible with rails 5.2? Because
that was the version that got broken and ain't using 6.0 yet other than for
testing features.

**Comment by mshibuya** [comment]
I'm not saying so, if you could provide the reproducible example then I can take a look.
