### ISSUE TITLE
Filtering by datetime range actually filters by date range

### ISSUE THREAD

**Issue by tinbka** [sferik/rails_admin#3179]
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/abstract_model.rb#L181

I wonder what's the reasoning behind these `beginning_of_day` and `end_of_day` conversions.

My use case:  
I'm looking up dozens of thousands of records made within the same date, and with this approach it's barely possible because I have to go through hundreds of pages just to find the records from the sought time interval somewhere in the middle of the pages range.

If I want to filter by a date range, I can type in 00:00:00 and 23:59:59 myself.  
Yeah, I know, there's an issue with that 23:59:59 is not 23:59:59**.999999** and SQL's BETWEEN **includes** interval edges.  
Well then, maybe it would be more logical to create one more operator in addition to "Between ... and ..." when searching by a datetime field, like "Between dates ... and ..." or something for the use case that is currently implemented.

Is anyone interested in such a patch?

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/commit/01e8d5fc8ec94e68af6fdbd80759a751cd83f74a solved this.
