### ISSUE TITLE
"Choose All" doesn't work

### ISSUE THREAD

**Issue by emmanuelperotto** [sferik/rails_admin#3181]
I have an application with coupons and I wanna send coupons to all my users. Now that I have more than 1700 users registered it shows me a placeholder.
![A](https://user-images.githubusercontent.com/26353371/62486496-d7cc2080-b795-11e9-86f3-890563c4b927.png)

But when I click "Choose all" It does nothing and don't associate a coupon to all users.

**Comment by mshibuya** [comment]
This is by design, you'll need to create some kind of batch job to do so.
