### ISSUE TITLE
has_any_belongs_to_many with join_table not supported on the view?

### ISSUE THREAD

**Issue by sandipsubedi** [sferik/rails_admin#3183]
I have a join_table that I created called `client_creators`. This is what the table looks like:
```
class ClientCreator < ApplicationRecord
  belongs_to :user
  belongs_to :client
end
```

User Table:
```
Class User < ApplicationRecord
  has_and_belongs_to_many :clients, join_table: :client_creators
end
```

Client Table:
```
Class Client < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :client_creators
end
```

When I go to the rails admin for that table I am seeing this error:
```
ActiveRecord::StatementInvalid at /client_creator
PG::UndefinedColumn: ERROR:  column client_creators.desc does not exist
LINE 1: ...ent_creators".* FROM "client_creators" ORDER BY client_app...
                                                             ^
: SELECT  "client_creators".* FROM "client_creators" ORDER BY client_creators. desc LIMIT $1 OFFSET $2
```

I went through this documentation:
https://github.com/sferik/rails_admin/wiki/Has-and-belongs-to-many-association

Does it not support for join_tables with custom names?

**Comment by mshibuya** [comment]
Because RailsAdmin can't handle a model without primary key, and `ClientCreator` doesn't have it.

BTW, has_many through will be what you want - not habtm.
https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many
