### ISSUE TITLE
NoMethodError in RailsAdmin::MainController#dashboard Rails 6

### ISSUE THREAD

**Issue by ph03n1x** [sferik/rails_admin#3187]
I am using
Rails 6.0.0
Rails Admin 2.0.0.rc
Rails Admin Import 2.2.0

When I go back to Rails 5.2 and previous version of Rails Admin, it works fine. But for Rails 6 I get the below messages.

undefined method `new' for nil:NilClass

Extracted source (around line #160)
| klass.setup if klass.respond_to? :setup
@authorize = proc do
@authorization_adapter = klass.new(*([self] + args).compact)
end
elsif block
@authorize = block

rails_admin (2.0.0.rc) lib/rails_admin/config.rb:160:in block in authorize_with' rails_admin (2.0.0.rc) app/controllers/rails_admin/application_controller.rb:54:in instance_eval'
rails_admin (2.0.0.rc) app/controllers/rails_admin/application_controller.rb:54:in _authorize!' activesupport (6.0.0) lib/active_support/callbacks.rb:429:in block in make_lambda'
activesupport (6.0.0) lib/active_support/callbacks.rb:201:in block (2 levels) in halting' actionpack (6.0.0) lib/abstract_controller/callbacks.rb:34:in block (2 levels) in module:Callbacks'
activesupport (6.0.0) lib/active_support/callbacks.rb:202:in block in halting' activesupport (6.0.0) lib/active_support/callbacks.rb:514:in block in invoke_before'
activesupport (6.0.0) lib/active_support/callbacks.rb:514:in each' activesupport (6.0.0) lib/active_support/callbacks.rb:514:in invoke_before'
activesupport (6.0.0) lib/active_support/callbacks.rb:110:in block in run_callbacks' react-rails (2.6.0) lib/react/rails/controller_lifecycle.rb:31:in use_react_component_helper'
activesupport (6.0.0) lib/active_support/callbacks.rb:121:in block in run_callbacks' activesupport (6.0.0) lib/active_support/callbacks.rb:139:in run_callbacks'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:41:in process_action' actionpack (6.0.0) lib/action_controller/metal/rescue.rb:22:in process_action'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:33:in block in process_action' activesupport (6.0.0) lib/active_support/notifications.rb:180:in block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in instrument' activesupport (6.0.0) lib/active_support/notifications.rb:180:in instrument'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:32:in process_action' actionpack (6.0.0) lib/action_controller/metal/params_wrapper.rb:245:in process_action'
activerecord (6.0.0) lib/active_record/railties/controller_runtime.rb:27:in process_action' actionpack (6.0.0) lib/abstract_controller/base.rb:136:in process'
actionview (6.0.0) lib/action_view/rendering.rb:39:in process' actionpack (6.0.0) lib/action_controller/metal.rb:191:in dispatch'
actionpack (6.0.0) lib/action_controller/metal.rb:252:in dispatch' actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:51:in dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:33:in serve' actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in each' actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in call' railties (6.0.0) lib/rails/engine.rb:526:in call'
railties (6.0.0) lib/rails/railtie.rb:190:in public_send' railties (6.0.0) lib/rails/railtie.rb:190:in method_missing'
actionpack (6.0.0) lib/action_dispatch/routing/mapper.rb:19:in block in <class:Constraints>' actionpack (6.0.0) lib/action_dispatch/routing/mapper.rb:48:in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in block in serve' actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in serve' actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in call' meta_request (0.7.2) lib/meta_request/middlewares/app_request_handler.rb:13:in call'
meta_request (0.7.2) lib/meta_request/middlewares/meta_request_handler.rb:13:in call' remotipart (1.4.3) lib/remotipart/middleware.rb:32:in call'
warden (1.2.8) lib/warden/manager.rb:36:in block in call' warden (1.2.8) lib/warden/manager.rb:34:in catch'
warden (1.2.8) lib/warden/manager.rb:34:in call' rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in call'
rack (2.0.7) lib/rack/etag.rb:25:in call' rack (2.0.7) lib/rack/conditional_get.rb:25:in call'
rack (2.0.7) lib/rack/head.rb:12:in call' actionpack (6.0.0) lib/action_dispatch/http/content_security_policy.rb:18:in call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in context' rack (2.0.7) lib/rack/session/abstract/id.rb:226:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/cookies.rb:648:in call' activerecord (6.0.0) lib/active_record/migration.rb:567:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in block in call' activesupport (6.0.0) lib/active_support/callbacks.rb:101:in run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in call' actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in call' actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in call'
rack-contrib (2.1.0) lib/rack/contrib/response_headers.rb:17:in call' meta_request (0.7.2) lib/meta_request/middlewares/headers.rb:16:in call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in call_app' web-console (3.7.0) lib/web_console/middleware.rb:30:in block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in catch' web-console (3.7.0) lib/web_console/middleware.rb:20:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in call' railties (6.0.0) lib/rails/rack/logger.rb:38:in call_app'
railties (6.0.0) lib/rails/rack/logger.rb:26:in block in call' activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in block in tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in tagged' activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in tagged'
railties (6.0.0) lib/rails/rack/logger.rb:26:in call' sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in call' actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in call'
rack (2.0.7) lib/rack/method_override.rb:22:in call' rack (2.0.7) lib/rack/runtime.rb:22:in call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in call' actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in call' rack (2.0.7) lib/rack/sendfile.rb:111:in call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:83:in call' webpacker (8845f37bb038) lib/webpacker/dev_server_proxy.rb:22:in perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in call' railties (6.0.0) lib/rails/engine.rb:526:in call'
rack (2.0.7) lib/rack/handler/webrick.rb:86:in service' /Users/ph03n1x/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpserver.rb:140:in service'
/Users/ph03n1x/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/httpserver.rb:96:in run' /Users/ph03n1x/.rbenv/versions/2.6.3/lib/ruby/2.6.0/webrick/server.rb:307:in block in start_thread'

**Comment by ph03n1x** [comment]
I have tried the same version with 5.2.3 and having the same issues

Started GET "/admin" for ::1 at 2019-08-24 21:44:41 -0400
   (0.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by RailsAdmin::MainController#dashboard as HTML
Completed 500  in 2ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `new' for nil:NilClass):

When I go back to the previous version I get this instead

Started GET "/admin" for ::1 at 2019-08-24 21:48:38 -0400
   (0.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by RailsAdmin::MainController#dashboard as HTML
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]

**Comment by jasnow** [comment]
Is it possible to share the repo that is causing this problem?

**Comment by RocKhalil** [comment]
I just debugged it and it's from the `rails_admin` initializer.

You'll need to update ` config.authorize_with` and set it as `:cancancan` instead of `:cancan`.

`rails_admin 2.0` uses `cancancan` and `pundit`.

**Comment by ph03n1x** [comment]
Thanks, that fixed it.
