### ISSUE TITLE
Rspec breaking for rails_admin 2.0.0

### ISSUE THREAD

**Issue by satendra-dhillon** [sferik/rails_admin#3192]
At earlier with rails_admin 1.4.2, everything working fine.
Updating the rails_admin version from 1.4.2 to 2.0.0, rspec failing for 'paper_trail_version' factory.

`Version admin behaves like a rails_admin model enables admin to edit a paper_trail_version
      Failure/Error: @model = FactoryBot.build(model_name)
      
      ArgumentError:
        Factory not registered: paper_trail_version
      
      [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_version_admin_behaves_like_a_rails_admin_model_enables_admin_to_edit_a_paper_trail_version_571.png
`
rails-5.2.3
factory_bot_rails-5.0.2

**Comment by mshibuya** [comment]
I don't have access to specs **you wrote**. 
At least you should provide a reason why you think the problem is in RailsAdmin, not in your specs.

**Comment by darrenterhune** [comment]
Adding `PaperTrail::Version` to `excluded_models` fixes the op's problem.
