### ISSUE TITLE
Devise authentication

### ISSUE THREAD

**Issue by Bdoom** [sferik/rails_admin#3193]
== Devise ==
config.authenticate_with do
warden.authenticate! scope: :user
end
config.current_user_method(&:current_user)

I have this setup with RailsAdmin, I'm wondering if I can also check if a boolean named "admin" on my user is true. I only want people to access /admin if they are logged in with devise, and also have the "admin" column in the database, set to true. How can I do this?

**Comment by Bdoom** [comment]
Unless I can get this to work, I will not be able to use rails_admin.

**Comment by jschwindt** [comment]
@Bdoom It's in the wiki: [Authorization](https://github.com/sferik/rails_admin/wiki/Authorization)

It's as simple as:

```
RailsAdmin.config do |config|
  config.authorize_with do
    redirect_to main_app.root_path unless current_user.is_admin?
  end
end
```

**Comment by Bdoom** [comment]
Thank you my dude. It worked! :)
