### ISSUE TITLE
Active Storage - undefined method 'upload'

### ISSUE THREAD

**Issue by travismmorgan** [sferik/rails_admin#3199]
When clicking save after adding an image, I get an error 'undefined method `upload' for nil:NilClass'. 

`def upload_without_unfurling(io) #:nodoc:
    service.upload key, io, checksum: checksum, **service_metadata
 end`

**Comment by shunchu** [comment]
> When clicking save after adding an image, I get an error 'undefined method `upload' for nil:NilClass'.
> 
> `def upload_without_unfurling(io) #:nodoc: service.upload key, io, checksum: checksum, **service_metadata end`

Hey @travismmorgan, I noticed you opened the ticket but closed it right away. I'm having the same issue. Did you manage to resolve it? Any insight would be helpful. Thanks.
