### ISSUE TITLE
Vendorized FontAwesome is unreadable with Sprockets 4

### ISSUE THREAD

**Issue by bodrovis** [sferik/rails_admin#3204]
After upgrading to Sprockets 4, admin page stops working at all:

```
Error: File to import not found or unreadable: rails_admin/font-awesome.
        on line 60:1 of F:/Ruby25/lib/ruby/gems/2.5.0/gems/rails_admin-2.0.0/app/assets/stylesheets/rails_admin/rails_admin.scss.erb
>> @import 'rails_admin/font-awesome';
```

Commenting out the specified line fixes the issue. This happens on Rails 6 on Windows and Mac.

Here is a sample fresh app demonstrating the problem: https://github.com/bodrovis/RailsAdminSprockets To reproduce:

1. Clone the repo
2. Install gems
3. Run server
4. Visit `http://localhost:3000/admin`
5. Observe the error

**Comment by bodrovis** [comment]
Here's the proposed fix https://github.com/cselmer/rails_admin/commit/3fe37830fa2421455d00dfde3f2110c18ea7cc83 but I can't sent PR atm because the test suite is not working for me (even before I start changing anything). I keep seeing `CanCan` is undefined at `./spec/integration/authorization/cancancan_spec.rb:5:in `<class:Ability>' `

**Comment by gaganawhad** [comment]
@mshibuya Thanks for your work on maintaining `rails_admin`! 

Thoughts on this issue? We are experiencing this as well, and I would expect a lot of others too given that Sprockets 4 was released recently, except that I am not seeing that much activity on this issue. Let us know if the two of us are missing something.

Looks like https://github.com/cselmer/rails_admin/commit/3fe37830fa2421455d00dfde3f2110c18ea7cc83, commit, which @bodrovis linked above, should be the fix. 

@bodrovis Thanks for creating this issue!

**Comment by bodrovis** [comment]
@gaganawhad Hello! Please check my PR, I've fixed this issue (with Chris' help) and other failing tests https://github.com/sferik/rails_admin/pull/3207
