### ISSUE TITLE
custom route name for model?

### ISSUE THREAD

**Issue by vitroz** [sferik/rails_admin#3205]
I have this model called `story_categories`, which is being displayed as `story_series` on rails_admin, via label and label_plural
```
  config.model StoryCategory do
    field :id
    field :name
    field :projects
    label "Story series" 
    label_plural "Story series"
  end
```
Although, the link/route to it, it's still `admin/story_category`. is there a way to display it as `admin/story_series`?

I tried following this tutorial: (https://web.archive.org/web/20180828051240/http://blog.paulrugelhiatt.com/ruby/rails/2014/10/27/rails-admin-custom-action-example.html) but, no success.

**Comment by mshibuya** [comment]
That's not supported as of now.
