### ISSUE TITLE
SASSC-rails support

### ISSUE THREAD

**Issue by JensDebergh** [sferik/rails_admin#3214]
Hey there!

I was wondering if there are any plans to switch to `sassc-rails` gem since dependency `sass-rails` has been deprecated.

I'm willing to work on this but before I put in the work, I'd like to know if you guys will merge it when done?

Reason:

I was updating all my gems in my repo and got deprecation warning on `sass-rails` favoring `sassc-rails`. Tried to upgrade but it seems `rails_admin` has `sass-rails` as a peer dependency and I'm unable to run both gems side by side.

**Comment by jjjcheetah** [comment]
This happened in #3156.

**Comment by JensDebergh** [comment]
@jjjcheetah Great! Thanks.
