### ISSUE TITLE
Font-awesome issue. Again.

### ISSUE THREAD

**Issue by airled** [sferik/rails_admin#3216]
New `rails 6.0.1` with `sass-rails 6.0.0` with `sprockets 4` and `rails_admin 2.0.0` raises this again:
```
Error: File to import not found or unreadable: rails_admin/font-awesome.
        on line 61:1 of ../.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rails_admin-2.0.0/app/assets/stylesheets/rails_admin/rails_admin.scss.erb
>> @import 'rails_admin/font-awesome';
```

**Comment by designium** [comment]
I have the same issue too:

    SassC::SyntaxError in RailsAdmin::Main#dashboard
    Showing /usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rails_admin- 2.0.0/app/views/layouts/rails_admin/_head.html.haml where line #6 raised:

    Error: File to import not found or unreadable: rails_admin/font-awesome.
        on line 61:1 of ../../../../../usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rails_admin-2.0.0/app/assets/stylesheets/rails_admin/rails_admin.scss.erb
    >> @import 'rails_admin/font-awesome';

**Comment by tuanbht** [comment]
Same too :((

> Error: File to import not found or unreadable: rails_admin/font-awesome.
        on line 61:1 of ../../../.rvm/gems/ruby-2.6.5/gems/rails_admin-2.0.0/app/assets/stylesheets/rails_admin/rails_admin.scss.erb
>> @import 'rails_admin/font-awesome';

**Comment by airled** [comment]
As mentioned @CHTJonas, we can use rails_admin directly from github
```
gem 'rails_admin', '~> 2.0', git: 'https://github.com/sferik/rails_admin.git'
```
instead of rubygems.

**Comment by designium** [comment]
@airled Thanks! Your solution works. I just didn't know I could import gem like that.

**Comment by ziaulrehman40** [comment]
Why using it like this from git directly is needed? Curious.

**Comment by airled** [comment]
> Why using it like this from git directly is needed? Curious.
Because last version on rubygems is 2.0.0 (august) and fix was merged after that time. You can use the gem from rubygems again after it will be updated on rubygems.

**Comment by ziaulrehman40** [comment]
Such patches should be released on ASAP basis though, thanks for explaining. :slightly_smiling_face:

**Comment by mshibuya** [comment]
Dup of #3204 and fixed in the latest release 2.0.1.

**Comment by nezirz** [comment]
I had issue in version 2.2.1 and tried that one above with url 2.0 but like url dont exists anymore so tried also 2.0.2 and worked. Thank you!

**Comment by Saworieza** [comment]
Popping up again in version 3.0.1. Kindly take a look

**Comment by mshibuya** [comment]
What issue are you referring to? Please provide the error trace.

**Comment by coenvgunst** [comment]
> 
I think I also have the same issue in version 3.1

SassC::SyntaxError in RailsAdmin::Main#dashboard 

Error: File to import not found or unreadable: rails_admin/src/rails_admin/styles/base.
        on line 2:1 of app/assets/stylesheets/rails_admin.scss
>> @import "rails_admin/src/rails_admin/styles/base";

In my gemfile I have specified: gem 'rails_admin', '~> 3.1', git: 'https://github.com/sferik/rails_admin.git'

**Comment by mshibuya** [comment]
That looks unrelated to font-awesome, please open a new issue.

**Comment by kokorolx** [comment]
In `config/manifest.js`
**remove** `//= link_directory ../stylesheets .css`
**add** `//= link_tree ../builds`

the manifest.js will become:
```
//= link_tree ../images
//= link_directory ../stylesheets .css
//= link_tree ../../javascript .js
//= link_tree ../../../vendor/javascript .js
//= link_tree ../builds
```

I'm using rails_admin 3.1.2, ruby 3.1.4, rails 7.0.5 and it works for me.

**Comment by princetechs** [comment]
here is the perfect mainfest ;-

//= link_tree ../images
//= link_tree ../../javascript .js
//= link_tree ../../../vendor/javascript .js
//= link_tree ../builds
//= link rails_admin/src/rails_admin/base.js

Assets.rb

# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path

# Ensure that Yarn packages are also loaded from node_modules
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )

# Precompile additional assets including fonts and icons
Rails.application.config.assets.precompile += %w[application.css tailwind.css]

# Ensure importmaps-rails dependencies are precompiled
Rails.application.config.assets.paths << Rails.root.join('app', 'assets', 'builds')

# Add Font Awesome webfonts to the asset load path
Rails.application.config.assets.paths << Rails.root.join('node_modules/@fortawesome/fontawesome-free/webfonts')
Rails.application.config.assets.precompile += %w[.svg .eot .woff .ttf]
