### ISSUE TITLE
Arrays disappeared

### ISSUE THREAD

**Issue by ntinti** [sferik/rails_admin#3218]
I have two array data types in a postgresql table: **inet[]** and **smallint[]**. Both are completely suppressed with rails_admin. They are not shown in the list view, in the information and they are not editable. In the app view they are there.

**Comment by airled** [comment]
Rails_admin does not support postgresql arrays. You can use this [hack](https://github.com/sferik/rails_admin/issues/1218#issuecomment-37345730).
