### ISSUE TITLE
Please Help! active_storage and multiple_active_storage, how shall I show filename?

### ISSUE THREAD

**Issue by erniux** [sferik/rails_admin#3219]
Hello,

I would like to know how to show filename when multiple_active_storage.

![image](https://user-images.githubusercontent.com/34988091/68603701-725f8e00-046e-11ea-8730-6c9e0c6f0c7e.png)

It works for has_one_attached, but can't find the way to show the filename when multiple_active_storage.

Thanks in advance.

**Comment by airled** [comment]
Hi. Did you tries [this](https://github.com/sferik/rails_admin/wiki/ActiveStorage#show-correct-file-name)?

**Comment by airled** [comment]
Try this code in your `edit` section of model:
```ruby
field :my_attribute, :active_storage do
  pretty_value do
    if value
      tags = value.blobs.map do |blob|
        path = Rails.application.routes.url_helpers.rails_blob_path(blob, only_path: true)
        bindings[:view].content_tag(:div,
          bindings[:view].content_tag(:a, blob.filename, href: path)
        )
      end
      tags.join.html_safe
    end
  end
end
```

**Comment by erniux** [comment]
thanks aired I tryied that way with no luck, even I tried to do it via partial, where the name is shown but no luck to delete file :-(. this is a multiple_active_storage field :-(.

The problem with my partial is routing the delete method because I do not know where to handle the controller action for that route:

here is the partial:
<div class='col-sm-10 controls ui-sortable'>
<% if @object.obligatorio.attached? %>
	<% @object.obligatorio.map do |archivo| %>
		<div class="row">
		   <div class="col-md-4">	
		      <%= link_to archivo.filename, Rails.application.routes.url_helpers.rails_blob_path(archivo, only_path: true), target: '_blank' %>
		   </div>
		   <div class="col-md-2">
		   	<small><%= link_to 'Eliminar Archivo', estandar_etapa_certificacion_delete_obligatorio_path(:todo_id => @object.id, :upload_id => archivo.id),
          method: :delete, data: { confirm: '¿Confirma Eliminar el Archivo?' } %></small><br/> 

			    
			       
		   </div> 
		   
		</div>
	<% end %>
<% end %>
<div class="row">
	<p><%= form.file_field :obligatorio, multiple: true %></p>
</div>

**Comment by airled** [comment]
I did not ry partial but I tried my code above and it worked well. Can you provide your rails_admin.rb config to show me how you use it?

**Comment by erniux** [comment]
field :obligatorio do
        partial 'documentos'
end

**Comment by airled** [comment]
Can you try to use my code above in rails_admin.rb?

**Comment by erniux** [comment]
I did, 

`field :obligatorio, :active_storage do
        pretty_value do
          if value
            tags = value.blobs.map do |blob|
              path = Rails.application.routes.url_helpers.rails_blob_path(blob, only_path: true)
              bindings[:view].content_tag(:div, bindings[:view].content_tag(:a, blob.filename, href: path))
            end
          tags.join.html_safe
          end
        end
      end`

and I got this error message:
`undefined method `blobs' for #<ActiveStorage::Attached::Many:0x00007f85344cb1c8>`

in line:
`tags = value.blobs.map do |blob|`

**Comment by erniux** [comment]
when I change first line in rails_admin.rb to:

`field :obligatorio, :multiple_active_storage`

it run but do not show filename

**Comment by airled** [comment]
@erniux I think, I found the solution.
In model:
```ruby
has_many_attached :my_attrbute
```
`Rails_admin.rb`:
```ruby
field :my_attrbute, :multiple_active_storage do
  partial 'my_partial'
end
```
`app/views/rails_admin/main/_my_partial.html.haml`:
```haml
- field.attachments.each_with_index do |attachment, i|
  .toggle{class: field.reorderable? ? 'sortables' : ''}
    = link_to attachment.value.blob.filename, Rails.application.routes.url_helpers.rails_blob_path(attachment.value.blob, only_path: true), target: '_blank'
    %a.btn.btn-info.btn-remove-image{href: '#', :'data-toggle' => 'button', role: 'button'}
      %i.icon-white.icon-trash
      = I18n.t('admin.actions.delete.menu').capitalize + " #{field.label.downcase} ##{i + 1}"
    = form.check_box("my_attrbute", {multiple:true, checked: true, style: 'display:none;'}, attachment.value.blob.signed_id, nil)
= form.file_field(field.name, field.html_attributes.reverse_merge({ data: { :"multiple-fileupload" => true }, multiple: true }))
```
Replace all `my_attrbute` to your value.

**Comment by erniux** [comment]
Thank you, It looks fine, but, it is not deleting the files, I have some problems with this line:

.toggle{class: field.reorderable? ? 'sortables' : ''}

**Comment by airled** [comment]
Your code does not work for me. You just copy partial from rails_admin gem. It expects either `field.delete_method` or `field.keep_method`. They both return `nil` so delete buttons does not showing. My version of gem is `gem 'rails_admin', '~> 2.0', git: 'https://github.com/sferik/rails_admin.git'`.
I have just tested my code one more time and it works absolutely fine. Strange, that it does not work for you. What is your gem version? Anyway, glad it works now.

**Comment by erniux** [comment]
yes you help me to set the name, because the partial doesn't show the filename, so I change third line with your solution. And really appreciate your time to help me. Very valuable.
