### ISSUE TITLE
FATAL: NoMethodError (undefined method `new' for nil:NilClass)

### ISSUE THREAD

**Issue by davethegr8** [sferik/rails_admin#3222]
I recently upgraded rails_admin to 2.0.0, and now when trying to view my dashboard (or any rails_admin view really) I get a fatal error. I'm running the site with phusion and nginx on Ubuntu 16.04.6, but the same error doesn't repro with `rails server`

Phusion is v6.0.4

Gist with gemfile & error: https://gist.github.com/davethegr8/cca501249c73aba78058d8d099f21bf4

**Comment by TheStu** [comment]
just ran in to this, in our case we're updating a pretty out of date app that was using `config.authorize_with :cancan` in /config/rails_admin.rb. Updating to `:cancancan` fixed it.

**Comment by mattwr18** [comment]
thanks @TheStu you saved me debugging time!! :smiley_cat: that's exactly what I needed as well :blush:
