### ISSUE TITLE
SassC::SyntaxError in RailsAdmin::Main#dashboard

### ISSUE THREAD

**Issue by shivabhusal** [sferik/rails_admin#3224]
```
Showing /Users/john/.rvm/gems/ruby-2.6.3/gems/rails_admin-2.0.0/app/views/layouts/rails_admin/_head.html.haml where line #6 raised:
```
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/8004593/69307609-3e951d00-0c53-11ea-9474-894c6f08eb3c.png">

ruby: 2.6.3
rails: 6.0

**Comment by shivabhusal** [comment]
there is no error when I use master branch though.

**Comment by airled** [comment]
Duplication https://github.com/sferik/rails_admin/issues/3216
