### ISSUE TITLE
Can't change Locale for RailsAdmin.

### ISSUE THREAD

**Issue by limjinsun** [sferik/rails_admin#3225]
I am on Rails6. I want to run my app running as my local language. but I want to make RailsAdmin stay as English. I tried instruction from here. https://github.com/sferik/rails_admin/wiki/Base-configuration

but didn't work. 

```
RailsAdmin.config do |config|
  require 'i18n'
  I18n.default_locale = :en

  ### Popular gems integration
```
and 
```
require 'i18n'
I18n.default_locale = :en

RailsAdmin.config do |config|
```
Both didn't work. 
```
I18n.locale = :en
```
is not working either.

and 
https://stackoverflow.com/a/33432477/4735043
This solution didn't work either.

**Comment by airled** [comment]
I did not check it but try to create separate controller with I18n logic and inherit rails_admin controller from it in a config file. Something like this:
Rails admin abstract controller:
```
class RailsAdminAbstractController < ActionController::Base
  before_action :set_admin_locale

  private

  def set_admin_locale
    I18n.locale = :en
  end
end
```
In `config/initializers/rails_admin.rb`:
```
...
RailsAdmin.config do |config|
  ...
 config.parent_controller = '::RailsAdminAbstractController'
  ...
```

See also [this](https://github.com/sferik/rails_admin/pull/2805) and never forget about [this](https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests)

**Comment by mt-kelvintaywl** [comment]
in addition to the suggestions from @airled above, you can also set the context on the controller:

```
# your rails_admin_controller.rb

class RailsAdminController < ActionController::Base
  include ActionController::MimeResponds
  include ActionController::Helpers
  include ActionController::Flash

  around_action :switch_locale

  ...

  def switch_locale(&action)
    # force RailsAdmin to be always localized to `en`
    I18n.with_locale(:en, &action)
  end
```

**Comment by mshibuya** [comment]
@airled @mt-kelvintaywl Created a wiki entry based on your comments, thanks.
https://github.com/sferik/rails_admin/wiki/Changing-locale
