### ISSUE TITLE
undefined local variable or method `current_user' for #<RailsAdmin::MainController:0x007f9ca9a49b90> Did you mean? _current_user

### ISSUE THREAD

**Issue by bacmive** [sferik/rails_admin#3228]
I want to ask if someone happened to meet the situation like me? I dont know  where the problem is.   
I simply have done the following steps to apply rails_admin:

> 1. Open gem file and writer gem 'rails_admin', '~> 1.0'
> 2. bundle install
> 3. rails g rails_admin:install
> 4. it will ask you about the admin route if you want to go with the default press Enter.
> 5. go to app/config/initializers/rails_admin.rb and paste this code: 
> config.authorize_with do redirect_to main_app.root_path unless current_user.try(:admin?) end 

![image](https://user-images.githubusercontent.com/19278946/69842829-c1dfef80-129f-11ea-89e5-d45ebc4f9655.png)

**Comment by airled** [comment]
Can you provide more detailed `rails_admin.rb` config?

**Comment by sharat-hegde** [comment]
I am also getting same error.

This is rails_admin.rb 
RailsAdmin.config do |config|

  ### Popular gems integration

  ## == Devise ==
  # config.authenticate_with do
  #   warden.authenticate! scope: :user
  # end
  # config.current_user_method(&:current_user)

  ## == CancanCan ==
  # config.authorize_with :cancancan

  ## == Pundit ==
  # config.authorize_with :pundit

  ## == PaperTrail ==
  # config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0

  ### More at https://github.com/sferik/rails_admin/wiki/Base-configuration

  ## == Gravatar integration ==
  ## To disable Gravatar integration in Navigation Bar set to false
  # config.show_gravatar = true

  config.actions do
    dashboard                     # mandatory
    index                         # mandatory
    new
    export
    bulk_delete
    show
    edit
    delete
    show_in_app

    ## With an audit adapter, you can add:
    # history_index
    # history_show
  end
end

**Comment by sharat-hegde** [comment]
I am also getting same error

**Comment by sharat-hegde** [comment]
This is rails_admin.rb


``RailsAdmin.config` do |config|

  ### Popular gems integration

  ## == Devise ==
  # config.authenticate_with do
  #   warden.authenticate! scope: :user
  # end
  # config.current_user_method(&:current_user)

  ## == CancanCan ==
  # config.authorize_with :cancancan

  ## == Pundit ==
  # config.authorize_with :pundit

  ## == PaperTrail ==
  # config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0

  ### More at https://github.com/sferik/rails_admin/wiki/Base-configuration

  ## == Gravatar integration ==
  ## To disable Gravatar integration in Navigation Bar set to false
  # config.show_gravatar = true

  config.actions do
    dashboard                     # mandatory
    index                         # mandatory
    new
    export
    bulk_delete
    show
    edit
    delete
    show_in_app

    ## With an audit adapter, you can add:
    # history_index
    # history_show
  end
end
`

**Comment by mshibuya** [comment]
You need to setup your authentication method properly to make it work.
https://github.com/sferik/rails_admin/wiki/Authentication
