### ISSUE TITLE
Need help to Limiting the number of rows in Dashboard for History_Index Action

### ISSUE THREAD

**Issue by BrunoCampana** [sferik/rails_admin#3229]
Hello,
I'm using Rails_admin together with Papertrail.

Because I inserted the "History_Index" action, in "config.actions", like below:

history_index do
   only PAPER_TRAIL_AUDIT_MODEL
end

Now, the number of rows that are appearing in the Dashboard are at least 100. 
Can I limit this number for, for example ONLY the last 10 records?

Can you guys help me?

**Comment by twikah** [comment]
@BrunoCampana,

In my case I wanted to change my dashboard completely which included also changing the number of rows for Papertrail history, so I added a new file on my project on <root>/lib/rails_admin.rb and added the following code there:

```
module RailsAdmin
  module Config
    module Actions
      class Dashboard < RailsAdmin::Config::Actions::Base
        RailsAdmin::Config::Actions.register(self)

        register_instance_option :root? do
          true
        end

        register_instance_option :breadcrumb_parent do
          nil
        end

        register_instance_option :auditing_versions_limit do
          25
        end

        register_instance_option :controller do
          proc do
              # dashboard logic
          end

        register_instance_option :route_fragment do
          ''
        end

        register_instance_option :link_icon do
          'icon-home'
        end

        register_instance_option :statistics? do
          true
        end
      end
    end
  end
```

I added my whole file but the bit of code you need is the one with the `:auditing_versions_limit`.

Hope this helps!

**Comment by BrunoCampana** [comment]
It worked! 

Thank you soooo much Vanessa! @twikah 

Observation:
Instead of creating a new "dashboard" file, I inserted:

```
register_instance_option :auditing_versions_limit do
   25
end
```
inside /config/initializers/rails_admin.rb 

Inside the "dashboard" action. Thus:

```
RailsAdmin.config do |config|
config.actions do
     
     ... a lot of stuff...
    
    dashboard do
      register_instance_option :auditing_versions_limit do
        10
      end
    end                     
    ... a lot of other actions ...
  end
end
```
