### ISSUE TITLE
Rails admin should not set empty form fields as empty strings on model

### ISSUE THREAD

**Issue by ajsharp** [sferik/rails_admin#3233]
I'm using rails_admin 1.4.2. 

If I leave a field empty in an edit form, that field gets passed through and set on the model as an empty string. This causes a whole host of problems with unique sparse indexes, and a host of other things that rely on null-ish values to be null in the database. Rails admin should just replicate the rails default behavior here and not pass in empty strings.

**Comment by airled** [comment]
As a workaround, you can use [strip_attributes](https://github.com/rmm5t/strip_attributes) gem. **By default** (without `allow_empty` key) it converts empty strings to nil. You can strip any attribute you want on any model. Or you can just add `strip_attributes` to `ApplicationRecord` and every empty field on every model (if you inherit it from `ApplicationRecord`) will automatically convert `''` ti `nil`.

**Comment by tom-lord** [comment]
> a host of other things that rely on null-ish values to be null in the database

```
validate :my_field, presence: true, allow_nil: true
```

**Comment by ajsharp** [comment]
@mshibuya Any thoughts here?

**Comment by cs0511** [comment]
have same issue

**Comment by asanger** [comment]
Also experiencing the same problem. I've needed to create unique setters on all of my models for anything that needs to be set explicitly to `NULL` rather than `EMPTY` in my postgres db.

In your model, for whatever fields need to remain `NULL`, do something like this:

```ruby
  def last_name=(val)
    super(val == "" ? nil : val)
  end
```

Would still prefer a proper solution, though.

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/commit/3f9ab1cc009caa8b466f34da692c3561da2235e4 should have solved this.
