### ISSUE TITLE
Strange "undefined method" error, that persists after reverting from an earlier error

### ISSUE THREAD

**Issue by bo-oz** [sferik/rails_admin#3242]
I was playing around with configuration of which field to display in my Rails Admin, when I got a NoMethod error. Ater fixing the issue and hitting refresh, I keep getting the same error. The only solution is to restart the server entirely. After that the configuration works. Is there some kind of Caching I need to disable in development mode? Thanks! See screenshot with the strange error below.

![image](https://user-images.githubusercontent.com/872812/72427811-d6634300-378c-11ea-8986-6dce99483a26.png)

**Comment by lanks** [comment]
I'm getting this error as well when I define fields that are virtual. @bo-oz did you have any luck figuring this out?

**Comment by bo-oz** [comment]
It seems that when you configure fields for your models, the configuration is sticky. So in other words, when you run the code the configuration is set, but when you remove a line it is not removed from cache. I solved it by running a reset command on all my modules:

`RailsAdmin::Config.reset_model(ModelName)`
