### ISSUE TITLE
has_many associations show page

### ISSUE THREAD

**Issue by jayaprakash88** [sferik/rails_admin#3244]
Hi,
I have two models User and Role. The User having has many roles, the role belongs to the user.

I want to display in user show page all the role names in one by one. But now it's coming all the roles name is the same line with a comma separator. Kindly see my below code. 

config.model 'User' do
    show do
      include_all_fields
      field :roles do
        orderable true
      end
    end
  end

Could you please help me with how to show user role name one by one.

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
