### ISSUE TITLE
Problems with Rails 5 API only

### ISSUE THREAD

**Issue by Cremz** [sferik/rails_admin#3245]
I have an api only rails 5 app with rails_admin. Everything works fine, but now I want to add ckeditor for one of the fields in a model.
I don't really want to add the asset pipeline just for the js from ckedtor, I would rather just load the js from a cdn. 
Any tips on how I could edit the layout of the rails admin page to include a script snippet ?
Or any other solution to have a nice text editor for a rails api app.

**Comment by mshibuya** [comment]
#3126 should have solved this.
