### ISSUE TITLE
NameError in RailsAdmin::Main#dashboard 

### ISSUE THREAD

**Issue by rajamasker07** [sferik/rails_admin#3247]
NameError in RailsAdmin::Main#dashboard 
undefined local variable or method `rails_admin' for #<#<Class:0x00007fe1ad4b18b0>:0x00007fe1ad017908>
Did you mean?  rails_in

![image](https://user-images.githubusercontent.com/50787346/73607242-f9984a00-45f6-11ea-95b7-4779d04b623c.png)

rails_admin (2.0.1) app/helpers/rails_admin/application_helper.rb:161:in `block in menu_for'
rails_admin (2.0.1) app/helpers/rails_admin/application_helper.rb:157:in `collect'
rails_admin (2.0.1) app/helpers/rails_admin/application_helper.rb:157:in `menu_for'
rails_admin (2.0.1) app/views/rails_admin/main/dashboard.html.haml:29:in `block in __home_rosyid__rvm_gems_ruby_______gems_rails_admin_______app_views_rails_admin_main_dashboard_html_haml__1180115267540510585_70303623456900'
rails_admin (2.0.1) app/views/rails_admin/main/dashboard.html.haml:10:in `each'
rails_admin (2.0.1) app/views/rails_admin/main/dashboard.html.haml:10:in `__home_rosyid__rvm_gems_ruby_______gems_rails_admin_______app_views_rails_admin_main_dashboard_html_haml__1180115267540510585_70303623456900'
actionview (5.2.4.1) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.4.1) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.4.1) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.4.1) lib/action_view/template.rb:157:in `render'
actionview (5.2.4.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.4.1) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.4.1) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.4.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.4.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.4.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.2.4.1) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.4.1) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.4.1) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.4.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.4.1) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.4.1) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.4.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.4.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.4.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.4.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.4.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/home/rosyid/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.2.4.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.4.1) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:45:in `render'
remotipart (1.4.4) lib/remotipart/render_overrides.rb:23:in `render'
rails_admin (2.0.1) lib/rails_admin/config/actions/dashboard.rb:37:in `block (2 levels) in <class:Dashboard>'
rails_admin (2.0.1) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
rails_admin (2.0.1) app/controllers/rails_admin/main_controller.rb:22:in `dashboard'
actionpack (5.2.4.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
railties (5.2.4.1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.4.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.1.1) lib/rack/tempfile_reaper.rb:17:in `call'
rack (2.1.1) lib/rack/etag.rb:27:in `call'
rack (2.1.1) lib/rack/conditional_get.rb:27:in `call'
rack (2.1.1) lib/rack/head.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.1.1) lib/rack/session/abstract/id.rb:277:in `context'
rack (2.1.1) lib/rack/session/abstract/id.rb:271:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.1) lib/rack/method_override.rb:24:in `call'
rack (2.1.1) lib/rack/runtime.rb:24:in `call'
activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.1.1) lib/rack/sendfile.rb:113:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

**Comment by chychkan** [comment]
I had the same error and was able to resolve by changing in my `routes.rb`
```
mount RailsAdmin::Engine => '/app_admin', :as => 'app_admin'
```
to
```
mount RailsAdmin::Engine => '/app_admin', :as => 'rails_admin'
```
