### ISSUE TITLE
Order of inline_add and inline_edit fields

### ISSUE THREAD

**Issue by gerardo-navarro** [sferik/rails_admin#3252]
Dear rails_admin team,

first of all: thank you for this great gem.

The issue I have experienced concerns the order of the fields in the inline_{add, edit} forms.

When using nested forms the field order cannot be overridden by the `include_fields :field1, :field2`. It is only picked up the by field definition outside of the action config. Is this supposed to be like that?

```
RailsAdmin.config do |config|
  config.model 'Model' do
    field :field1 { ... } # <-- this is relevant for the field order in the inline_add nested field
    field :field2 { ... }
      
    create do
      include_fields :field2, field1  # <-- this field order is ignored for the inline_add nested form although it is considered when creating the mode in the plain form
    end
  end
end
```

**Comment by mshibuya** [comment]
Use [Modal](https://github.com/sferik/rails_admin/wiki/Modal) section for that.
