### ISSUE TITLE
Rails Admin can't create records in table that has records --> PG::UniqueViolation: ERROR:

### ISSUE THREAD

**Issue by bo-oz** [sferik/rails_admin#3258]
When I try to add new records to a table, it seems that Rails-Admin is not respecting the sequence on the ID field in Postgres. It looks like Rails Admin is trying to add records with ID=1, then ID=2 etc. Since there are already a few thousands records in the table, it will not work for a long time. Is there any way to reset this behavior, so that Rails Admin tries to find the correct ID? Or is this a Postgres error?

```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "companies_pkey"
DETAIL:  Key (id)=(5) already exists.
```

**Comment by mshibuya** [comment]
You need to adjust the value in Postgres side.
https://stackoverflow.com/a/9108929
