### ISSUE TITLE
Rails Admin not working well with customized Trix

### ISSUE THREAD

**Issue by lsnn** [sferik/rails_admin#3272]
I'm using Rails 6.0.2 + RailsAdmin and have integrated Action Text for 1 field. Everything is working fine with the standard Action Text toolbar. 
I've added a custom button for `<h2>` tags, which are correctly displayed in the text field when I'm editing my content, and they're correctly saved on the model as `RichText`. They're also displayed correctly as `<h2>` on my webpage. 
However, when I want to edit my model again in RailsAdmin, _most of the time_ the custom `h2` tags have disappeared. The text is shown without tags. Only the default tags that came with ActionText are still there (like `h1`).
I say _most of the time_, because if I first edit another model, then cancel and return to edit the original one, the `h2` tags are all visible.

I'm suspecting this has something to do with the js not being loaded on time.
I've added the custom js for the `h2` button under `javascript/packs` and this is my `javascript/packs/application.js`
```
require("@rails/ujs").start()
require("@rails/activestorage").start()

require("trix")
require("@rails/actiontext")

import '../stylesheets/application';
import 'bootstrap/js/dist/carousel';
```
The custom scss to style the Action Text toolbar is located in `assets/stylesheets/rails_admin/custom/theming.scss`. I tried loading them through webpacker before, and they would load, but the css was not applied.

Should I be loading the js or scss in a different place? What am I missing?

**Comment by lsnn** [comment]
If this helps anyone: the problem is that Rails Admin does not work well with webpacker. And since Action Text and  Trix are part of Rails >= 6 and loaded through webpacker, any js customization within Rails Admin seems impossible/very hard.
I decided to move away from Rails Admin. I went with Administrate instead and had everything working in 30 mins.

**Comment by PuZZleDucK** [comment]
While having issues with Action Text in Rails Admin I came across this thread and started to despair.

After trying a dozen things that didn't work I stumbled across this from the official wiki explaining how to setup **Rails Admin** + **Action Text** + **Attachments**: [https://github.com/railsadminteam/rails_admin/wiki/ActionText](https://github.com/railsadminteam/rails_admin/wiki/ActionText)

According to the change log support was introduced in RailsAdmin 2.0.0.beta. Hopefully this might help someone else who comes across this.
