### ISSUE TITLE
Error 500 when call /admin in browser

### ISSUE THREAD

**Issue by gporpino** [sferik/rails_admin#3273]
I just already installed rails_admin with devise and cancancan, in browser i receive a error 500. at development log it just print this. 

config/initializers/rails_admin.rb:7:in `block (2 levels) in <main>'

That is the complete log: 

Started GET "/admin" for 127.0.0.1 at 2020-04-14 22:39:58 -0300
22:39:58 log.1  |    (1.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
22:40:00 log.1  | Processing by RailsAdmin::MainController#dashboard as HTML
22:40:00 log.1  |   User Load (22.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
22:40:00 log.1  |   ↳ config/initializers/rails_admin.rb:7:in `block (2 levels) in <main>'
22:40:01 log.1  |    (21.8ms)  SELECT COUNT(*) FROM "users"
22:40:01 log.1  |   User Load (3.8ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
22:40:01 log.1  |   Rendering /Users/gporpino/.rvm/gems/ruby-2.7.1/gems/rails_admin-2.0.2/app/views/rails_admin/main/dashboard.html.haml within layouts/rails_admin/application
22:40:01 log.1  |   Rendered /Users/gporpino/.rvm/gems/ruby-2.7.1/gems/rails_admin-2.0.2/app/views/rails_admin/main/dashboard.html.haml within layouts/rails_admin/application (Duration: 164.3ms | Allocations: 13283)
22:40:03 log.1  |   Rendered /Users/gporpino/.rvm/gems/ruby-2.7.1/gems/rails_admin-2.0.2/app/views/layouts/rails_admin/_head.html.haml (Duration: 1899.5ms | Allocations: 271446)
22:40:03 log.1  | Completed 500 Internal Server Error in 3563ms (ActiveRecord: 116.7ms | Allocations: 416788)
22:40:03 log.1  |

**Comment by VladimirCourse** [comment]
Having the same problem, just crash without errors. 

Started GET "/admin" for ::1 at 2020-04-27 13:19:58 +0300
Processing by RailsAdmin::MainController#dashboard as HTML
MONGODB | [23] localhost:27017 #1 | back_development.count | STARTED | {"count"=>"motorcycles", "query"=>{}, "$db"=>"back_development", "lsid"=>{"id"=><BSON::Binary:0x16500 type=uuid data=0x5d60554944094bc4...>}}
MONGODB | [23] localhost:27017 | back_development.count | SUCCEEDED | 0.000s
MONGODB | [24] localhost:27017 #1 | back_development.count | STARTED | {"count"=>"motorcycle_types", "query"=>{}, "$db"=>"back_development", "lsid"=>{"id"=><BSON::Binary:0x16500 type=uuid data=0x5d60554944094bc4...>}}
MONGODB | [24] localhost:27017 | back_development.count | SUCCEEDED | 0.000s
  Rendering /home/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rails_admin-2.0.2/app/views/rails_admin/main/dashboard.html.haml within layouts/rails_admin/application
  Rendered /home/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rails_admin-2.0.2/app/views/rails_admin/main/dashboard.html.haml within layouts/rails_admin/application (Duration: 3.0ms | Allocations: 2269)
  Rendered /home/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rails_admin-2.0.2/app/views/layouts/rails_admin/_head.html.haml (Duration: 18.7ms | Allocations: 11279)
Completed 500 Internal Server Error in 34ms (MongoDB: 0.0ms | Allocations: 19012)

Key gems used in projec:t 

ruby '2.7.0'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
gem 'puma', '~> 4.1'
gem 'mongoid', '~> 7.0.5'
gem 'rails_admin', '~> 2.0'
