### ISSUE TITLE
can't modify frozen fatal: #<fatal: exception reentered> (FrozenError) / (ActionView::Template::Error)

### ISSUE THREAD

**Issue by fcabanasm** [sferik/rails_admin#3280]
rails 6.0.3.1
ruby 2.7.1
rails_admin 2.0.2

its occur when run rails s, after gem installation and rails g rails admin:install

<details>
<summary>Full error message:</summary>

Traceback (most recent call last):
/home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:17:in `catch': exception reentered (fatal)
/home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:17:in `catch': can't modify frozen fatal: #<fatal: exception reentered> (FrozenError)
	87: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
	86: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
	85: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
	84: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
	83: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
	82: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
	81: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
	80: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/webpacker-4.2.2/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
	79: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
	78: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
	77: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
	76: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
	75: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	74: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
	73: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
	72: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
	71: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	70: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	69: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'
	68: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
	67: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
	66: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
	65: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'
	64: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'
	63: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	62: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:17:in `call'
	61: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:17:in `catch'
	60: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:28:in `block in call'
	59: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:132:in `call_app'
	58: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:30:in `call'
	57: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:43:in `rescue in call'
	56: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:73:in `render_exception'
	55: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:88:in `render_for_browser_request'
	54: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_view.rb:50:in `render'
	53: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
	52: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger_silence.rb:36:in `silence'
	51: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger.rb:64:in `block (3 levels) in broadcast'
	50: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger_silence.rb:36:in `silence'
	49: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_view.rb:50:in `block in render'
	48: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/haml-5.1.2/lib/haml/helpers/action_view_mods.rb:15:in `render'
	47: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/helpers/rendering_helper.rb:30:in `render'
	46: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/base.rb:304:in `in_rendering_context'
	45: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
	44: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:22:in `render'
	43: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
	42: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
	41: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:13:in `render'
	40: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:56:in `render_template'
	39: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
	38: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
	37: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
	36: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
	35: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	34: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
	33: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
	32: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
	31: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/template.rb:183:in `render'
	30: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/template.rb:385:in `instrument_render_template'
	29: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:182:in `instrument'
	28: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/template.rb:185:in `block in render'
	27: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/base.rb:274:in `_run'
	26: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb:37:in `__home_fcabanasm__rvm_gems_ruby_______gems_actionpack_________lib_action_dispatch_middleware_templates_rescues_diagnostics_html_erb__4324384474606813194_41980'
	25: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_view.rb:50:in `render'
	24: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
	23: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger_silence.rb:36:in `silence'
	22: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger.rb:64:in `block (3 levels) in broadcast'
	21: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/logger_silence.rb:36:in `silence'
	20: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_view.rb:50:in `block in render'
	19: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/haml-5.1.2/lib/haml/helpers/action_view_mods.rb:15:in `render'
	18: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/helpers/rendering_helper.rb:30:in `render'
	17: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/base.rb:304:in `in_rendering_context'
	16: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
	15: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:22:in `render'
	14: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
	13: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
	12: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:13:in `render'
	11: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:56:in `render_template'
	10: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
	 9: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
	 8: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
	 7: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
	 6: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	 5: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
	 4: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
	 3: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
	 2: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/template.rb:182:in `render'
	 1: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/template.rb:188:in `rescue in render'

/home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.1/lib/action_view/template.rb:354:in `handle_render_error': can't modify frozen fatal: #<fatal: exception reentered> (ActionView::Template::Error)
	30: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
	29: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
	28: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
	27: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
	26: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
	25: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
	24: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
	23: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/webpacker-4.2.2/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
	22: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
	21: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
	20: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
	19: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
	18: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	17: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
	16: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
	15: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
	14: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	13: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	12: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'
	11: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
	10: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
	 9: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
	 8: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'
	 7: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'
	 6: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	 5: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:17:in `call'
	 4: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:17:in `catch'
	 3: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:28:in `block in call'
	 2: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:131:in `call_app'
	 1: from /home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:134:in `rescue in call_app'
/home/fcabanasm/.rvm/gems/ruby-2.7.1/gems/web-console-4.0.2/lib/web_console/middleware.rb:134:in `throw': uncaught throw :app_exception (UncaughtThrowError)

</details>

**Comment by mshibuya** [comment]
I don't think this is related to RailsAdmin. Did you see this?
https://stackoverflow.com/questions/60683842/uncaughtthrowerror-uncaught-throw-app-exception
