### ISSUE TITLE
Icon for custom action is not showing

### ISSUE THREAD

**Issue by Aman2804** [sferik/rails_admin#3284]
I already configure all the things for the custom action
this is the configuration for the icon

register_instance_option :link_icon do
   'icon-envelope'
end

but still it is not showing in the admin panel
please help me out this issue

**Comment by mshibuya** [comment]
You need to mark it as a member action to make it interact with each record.
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/base.rb#L71-L74
