### ISSUE TITLE
undefined local variable or method `current_user' for #<RailsAdmin::MainController:0x00007ff680a0e8e8> Did you mean? _current_user

### ISSUE THREAD

**Issue by sharat-hegde** [sferik/rails_admin#3292]
This is ralls_admin.rb

RailsAdmin.config do |config|
	config.actions do
	    dashboard
	    index
	    new
	    export
	    bulk_delete
	    show
	    edit
	    delete
	    show_in_app
  	end
end

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/issues/3228#issuecomment-894754042
