### ISSUE TITLE
Documented list of options that can appear within a configure block?

### ISSUE THREAD

**Issue by Syntaf** [sferik/rails_admin#3297]
Hey all, I've looked everywhere but can't find any documentation about the available options that can be passed into `configure`:

```ruby
rails_admin do
  list do
    configure :my_field do
      # what are all of the available options
    end
  end
end
```

[This](https://github.com/sferik/rails_admin/wiki/Fields) wiki page is the closest I could find, but are these the only options available?

**Comment by okasha-blink** [comment]
Not sure if they are all documented somewhere, but you can get it from the source code ..
It depends on the field type, 
But they all inherit from base
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/base.rb
which have common options: visible, label, read_only ..
and specific options for every field type are in fields/types directory , text, boolean, enum, date, color ..

they are the ones registered via: register_instance_option

**Comment by okashoon** [comment]
Not sure if they are all documented somewhere, but you can get it from the source code ..
It depends on the field type,
But they all inherit from base
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/base.rb
which have common options: visible, label, read_only ..
and specific options for every field type are in fields/types directory , text, boolean, enum, date, color ..

they are the ones registered via: register_instance_option
