### ISSUE TITLE
Could not load model ModelName, undefined method `has_one_attached' 

### ISSUE THREAD

**Issue by Saleh-Salem** [sferik/rails_admin#3303]
I am workin on project 
Ruby version => 2.7.1
Rails Version => 6.0.3.2

I add rails admin gem on project  => `gem 'rails_admin'`

It worked fine.
But after few days get issue when back to project and run rails server to complete my work, I get issue 
**`[RailsAdmin] Could not load model Project, assuming model is non existing. (undefined method `has_one_attached' for #<Class:0x00005585f7ed0bc0>)`**

I follow all steps in this issue [3025](https://github.com/sferik/rails_admin/issues/3025) but not solved my issue

**Comment by mshibuya** [comment]
I believe this should be the same issue as #3025, describing what actually you did will help find the issue.
