### ISSUE TITLE
RailsAdmin::Config.reset does not fully reset config

### ISSUE THREAD

**Issue by adambruss** [sferik/rails_admin#3305]
In my app, I'm attempting to manage which models are excluded by customer, which I'm doing with a decorator (see below):
```
RailsAdmin::ApplicationController.class_eval do
	before_action :switch_tenant, :reload_rails_admin

	def switch_tenant
		Apartment::Tenant.switch!(params[:customer_id])
	end

	def reload_rails_admin
		Rails.application.eager_load!
		excluded_models = ApplicationRecord.descendants.map { |m| m.name unless m.base_class.table_exists? }.compact
		puts "Excluded models: #{excluded_models}"

		RailsAdmin::Config.reset
		RailsAdmin.config do |config|
			config.excluded_models = excluded_models

			config.actions do
				dashboard
				index
				new
				export
				bulk_delete
				show
				edit
				delete
				show_in_app
			end
		end
	end

end
```

What I've found is that the RailsAdmin config is sticky.  Depending on which customer I load first, that's the set of models that are used for the next customer.  At first, I thought maybe it was a caching thing (maybe it still is?), but I've attempted to insert Rails.cache.clear calls at various stages to no effect.

Any thoughts?

**Comment by grillermo** [comment]
Yeah, you need to reload the server each time you change this config. It is the same with all initializers.

**Comment by computeus** [comment]
I have the same exact problem. No matter what I tried, I am not able to make the changes to included_models option work.

When I print the included_models option value, it seems it is changed but it doesn't affect the frontend.

**Comment by mshibuya** [comment]
Yeah this is not ideal, I'll take a look into this to see if it's fixable.
