### ISSUE TITLE
Using actiontext with rails_admin?

### ISSUE THREAD

**Issue by vnguyen13** [sferik/rails_admin#3314]
I am running on rails 6, but I'd like to take advantage of the integration of actiontext. I went through the documentation to install:
https://edgeguides.rubyonrails.org/action_text_overview.html

However, I've tried to add the following in the model:

```
has_rich_text :body

  rails_admin do
    edit do
      field :body, :rich_text_area
      field :prompt_id
    end
  end
```

but I get "Unsupported field datatype: rich_text_area". 

Has anyone successfully integrated actiontext with rails_admin?

**Comment by zaknafain** [comment]
Yes, it's working out pretty fine. If you followed that rails guide you linked you will have a model like this one:

```ruby
class Post < ApplicationRecord
  has_rich_text :body
end
```

Following the [wiki entry of rails_admin](https://github.com/sferik/rails_admin/wiki/ActionText) you come out with something like:

```ruby
class Post < ApplicationRecord
  has_rich_text :body

  rails_admin do
    field :body do
      js_location { bindings[:view].asset_pack_path 'actiontext.js' }
    end
  end
end
```

To get the js file loaded you need to separate the following lines from the `application.js` and put them into the file mentioned above:

```js
require("trix")
require("@rails/actiontext")
```

After you restarted your server it should work.
