### ISSUE TITLE
Show "no records found" when a list is empty

### ISSUE THREAD

**Issue by jigarius** [sferik/rails_admin#3329]
I searched a lot but couldn't find anything on it. What I want to do is:

  * Create an admin list page for a, say, `Post` model.
  * If there are no posts, the page should say, "No (matching) records found."

Is that doable?

**Comment by matthewfu** [comment]
@jigarius  Like this? 
![image](https://user-images.githubusercontent.com/474270/122497205-9a867a00-d01f-11eb-9ad6-12b39b759ba5.png)

I just found that I need that on my project. You may find my code on my forked repo on branch: https://github.com/matthewfu/rails_admin/tree/show-new-records-found-on-list

**Comment by mshibuya** [comment]
Closed by #3365.
