### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by StephenSoft** [sferik/rails_admin#3334]
![image](https://user-images.githubusercontent.com/26949266/105722899-1b55b400-5f61-11eb-85a0-59112a4933db.png)
```ruby
# my gemfile
gem 'rails_admin', '~> 2.0'
```

i fix this error use gem 'rails_admin', git: 'git@github.com:sferik/rails_admin.git'

**Comment by kaiomagalhaes** [comment]
@StephenSoft what do you mean by you fixed this issue? I see no commit changes on master about it

**Comment by dennyf** [comment]
Thanks a lot for sharing, that helped me resolve the issue!
So, if I understand correctly the issue has been fixed in master but it wasn't released as a new version?

**Comment by mplewis** [comment]
Thank you for sharing the solution.

@dennyf That is how I understand this as well.

**Comment by mshibuya** [comment]
Fixed in 2.1.0.
