### ISSUE TITLE
Cannot save attachments

### ISSUE THREAD

**Issue by KerronKing** [sferik/rails_admin#3335]
When configuring rails_admin with action_text, I'm able to edit the text with bold, italics etc. However, image attachments are not saved when dragged and dropped in and the attachment button does not show up. Furthermore, if I add the following code to the rails_admin.rb file, I'm able to save attachments but the other fields in the Post model disappear:

```
config.model 'Post' do
    field :content do
      js_location { bindings[:view].asset_pack_path 'actiontext.js' }
    end
  end
```

**Comment by mshibuya** [comment]
Both of them are documented in Wiki.
https://github.com/sferik/rails_admin/wiki/ActionText#easy-to-use-setup
https://github.com/sferik/rails_admin/wiki/Fields#visibility-and-ordering
