### ISSUE TITLE
associated_collection_scope works only once after starting the application

### ISSUE THREAD

**Issue by bartosz-michalak** [sferik/rails_admin#3336]
Hello,
I have a problem with `associated_collection_scope` which seems to work only when the page is loaded the first time after starting the application.

I used `binding.pry` to check, if the code inside configuration is executed:

```
associated_collection_scope do
  associated_collection_cache_all false
  Proc.new { |scope|
    binding.pry
    scope = scope.without_erased
  }
end
```

And turns out, that the code is executed only when the page is loaded first time after starting the application. On each subsequent request on the page with this model, this code is skipped, which results in the use of default scope.

Any idea?

Spec:
**rails** -> 6.0.3.4
**rails_admin** -> 2.0.2

**Comment by sharvy** [comment]
@bartosz-michalak could you fix the problem?
