### ISSUE TITLE
rails g rails_admin:install Stuck on Mount Question (Git Bash/Win 10x64)

### ISSUE THREAD

**Issue by jkh0309** [sferik/rails_admin#3338]
Hello,

Now that I resolved my previous issue (#3330), I'm still having trouble installing rails_admin. I get the following when I try to run the ```rails g rails_admin:install``` prompt:

```
$ rails g rails_admin:install
< to mount rails_admin? Press <enter> for [admin] >

```

It does nothing from here. I even left it there overnight and still no response, no error, nothing. I read on a previous issue ([#2334](https://github.com/sferik/rails_admin/issues/2334) something about doing ```spring stop``` and trying again, but I'm not running it and Spring doesn't work on Windows machines, so that solution does not work for me.

Anyone else have any other ideas?

Specs:
- Ruby 2.7.2p137
- Rails 6.1.1
- Windows 10 x64
- Git Bash for Terminal

**Comment by jkh0309** [comment]
I really want to use this gem, but I really need some assistance with this. Is this project being actively worked on at all?

**Comment by mshibuya** [comment]
This does not directly solve the issue, but you can bypass the prompt by following this way.
https://github.com/sferik/rails_admin/issues/3023#issuecomment-894771915
