### ISSUE TITLE
Crash on trying to reopen an URL that was generated by a rails admin filter

### ISSUE THREAD

**Issue by fynsta** [sferik/rails_admin#3345]
NoMethodError: undefined method `gsub' for #<ActionController::Parameters {"0"=>"Montag, 01. März 2021, 18:41 Uhr", "1"=>"Montag, 01. Februar 2021, 18:41 Uhr", "2"=>"Sonntag, 28. Februar 2021, 18:41 Uhr"} permitted: false>

when trying to open an url ending with `admin/model?model_name=model&f%5Bcreated_at%5D%5B04801%5D%5Bo%5D=between&f%5Bcreated_at%5D%5B04801%5D%5Bv%5D%5B%5D=Montag%2C+01.+M%C3%A4rz+2021%2C+18%3A41+Uhr&f%5Bcreated_at%5D%5B04801%5D%5Bv%5D%5B%5D=Montag%2C+01.+Februar+2021%2C+18%3A41+Uhr&f%5Bcreated_at%5D%5B04801%5D%5Bv%5D%5B%5D=Sonntag%2C+28.+Februar+2021%2C+18%3A41+Uhr&query=`

I had added a filter (created_at between 1.Feb and 28.Feb) and saved the url, then reopened

**Comment by codealchemy** [comment]
What version of Ruby / Rails / RailsAdmin are you using?

Also can you share more insights to the stacktrace from the error? Did anything in your `rails_admin` config change between the time you save the filter and when things started breaking?

**Comment by fynsta** [comment]
I have updated to the newest rails admin version and it seems to work now.. I'll reopen if I see it again. Thanks!
