### ISSUE TITLE
datepicker dialog not showing up below filter box when not first element

### ISSUE THREAD

**Issue by nicolasfranck** [sferik/rails_admin#3347]
**Version used**

`2.1.1`

**What happens**

* in the  `index` of a model, click button `add filter` and add a filter on a datetime field like `created_at`
* click in the input field of that filter: a datepicker dialog appears
* add a second filter, for example on field `updated_at`, and enter the input value: no dialog appears
* only the first datetime input seems to be able to make the dialog appear
* this also happens when the filters are preloaded

**Comment by codealchemy** [comment]
I was unable to reproduce this on a Mac (macOS `10.15.7`) using the `spec/dummy_app` with Firefox (`83.0`), Safari (`14.0.3`), or Chrome (`89.0.4389.90`).

Any chance you could provide additional context for debugging, including the Rails / Ruby version, Browser (and plugins / extensions, if applicable), and if there are any errors in the browser's console when the issue occurs?

**Comment by mshibuya** [comment]
Please reopen on update.
