### ISSUE TITLE
Issue publishing to Heroku - NestedForm::BuilderMixin (NameError)

### ISSUE THREAD

**Issue by gregframe** [sferik/rails_admin#3350]
Thanks for the great work on this.  It is super cool and works locally great.  However when I
 publish to Heroku the server immediately gets a crash on startup with this error:

/app/vendor/bundle/ruby/2.7.0/gems/rails_admin-2.1.1/app/helpers/rails_admin/form_builder.rb:3:in `<class:FormBuilder>': uninitialized constant NestedForm::BuilderMixin (NameError)

I see some very old talk about this issue but nothing recent.  I am on Rails 6.1.3, Ruby 2.7.1 on the Heroku-20 stack.  Full stack trace attached.

Any help appreciated!

--Greg

[stack.txt](https://github.com/sferik/rails_admin/files/6175987/stack.txt)

**Comment by gregframe** [comment]
Seems to be that rails_admin is not compatible with eager loading in Rails 6+, you can add config.autoloader = :classic to your application.rb to get past this issue, however, starting out my new app in an already deprecated state does not sit well.  Any help appreciated.

**Comment by victormaths** [comment]
+1. Same problem here

**Comment by victormaths** [comment]
https://github.com/sferik/rails_admin/issues/887#issuecomment-636622362

This workaround worked for me.

**Comment by gregframe** [comment]
Confirmed that adding these lines to the top of config/initializers/rails_admin.rb worked, thanks @victormaths 
`require "nested_form/engine"
require "nested_form/builder_mixin"
`

**Comment by mshibuya** [comment]
Dup of #3328.
