### ISSUE TITLE
SystemStackError in RailsAdmin::MainController#delete

### ISSUE THREAD

**Issue by interpegasus** [sferik/rails_admin#3355]
I would like to know how to solve or prevent the following error when deleting a record with  `has_many` associations and  `dependent: :destroy` ?
Thank you
<img width="1064" alt="Screen Shot 2021-04-28 at 4 25 38 PM" src="https://user-images.githubusercontent.com/934795/116474683-6de38c80-a83e-11eb-9bfb-ad487336a01c.png">

**Comment by mshibuya** [comment]
Full stack trace, please.

**Comment by mshibuya** [comment]
Please reopen on update.
