### ISSUE TITLE
Postgresql Array fields not showing in the show page and edit form

### ISSUE THREAD

**Issue by ksbek** [sferik/rails_admin#3363]
Hello,

I can't see array fields in the show page and edit form. Is it just a bug or do I need to configure something?

Thanks in advance

**Comment by coolprobn** [comment]
As far as I know, array is not supported in Rails Admin. You have to configure it yourself.

Here is a resource with the workaround: https://gist.github.com/meirabruno/745597eeccd7b876dc1edcf9a081a9a4
