### ISSUE TITLE
filtering-select not working!!

### ISSUE THREAD

**Issue by zeyadsaleh** [sferik/rails_admin#3367]
I'm working on project where I have some table that have so many records. and when I'm trying to filtering-select the record to choose it when I'm in Add new action, it doesn't work and I'm stuck!

![Screenshot from 2021-06-24 10-35-02](https://user-images.githubusercontent.com/46134907/123231054-2133cf00-d4d8-11eb-85dd-258a6ae93b87.png)

**Comment by mshibuya** [comment]
What version of RailsAdmin are you using? Do you see any errors in your browser console?
