### ISSUE TITLE
Uninitialized constant in production on Ruby 3.0.1

### ISSUE THREAD

**Issue by u2000** [sferik/rails_admin#3368]
Upgrading to Ruby 3 in run on Heroku. Admin gem is failing with uninitialized constant. This  only happens in the production environment.

Is this a known issue?

/Users/{username}/.rvm/gems/ruby-3.0.1@6.1.3/gems/rails_admin-2.1.1/app/helpers/rails_admin/form_builder.rb:3:in `<class:FormBuilder>': uninitialized constant NestedForm::BuilderMixin (NameError)

Thanks!

**Comment by codealchemy** [comment]
Appears to be the same issue as https://github.com/sferik/rails_admin/issues/3328 (fixed in https://github.com/sferik/rails_admin/commit/97ccc28940d65fee53b30c409c49032fbb0885db - but not yet part of a release)

**Comment by u2000** [comment]
Prevents deployment to Heroku with Ruby 3. Any idea on when this will prioritized into a release?

**Comment by mshibuya** [comment]
Just released 2.2.0, please try.
